export type Locale='zh-TW'|'zh-CN'|'en';
export const locales=['zh-TW','zh-CN','en'] as const satisfies readonly Locale[];
export const defaultLocale:Locale='zh-TW';
export function parseLocale(value:string):Locale|undefined{return locales.find(locale=>locale===value)}
export function localeOrFallback(value:string|undefined):Locale{return value&&parseLocale(value)||defaultLocale}
type Labels={features:string;agents:string;readback:string;download:string;buy:string;docs:string;support:string;security:string;cta:string;candidate:string;language:string;traditional:string;simplified:string;english:string;home:string};
export const labels={
'zh-TW':{features:'怎麼使用',agents:'與 Agent 協作',readback:'實作讀回',download:'下載',buy:'購買授權',docs:'文件',support:'支援',security:'規格與安全性',cta:'探索功能',candidate:'查看 Windows 版本',language:'語言',traditional:'繁體中文',simplified:'简体中文',english:'English',home:'首頁'},
'zh-CN':{features:'怎么使用',agents:'与 Agent 协作',readback:'实现读回',download:'下载',buy:'购买授权',docs:'文档',support:'支持',security:'规格与安全性',cta:'探索功能',candidate:'查看 Windows 版本',language:'语言',traditional:'繁體中文',simplified:'简体中文',english:'English',home:'首页'},
en:{features:'How it works',agents:'Work with agents',readback:'Implementation Readback',download:'Download',buy:'Purchase License',docs:'Docs',support:'Support',security:'Specs & Security',cta:'Explore features',candidate:'View Windows release',language:'Language',traditional:'繁體中文',simplified:'简体中文',english:'English',home:'Home'}} satisfies Record<Locale,Labels>;
type Hero={eyebrow:string;title:string;lead:string};
type CoreCatalog={home:Hero&{map:string;docs:string};product:Hero&{items:string[]};agents:Hero&{tree:string;graph:string;human:string;agent:string;readback:string;caption:string};download:Hero&{verify:string};pricing:{eyebrow:string;title:string;first:string;after:string;terms:string[];notice:string;demo:string};buy:Hero&{early:string;standard:string;notice:string};order:{eyebrow:string;title:string;lead:string;verification:string;hint:string;support:string;retry:string}};
export const core={
'zh-TW':{home:{eyebrow:'LOCAL-FIRST PROJECT GROWTH',title:'讓專案從想法，長成可驗證的成果。',lead:'GrowthMap 是人類與任意 AI Agent 共用的專案生長工作區。把節點、分支、實作與證據放進同一張可讀的地圖。',map:'查看協作地圖',docs:'查看操作文件'},product:{eyebrow:'AI-NEUTRAL PRODUCT',title:'不綁模型，把共同脈絡留給每一位協作者。',lead:'GrowthMap 不是黑盒 Agent 管理器，也不是雲端專案替身。它是 Windows 本機優先的共享工作區：人類與任意 Agent 在同一份可讀脈絡上推進。',items:['Tree 與 Graph 同時呈現層級與關係。','Revision 與 atomic changes 讓每一步都可追溯。','Context packet 帶走目標、限制與現況。','History、diff、undo 與 readback 讓實作回到地圖。']},agents:{eyebrow:'TREE · GRAPH · BRANCH · NODE',title:'看見一條分支如何長成成果。',lead:'切換 Tree 與 Graph 視圖，模擬人類與 Agent 在同一張地圖上接力：讀取脈絡、提出原子變更、讀回實作。',tree:'Tree 視圖',graph:'Graph 視圖',human:'人類校正',agent:'Agent 變更',readback:'實作讀回',caption:'互動示意；不會寫入資料或呼叫模型。'},download:{eyebrow:'下載',title:'下載 GrowthMap',lead:'目前提供 Windows x64 桌面版，可立即下載安裝。',verify:'如何驗證 hash'},pricing:{eyebrow:'LICENSE',title:'簡單的個人授權。',first:'前 50 名',after:'之後為 US$29',terms:['個人永久授權','2 台個人裝置','不限專案數量'],notice:'Early 與 Standard 可在 Whop 購買；完成購買後可在 GrowthMap License Experience 取得啟用碼。',demo:'查看授權與購買'},buy:{eyebrow:'購買授權',title:'選擇 Free 或 GrowthMap Personal。',lead:'Free 永久可用並包含全部核心功能；Personal 增加不限啟用專案與兩台個人裝置。',early:'購買 Early — US$10',standard:'購買 Standard — US$29',notice:'在 Whop 完成購買後，於 GrowthMap License Experience 取得啟用碼，再在 Windows 桌面版啟用。'},order:{eyebrow:'訂單狀態',title:'等待授權服務確認。',lead:'此頁的網址參數只供顯示參考，不能證明付款或授權資格。',verification:'付款與履約會由伺服器端 License Authority 驗證；確認前不會交付授權。',hint:'若你剛從 Whop 返回，請保留訂單資料並稍後重試。',support:'聯絡支援',retry:'返回購買頁'}},
'zh-CN':{home:{eyebrow:'本地优先的项目生长',title:'让项目从想法，长成可验证的成果。',lead:'GrowthMap 是人类与任意 AI Agent 共用的项目生长工作区。把节点、分支、实现与证据放进同一张可读的地图。',map:'查看协作地图',docs:'查看操作文档'},product:{eyebrow:'AI-NEUTRAL PRODUCT',title:'不绑定模型，把共同脉络留给每一位协作者。',lead:'GrowthMap 不是黑盒 Agent 管理器，也不是云端项目替身。它是 Windows 本机优先的共享工作区：人类与任意 Agent 在同一份可读脉络上推进。',items:['Tree 与 Graph 同时呈现层级与关系。','Revision 与 atomic changes 让每一步都可追溯。','Context packet 带走目标、限制与现况。','History、diff、undo 与 readback 让实现回到地图。']},agents:{eyebrow:'TREE · GRAPH · BRANCH · NODE',title:'看见一条分支如何长成成果。',lead:'切换 Tree 与 Graph 视图，模拟人类与 Agent 在同一张地图上接力：读取脉络、提出原子变更、读回实现。',tree:'Tree 视图',graph:'Graph 视图',human:'人类校正',agent:'Agent 变更',readback:'实现读回',caption:'交互示意；不会写入数据或调用模型。'},download:{eyebrow:'下载',title:'下载 GrowthMap',lead:'目前提供 Windows x64 桌面版，可立即下载安装。',verify:'如何验证 hash'},pricing:{eyebrow:'LICENSE',title:'简单的个人授权。',first:'前 50 名',after:'之后为 US$29',terms:['个人永久授权','2 台个人设备','不限项目数量'],notice:'Early 与 Standard 可在 Whop 购买；完成购买后可在 GrowthMap License Experience 获取激活码。',demo:'查看授权与购买'},buy:{eyebrow:'购买授权',title:'选择 Free 或 GrowthMap Personal。',lead:'Free 永久可用且包含全部核心功能；Personal 增加不限启用项目与两台个人设备。',early:'购买 Early — US$10',standard:'购买 Standard — US$29',notice:'在 Whop 完成购买后，于 GrowthMap License Experience 获取激活码，再在 Windows 桌面版激活。'},order:{eyebrow:'订单状态',title:'等待授权服务确认。',lead:'本页网址参数仅供显示参考，不能证明付款或授权资格。',verification:'付款与履约由服务器端 License Authority 验证；确认前不会交付授权。',hint:'如果你刚从 Whop 返回，请保留订单资料并稍后重试。',support:'联系支持',retry:'返回购买页'}},
en:{home:{eyebrow:'LOCAL-FIRST PROJECT GROWTH',title:'Let projects grow from ideas into verifiable outcomes.',lead:'GrowthMap is a shared project-growth workspace for people and any AI agent. Keep nodes, branches, implementation, and evidence on one readable map.',map:'See the collaboration map',docs:'Read the docs'},product:{eyebrow:'AI-NEUTRAL PRODUCT',title:'Keep shared context—not allegiance to one model.',lead:'GrowthMap is neither a black-box agent manager nor a cloud replacement for your project. It is a Windows local-first shared workspace where people and arbitrary agents advance through the same readable context.',items:['Tree and Graph reveal hierarchy and relationships together.','Revisions and atomic changes make each step traceable.','Context packets carry goals, constraints, and current state.','History, diff, undo, and readback return implementation to the map.']},agents:{eyebrow:'TREE · GRAPH · BRANCH · NODE',title:'Watch a branch grow into an outcome.',lead:'Switch between Tree and Graph views to explore a simulation: people and agents read context, propose atomic changes, and read implementation back into one map.',tree:'Tree view',graph:'Graph view',human:'Human correction',agent:'Agent change',readback:'Implementation readback',caption:'Interactive illustration only; it writes no data and calls no model.'},download:{eyebrow:'DOWNLOAD',title:'Download GrowthMap',lead:'GrowthMap is available now as a Windows x64 desktop application.',verify:'How to verify the hash'},pricing:{eyebrow:'LICENSE',title:'A simple personal license.',first:'First 50',after:'Then US$29',terms:['Perpetual personal license','2 personal devices','No project limit'],notice:'Early and Standard are available on Whop; after purchase, get your activation key in the GrowthMap License Experience.',demo:'View licensing and purchase'},buy:{eyebrow:'PURCHASE',title:'Choose Free or GrowthMap Personal.',lead:'Free is available forever with every core feature; Personal adds unlimited active projects and two personal devices.',early:'Buy Early — US$10',standard:'Buy Standard — US$29',notice:'After purchasing on Whop, open the GrowthMap License Experience for your activation key, then activate in the Windows desktop app.'},order:{eyebrow:'ORDER STATUS',title:'Awaiting License Authority verification.',lead:'URL query parameters on this page are display hints only; they never prove payment or entitlement.',verification:'Payment and fulfillment are verified server-side by the License Authority. No license is delivered before verification.',hint:'If you just returned from Whop, keep your order details and try again shortly.',support:'Contact support',retry:'Return to purchase page'}}} satisfies Record<Locale,CoreCatalog>;
