import type {Locale} from './i18n';
export type ProofItem={title:string;body:string;status?:string;evidence?:string};
export type ProofSection={eyebrow:string;title:string;lead:string;sections:{title:string;items:ProofItem[]}[]};
export const homeProof:Record<Locale,ProofSection>={
'zh-TW':{eyebrow:'10 秒定位',title:'它補上 Git、待辦工具與 AI 對話之間的缺口。',lead:'當聊天、文件、issue、程式碼和 AI 對話開始讓你忘記「為什麼做到這裡」，GrowthMap 把它們重新連回一張可讀、可驗證、由你掌控的專案地圖。',sections:[{title:'GrowthMap 不是什麼',items:[{title:'不是取代 Git',body:'Git 保存程式碼與版本；GrowthMap 保存為何做、接下來做什麼、誰做過，以及結果如何。'},{title:'不只是待辦工具',body:'Task 只是節點之一；Decision、Risk、Question、Resource 與 Note 也是一級資訊。'},{title:'不是把專案交給 AI',body:'你可以完全不用 Agent。接入 Agent 時，它也只能在被授權的節點與範圍內讀取、提案或寫入。'},{title:'不綁模型或 Agent',body:'共同脈絡與協作規則屬於專案；更換工具時，不必重新拼湊專案記憶。'}]}]},
'zh-CN':{eyebrow:'10 秒定位',title:'它补上 Git、待办工具与 AI 对话之间的缺口。',lead:'当聊天、文档、issue、代码和 AI 对话开始让你忘记“为什么做到这里”，GrowthMap 把它们重新连回一张可读、可验证、由你掌控的项目地图。',sections:[{title:'GrowthMap 不是什么',items:[{title:'不是取代 Git',body:'Git 保存代码与版本；GrowthMap 保存为什么做、接下来做什么、谁做过，以及结果如何。'},{title:'不只是待办工具',body:'Task 只是节点之一；Decision、Risk、Question、Resource 与 Note 也是一级信息。'},{title:'不是把项目交给 AI',body:'你可以完全不用 Agent。接入 Agent 时，它也只能在被授权的节点与范围内读取、提案或写入。'},{title:'不绑定模型或 Agent',body:'共同脉络与协作规则属于项目；更换工具时，不必重新拼凑项目记忆。'}]}]},
en:{eyebrow:'THE 10-SECOND POSITION',title:'It fills the gap between Git, task tools, and AI conversations.',lead:'When chats, docs, issues, code, and AI conversations make you forget why the project reached this point, GrowthMap reconnects them in one readable, verifiable project map you control.',sections:[{title:'What GrowthMap is not',items:[{title:'Not a replacement for Git',body:'Git preserves code and versions. GrowthMap preserves why work exists, what comes next, who worked on it, and what happened.'},{title:'Not merely a task list',body:'Task is only one node type. Decision, Risk, Question, Resource, and Note are first-class information too.'},{title:'Not handing the project to AI',body:'You can use GrowthMap without any Agent. When connected, an Agent can only read, propose, or write inside its granted scope.'},{title:'Not tied to one model or Agent',body:'Shared context and collaboration rules belong to the project, so changing tools does not mean rebuilding project memory.'}]}]}}
;
export const caseStudy:Record<Locale,ProofSection>={
'zh-TW':{eyebrow:'真實案例 / WINDOWS RELEASE',title:'一條發布分支，如何變成可驗證的安裝程式。',lead:'以下是目前公開 Windows Personal v1 release 的可核對證據鏈；下載前仍應以目前 release 的檔名、bytes 與 SHA-256 為準。',sections:[{title:'從節點到成果',items:[{title:'01 · 目標',body:'建立 GrowthMap v0.1 Windows x64 安裝程式，並保留可回滾、可核對的發布證據。',evidence:'Release goal'},{title:'02 · 分支',body:'分開評估 unsigned installer、code signing 與 activation design；不把尚未具備的 production 能力混進候選版。',evidence:'Release branches'},{title:'03 · 決策',body:'採用人工 unsigned 發行模式，不購買或偽裝受信任簽章；公開下載與 Whop 購買現已提供。',evidence:'Human release decision'},{title:'04 · 風險',body:'未簽署安裝程式可能顯示 Unknown Publisher，並可能觸發 SmartScreen；網站明確揭露而不把 hash 冒充簽章。',evidence:'Risk record'},{title:'05 · Renderer responsiveness',body:'每個節點的 subtree width 只計算一次；僅變更選取時不重跑 structural layout，並保留 focus、graph 與 relation 行為。',evidence:'Renderer acceptance'},{title:'06 · 實作',body:'目前 installer source 對應 commit 8d06f64e01d86f95b1ce361467c68f310718e991；production-personal workflow all gates pass；Security P0/P1/P2 為 0/0/0，focused 6/6、frontend 236/236、stable modules 20/20 通過。',evidence:'Commit + CI'},{title:'07 · 讀回',body:'目前 GrowthMap-Setup-0.1.0-desktop.2-x64.exe 為 145384654 bytes，SHA-256 為 1b2075734ed82d2bbec60cdddf65c70d88bdfec5d0a602b0e307324b8a962110；installer 仍未簽章，更新採手動覆蓋。',evidence:'Artifact + remaining gate'}]}]},
'zh-CN':{eyebrow:'真实案例 / WINDOWS RELEASE',title:'一条发布分支，如何变成可验证的安装程序。',lead:'以下是当前公开 Windows Personal v1 release 的可核对证据链；下载前仍应以当前 release 的文件名、bytes 与 SHA-256 为准。',sections:[{title:'从节点到成果',items:[{title:'01 · 目标',body:'建立 GrowthMap v0.1 Windows x64 安装程序，并保留可回滚、可核对的发布证据。',evidence:'Release goal'},{title:'02 · 分支',body:'分别评估 unsigned installer、code signing 与 activation design，不把尚未具备的生产能力混进候选版。',evidence:'Release branches'},{title:'03 · 决策',body:'采用人工 unsigned 发布模式，不购买或伪装受信任签名；公开下载与 Whop 购买现已提供。',evidence:'Human release decision'},{title:'04 · 风险',body:'未签名安装程序可能显示 Unknown Publisher，并可能触发 SmartScreen；网站明确披露，不把 hash 冒充签名。',evidence:'Risk record'},{title:'05 · Renderer responsiveness',body:'每个节点的 subtree width 只计算一次；仅变更选择时不重跑 structural layout，并保留 focus、graph 与 relation 行为。',evidence:'Renderer acceptance'},{title:'06 · 实现',body:'当前 installer source 对应 commit 8d06f64e01d86f95b1ce361467c68f310718e991；production-personal workflow 全部门禁通过；Security P0/P1/P2 为 0/0/0，focused 6/6、frontend 236/236、stable modules 20/20 通过。',evidence:'Commit + CI'},{title:'07 · 读回',body:'当前 GrowthMap-Setup-0.1.0-desktop.2-x64.exe 为 145384654 bytes，SHA-256 为 1b2075734ed82d2bbec60cdddf65c70d88bdfec5d0a602b0e307324b8a962110；installer 仍未签名，更新采用手动覆盖。',evidence:'Artifact + remaining gate'}]}]},
en:{eyebrow:'REAL CASE / WINDOWS RELEASE',title:'How one release branch became a verifiable installer.',lead:'This is the checkable evidence chain for the current public Windows Personal v1 release. Before downloading, treat the current release filename, byte size, and SHA-256 as authoritative.',sections:[{title:'From node to outcome',items:[{title:'01 · Goal',body:'Produce a GrowthMap v0.1 Windows x64 installer with evidence that can be checked and rolled back.',evidence:'Release goal'},{title:'02 · Branches',body:'Evaluate unsigned installer, code signing, and activation design separately; do not smuggle unavailable production capability into the candidate.',evidence:'Release branches'},{title:'03 · Decision',body:'Use a manual unsigned-release mode without buying or impersonating trusted signing. Public download and Whop purchases are now available.',evidence:'Human release decision'},{title:'04 · Risk',body:'An unsigned installer may show Unknown Publisher and trigger SmartScreen. The site discloses this and never presents a hash as a signature.',evidence:'Risk record'},{title:'05 · Renderer responsiveness',body:'Each node’s subtree width is computed once; selection-only changes do not rerun structural layout, preserving focus, graph, and relation behavior.',evidence:'Renderer acceptance'},{title:'06 · Implementation',body:'The current installer source maps to commit 8d06f64e01d86f95b1ce361467c68f310718e991; production-personal workflow gates all passed: Security P0/P1/P2 0/0/0; focused 6/6, frontend 236/236, and stable modules 20/20.',evidence:'Commit + CI'},{title:'07 · Readback',body:'The current GrowthMap-Setup-0.1.0-desktop.2-x64.exe is 145384654 bytes with SHA-256 1b2075734ed82d2bbec60cdddf65c70d88bdfec5d0a602b0e307324b8a962110. The installer remains unsigned and updates are manual overwrite installs.',evidence:'Artifact + remaining gate'}]}]}}
;
