import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const source=fs.readFileSync(path.resolve(__dirname,"../components/AgentPortPanel.tsx"),"utf8");
test("Agent Access pending state locks captured and shared grant configuration",()=>{for(const marker of ['disabled={pending} aria-label="grant label"','disabled={pending} aria-label="agent identity"','aria-label="grant permission" disabled={pending}','disabled={pending} aria-label="expiry hours (hours)"','disabled={pending} onClick={()=>void create()}'])assert.match(source,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});
test("Agent Port async settlements have mount project generation fencing and synchronous latches",()=>{for(const marker of ['mountedRef','requestRef','projectRef','current(ticket,project)','busyRef.current=owner','actionRef.current=owner','if(busyRef.current||actionRef.current||pending)return'])assert.ok(source.includes(marker),marker);assert.match(source,/if\(!current\(ticket,project\)\)return/);});
test("localized safe status wording and primary error preservation remain",()=>{for(const marker of ['正在確認 Agent Access 狀態','正在确认 Agent Access 状态','Checking Agent Access status','Enabled and confirmed by the local service','Confirmed disabled','Repair required:','Status unavailable;','reloadPreserving(primary)'])assert.ok(source.includes(marker),marker);});
test("workspace master and advanced project grant copy are unambiguous and all modes are three-locale",()=>{for(const marker of ['工作區主授權','工作区主授权','workspace master','進階：建立專案／任務範圍的有限期 grant','高级：创建项目／任务范围的限时 grant','Advanced: create project/task-scoped expiring grant','直接協作（建議）','直接协作（推荐）','Direct collaboration (recommended)','唯讀','只读','Read only','先審閱','先审阅','Review first'])assert.ok(source.includes(marker),marker);assert.doesNotMatch(source,/project-wide/);assert.match(source,/legacyPermission=permission==="read_only"\?"read":permission==="review_first"\?"propose":"write"/);});

test("stale owners cannot unlock a newer project operation",()=>{assert.match(source,/const owner=Symbol\("agent-access-master"\)/);assert.match(source,/if\(busyRef\.current===owner\)busyRef\.current=null/);assert.match(source,/const owner=Symbol\("agent-(?:access|port)-action"\)/);assert.match(source,/if\(actionRef\.current===owner\)actionRef\.current=null/);assert.doesNotMatch(source,/finally\{actionRef\.current=null/);assert.doesNotMatch(source,/finally\{busyRef\.current=null/);});
test("retry status is synchronously single-flight, cross-operation owned, and fenced",()=>{assert.match(source,/const retryStatus=async\(\)=>manual\(async\(\)=>\{await reload\(\);\}\)/);assert.match(source,/data-testid="agent-access-retry"[^>]*onClick=\{\(\)=>void retryStatus\(\)\}/);assert.doesNotMatch(source,/agent-access-retry"[^>]*reload\(\)\.catch/);assert.match(source,/const manual=[\s\S]*if\(busyRef\.current\|\|actionRef\.current\|\|pending\)return[\s\S]*current\(ticket,project\)[\s\S]*actionRef\.current===owner/);});
test("project-owned render projection hides stale token grants activity access and message",()=>{for(const marker of ['pendingOwner?.project===projectId','projectCurrent=stateProject===projectId','visibleAccess=projectCurrent?access:null','visibleGrants=projectCurrent?grants:[]','visibleToken=projectCurrent?token:""','visibleMessage=projectCurrent?message:""','setToken("")','setGrants([])','setAccess(null)','setMessage("")'])assert.ok(source.includes(marker),marker);assert.doesNotMatch(source,/\{token&&|\{grants\.map|\{activity\.(?:events|proposals|readbacks)\.map/)});
