import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const source=fs.readFileSync(path.resolve(__dirname,"../components/AgentPortPanel.tsx"),"utf8");

test("Agent Access pending state locks captured and shared grant configuration",()=>{for(const marker of ['disabled={pending} aria-label="grant label"','disabled={pending} aria-label="agent identity"','aria-label="grant permission" disabled={pending}','disabled={pending} aria-label="expiry hours (hours)"','disabled={pending} onClick={()=>void create()}'])assert.match(source,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("workspace-global and project-local reloads have independent generation fences",()=>{for(const marker of ["mountedRef","localRequestRef","globalRequestRef","projectRef","localCurrent(owner.generation,project)","globalCurrent(ticket)","busyRef.current=owner","globalActionRef.current=owner","Promise.allSettled([d.agentPort.list(project),d.agentPort.activity(project)])","window.growthmapDesktop!.agentAccess.status()"] )assert.ok(source.includes(marker),marker);assert.doesNotMatch(source,/Promise\.allSettled\(\[d\.agentPort\.list\(project\),d\.agentPort\.activity\(project\),d\.agentAccess\.status\(\)\]\)/);});

test("localized status and split refresh warnings remain truthful",()=>{for(const marker of ['正在確認 Agent Access 狀態','正在确认 Agent Access 状态','Checking Agent Access status','Enabled and confirmed by the local service','Confirmed disabled','Repair required:','Status unavailable;','專案資料重新整理失敗；Agent Access 狀態不受影響。','Access change succeeded, but project panel refresh failed.'])assert.ok(source.includes(marker),marker);});

test("workspace master and advanced project grant copy are unambiguous and all modes are three-locale",()=>{for(const marker of ['工作區主授權','工作区主授权','workspace master','進階：建立專案／任務範圍的有限期 grant','高级：创建项目／任务范围的限时 grant','Advanced: create project/task-scoped expiring grant','直接協作（建議）','直接协作（推荐）','Direct collaboration (recommended)','唯讀','只读','Read only','先審閱','先审阅','Review first'])assert.ok(source.includes(marker),marker);assert.doesNotMatch(source,/project-wide/);assert.match(source,/legacyPermission=permission==="read_only"\?"read":permission==="review_first"\?"propose":"write"/);});

test("operation owners only release their own split latches",()=>{assert.match(source,/const owner=Symbol\("agent-access-master"\)/);assert.match(source,/if\(busyRef\.current===owner\)\{busyRef\.current=null;if\(mountedRef\.current\)setPending\(false\);\}/);assert.match(source,/if\(globalActionRef\.current===latch\)globalActionRef\.current=null/);assert.match(source,/if\(localActionRef\.current===latch\)localActionRef\.current=null/);assert.doesNotMatch(source,/finally\{(?:globalActionRef|localActionRef|busyRef)\.current=null/);});

test("retry status has visible localized feedback and synchronous single-flight",()=>{for(const marker of ['正在重新檢查 Agent Access 狀態…','正在重新检查 Agent Access 状态…','Rechecking Agent Access status…','Symbol("agent-access-status-retry")','operation=captureProjectOperation(projectId,localRequestRef.current)','if(!ok&&operationCurrent(operation))setMessage','setStatusRetrying(true)','if(globalActionRef.current===owner){globalActionRef.current=null;if(mountedRef.current)setStatusRetrying(false);}','disabled={pending||statusRetrying}'])assert.ok(source.includes(marker),marker);assert.match(source,/const retryStatus=async\(\)=>\{if\(busyRef\.current\|\|globalActionRef\.current\|\|localActionRef\.current\|\|pending\|\|statusRetrying\)return/);assert.match(source,/data-testid="agent-access-retry"[^>]*onClick=\{\(\)=>void retryStatus\(\)\}/);});

test("project switching clears only the local latch and projection, never global access ownership",()=>{for(const marker of ['localActionRef.current=null','setToken("")','setGrants([])','setActivity({proposals:[],events:[],readbacks:[]})','setMessage("")','void reloadLocal()'])assert.ok(source.includes(marker),marker);assert.match(source,/if\(projectRef\.current!==projectId\)\{projectRef\.current=projectId;localRequestRef\.current\+\+;localActionRef\.current=null;\}/);assert.doesNotMatch(source,/setAccess\(null\)/);assert.doesNotMatch(source,/visibleAccess|stateProject|projectCurrent/);assert.match(source,/access\?\.state==="disabled"\?u\("啟用 Agent Access"/);assert.match(source,/access\?\.state==="unknown"/);});
