/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import {createAIPanelController,confirmationText,diagnosticMessage,MAX_MODEL_NAME,resetAIPanelProfileCacheForTests,sameProviderIdentity,validateModelName,type AIProviderIdentity} from "./ai-panel-controller";
test.beforeEach(()=>resetAIPanelProfileCacheForTests());
const id:AIProviderIdentity={providerId:"profile-abcdefgh-EXACT",providerType:"custom",model:"model-x",revision:123456789,selectionRevision:7};
const profile=(overrides={})=>({id:id.providerId,name:"Named",provider_type:id.providerType,endpoint:"",auth_type:"env",secret_env_key:"GROWTHMAP_LLM_KEY_X",model_name:id.model,capabilities:[],cost_level:"paid",enabled:true,created_at:"",updated_at:"",revision:id.revision,secret_change_pending:false,credential_status:"ready" as const,...overrides});
const deferred=<T>()=>{let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const harness=()=>{let current:AIProviderIdentity|null=id,confirmed=true,confirmSeen="",copied="",invalidated=0,saved:any=null,now=100;const lists:any[]=[];const saves:any[]=[];const tests:any[]=[];const c=createAIPanelController({listProviders:()=>{const d=deferred<any[]>();lists.push(d);return d.promise},updateModel:()=>{const d=deferred<any>();saves.push(d);return d.promise},testConnection:()=>{const d=deferred<any>();tests.push(d);return d.promise},confirm:s=>(confirmSeen=s,confirmed),copy:async s=>{if(s==="fail")throw Error();copied=s},now:()=>now,locale:()=>"en",currentIdentity:()=>current,onSaved:p=>saved=p,onInvalidate:()=>invalidated++});return{c,lists,saves,tests,get current(){return current},set current(v){current=v},set confirmed(v:boolean){confirmed=v},get confirmSeen(){return confirmSeen},get copied(){return copied},get saved(){return saved},get invalidated(){return invalidated},tick:()=>now+=25}};
test("validation, exact identity and complete confirmation",()=>{assert.deepEqual(validateModelName(" x "),{ok:true,value:"x"});assert.deepEqual(validateModelName(" "),{ok:false,reason:"empty"});assert.equal(validateModelName("x".repeat(MAX_MODEL_NAME+1)).ok,false);for(const x of [{...id,providerId:"other"},{...id,providerType:"mock" as const},{...id,model:"other"},{...id,revision:2,selectionRevision:2}])assert.equal(sameProviderIdentity(id,x),false);const text=confirmationText("en","Expand",id,"Named");for(const exact of [id.providerId,id.providerType,id.model,String(id.revision)])assert.ok(text.includes(exact));});
test("list retry overlap: late success/error, filter and empty",async()=>{const h=harness();const a=h.c.list(),b=h.c.list();h.lists[1].resolve([profile(),profile({id:"off",enabled:false})]);await b;assert.deepEqual(h.c.getSnapshot().profiles.map(x=>x.id),[id.providerId]);h.lists[0].reject(Error());await a;assert.equal(h.c.getSnapshot().profileState,"ready");const c=h.c.list();h.lists[2].resolve([]);await c;assert.equal(h.c.getSnapshot().profiles.length,0);});
test("model save owns exact identity, rejects, overlaps blocked, A-B-A and unmount",async()=>{const h=harness();h.c.getSnapshot().profiles.push(profile());const a=h.c.save("new");await h.c.save("overlap");assert.equal(h.saves.length,1);h.current={...id,providerId:"B"};h.c.invalidate();h.current=id;h.saves[0].resolve(profile({model_name:"new",revision:124}));await a;assert.equal(h.saved,null);const b=h.c.save("new");h.saves[1].reject(Error());await b;assert.match(h.c.getSnapshot().modelError||"",/previous/);const u=h.c.save("next");h.c.destroy();h.saves[2].resolve(profile({model_name:"next"}));await u;assert.notEqual((h.saved as any)?.model_name,"next");});
test("strict effect replay reactivates controller and publishes second list",async()=>{const h=harness();const first=h.c.list();h.c.suspend();h.lists[0].resolve([profile()]);await first;assert.equal(h.c.getSnapshot().profiles.length,0);h.c.activate();const second=h.c.list();h.lists[1].resolve([profile()]);await second;assert.equal(h.c.getSnapshot().profileState,"ready");assert.equal(h.c.getSnapshot().profiles.length,1);});
test("a remounted panel renders the last verified profile while refreshing in background",async()=>{const first=harness();const load=first.c.list();first.lists[0].resolve([profile()]);await load;first.c.suspend();const second=harness();assert.equal(second.c.getSnapshot().profileState,"ready");assert.deepEqual(second.c.getSnapshot().profiles.map(x=>x.id),[id.providerId]);const refresh=second.c.list();assert.equal(second.c.getSnapshot().profileState,"ready");assert.equal(second.c.getSnapshot().profiles.length,1);second.lists[0].resolve([profile({model_name:"new"})]);await refresh;assert.equal(second.c.getSnapshot().profiles[0].model_name,"new")});
test("generate full confirmation/cancel/mock and exact tuple dispatch",()=>{const h=harness();let calls=0;const args={actionLabel:"Deepen",profileName:"Named",identity:id,savedIdentity:()=>id,dispatch:()=>calls++};h.confirmed=false;assert.equal(h.c.generate(args),false);assert.equal(calls,0);assert.ok(h.confirmSeen.includes(id.providerId)&&h.confirmSeen.includes(String(id.revision)));h.confirmed=true;assert.equal(h.c.generate(args),true);assert.equal(calls,1);h.current={...id,revision:2,selectionRevision:2};assert.equal(h.c.generate(args),false);assert.match(h.c.getSnapshot().generationError||"",/changed/);h.current={...id,providerType:"mock"};assert.equal(h.c.generate({...args,identity:h.current,savedIdentity:()=>h.current}),true);assert.equal(h.c.getSnapshot().generationError,null);});
test("test overlap, external invalidation, elapsed and no stale result/error",async()=>{const h=harness();const a=h.c.test();await h.c.test();assert.equal(h.tests.length,1);h.tick();h.c.invalidate();h.tests[0].resolve({code:"OK",request_id:"0123456789abcdef"});await a;assert.equal(h.c.getSnapshot().test,null);const b=h.c.test();h.tick();h.tests[1].reject({code:"LLM_TIMEOUT",status:504,requestId:"fedcba9876543210"});await b;assert.equal(h.c.getSnapshot().test?.elapsed,25);assert.equal(h.c.getSnapshot().test?.code,"LLM_TIMEOUT");});
test("copy success/failure and localized closed diagnostics",async()=>{const h=harness();await h.c.copy("abc");assert.equal(h.copied,"abc");assert.match(h.c.getSnapshot().copyMessage||"",/copied/i);await h.c.copy("fail");assert.match(h.c.getSnapshot().copyMessage||"",/Could not/);for(const l of ["en","zh-TW","zh-CN"] as const)assert.doesNotMatch(diagnosticMessage(l,"raw attacker"),/attacker/)});
test("NodeAI imports and constructs the injected controller (wiring guard)",()=>{const source=fs.readFileSync(new URL("../components/NodePanel/NodeAI.tsx",import.meta.url),"utf8");assert.match(source,/createAIPanelController\(/);assert.match(source,/useSyncExternalStore\(controller\.subscribe/);assert.doesNotMatch(source,/new LatestAsync|new MonotonicOwner/)});
test("operation invalidation never cancels delayed profile-list ownership",async()=>{const h=harness();const pending=h.c.list();h.c.invalidateOperations();h.lists[0].resolve([profile()]);await pending;assert.equal(h.c.getSnapshot().profileState,"ready");assert.equal(h.c.getSnapshot().profiles.length,1)});
