import test from "node:test";
import assert from "node:assert/strict";
import { api, MalformedAuthoritativeResponseError, resetRevisionCacheForTests } from "./api";
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json"}});
const project=(r:number)=>({id:"p",revision:r,root_node_id:"n"});
const edges=(target=3,sibling=5)=>[
 {id:"t",project_id:"p",from_node_id:"a",to_node_id:"b",relation_type:"child_of",weight:1,note:"",is_mainline:false,created_at:"x",revision:target},
 {id:"s",project_id:"p",from_node_id:"a",to_node_id:"c",relation_type:"child_of",weight:1,note:"",is_mainline:true,created_at:"x",revision:sibling},
];
type PromotionResult=ReturnType<typeof result>;
const result=(target=4,sibling=6,extra:Record<string,unknown>={})=>({ok:true,project_id:"p",edge_id:"t",parent_node_id:"a",child_node_id:"b",project_revision:11,target_revision:target,touched_sibling_revisions:{s:sibling} as Record<string,number>,touched_node_revisions:{a:8,b:2,c:2},...extra});
async function seed(){await api.listProjects();await api.listEdges("p")}
test("promotion owns exact target+sibling CAS and sequential call consumes authoritative revisions",async()=>{resetRevisionCacheForTests();const bodies:unknown[]=[];let writes=0;globalThis.fetch=async(input,init)=>{const u=String(input);if(u.endsWith("/projects"))return json(project(10));if(u.endsWith("/projects/p/edges"))return json(edges());bodies.push(JSON.parse(String(init?.body)));writes++;return json(writes===1?result():{...result(5,6),project_revision:12,touched_sibling_revisions:{}})};await seed();await api.promoteMainline("t");await api.promoteMainline("t");assert.deepEqual(bodies,[{expected_project_revision:10,expected_revision:3,expected_sibling_revisions:{s:5}},{expected_project_revision:11,expected_revision:4,expected_sibling_revisions:{}}])});
test("409 leaves promotion cache unchanged",async()=>{resetRevisionCacheForTests();let writes=0;globalThis.fetch=async(input)=>{const u=String(input);if(u.endsWith("/projects"))return json(project(10));if(u.endsWith("/projects/p/edges"))return json(edges());writes++;if(writes===1)return json({detail:{code:"REVISION_CONFLICT",message:"stale"}},409);return json(result())};await seed();await assert.rejects(api.promoteMainline("t"),/stale/);await api.promoteMainline("t")});
const mutations:Record<string,(value:PromotionResult)=>void>={missing:(x)=>{delete (x as Partial<PromotionResult>).touched_sibling_revisions},extra:(x)=>{x.touched_sibling_revisions.x=9},wrongId:(x)=>{x.edge_id="x"},wrongSibling:(x)=>{x.touched_sibling_revisions={x:6}}};
for(const [name,mutate] of Object.entries(mutations))test(`malformed ${name} fails closed and invalidates union`,async()=>{resetRevisionCacheForTests();globalThis.fetch=async(input)=>{const u=String(input);if(u.endsWith("/projects"))return json(project(10));if(u.endsWith("/projects/p/edges"))return json(edges());const x=result();mutate(x);return json(x)};await seed();await assert.rejects(api.promoteMainline("t"),MalformedAuthoritativeResponseError);await assert.rejects(api.promoteMainline("t"),/Target edge revision unavailable/)});
test("inflight cache mismatch invalidates full union",async()=>{resetRevisionCacheForTests();let release!:(r:Response)=>void;const pending=new Promise<Response>(r=>release=r);let reads=0;globalThis.fetch=async(input)=>{const u=String(input);if(u.endsWith("/projects"))return json(project(reads++?12:10));if(u.endsWith("/projects/p/edges"))return json(reads>1?edges(9,9):edges());return pending};await seed();const promote=api.promoteMainline("t");await new Promise(r=>setTimeout(r,0));await api.listProjects();await api.listEdges("p");release(json(result()));await promote;await assert.rejects(api.promoteMainline("t"),/Target edge revision unavailable/)});
