import test from "node:test";
import assert from "node:assert/strict";
import { AI_DIAGNOSTIC_STATUS, ApiError, api, parseAIError } from "./api";
const id="0123456789abcdef";
for(const [code,status] of Object.entries(AI_DIAGNOSTIC_STATUS))test(`accepts exact ${code}`,()=>{const x=parseAIError(status,JSON.stringify({detail:{code,message:"ignored safe server English",request_id:id}}));assert.equal(x.status,status);assert.equal(x.code,code);assert.equal(x.requestId,id);assert.doesNotMatch(x.message,/server English/);});
test("malformed diagnostics become internally consistent local invalid response",()=>{const invalid=["<html>secret</html>","[]",JSON.stringify({detail:"raw"}),JSON.stringify({detail:{code:"UNKNOWN",message:"secret",request_id:id}}),JSON.stringify({detail:{code:"LLM_TIMEOUT",message:"x",request_id:id,extra:1}}),JSON.stringify({detail:{code:"LLM_TIMEOUT",message:"x",request_id:"abc123"}}),JSON.stringify({detail:{code:"LLM_TIMEOUT",message:"x",request_id:id}}),JSON.stringify({detail:{code:"LLM_UPSTREAM_ERROR",message:"x\u0001",request_id:id}}),"é".repeat(1100)];for(const body of invalid){const x=parseAIError(400,body);assert.equal(x.status,502);assert.equal(x.code,"LLM_INVALID_RESPONSE");assert.equal(x.requestId,undefined);assert.doesNotMatch(x.message,/secret|raw/);}});
test("AI endpoint never publishes raw detail",async()=>{const original=globalThis.fetch;globalThis.fetch=(async()=>new Response(JSON.stringify({detail:{code:"LLM_AUTH_FAILED",message:"key=secret",request_id:id}}),{status:401})) as typeof fetch;try{await assert.rejects(api.testConnection("profile",1,1),(e:ApiError)=>e.code==="LLM_AUTH_FAILED"&&!e.message.includes("secret"));}finally{globalThis.fetch=original;}});
test("AI test client watchdog aborts a hung local request and returns fixed timeout",async()=>{const originalFetch=globalThis.fetch,originalTimer=globalThis.setTimeout,originalClear=globalThis.clearTimeout;let aborted=false,cleared=false;globalThis.setTimeout=((fn:TimerHandler)=>{queueMicrotask(()=>typeof fn==="function"&&fn());return 7 as unknown as ReturnType<typeof setTimeout>}) as unknown as typeof setTimeout;globalThis.clearTimeout=((id)=>{assert.equal(id,7);cleared=true}) as typeof clearTimeout;globalThis.fetch=((_input,init)=>new Promise((_resolve,reject)=>{init?.signal?.addEventListener("abort",()=>{aborted=true;reject(new DOMException("private path","AbortError"))},{once:true})})) as typeof fetch;try{await assert.rejects(api.testConnection("profile",1,1),(e:ApiError)=>e.status===504&&e.code==="LLM_TIMEOUT"&&e.requestId===undefined&&!e.message.includes("private"));assert.equal(aborted,true);assert.equal(cleared,true)}finally{globalThis.fetch=originalFetch;globalThis.setTimeout=originalTimer;globalThis.clearTimeout=originalClear}});
test("model update uses dedicated PATCH and exact body",async()=>{const original=globalThis.fetch;let seen:{url:string,init?:RequestInit}|null=null;globalThis.fetch=(async(url,init)=>{seen={url:String(url),init};return new Response(JSON.stringify({id:"p",name:"P",provider_type:"mock",endpoint:"",auth_type:"env",secret_env_key:"GROWTHMAP_LLM_KEY_DEFAULT",model_name:"new",capabilities:[],cost_level:"low",enabled:true,created_at:"1",updated_at:"2"}),{status:200});}) as typeof fetch;try{await api.updateProviderModel("p","new");assert.match(seen!.url,/\/providers\/p\/model$/);assert.equal(seen!.init?.method,"PATCH");assert.deepEqual(JSON.parse(String(seen!.init?.body)),{model_name:"new"});}finally{globalThis.fetch=original;}});
