/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";import assert from "node:assert/strict";import {applyCanonicalDelta} from "./canonical-sync";import type {GNode,Project} from "./types";import type {CanonicalDelta} from "./api";
const node=(id:string):GNode=>({id,project_id:"p",title:id,summary:"",node_type:"idea",status:"active",maturity:"seed",priority:0,confidence:.5,description:"",rules_text:"",constraints_text:"",examples_text:"",questions_text:"",decision_notes:"",workflow_status:"draft",tags:[],file_paths:[],created_by:"",last_edited_by:"",position_x:0,position_y:0,meta:{},content_blocks:[],created_at:"",updated_at:"",revision:1,branch_id:null,children:[]});
const project={id:"p",name:"p",description:"",goal:"",root_node_id:"root",status:"active",settings:{},created_at:"",updated_at:"",revision:1} as Project;
const make=():CanonicalDelta=>({schema:1,project_id:"p",since_revision:1,current_revision:2,complete:true,full_refresh_required:false,gap:false,changes:[{schema:1,kind:"graph",project_id:"p",revision:2,cursor:"c",hints:{}}],nodes:[node("child")],edges:[{id:"e",project_id:"p",from_node_id:"root",to_node_id:"child",relation_type:"child_of",weight:1,note:"",is_mainline:true,created_at:"",revision:1}],content_blocks:[],branches:[]});
const run=(d:CanonicalDelta,root=node("root"),selected:string|null=null)=>applyCanonicalDelta({projectId:"p",branchId:null,loadedRevision:1},{project,root,selectedId:selected},d);
test("safe create is pure and selected rebinds",()=>{const d=make(),root=node("root"),before=JSON.stringify(d);const got=run(d,root,"root");assert.equal(got?.root.children?.[0].id,"child");assert.equal(got?.selected?.id,"root");assert.equal(JSON.stringify(d),before);assert.equal(root.children?.length,0);});
test("existing scalar patch needs no topology edge and selected rebinds",()=>{const root=node("root"),child=node("child");root.children=[child];const d=make();d.nodes=[{...node("child"),title:"changed"}];d.edges=[];const got=run(d,root,"child");assert.equal(got?.root.children?.[0].title,"changed");assert.equal(got?.selected?.title,"changed");});
test("blocks sort exactly and reject atomically",()=>{const d=make();d.nodes=[];d.edges=[];d.content_blocks=[{id:"b2",node_id:"root",block_type:"x",content:{},order_index:2,revision:1},{id:"b1",node_id:"root",block_type:"x",content:{},order_index:1,revision:1}];assert.deepEqual(run(d)?.root.content_blocks.map(x=>x.id),["b1","b2"]);const bad=make();bad.content_blocks=[{id:"ok",node_id:"child",block_type:"x",content:{},order_index:1,revision:1},{id:"bad",node_id:"missing",block_type:"x",content:{},order_index:2,revision:1}];assert.equal(run(bad),null);});
test("topology and envelope failures close without partial state",()=>{for(const mutate of [(d:CanonicalDelta)=>d.edges[0].relation_type="related" as any,(d:CanonicalDelta)=>d.edges.push({...d.edges[0],id:"two",from_node_id:"x"}),(d:CanonicalDelta)=>d.edges[0].to_node_id="root",(d:CanonicalDelta)=>d.nodes[0].branch_id="b",(d:CanonicalDelta)=>d.gap=true,(d:CanonicalDelta)=>d.full_refresh_required=true,(d:CanonicalDelta)=>d.truncated=true,(d:CanonicalDelta)=>d.branches.push({} as any),(d:CanonicalDelta)=>d.since_revision=0]){const d=make();mutate(d);assert.equal(run(d),null);}});
