import {describe,it} from "node:test";
import assert from "node:assert/strict";
import {desktopErrorMessage,parseDesktopError} from "./desktop-error";
const t=(key:string)=>({"agentAccess.error.readOnly":"read-only: activate a license, contact support, or export","agentAccess.error.unavailable":"service unavailable","agentAccess.error.generic":"safe generic error"}[key]||key);
describe("structured desktop errors",()=>{
 it("parses only the IPC-safe envelope and never returns sidecar detail",()=>{const e=new Error('Error invoking remote method: GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"ENTITLEMENT_READ_ONLY","reason":"prior_installation_evidence","detail":"C:\\\\Users\\\\name token=secret"}');assert.deepEqual(parseDesktopError(e),{status:403,code:"ENTITLEMENT_READ_ONLY",reason:"prior_installation_evidence"});const message=desktopErrorMessage(e,t as never);assert.match(message,/read-only/);assert.doesNotMatch(message,/Users|token|secret/);});
 it("fails closed for unallowlisted codes, reasons, arbitrary text, and malformed envelopes",()=>{assert.equal(parseDesktopError(new Error('GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"EVIL_CODE","reason":"/private/path"}')),null);assert.deepEqual(parseDesktopError(new Error('GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"ENTITLEMENT_READ_ONLY","reason":"/private/path"}')),{status:403,code:"ENTITLEMENT_READ_ONLY",reason:null});assert.equal(desktopErrorMessage(new Error("helper stderr token=secret"),t as never),"safe generic error");});
 it("preserves the unavailable fallback and bounded support identifiers",()=>{const e=new Error('GROWTHMAP_DESKTOP_ERROR:{"status":0,"code":"SIDECAR_UNAVAILABLE","reason":null,"detail":null}');assert.match(desktopErrorMessage(e,t as never),/service unavailable.*SIDECAR_UNAVAILABLE/);});
 it("routes every Agent Port message-surface sidecar failure through the safe localized formatter",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/AgentPortPanel.tsx",import.meta.url),"utf8"));assert.match(source,/reload\(\)\.catch\(e=>setMessage\(desktopErrorMessage\(e,t\)\)\)/);assert.match(source,/agentPort\.create\([\s\S]*?catch\(e\)\{setMessage\(desktopErrorMessage\(e,t\)\)/);assert.match(source,/agentPort\.review\([\s\S]*?catch\(e\)\{setMessage\(desktopErrorMessage\(e,t\)\)/);assert.match(source,/agentAccess\.enable\([\s\S]*?catch\(e\)\{setMessage\(desktopErrorMessage\(e,t\)\)/);assert.match(source,/agentAccess\.regenerate\(\)\.then\(reload\)\.catch\(e=>setMessage\(desktopErrorMessage\(e,t\)\)\)/);assert.doesNotMatch(source,/setMessage\(String\(e\)\)|setMessage\([^\n]*\$\{String\(e\)\}/);});
});
