import {describe,it} from "node:test";
import assert from "node:assert/strict";
import {desktopErrorMessage,parseDesktopError} from "./desktop-error";
const t=(key:string)=>({"agentAccess.error.readOnly":"read-only: activate a license, contact support, or export","agentAccess.error.unavailable":"service unavailable","agentAccess.error.generic":"safe generic error"}[key]||key);
describe("structured desktop errors",()=>{
 it("parses only the IPC-safe envelope and never returns sidecar detail",()=>{const e=new Error('Error invoking remote method: GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"ENTITLEMENT_READ_ONLY","reason":"prior_installation_evidence","detail":"C:\\\\Users\\\\name token=secret"}');assert.deepEqual(parseDesktopError(e),{status:403,code:"ENTITLEMENT_READ_ONLY",reason:"prior_installation_evidence"});const message=desktopErrorMessage(e,t as never);assert.match(message,/read-only/);assert.doesNotMatch(message,/Users|token|secret/);});
 it("fails closed for unallowlisted codes, reasons, arbitrary text, and malformed envelopes",()=>{assert.equal(parseDesktopError(new Error('GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"EVIL_CODE","reason":"/private/path"}')),null);assert.deepEqual(parseDesktopError(new Error('GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"ENTITLEMENT_READ_ONLY","reason":"/private/path"}')),{status:403,code:"ENTITLEMENT_READ_ONLY",reason:null});assert.equal(desktopErrorMessage(new Error("helper stderr token=secret"),t as never),"safe generic error");});
 it("preserves the unavailable fallback and bounded support identifiers",()=>{const e=new Error('GROWTHMAP_DESKTOP_ERROR:{"status":0,"code":"SIDECAR_UNAVAILABLE","reason":null,"detail":null}');assert.match(desktopErrorMessage(e,t as never),/service unavailable.*SIDECAR_UNAVAILABLE/);});
 it("routes every Agent Port promise failure through the safe localized formatter",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/AgentPortPanel.tsx",import.meta.url),"utf8"));for(const call of ["agentPort.create","agentPort.review","agentPort.revoke","navigator.clipboard.writeText","agentAccess.regenerate","agentAccess.copy","agentAccess.download","agentAccess.test"])assert.ok(source.includes(call),`missing covered call ${call}`);assert.match(source,/const safeAccess=.*desktopErrorMessage\(e,t\)/);assert.match(source,/const manual=.*desktopErrorMessage\(e,t\)/);assert.match(source,/const revoke=.*manual/);assert.match(source,/const copyToken=.*manual/);assert.match(source,/finally\{if\(mountedRef\.current\)await reloadGlobal\(\);if\(operationCurrent\(localOwner\)\)\{const failures=await reloadLocal\(\);if\(!primary&&failures\.length\)setMessage\([\s\S]*?if\(busyRef\.current===owner\)\{busyRef\.current=null;if\(mountedRef\.current\)setPending\(false\);\}\}/);assert.doesNotMatch(source,/setMessage\(String\(e\)\)|setMessage\([^\n]*\$\{String\(e\)\}/);});
 it("gates loading, unknown, pending, and enabled-only controls without relying on color",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../components/AgentPortPanel.tsx",import.meta.url),"utf8"));for(const label of ["正在確認 Agent Access 狀態","正在确认 Agent Access 状态","Checking Agent Access status","需要修復","需要修复","Repair required","狀態無法確認","状态无法确认","Status unavailable","Retry status check","Disable Agent Access","Enable Agent Access"])assert.ok(source.includes(label),`missing localized Agent Access label: ${label}`);assert.match(source,/data-testid="agent-access-status" role="status" aria-live="polite"/);assert.match(source,/disabled=\{pending\|\|!accessKnown\|\|access\?\.state==="unknown"\}/);assert.match(source,/accessControlsDisabled=pending\|\|!agentAccessEnabled/);assert.match(source,/if\(busyRef\.current\|\|globalActionRef\.current\|\|localActionRef\.current\|\|pending\|\|!accessKnown\|\|access\?\.state==="unknown"\)return/);assert.match(source,/require backend-confirmed enabled access/);});
});
