/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test"; import assert from "node:assert/strict";
import { LiveSyncController } from "./live-sync-controller";
const tick=async()=>{for(let i=0;i<5;i++) await Promise.resolve();};
const defer=<T>()=>{let resolve!: (x:T)=>void, reject!: (e?:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const delta=(p="p", since=1, revision=2)=>({schema:1,project_id:p,since_revision:since,current_revision:revision,complete:true,full_refresh_required:false,gap:false,changes:[],nodes:[],edges:[],content_blocks:[],branches:[]} as any);
function env(){let visible:DocumentVisibilityState="visible", owner:any={projectId:"p",branchId:null,loadedRevision:1,epoch:1}, unsafe=false;let interval:()=>void=()=>{};const win=new Map<string,()=>void>(),doc=new Map<string,()=>void>();const scalars:any[]=[],deltas:any[]=[], sleeps:number[]=[],notices:boolean[]=[];let applies=0,refreshes=0, fetches=0;const scalarQueue:any[]=[],deltaQueue:any[]=[],fetchQueue:any[]=[];const d:any={getOwner:()=>owner,getRevision:(p:string)=>{scalars.push(p);return (scalarQueue.shift()??Promise.resolve({revision:1}));},getChanges:(p:string,s:number)=>{deltas.push([p,s]);return deltaQueue.shift()??Promise.resolve(delta(p,s,s+1));},applyDelta:()=>{applies++;return true;},refresh:async()=>{refreshes++;},isUnsafe:()=>unsafe,notice:(x:boolean)=>notices.push(x),fetch:async()=>{fetches++;return fetchQueue.shift()??{ok:true,status:403};},document:{get visibilityState(){return visible;},addEventListener:(k:string,f:()=>void)=>doc.set(k,f),removeEventListener:(k:string)=>doc.delete(k)},window:{addEventListener:(k:string,f:()=>void)=>win.set(k,f),removeEventListener:(k:string)=>win.delete(k)},setInterval:(f:()=>void)=>{interval=f;return 7;},clearInterval:()=>{interval=()=>{};},sleep:(n:number,signal:AbortSignal)=>{sleeps.push(n);return new Promise<void>((resolve,reject)=>signal.addEventListener("abort",()=>reject(Error("abort")),{once:true}));}};return {d,get c(){return new LiveSyncController(d);}, scalarQueue,deltaQueue,fetchQueue,scalars,deltas,sleeps,notices,win,doc,get visible(){return visible},set visible(x){visible=x},get owner(){return owner},set owner(x){owner=x},get unsafe(){return unsafe},set unsafe(x){unsafe=x},get applies(){return applies},set apply(v:boolean){d.applyDelta=()=>{applies++;return v;}},get refreshes(){return refreshes},callInterval:()=>interval(), get fetches(){return fetches}};
}
test("safe wake burst is one scalar/delta and one latest trailing pair",async()=>{const e=env(),c=e.c;const a=defer<{revision:number}>();e.scalarQueue.push(a.promise,Promise.resolve({revision:1}));c.mount();void c.wake();void c.wake();void c.wake();assert.equal(e.scalars.length,1);a.resolve({revision:2});await tick();assert.deepEqual(e.deltas,[["p",1]]);assert.equal(e.scalars.length,2);assert.equal(e.deltas.length,1);c.unmount();});
test("unchanged, no wake, and visible/hidden interval request counts",async()=>{const e=env(),c=e.c;c.mount();assert.equal(e.scalars.length,0);e.callInterval();await tick();assert.equal(e.scalars.length,1);assert.equal(e.deltas.length,0);e.visible="hidden";e.callInterval();await tick();assert.equal(e.scalars.length,1);c.unmount();});
test("focus and visibility repair only when visible",async()=>{const e=env(),c=e.c;c.mount();e.win.get("focus")!();await tick();assert.equal(e.scalars.length,1);e.visible="hidden";e.win.get("focus")!();await tick();assert.equal(e.scalars.length,1);e.visible="visible";e.doc.get("visibilitychange")!();await tick();assert.equal(e.scalars.length,2);c.unmount();});
test("owner ABA, branch, revision, and unsafe fences prevent stale settlement",async()=>{const e=env(),c=e.c,a=defer<{revision:number}>();e.scalarQueue.push(a.promise);c.mount();void c.wake();e.owner={projectId:"q",branchId:null,loadedRevision:1,epoch:2};e.owner={projectId:"p",branchId:null,loadedRevision:1,epoch:3};a.resolve({revision:2});await tick();assert.equal(e.deltas.length,0);assert.equal(e.applies,0);assert.equal(e.notices.length,0);const b=defer<{revision:number}>();e.scalarQueue.push(b.promise);void c.wake();e.unsafe=true;b.resolve({revision:2});await tick();assert.equal(e.deltas.length,0);assert.equal(e.notices.at(-1),true);c.unmount();});
test("apply outcome and manual refresh notices",async()=>{const e=env(),c=e.c;e.scalarQueue.push(Promise.resolve({revision:2}));e.apply=false;c.mount();await c.wake();assert.equal(e.notices.at(-1),true);e.d.refresh=async()=>{};await c.manualRefresh();assert.equal(e.notices.at(-1),false);e.d.refresh=async()=>{throw Error();};await c.manualRefresh();assert.equal(e.notices.at(-1),true);c.unmount();});
test("401 stops stream; teardown removes listeners and aborts reconnect sleep",async()=>{const e=env(),c=e.c;c.mount();await tick();assert.equal(e.fetches,1);assert.deepEqual(e.sleeps,[]);assert.equal(e.win.has("focus"),true);c.unmount();assert.equal(e.win.has("focus"),false);assert.equal(e.doc.has("visibilitychange"),false);});
test("bad stream retries with bounded exponential sleep",async()=>{const e=env(),c=e.c;e.fetchQueue.push({ok:false,status:500});c.mount();await tick();assert.deepEqual(e.sleeps,[1000]);c.unmount();});
test("SSE ready and selected canonical event wake; foreign event does not",async()=>{const e=env();const encoder=new TextEncoder();let sent=false;const body=new ReadableStream<Uint8Array>({pull(ctrl){if(!sent){sent=true;ctrl.enqueue(encoder.encode('event: ready\ndata: {"schema":1}\n\nevent: canonical-change\ndata: {"schema":1,"kind":"graph","project_id":"q","revision":2}\n\n'));ctrl.close();}}});e.fetchQueue.push({ok:true,status:200,body});const c=e.c;c.mount();await tick();assert.equal(e.scalars.length,1);c.unmount();});
