/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";import assert from "node:assert/strict";import {LiveSyncController} from "./live-sync-controller";
const micro=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};const deferred=<T>()=>{let resolve!:(x:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve};};const D=(s=1)=>({schema:1,project_id:"p",since_revision:s,current_revision:s+1,complete:true,full_refresh_required:false,gap:false,changes:[],nodes:[],edges:[],content_blocks:[],branches:[]} as any);
function fake(){let owner:any={projectId:"p",branchId:null,loadedRevision:1,epoch:1}, unsafe=false;const scalars:any[]=[],deltas:any[]=[],notices:boolean[]=[];const sq:any[]=[],dq:any[]=[],fq:any[]=[],sleepq:any[]=[];let fetches=0;const cancelled=0;const d:any={getOwner:()=>owner,getRevision:()=>{scalars.push(1);return sq.shift()??Promise.resolve({revision:1});},getChanges:(_p:string,s:number)=>{deltas.push(s);return dq.shift()??Promise.resolve(D(s));},applyDelta:()=>true,refresh:async()=>{},isUnsafe:()=>unsafe,notice:(x:boolean)=>notices.push(x),fetch:async()=>{fetches++;return fq.shift()??{ok:true,status:403};},document:{visibilityState:"visible",addEventListener:()=>{},removeEventListener:()=>{}},window:{addEventListener:()=>{},removeEventListener:()=>{}},setInterval:()=>1,clearInterval:()=>{},sleep:(n:number,signal:AbortSignal)=>{const z=deferred<void>();sleepq.push({n,z,signal});signal.addEventListener("abort",()=>z.resolve());return z.promise;}};return{d,get c(){return new LiveSyncController(d)},sq,dq,fq,sleepq,scalars,deltas,notices,get owner(){return owner},set owner(v){owner=v},get unsafe(){return unsafe},set unsafe(v){unsafe=v},get fetches(){return fetches},cancel:()=>cancelled,get cancelled(){return cancelled}};}
test("delta-pending burst uses exactly one latest trailing pair",async()=>{const e=fake(),c=e.c,dd=deferred<any>();e.sq.push(Promise.resolve({revision:2}),Promise.resolve({revision:3}));e.dq.push(dd.promise,Promise.resolve(D(2)));c.mount();void c.wake();await micro();void c.wake();void c.wake();assert.deepEqual(e.deltas,[1]);e.owner={...e.owner,loadedRevision:2,epoch:2};dd.resolve(D(1));await micro();assert.deepEqual(e.deltas,[1,2]);c.unmount();});
test("manual refresh late success/failure is owner epoch fenced",async()=>{const e=fake(),c=e.c,a=deferred<void>();e.d.refresh=()=>a.promise;const p=c.manualRefresh();e.owner={projectId:"q",branchId:null,loadedRevision:1,epoch:2};a.resolve();await p;assert.equal(e.notices.length,0);const b=deferred<void>();e.d.refresh=()=>b.promise;const q=c.manualRefresh();e.owner={projectId:"p",branchId:null,loadedRevision:1,epoch:3};b.resolve();await q;assert.equal(e.notices.length,0);});
test("backoff grows 1 2 4 to 30 seconds and successful stream resets",async()=>{const e=fake(),c=e.c;e.fq.push({ok:false,status:500},{ok:false,status:500},{ok:false,status:500});c.mount();await micro();for(const n of [1000,2000,4000]){assert.equal(e.sleepq.at(-1).n,n);e.sleepq.at(-1).z.resolve();await micro();}c.unmount();});
test("unmount aborts active stream reader and reconnect sleep with no later fetch",async()=>{const e=fake(),c=e.c;e.fq.push({ok:false,status:500});c.mount();await micro();assert.equal(e.sleepq.length,1);c.unmount();await micro();assert.equal(e.fetches,1);assert.equal(e.sleepq[0].signal.aborted,true);});
test("selected canonical event wakes and foreign does not",async()=>{const e=fake();const enc=new TextEncoder();const body=new ReadableStream<Uint8Array>({start(x){x.enqueue(enc.encode('event: canonical-change\ndata: {"schema":1,"kind":"graph","project_id":"p","revision":2}\n\nevent: canonical-change\ndata: {"schema":1,"kind":"graph","project_id":"q","revision":2}\n\n'));x.close();}});e.fq.push({ok:true,status:200,body});const c=e.c;c.mount();await micro();assert.equal(e.scalars.length,1);c.unmount();});
test("invalid ready is ignored",async()=>{const e=fake();const body=new ReadableStream<Uint8Array>({start(x){x.enqueue(new TextEncoder().encode('event: ready\ndata: {"schema":2}\n\n'));x.close();}});e.fq.push({ok:true,status:200,body});const c=e.c;c.mount();await micro();assert.equal(e.scalars.length,0);c.unmount();});
test("late delta branch revision epoch and unsafe fences",async()=>{for(const change of [(e:any)=>e.owner={...e.owner,branchId:"b",epoch:2},(e:any)=>e.owner={...e.owner,loadedRevision:2,epoch:2},(e:any)=>e.owner={...e.owner,epoch:2},(e:any)=>e.unsafe=true]){const e=fake(),c=e.c,z=deferred<any>();e.sq.push(Promise.resolve({revision:2}));e.dq.push(z.promise);c.mount();void c.wake();await micro();change(e);z.resolve(D());await micro();assert.equal(e.notices.at(-1),true);c.unmount();}});
