'use strict';
const fs=require('node:fs'),net=require('node:net'),os=require('node:os'),path=require('node:path'),{spawn,spawnSync}=require('node:child_process'),{chromium}=require('playwright-core');
const {launchArgs,timeoutDiagnostic,parseDevToolsWebSocket,assertE2EPackage,assertReadbackText,activateProjectForAgentPort}=require('./renderer-e2e-support');
const importedProjectId='11111111-1111-4111-8111-111111111111',importedRootId='22222222-2222-4222-8222-222222222222';
if(process.platform!=='win32')throw new Error('Packaged renderer E2E must run on Windows');
if(process.env.CI!=='true')throw new Error('Renderer E2E is CI-only');
const root=path.resolve(__dirname,'..');
const executable=process.env.GROWTHMAP_PACKAGED_EXE||path.join(root,'dist','win-unpacked','GrowthMap.exe');
const screenshot=process.env.GROWTHMAP_E2E_SCREENSHOT||path.join(root,'artifacts','growthmap-renderer.png');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function port(){return new Promise((ok,no)=>{const s=net.createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p));});});}
function descendants(rootPid){const q=`$root=${rootPid};$all=Get-CimInstance Win32_Process;$seen=@($root);do{$before=$seen.Count;$seen+=@($all|Where-Object{$seen -contains $_.ParentProcessId}|ForEach-Object ProcessId);$seen=@($seen|Sort-Object -Unique)}while($seen.Count -gt $before);$seen -join ','`;const r=spawnSync('powershell',['-NoProfile','-Command',q],{encoding:'utf8',windowsHide:true});return (r.stdout||'').trim().split(',').filter(Boolean).map(Number);}
function treeGone(pids){const q=`$ids=@(${pids.join(',')});if(Get-CimInstance Win32_Process|Where-Object{$ids -contains $_.ProcessId}){exit 1}`;if(spawnSync('powershell',['-NoProfile','-Command',q],{windowsHide:true}).status!==0)throw Error('spawned process tree remained after close');}
async function snapshot(page){return page.evaluate(async()=>{const state={url:location.href,title:document.title,text:(document.body?.innerText||'').slice(0,2000),html:(document.body?.innerHTML||'').slice(0,1000)};try{const response=await fetch('/api/projects'),body=await response.json(),ids=Array.isArray(body)?body.map(row=>row?.id).filter(id=>typeof id==='string').sort():[];return {...state,projects:{status:response.status,count:ids.length,ids}};}catch(error){return {...state,projects:{error:error?.name||'Error'}};}}).catch(()=>({unavailable:true}));}
function fileEvidence(file){try{const bytes=fs.readFileSync(file);return {basename:path.basename(file),size:bytes.length,sha256:require('node:crypto').createHash('sha256').update(bytes).digest('hex')};}catch(error){return {basename:path.basename(file),error:error.code||error.name||'Error'};}}
async function stageWait(run,name,predicate,timeout=30000,arg){console.log(`E2E stage start: ${name}`);const deadline=Date.now()+timeout;while(Date.now()<deadline){if(run.child.exitCode!==null)throw Error(`${name}: app exited; child=${run.output().slice(-1500)}`);const state=await run.page.evaluate(predicate,arg).catch(()=>null);if(state===true){console.log(`E2E stage pass: ${name}`);return;}if(state&&state.error)throw Error(`${name}: UI error=${state.error}; diagnostic=${JSON.stringify(await snapshot(run.page))}; child=${run.output().slice(-1500)}`);await sleep(250);}throw Error(`${name}: timeout; diagnostic=${JSON.stringify(await snapshot(run.page))}; child=${run.output().slice(-1500)}`);}
async function launch(userData,fixture){const debugPort=await port(),diagnosticPath=path.join(userData,'e2e-phases.log'),electronLogPath=path.join(userData,'electron.log');const child=spawn(executable,launchArgs({userData,debugPort,logPath:electronLogPath}),{env:{...process.env,CI:'true',GROWTHMAP_DESKTOP_E2E:'1',GROWTHMAP_E2E_USER_DATA:userData,GROWTHMAP_E2E_IMPORT_PATH:fixture,GROWTHMAP_E2E_DIAGNOSTIC_PATH:diagnosticPath},stdio:['ignore','pipe','pipe'],windowsHide:true});let output='',directWebSocket=null;const capture=x=>{output+=x;directWebSocket=parseDevToolsWebSocket(output,debugPort);};child.stdout.on('data',capture);child.stderr.on('data',capture);let browser;const deadline=Date.now()+120000;while(Date.now()<deadline){if(child.exitCode!==null)throw Error(`app exited early: ${output.slice(-1500)}`);try{browser=await chromium.connectOverCDP(directWebSocket||`http://127.0.0.1:${debugPort}`,{timeout:2000});break;}catch{await sleep(250);}}if(!browser)throw Error(JSON.stringify(await timeoutDiagnostic({child,debugPort,output,diagnosticPath,electronLogPath}),null,2));let page;while(Date.now()<deadline&&!page){page=browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().startsWith('http://127.0.0.1:'));if(!page)await sleep(200);}if(!page)throw Error(`renderer page missing; child=${output.slice(-1500)}`);const run={child,browser,page,tree:descendants(child.pid),output:()=>output};await stageWait(run,'renderer-ready',()=>Boolean(document.querySelector('[data-testid="growthmap-title"]')&&document.querySelector('[data-testid="desktop-settings-button"]')),90000);return run;}
async function close(run){await run.page.close();const deadline=Date.now()+20000;while(run.child.exitCode===null&&Date.now()<deadline)await sleep(100);if(run.child.exitCode===null)throw Error('GrowthMap.exe did not exit');await run.browser.close().catch(()=>{});treeGone(run.tree);}
(async()=>{
 if(!fs.existsSync(executable))throw Error('packaged resources missing');
 const resources=path.join(path.dirname(executable),'resources');assertE2EPackage(path.join(resources,'app.asar'),resources);
 const userData=fs.mkdtempSync(path.join(os.tmpdir(),'growthmap-e2e-profile-'));
 const fixtureDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'growthmap-e2e-input-')),fixture=path.join(fixtureDirectory,'fixture.sqlite');
 const helper=path.join(root,'scripts','create-e2e-fixture.py');
 let made=spawnSync('python',[helper,fixture],{encoding:'utf8'});if(made.status!==0)throw Error(made.stderr);
 let run=await launch(userData,fixture);
 try{
  await stageWait(run,'fresh-trial',async()=>{const status=document.querySelector('[data-testid="entitlement-status"]')?.textContent||'';let entitlement;try{const response=await fetch('/api/desktop/entitlement');entitlement=response.ok?await response.json():{http_status:response.status};}catch(error){return {error:`entitlement request failed: ${error?.name||'Error'}`};}if(status.startsWith('Trial ·')&&entitlement.state==='trial'&&entitlement.valid===true&&entitlement.mutations_allowed===true)return true;if(status.includes('Read-only')||entitlement.state==='extraction')return {error:`unexpected entitlement: ui=${status}; state=${entitlement.state}; valid=${entitlement.valid}; mutations_allowed=${entitlement.mutations_allowed}; reason=${entitlement.reason}`};return false;},30000);
  for(const name of ['trial-marker.bin','installation-identity.bin','trial-state.json']){const target=path.join(userData,name);if(!fs.existsSync(target)||fs.statSync(target).size===0)throw Error(`fresh-trial: missing initialized artifact ${name}`);}
  await run.page.getByTestId('desktop-settings-button').click();
  await run.page.getByTestId('database-management').waitFor();
  const oldSessionRequest=await run.page.evaluate(async()=>{const response=await fetch('/api/projects');return {status:response.status,body:await response.text()};});
  if(oldSessionRequest.status!==200)throw Error(`pre-import desktop session is not authenticated: ${JSON.stringify(oldSessionRequest)}`);
  const preImportDocumentOrigin=await run.page.evaluate(()=>performance.timeOrigin);
  run.page.once('dialog',d=>d.accept());
  await run.page.getByTestId('database-import').click();
  try{await stageWait(run,'import-rebootstrap',async beforeOrigin=>{const projectId='11111111-1111-4111-8111-111111111111',rootId='22222222-2222-4222-8222-222222222222';if(performance.timeOrigin===beforeOrigin||!document.querySelector('[data-testid="growthmap-title"]'))return false;const projects=await fetch('/api/projects'),projectsBody=await projects.text();if(projects.status!==200)return {error:`new-session projects HTTP ${projects.status} ${projectsBody.slice(0,200)}`};let rows;try{rows=JSON.parse(projectsBody);}catch{return {error:'new-session projects returned invalid JSON'};}const project=Array.isArray(rows)?rows.find(row=>row?.id===projectId):null;if(!project)return false;const subtree=await fetch(`/api/nodes/${encodeURIComponent(rootId)}/subtree`),subtreeBody=await subtree.text();if(subtree.status!==200)return {error:`new-session subtree HTTP ${subtree.status} ${subtreeBody.slice(0,200)}`};return document.body.innerText.includes('Desktop Fixture');},90000,preImportDocumentOrigin);}catch(error){error.message+=`; database=${JSON.stringify({managed:fileEvidence(path.join(userData,'growthmap.db')),fixture:fileEvidence(fixture)})}`;throw error;}
  const sessionDiagnostics=run.output();if(!sessionDiagnostics.includes('[renderer:desktop-session] retired projects=401')||!sessionDiagnostics.includes('[renderer:desktop-session] current projects=200'))throw Error(`desktop session lifecycle diagnostics missing; child=${sessionDiagnostics.slice(-3000)}`);
  await stageWait(run,'post-import-fresh-trial',async()=>{const response=await fetch('/api/desktop/entitlement');if(!response.ok)return {error:`new-session entitlement HTTP ${response.status}`};const entitlement=await response.json(),status=document.querySelector('[data-testid="entitlement-status"]')?.textContent||'';return status.startsWith('Trial ·')&&entitlement.state==='trial'&&entitlement.valid===true&&entitlement.mutations_allowed===true;},30000);
  const agentPortEntry=await activateProjectForAgentPort(run.page,{projectId:importedProjectId,projectName:'Desktop Fixture'});await agentPortEntry.click();await run.page.getByTestId('agent-port-panel').waitFor();
  await stageWait(run,'agent-readbacks-loaded',async projectId=>{const count=document.querySelectorAll('[data-testid="agent-readback-card"]').length;if(count===2)return true;if(count>2)return {error:`expected exactly 2 readback cards; count=${count}`};const response=await fetch(`/api/agent-port/activity?project_id=${encodeURIComponent(projectId)}`),body=await response.text();if(response.status!==200)return {error:`activity HTTP ${response.status} ${body.slice(0,200)}`};let activity;try{activity=JSON.parse(body);}catch{return {error:'activity returned invalid JSON'};}if(!Array.isArray(activity.readbacks)||activity.readbacks.length!==2)return {error:`activity expected 2 readbacks; count=${Array.isArray(activity.readbacks)?activity.readbacks.length:'invalid'}`};return false;},30000,importedProjectId);
  const cards=run.page.getByTestId('agent-readback-card');
  for(const [summary,state] of [['Packaged current implementation','current r1'],['Packaged stale implementation','stale · current r2']]){const card=cards.filter({hasText:summary});await card.getByRole('button',{name:'22222222-2222-4222-8222-222222222222'}).click();const text=await card.innerText();assertReadbackText(text,{summary,state,target:'22222222-2222-4222-8222-222222222222'});}
  await run.page.getByRole('button',{name:'×'}).last().click();
  await run.page.getByTestId('desktop-settings-button').click();
  await run.page.getByTestId('database-backup').click();
  await stageWait(run,'backup',()=>{const t=document.body.innerText;if(t.includes('備份完成'))return true;return t.includes('資料庫操作失敗')?{error:'database operation failed'}:false;},90000);
  fs.mkdirSync(path.dirname(screenshot),{recursive:true});await run.page.screenshot({path:screenshot,fullPage:true});
  await close(run);
  made=spawnSync('python',['-c',`import sqlite3,sys;c=sqlite3.connect(sys.argv[1]);c.execute("update projects set name='Mutated Fixture'");c.commit();c.close()`,path.join(userData,'growthmap.db')],{encoding:'utf8'});if(made.status!==0)throw Error(made.stderr);
  run=await launch(userData,fixture);
  await stageWait(run,'restart-trial',async()=>{const status=document.querySelector('[data-testid="entitlement-status"]')?.textContent||'';const response=await fetch('/api/desktop/entitlement');if(!response.ok)return {error:`entitlement HTTP ${response.status}`};const entitlement=await response.json();if(status.startsWith('Trial ·')&&entitlement.state==='trial'&&entitlement.valid===true&&entitlement.mutations_allowed===true)return true;return status.includes('Read-only')||entitlement.state==='extraction'?{error:`trial identity not preserved: ui=${status}; state=${entitlement.state}; valid=${entitlement.valid}; mutations_allowed=${entitlement.mutations_allowed}; reason=${entitlement.reason}`}:false;},30000);
  await stageWait(run,'mutated-restart',()=>document.body.innerText.includes('Mutated Fixture'),90000);
  await run.page.getByTestId('desktop-settings-button').click();
  run.page.once('dialog',d=>d.accept());
  await run.page.getByTestId('database-restore').first().click();
  await stageWait(run,'restore',()=>{const t=document.body.innerText;if(t.includes('Desktop Fixture')&&!t.includes('Mutated Fixture'))return true;return t.includes('資料庫操作失敗')?{error:'database operation failed'}:false;},90000);
  await close(run);
  console.log(`Packaged database roundtrip/lifecycle E2E passed; screenshot=${screenshot}`);
 }finally{if(run?.child.exitCode===null)spawnSync('taskkill',['/PID',String(run.child.pid),'/T','/F'],{windowsHide:true});fs.rmSync(fixtureDirectory,{recursive:true,force:true});}
})().catch(e=>{console.error(e.stack||e);process.exit(1);});
