import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),bin=p=>fs.readFileSync(path.join(root,p));
const {verifiedCandidate}=await import(pathToFileURL(path.join(root,'content/release.ts')));const canonicalPages=['','features','agents','security','download','buy','docs','docs/developers','readback','support','status','privacy','terms','refund'];
test('typed trilingual metadata is complete',()=>{const m=read('content/metadata.ts');for(const p of canonicalPages)assert.ok(m.includes(p));for(const l of ['zh-TW','zh-CN','en'])assert.ok(m.includes(l));for(const x of ['x-default','summary_large_image','growthmap-share.png','openGraph','twitter'])assert.ok(m.includes(x))});
test('root html lang is request-derived without client patch',()=>{const l=read('app/layout.tsx'),p=read('proxy.ts');assert.ok(l.includes('<html lang={lang}>'));for(const x of ['zh-Hant','zh-Hans','x-growthmap-locale'])assert.ok(l.includes(x)||p.includes(x));assert.ok(!l.includes('<html lang="en">'))});
test('OG and product evidence dimensions and hashes match manifests',()=>{for(const [f,m] of [['public/og/growthmap-share.png','public/og/manifest.json'],['public/media/product/growthmap-windows-candidate.png','public/media/product/manifest.json']]){const b=bin(f),j=JSON.parse(read(m));assert.equal(b.readUInt32BE(16),j.width);assert.equal(b.readUInt32BE(20),j.height);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),j.sha256)}});
test('release rendering imports source of truth and disables non-public CTA',()=>{const c=read('components/Localized.tsx');assert.ok(c.includes("from '../content/release'"));for(const v of Object.values(verifiedCandidate).map(String))assert.ok(read('content/release.ts').includes(v));assert.equal(verifiedCandidate.publicRelease,false);assert.ok(c.includes('disabled={!r.publicRelease}'));for(const x of ['SHA-256','Unknown Publisher','publicRelease = false','最低 Windows 版本','Minimum Windows version'])assert.ok(read('content/release-copy.ts').includes(x))});
test('structured data is truthful',()=>{const s=read('components/StructuredData.tsx');for(const x of ['ProductivityApplication','Windows x64 (verified candidate)','verifiedCandidate.version','OutOfStock',"replace(/</g"])assert.ok(s.includes(x));for(const x of ['aggregateRating','review','downloadUrl'])assert.ok(!s.includes(x))});
test('contract examples and boundaries are exact',()=>{const w=read('content/workflows.ts'),cli=read('../scripts/growthmap_agent.py'),doc=read('../docs/AGENT-PORT-v1.md');for(const x of ['context --base-url http://127.0.0.1:8100/agent/v1 --target <PROJECT_NODE_UUID>','GET /agent/v1/context/<PROJECT_NODE_UUID>?objective=read-only-context','app API → validation → SQLite transaction','selected node and context','Agent Port neither executes models nor stores agent API keys'])assert.ok(w.includes(x),x);assert.ok(cli.includes('"context":("GET","/context/{target}")'));assert.ok(doc.includes('GET /context/{target_id}?objective='))});
