'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {DOMAIN,refreshActivationCertificate,verifyRefreshedCertificate,shouldRefresh}=require('../activation-refresh');
function keys(){const {privateKey,publicKey}=crypto.generateKeyPairSync('ed25519');return {privateKeyPem:privateKey.export({format:'pem',type:'pkcs8'}).toString(),publicKey:publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('base64'),publicPem:publicKey.export({format:'pem',type:'spki'}).toString()};}
const aid='gma_'+'a'.repeat(32),lid='license_1';
function cert(device,overrides={}){return {schema_version:2,certificate_type:'growthmap_device_activation',product:'growthmap',edition:'pro',license_id:lid,activation_id:aid,major_version:1,device_allowance:1,device_id:'gmdev_'+crypto.createHash('sha256').update(Buffer.from(device.publicKey,'base64')).digest('hex'),device_public_key:device.publicKey,issued_at:'2026-08-01T00:00:00Z',expires_at:'2027-01-01T00:00:00Z',revoked_at:null,max_active_projects:null,next_check_in_at:'2026-08-14T00:00:00Z',signature:'x',...overrides};}
function response(v,status=200){const s=JSON.stringify(v);return {ok:status===200,status,headers:{get:()=>String(s.length)},text:async()=>s};}
for(const flowKind of ['payment','gift'])test(`${flowKind} refresh uses exact secretless routes/body and canonical proof`,async()=>{const d=keys(),old=cert(d),calls=[];const fetchImpl=async(url,o)=>{calls.push({url,body:JSON.parse(o.body)});if(calls.length===1)return response({state:'challenge_issued',challenge:{challenge_id:'gmr_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',nonce:'0123456789abcdef',activation_id:aid,license_id:lid,device_public_key:d.publicKey}});const payload={activation_id:aid,device_public_key:d.publicKey,license_id:lid,nonce:'0123456789abcdef'};assert(crypto.verify(null,Buffer.concat([DOMAIN,Buffer.from(JSON.stringify(payload))]),crypto.createPublicKey(d.privateKeyPem),Buffer.from(calls[1].body.proof,'base64')));return response({state:'activated',certificate:cert(d)});};await refreshActivationCertificate({certificate:old,flowKind,activationApiOrigin:'https://activation.test',deviceIdentity:d,fetchImpl});const root=flowKind==='gift'?'gifts/refresh':'activation/refresh';assert.equal(calls[0].url,`https://activation.test/v1/${root}/challenge`);assert.equal(calls[1].url,`https://activation.test/v1/${root}/complete`);assert.deepEqual(calls[0].body,{activation_id:aid,license_id:lid,device_public_key:d.publicKey});assert.deepEqual(Object.keys(calls[1].body).sort(),['challenge_id','proof']);});
test('malformed, wrong identity, and non-contract refresh IDs fail closed',async()=>{const d=keys(),old=cert(d);for(const challenge of [{},...['gmc_'+ 'a'.repeat(32),'gmr_'+ 'A'.repeat(32),'gmr_'+ 'a'.repeat(31),'gmr_'+ 'a'.repeat(33),'gmr_'+ 'g'.repeat(32)].map(challenge_id=>({challenge_id,nonce:'0123456789abcdef',activation_id:aid,license_id:lid,device_public_key:d.publicKey})), {challenge_id:'gmr_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',nonce:'0123456789abcdef',activation_id:'gma_'+'b'.repeat(32),license_id:lid,device_public_key:d.publicKey}])await assert.rejects(()=>refreshActivationCertificate({certificate:old,flowKind:'payment',activationApiOrigin:'https://activation.test',deviceIdentity:d,fetchImpl:async()=>response({state:'challenge_issued',challenge})}));});
test('independent signature and monotonic identity verification rejects stale/wrong certificates',()=>{const d=keys(),authority=keys(),old=cert(d);function signed(overrides={}){const c=cert(d,{issued_at:'2026-08-13T00:00:00Z',next_check_in_at:'2026-08-20T00:00:00Z',...overrides,signature:''}),payload=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));c.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),crypto.createPrivateKey(authority.privateKeyPem)).toString('base64');return c;}assert.equal(verifyRefreshedCertificate({previous:old,candidate:signed(),deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,now:new Date('2026-08-13T01:00:00Z')}).license_id,lid);for(const bad of [signed({license_id:'other'}),signed({next_check_in_at:old.next_check_in_at}),{...signed(),signature:'bad'}])assert.throws(()=>verifyRefreshedCertificate({previous:old,candidate:bad,deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,now:new Date('2026-08-13T01:00:00Z')}));});
test('refresh window is deterministic',()=>{const d=keys(),c=cert(d),at=Date.parse(c.next_check_in_at);assert.equal(shouldRefresh(c,new Date(at-86400000-1)),false);assert.equal(shouldRefresh(c,new Date(at-86400000)),true);});
test('signature and UTC timestamp encodings are strict and canonical',()=>{const d=keys(),authority=keys(),old=cert(d);function signed(overrides={}){const c=cert(d,{issued_at:'2026-08-13T00:00:00Z',next_check_in_at:'2026-08-20T00:00:00Z',...overrides,signature:''}),payload=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));c.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),crypto.createPrivateKey(authority.privateKeyPem)).toString('base64');return c;}const options={previous:old,deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,now:new Date('2026-08-13T01:00:00Z')};let urlsafe;for(let i=0;i<100&&!urlsafe;i++){const s=signed({issued_at:`2026-08-13T00:00:${String(i%60).padStart(2,'0')}Z`});if(/[+/]/.test(s.signature))urlsafe={...s,signature:s.signature.replace(/\+/g,'-').replace(/\//g,'_')};}assert(urlsafe);for(const signature of ['',signed().signature+' ',urlsafe.signature,'!!!!',Buffer.alloc(65).toString('base64'),signed().signature.replace(/=$/,'')])assert.throws(()=>verifyRefreshedCertificate({...options,candidate:{...signed(),signature}}));assert.doesNotThrow(()=>verifyRefreshedCertificate({...options,candidate:signed({issued_at:'2026-08-13T00:00:00.000001Z',next_check_in_at:'2026-08-20T00:00:00.000002Z'})}));for(const issued_at of ['2026-08-13 00:00:00Z','2026-08-13T00:00:00+00:00','2026-08-13T00:00:00.1Z','2026-08-13T00:00:00.123Z','2026-08-13T00:00:00.12345Z','2026-08-13T00:00:00.1234567Z','2026-8-13T00:00:00Z','2026-02-30T00:00:00Z','9999-99-99T99:99:99Z'])assert.throws(()=>verifyRefreshedCertificate({...options,candidate:signed({issued_at})}));});
function rawResponse(text){return {ok:true,status:200,headers:{get:()=>String(Buffer.byteLength(text))},text:async()=>text};}
test('strict duplicate challenge JSON stops after exactly one fetch',async()=>{const d=keys(),old=cert(d);for(const text of [
 `{"state":"challenge_issued","state":"challenge_issued","challenge":{"challenge_id":"gmr_${'a'.repeat(32)}","nonce":"0123456789abcdef","activation_id":"${aid}","license_id":"${lid}","device_public_key":"${d.publicKey}"}}`,
 `{"state":"challenge_issued","STATE":"challenge_issued","challenge":{"challenge_id":"gmr_${'a'.repeat(32)}","nonce":"0123456789abcdef","Nonce":"0123456789abcdef","activation_id":"${aid}","license_id":"${lid}","device_public_key":"${d.publicKey}"}}`
 ]){let calls=0;await assert.rejects(()=>refreshActivationCertificate({certificate:old,flowKind:'payment',activationApiOrigin:'https://activation.test',deviceIdentity:d,fetchImpl:async()=>{calls++;return rawResponse(text);}}),/invalid response/);assert.equal(calls,1);}});
test('strict duplicate completion JSON stops after exactly two fetches and returns no certificate',async()=>{const d=keys(),old=cert(d),challenge=response({state:'challenge_issued',challenge:{challenge_id:'gmr_'+ 'a'.repeat(32),nonce:'0123456789abcdef',activation_id:aid,license_id:lid,device_public_key:d.publicKey}});for(const text of [
 `{"state":"activated","state":"activated","certificate":${JSON.stringify(old)}}`,
 `{"state":"activated","certificate":${JSON.stringify(old).replace(/"signature":"x"/, '"signature":"x","Signature":"x"')}}`
 ]){let calls=0,received=false;await assert.rejects(async()=>{const value=await refreshActivationCertificate({certificate:old,flowKind:'payment',activationApiOrigin:'https://activation.test',deviceIdentity:d,fetchImpl:async()=>++calls===1?challenge:rawResponse(text)});received=Boolean(value);},/invalid response/);assert.equal(calls,2);assert.equal(received,false);}});
test('installed identity verifier independently binds signature device product-major and entitlement',()=>{const {verifyInstalledCertificateIdentity,hasInstalledCertificateCapability}=require('../activation-refresh'),d=keys(),authority=keys();function signed(overrides={}){const c=cert(d,{...overrides,signature:''}),payload=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));c.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),crypto.createPrivateKey(authority.privateKeyPem)).toString('base64');return c;}const good=signed(),entitlement={state:'paid',reason:'valid',license_id:lid,edition:'pro',major_version:1,device_allowance:1,max_active_projects:null},options={entitlement,deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,currentMajor:1,now:new Date('2026-08-13T00:00:00Z')},cap=verifyInstalledCertificateIdentity({...options,certificate:good});assert(hasInstalledCertificateCapability(cap,good,entitlement));assert(!hasInstalledCertificateCapability(Object.freeze({}),good,entitlement));const other=keys(),wrongRaw=Buffer.from(other.publicKey,'base64'),bad=[{...good,signature:Buffer.alloc(64).toString('base64')},signed({device_public_key:other.publicKey}),signed({device_id:'gmdev_'+crypto.createHash('sha256').update(wrongRaw).digest('hex')}),signed({major_version:2}),signed({product:'other'}),signed({edition:'personal'}),signed({device_allowance:2}),signed({max_active_projects:1}),signed({expires_at:'2026-08-12T00:00:00Z'}),signed({revoked_at:'2026-08-12T00:00:00Z'})];for(const certificate of bad)assert.throws(()=>verifyInstalledCertificateIdentity({...options,certificate}),/identity verification failed/);const overdue=signed({next_check_in_at:'2026-08-12T00:00:00Z'}),limited={reason:'check_in_required',license_id:lid,major_version:1};assert.doesNotThrow(()=>verifyInstalledCertificateIdentity({...options,certificate:overdue,entitlement:limited}));});
test('certificate schema rejects hidden, symbol, accessor, and extra own properties for installed and refreshed certificates',()=>{
 const {verifyInstalledCertificateIdentity}=require('../activation-refresh'),d=keys(),authority=keys();
 function signed(){const c=cert(d,{signature:''}),payload=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));c.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),crypto.createPrivateKey(authority.privateKeyPem)).toString('base64');return c;}
 const entitlement={state:'paid',reason:'valid',license_id:lid,edition:'pro',major_version:1,device_allowance:1,max_active_projects:null},installedOptions={entitlement,deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,currentMajor:1,now:new Date('2026-08-13T00:00:00Z')};
 const attacks=[c=>Object.defineProperty(c,'hidden',{value:true,enumerable:false}),c=>{c[Symbol('hidden')]=true;},c=>Object.defineProperty(c,'edition',{get(){return 'pro';},enumerable:true}),c=>Object.defineProperty(c,'edition',{value:'pro',enumerable:false}),c=>{c.extra=true;}];
 for(const attack of attacks){const installed=signed();attack(installed);assert.throws(()=>verifyInstalledCertificateIdentity({...installedOptions,certificate:installed}),/identity verification failed/);}
 const old=signed(),refreshOptions={previous:old,deviceIdentity:d,authorityPublicKeyPem:authority.publicPem,now:new Date('2026-08-13T01:00:00Z')};
 for(const attack of attacks){const candidate=signed();candidate.issued_at='2026-08-13T00:00:00Z';candidate.next_check_in_at='2026-08-20T00:00:00Z';attack(candidate);assert.throws(()=>verifyRefreshedCertificate({...refreshOptions,candidate}));}
});
