'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {parseActivationKey,activateLicenseKey}=require('../activation-client');
const ORDER='11111111-1111-4111-8111-111111111111',CODE='A'.repeat(32),KEY=`GM1.${ORDER}.${CODE}`;
function identity(){const {privateKey,publicKey}=crypto.generateKeyPairSync('ed25519');return {privateKeyPem:privateKey.export({format:'pem',type:'pkcs8'}).toString(),publicKey:publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('base64')};}
function response(value,status=200){const text=JSON.stringify(value);return {ok:status>=200&&status<300,status,headers:{get:name=>name==='content-length'?String(text.length):null},text:async()=>text};}
test('activation key is strict and contains only order recovery capability',()=>{assert.deepEqual(parseActivationKey(KEY),{orderId:ORDER,recoveryCode:CODE});for(const value of ['',` ${KEY}`,`${KEY} `,KEY+'x','GM1.bad.'+CODE,`GM1.${ORDER}.${'A'.repeat(31)}`,'x'.repeat(129),null])assert.throws(()=>parseActivationKey(value),/Invalid activation-key format/);});
test('activation signs device-bound challenge and returns certificate',async()=>{const device=identity(),calls=[],certificate={schema_version:2,signature:'signed'};const fetchImpl=async(url,options)=>{calls.push({url,body:JSON.parse(options.body),options});if(calls.length===1)return response({state:'challenge_issued',challenge:{challenge_id:'gmc_1',nonce:'nonce_value_1234567890',license_id:'gm_license',device_public_key:device.publicKey}});const challenge=Buffer.concat([Buffer.from('growthmap-activation-request-v1\0'),Buffer.from(JSON.stringify({device_public_key:device.publicKey,license_id:'gm_license',nonce:'nonce_value_1234567890'}))]);assert.equal(crypto.verify(null,challenge,crypto.createPublicKey(device.privateKeyPem),Buffer.from(calls[1].body.proof,'base64')),true);return response({state:'activated',certificate});};assert.deepEqual(await activateLicenseKey({activationKey:KEY,activationApiOrigin:'https://activation.growthmap.test',deviceIdentity:device,fetchImpl}),certificate);assert.equal(calls[0].url,'https://activation.growthmap.test/v1/activation/challenge');assert.equal(calls[1].url,'https://activation.growthmap.test/v1/activation/complete');assert.deepEqual(calls[0].body,{order_id:ORDER,recovery_code:CODE,device_public_key:device.publicKey});for(const call of calls){assert.equal(call.options.redirect,'error');assert.equal(call.options.cache,'no-store');assert.equal(call.options.referrerPolicy,'no-referrer');}});
test('origin, response mismatch and remote details fail closed',async()=>{const device=identity();for(const origin of ['http://activation.test','https://127.0.0.1','https://ACTIVATION.test'])await assert.rejects(()=>activateLicenseKey({activationKey:KEY,activationApiOrigin:origin,deviceIdentity:device,fetchImpl:async()=>response({})}));await assert.rejects(()=>activateLicenseKey({activationKey:KEY,activationApiOrigin:'https://activation.test',deviceIdentity:device,fetchImpl:async()=>response({state:'challenge_issued',challenge:{challenge_id:'x',nonce:'x',license_id:'x',device_public_key:'wrong'}})}),/invalid response/);await assert.rejects(()=>activateLicenseKey({activationKey:KEY,activationApiOrigin:'https://activation.test',deviceIdentity:device,fetchImpl:async()=>{throw Error('SECRET_REMOTE_DETAIL');}}),error=>!String(error).includes('SECRET_REMOTE_DETAIL'));});

test('gift key is strict and selects only the gift claim endpoints',async()=>{const device=identity(),giftId='22222222-2222-4222-8222-222222222222',secret='B'.repeat(32),giftKey=`GMG1.${giftId}.${secret}`,calls=[];assert.deepEqual(parseActivationKey(giftKey),{kind:'gift',giftId,claimSecret:secret});const fetchImpl=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});if(calls.length===1)return response({state:'challenge_issued',challenge:{challenge_id:'gmc_gift',nonce:'nonce_value_1234567890',license_id:'gm_gift',device_public_key:device.publicKey}});return response({state:'activated',certificate:{schema_version:2,signature:'signed'}});};await activateLicenseKey({activationKey:giftKey,activationApiOrigin:'https://activation.growthmap.test',deviceIdentity:device,fetchImpl});assert.equal(calls[0].url,'https://activation.growthmap.test/v1/gifts/claim/challenge');assert.deepEqual(calls[0].body,{claim_key:giftKey,device_public_key:device.publicKey});assert.equal(calls[1].url,'https://activation.growthmap.test/v1/gifts/claim/complete');for(const bad of [`gmg1.${giftId}.${secret}`,` GMG1.${giftId}.${secret}`,`GMG1.${giftId}.${secret}x`])assert.throws(()=>parseActivationKey(bad),/Invalid activation-key format/);});
