'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {atomic,config,target,manager}=require('../agent-access');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'gm-agent-'));
test('generic config contains command only and no secret or port',()=>{const x=config('C:\\GrowthMap\\resources\\growthmap-mcp.exe');assert.deepEqual(x,{mcpServers:{growthmap:{command:'C:\\GrowthMap\\resources\\growthmap-mcp.exe'}}});assert.doesNotMatch(JSON.stringify(x),/token|bearer|endpoint|port|env/i)});
test('target is product and installation scoped and rejects hostile identity',()=>{assert.equal(target(1,'abcdefghijklmnop'),'GrowthMap/AgentPort/v1/product-1/installation-abcdefghijklmnop/primary');assert.throws(()=>target(1,'bad\0identity'))});
test('atomic descriptor rejects symlink',()=>{const d=tmp(),real=path.join(d,'real'),link=path.join(d,'link');fs.writeFileSync(real,'safe');fs.symlinkSync(real,link);assert.throws(()=>atomic(link,{x:1}),/unsafe/);assert.equal(fs.readFileSync(real,'utf8'),'safe')});
test('disable blocks discovery first and marks repair when revoke fails',async()=>{const d=tmp(),local=path.join(d,'local'),user=path.join(d,'user'),exe=process.execPath,m=manager({userData:user,localAppData:local,exe,major:1,installation:'abcdefghijklmnop',api:async()=>{throw Error('offline')},endpoint:'http://127.0.0.1:1234/agent/v1',sidecarPid:()=>123,instanceNonce:'x'.repeat(32)});atomic(path.join(user,'agent-access.json'),{schema:'growthmap.agent-profile.v1',status:'enabled',grantId:'g',projectId:'p',permission:'propose',lifetime:'unlimited',credentialTarget:'GrowthMap/AgentPort/v1/product-1/installation-abcdefghijklmnop/primary'});await m.restore();await assert.rejects(()=>m.disable(),/revocation failed/);assert.equal(fs.existsSync(path.join(local,'GrowthMap','agent-access.json')),false);assert.equal(m.status().repairRequired,true)});

test('download rejects symlink overwrite and copy stays in main-process seam',async()=>{const d=tmp(),real=path.join(d,'real.json'),link=path.join(d,'link.json');fs.writeFileSync(real,'unchanged');fs.symlinkSync(real,link);let copied='';const m=manager({userData:path.join(d,'u'),localAppData:path.join(d,'l'),exe:'C:\\GrowthMap\\growthmap-mcp.exe',major:1,installation:'abcdefghijklmnop',api:async()=>{},endpoint:'http://127.0.0.1:1/agent/v1',sidecarPid:()=>1,instanceNonce:'x'.repeat(32),clipboard:{writeText:x=>copied=x},saveDialog:async()=>({canceled:false,filePath:link})});assert.equal(m.copyConfig(),true);assert.deepEqual(JSON.parse(copied),config('C:\\GrowthMap\\growthmap-mcp.exe'));await assert.rejects(()=>m.downloadConfig(),/unsafe/);assert.equal(fs.readFileSync(real,'utf8'),'unchanged')});
test('grant 403 has zero credential, descriptor, profile, or compensation side effects',async()=>{const d=tmp(),local=path.join(d,'local'),user=path.join(d,'user');let calls=0;const denied=Object.assign(Error('GROWTHMAP_DESKTOP_ERROR:{"status":403,"code":"ENTITLEMENT_READ_ONLY","reason":"prior_installation_evidence","detail":null}'),{statusCode:403});const m=manager({userData:user,localAppData:local,exe:process.execPath,major:1,installation:'abcdefghijklmnop',api:async(method,route)=>{calls++;assert.equal(method,'POST');assert.equal(route,'/api/agent-port/grants');throw denied;},endpoint:'http://127.0.0.1:1/agent/v1',sidecarPid:()=>1,instanceNonce:'x'.repeat(32)});await assert.rejects(()=>m.enable({projectId:'p',permission:'propose',lifetime:'unlimited'}),error=>error===denied);assert.equal(calls,1);assert.equal(fs.existsSync(path.join(user,'agent-access.json')),false);assert.equal(fs.existsSync(path.join(local,'GrowthMap','agent-access.json')),false);assert.deepEqual(m.status(),{enabled:false,permission:'propose',lifetime:'unlimited',config:config(process.execPath),repairRequired:false});});
test('persistent grant rendering source never constructs a Date from null',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../../src/frontend/src/components/AgentPortPanel.tsx'),'utf8');assert.match(source,/g\.persistent\?u\(/);assert.doesNotMatch(source,/new Date\(['"]null['"]\)/)});
