'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{loadCommercialConfig}=require('../commercial-config');
function fixture(changes={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-config-'));fs.mkdirSync(path.join(root,'commercial'));const key=Buffer.from('trusted-key');fs.writeFileSync(path.join(root,'commercial/license_public_key.pem'),key);const doc={schemaVersion:3,productMajor:1,licenseIssuer:'Growthmap',supportEmail:'owner@example.test',supportUrl:'https://x.com/growthmap_test',publisher:'月影塵（nerv00kaworu）',publisherStatus:'APPROVED',licensePublicKeyResource:'commercial/license_public_key.pem',licensePublicKeySha256:crypto.createHash('sha256').update(key).digest('hex'),paymentApiOrigin:'https://api.growthmap.test',purchasePortalOrigin:'https://pay.growthmap.test',purchasePortalUrl:'https://pay.growthmap.test/buy',baseNetwork:'eip155:8453',baseUsdc:'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',basePayee:'0x81d30e175a22c1c2f78b3db6fc0600a6e1cb3591',earlyLimit:50,earlyPriceMicros:10000000,regularPriceMicros:29000000,paypalUrl:'https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA',updateUrl:'https://updates.growthmap.test',updateOrigin:'https://updates.growthmap.test',...changes};fs.writeFileSync(path.join(root,'commercial-config.json'),JSON.stringify(doc));return root;}
test('packaged configuration ignores attacker authority environment',()=>{const root=fixture(),config=loadCommercialConfig({isPackaged:true,resourcesPath:root,env:{GROWTHMAP_LICENSE_PUBLIC_KEY:'/attacker',GROWTHMAP_PURCHASE_PORTAL_URL:'https://evil.test',GROWTHMAP_UPDATE_URL:'https://evil.test'}});assert.equal(config.purchasePortalUrl,'https://pay.growthmap.test/buy');assert.equal(config.updateUrl,'https://updates.growthmap.test');assert(config.licensePublicKeyPath.startsWith(root));});
test('packaged placeholder, mismatch and wrong public key hash fail closed',()=>{for(const changes of [{publisher:'TBD'},{productMajor:2},{publisherStatus:'UNAPPROVED'},{basePayee:'0x1111111111111111111111111111111111111111'},{licensePublicKeySha256:'0'.repeat(64)}])assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:fixture(changes)}));});
test('development authority overrides are explicitly labelled',()=>assert.equal(loadCommercialConfig({isPackaged:false,resourcesPath:'',env:{GROWTHMAP_UPDATE_URL:'https://dev.test'}}).developmentOverride,true));
test('production cannot select E2E status through environment or CLI',()=>{
 const root=fixture({publisherStatus:'E2E_ONLY',paymentApiOrigin:'',purchasePortalOrigin:'',purchasePortalUrl:'',paypalUrl:'',updateUrl:'',updateOrigin:''}),savedArgv=process.argv;
 try{process.argv=[...savedArgv,'--growthmap-e2e-commercial'];assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:root,env:{CI:'true',GROWTHMAP_DESKTOP_E2E:'1',GROWTHMAP_E2E_COMMERCIAL_CONFIG:'1'}}),/invalid/);}finally{process.argv=savedArgv;}
});

test('PayPal target is one exact immutable approved URL',()=>{for(const paypalUrl of ['https://paypal.me/name','https://www.paypal.com.evil.test/ncp/payment/R2M3YAQJNNCZA','https://user@www.paypal.com/ncp/payment/R2M3YAQJNNCZA','https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA?q=1','https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA#x','https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA/','https://WWW.paypal.com/ncp/payment/R2M3YAQJNNCZA','https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA%2f'])assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:fixture({paypalUrl})}),/payment trust mismatch/);});
test('payment API and purchase portal are distinct canonical public authorities',()=>{for(const changes of [{paymentApiOrigin:'https://pay.growthmap.test'},{paymentApiOrigin:'https://pay.growthmap.test.'},{purchasePortalOrigin:'https://pay.growthmap.test.'},{paymentApiOrigin:'https://API.growthmap.test'},{paymentApiOrigin:'https://api.growthmap.test:443'},{paymentApiOrigin:'https://10.0.0.1'},{paymentApiOrigin:'https://[fc00::1]'},{purchasePortalOrigin:'https://[fe80::1]',purchasePortalUrl:'https://[fe80::1]/buy'},{purchasePortalUrl:'https://pay.growthmap.test/buy?token=secret'},{purchasePortalUrl:'https://api.growthmap.test/buy'},{paymentApiOrigin:'http://api.growthmap.test'}])assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:fixture(changes)}),/payment trust mismatch/);});

test('schema 3 public identity is strict and rejects unknown/case-colliding keys',()=>{for(const changes of [{licenseIssuer:'TBD'},{licenseIssuer:'x\n'},{supportEmail:'not-email'},{supportUrl:'https://twitter.com/name'},{supportUrl:'https://X.com/name'},{extra:true}])assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:fixture(changes)}));const root=fixture();const file=path.join(root,'commercial-config.json'),raw=fs.readFileSync(file,'utf8').replace('{','{\"SupportEmail\":\"collision@example.test\",');fs.writeFileSync(file,raw);assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:root}),/Case-colliding/);});
