'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{loadCommercialConfig}=require('../commercial-config');
function fixture(changes={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-config-'));fs.mkdirSync(path.join(root,'commercial'));const key=Buffer.from('trusted-key');fs.writeFileSync(path.join(root,'commercial/license_public_key.pem'),key);const doc={schemaVersion:1,productMajor:1,publisher:'GrowthMap Software Ltd.',publisherStatus:'APPROVED',licensePublicKeyResource:'commercial/license_public_key.pem',licensePublicKeySha256:crypto.createHash('sha256').update(key).digest('hex'),checkoutOrigin:'https://pay.growthmap.test',checkoutUrl:'https://pay.growthmap.test/buy',updateUrl:'https://updates.growthmap.test',updateOrigin:'https://updates.growthmap.test',...changes};fs.writeFileSync(path.join(root,'commercial-config.json'),JSON.stringify(doc));return root;}
test('packaged configuration ignores attacker authority environment',()=>{const root=fixture(),config=loadCommercialConfig({isPackaged:true,resourcesPath:root,env:{GROWTHMAP_LICENSE_PUBLIC_KEY:'/attacker',GROWTHMAP_CHECKOUT_URL:'https://evil.test',GROWTHMAP_UPDATE_URL:'https://evil.test'}});assert.equal(config.checkoutUrl,'https://pay.growthmap.test/buy');assert.equal(config.updateUrl,'https://updates.growthmap.test');assert(config.licensePublicKeyPath.startsWith(root));});
test('packaged placeholder, mismatch and wrong public key hash fail closed',()=>{for(const changes of [{publisher:'TBD'},{productMajor:2},{publisherStatus:'UNAPPROVED'},{licensePublicKeySha256:'0'.repeat(64)}])assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:fixture(changes)}));});
test('development authority overrides are explicitly labelled',()=>assert.equal(loadCommercialConfig({isPackaged:false,resourcesPath:'',env:{GROWTHMAP_UPDATE_URL:'https://dev.test'}}).developmentOverride,true));
test('production cannot select E2E status through environment or CLI',()=>{
 const root=fixture({publisherStatus:'E2E_ONLY',checkoutOrigin:'',checkoutUrl:'',updateUrl:'',updateOrigin:''}),savedArgv=process.argv;
 try{process.argv=[...savedArgv,'--growthmap-e2e-commercial'];assert.throws(()=>loadCommercialConfig({isPackaged:true,resourcesPath:root,env:{CI:'true',GROWTHMAP_DESKTOP_E2E:'1',GROWTHMAP_E2E_COMMERCIAL_CONFIG:'1'}}),/invalid/);}finally{process.argv=savedArgv;}
});
