const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const main=fs.readFileSync(require.resolve('../main.js'),'utf8'),preload=fs.readFileSync(require.resolve('../preload.js'),'utf8'),pkg=require('../package.json');test('shell hardening',()=>{for(const x of ['requestSingleInstanceLock','nodeIntegration:false','contextIsolation:true','sandbox:true','setWindowOpenHandler','will-navigate','127.0.0.1'])assert.match(main,new RegExp(x));});test('token header only',()=>{assert.match(main,/randomBytes\(32\)/);assert.match(main,/Authorization/);assert.doesNotMatch(main,/localStorage|searchParams/);});test('desktop update and database recovery IPC contracts are exposed',()=>{for(const value of ["'updates:check'","'database:backup'","'database:list-backups'","'database:reveal'","'database:import'","'database:restore'"])assert.match(preload,new RegExp(value));assert.match(main,/updateRecovery/);assert.match(main,/method==='restore'&&!updateRecovery/);const page=fs.readFileSync(require('node:path').resolve(__dirname,'../../src/frontend/src/app/page.tsx'),'utf8');assert.match(page,/data-testid="check-updates-button"/);assert.match(page,/growthmapDesktop\.updates\.check\(\)/);});
test('safeStorage write-only IPC',()=>{assert.match(main,/safeStorage\.encryptString/);assert.match(main,/isEncryptionAvailable/);assert.deepEqual([...preload.matchAll(/'secrets:(has|set|delete)'/g)].map(x=>x[1]).sort(),['delete','has','set']);});test('NSIS',()=>{assert.equal(pkg.build.nsis.oneClick,true);assert.equal(pkg.build.win.target[0].target,'nsis');});
test('IPC guard and strict CSP/lifecycle contracts',()=>{assert.match(main,/event\.sender!==expected/);assert.match(main,/senderFrame/);assert.match(main,/origin!==baseUrl/);assert.match(main,/policy\(manifest\)/);assert.doesNotMatch(main,/unsafe-eval/);assert.match(main,/onHeadersReceived/);assert.match(main,/for\(let attempt=1;attempt<=3/);assert.match(main,/exited before readiness/);assert.match(main,/stopped unexpectedly/);});

test('dynamic loopback hook is broad but request policy checks current origin',()=>{assert.match(main,/createRequestPolicy/);assert.match(require('node:fs').readFileSync(require.resolve('../request-policy.js'),'utf8'),/127\.0\.0\.1:\*\/\*/);});

test('native menu removed and renderer diagnostics/error fallback wired',()=>{for(const x of ['Menu.setApplicationMenu(null)','autoHideMenuBar:true','setMenu(null)','did-fail-load','render-process-gone','console-message'])assert.match(main,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(main,/title:'GrowthMap'/);});
test('pending-update lock precedes recovery, schema, migration backup and writable policy',()=>{const source=fs.readFileSync(require('node:path').join(__dirname,'../main.js'),'utf8'),body=source.slice(source.indexOf('async function prepareAndStart'),source.indexOf('async function launch'));const pending=body.indexOf('if(pending)'),verify=body.indexOf('verifyPending'),recover=body.indexOf('recoverStartup'),schema=body.indexOf('schemaStatus'),backup=body.indexOf('migrationBackup');assert(pending>=0&&verify>pending&&recover>verify&&schema>recover&&backup>schema);assert.match(body,/await lifecycle\.cleanup\(\)/);});
test('packaged launch scrubs attacker trust env and injects bundled key mode',()=>{const source=fs.readFileSync(require('node:path').join(__dirname,'../main.js'),'utf8');for(const key of ['GROWTHMAP_CHECKOUT_ORIGIN','GROWTHMAP_CHECKOUT_URL','GROWTHMAP_UPDATE_URL','GROWTHMAP_LICENSE_PUBLIC_KEY'])assert.match(source,new RegExp(key));assert.match(source,/GROWTHMAP_BUNDLED_LICENSE_PUBLIC_KEY/);assert.match(source,/GROWTHMAP_PACKAGED_MODE/);});
