'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {runCredentialStartup}=require('../credential-startup');
test('deferred reconcile blocks hydrate, IPC/window/AI enable',async()=>{let release;const pending=new Promise(r=>release=r),events=[];const p=runCredentialStartup({store:{reconcile:async()=>{events.push('reconcile');await pending},hydrate:async()=>events.push('hydrate')},enable:async()=>events.push('enable')});await new Promise(r=>setImmediate(r));assert.deepEqual(events,['reconcile']);release();await p;assert.deepEqual(events,['reconcile','hydrate','enable'])});
test('reconcile rejection fails closed before hydrate and enable',async()=>{const events=[];await assert.rejects(runCredentialStartup({store:{reconcile:async()=>{events.push('reconcile');throw Error('invalid')},hydrate:async()=>events.push('hydrate')},enable:async()=>events.push('enable')}));assert.deepEqual(events,['reconcile'])});
test('success is exact reconcile then hydrate then enable order',async()=>{const events=[];await runCredentialStartup({store:{reconcile:async()=>events.push('reconcile'),hydrate:async()=>events.push('hydrate')},enable:async()=>events.push('enable')});assert.deepEqual(events,['reconcile','hydrate','enable'])});
test('actual launch imports and awaits production startup barrier before BrowserWindow',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8'),launch=main.slice(main.indexOf('async function launch'));assert.match(main,/require\('\.\/production-launch'\)/);const barrier=launch.indexOf('await completeProductionLaunch'),window=launch.indexOf('new BrowserWindow');assert(barrier>=0&&window>barrier)});
test('production uses behavioral hydration orchestration seam',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8');assert.match(main,/restartHydration\(\{prepare:\(\)=>prepareAndStart\(\{preferredPort\}\)/);assert.match(main,/hydrateAndSeal:\(ready,store\)=>hydrateAndSeal\(\{writable:ready\.policy\.writable/);assert.match(main,/hydrateRemote:\(id,v\)=>api\('PUT',`\/api\/desktop\/secrets\/\$\{encodeURIComponent\(id\)\}\/hydrate`/)});

test('ordinary sidecar restart preserves the active credential store and only replacement rotates authority',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8');assert.match(main,/ordinaryRestart=!_evidence&&!preserveCredentialLineage&&!rollbackReplacement&&!authorityTransition/);assert.match(main,/if\(ordinaryRestart\)\{if\(!credentialStore\)throw new Error\('Credential store is unavailable for sidecar restart'\);\}else\{try\{if\(!rotation\)rotation=await credentialAuthority\.activate/);assert.match(main,/if\(!ordinaryRestart\)credentialStore=null/);assert.match(main,/replacement-restart-failed-authority/)});

test('production store anchors secrets beneath lineage-bound Electron userData root',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8');assert.match(main,/credentialAuthority\.adoptLegacyOnce\(activeDatabasePath\)/);assert.match(main,/createLineageAuthority\(\{userData,protectKey:/);assert.match(main,/createSecretStore\(\{trustedRoot,directory:trustedRoot/)})
test('existing database launch absorbs its own legacy adoption before entering production barrier',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8'),launch=main.slice(main.indexOf('async function launch')),activate=launch.indexOf('initialBinding=await credentialAuthority.activate(activeDatabasePath)'),store=launch.indexOf('credentialStore=await makeStore()'),absorb=launch.indexOf('await initialBinding.absorbLegacyAdoption?.()'),barrier=launch.indexOf('await completeProductionLaunch');assert(activate>=0&&activate<store&&store<absorb&&absorb<barrier)})
test('startup native diagnostics expose only fixed operation and stage enums',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8'),secure=fs.readFileSync(require.resolve('../secure-files.js'),'utf8');for(const operation of ['secure-path-policy','secure-read-file','secure-remove-file','initialize-private-acl']){assert.ok(main.includes(operation));assert.ok(secure.includes(operation))}assert.match(main,/safeOperation=value=>\['secure-path-policy','secure-read-file','secure-remove-file','initialize-private-acl'\]\.includes\(value\)\?value:'unknown'/);assert.match(main,/stages=new Set\(\['timeout','closed','aborted'/);assert.match(main,/safeStage=value=>stages\.has\(value\)\?value:'unknown'/);assert.match(secure,/Object\.defineProperty\(error,'nativeOperation',\{value:operation,configurable:true\}\)/);for(const stage of ['response-schema-policy','response-schema-read','response-schema-remove','response-schema-initialize']){assert.ok(main.includes(stage));assert.ok(secure.includes(stage))}for(const stage of ['response-schema-policy-container','response-schema-policy-item','response-schema-policy-path','response-schema-policy-identity'])assert.ok(main.includes(stage));assert.match(main,/barriers=new Set\(\['prepare','bind','store','reconcile','hydrate','enable','commit'\]\)/);assert.match(main,/rollbackOperation=\$\{safeOperation\(error\.rollbackNativeOperation\)\} rollbackStage=\$\{safeStage\(error\.rollbackNativeStage\)\}/);assert.doesNotMatch(main,/nativeOperation[^\n]{0,100}(path|payload)/i)})

test('Windows startup awaits shared broker, authority journal and transitions before BrowserWindow',()=>{const main=fs.readFileSync(require.resolve('../main.js'),'utf8'),launch=main.slice(main.indexOf('async function launch'));for(const contract of [/await windowsProductionWiring\.assertAvailable\(\)/,/credentialAuthority=await credentialLineage\.createLineageAuthority/,/pendingReplacement=await replacementJournal\.read\(\)/,/await credentialAuthority\.activate/,/await initialBinding\?\.commit\?\.\(\)/,/await initialBinding\.rollback\(\)/])assert.match(launch,contract);const window=launch.indexOf('new BrowserWindow');for(const token of ['await windowsProductionWiring.assertAvailable()','credentialAuthority=await','pendingReplacement=await','await initialBinding?.commit?.()'])assert(launch.indexOf(token)>=0&&launch.indexOf(token)<window)})
