'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),{run,committedCleanup}=require('../database-manager');
function maintenance(){const c=new EventEmitter();c.pid=99;c.exitCode=null;c.signalCode=null;c.stdout=new PassThrough();c.stderr=new PassThrough();c.kill=()=>{};return c}
function killer(code,onKill=()=>{}){const c=new EventEmitter();queueMicrotask(()=>{onKill();c.emit('exit',code)});return c}
const systemEnv={SystemRoot:'C:\\Windows',PATH:'hostile'};
test('Windows timeout settles only after trusted taskkill exit 0 and maintenance exit confirmation',async()=>{const child=maintenance();let call,settled=false;const pending=run('maintenance',[],{},()=>child,1,{platform:'win32',systemEnv,killSpawn:(...args)=>(call=args,killer(0,()=>{child.exitCode=1;child.emit('exit',1)}))});pending.finally(()=>settled=true).catch(()=>{});await assert.rejects(pending,/timed out/);assert.equal(settled,true);assert.deepEqual(call,['C:\\Windows\\System32\\taskkill.exe',['/PID','99','/T','/F'],{stdio:'ignore',windowsHide:true,env:{SystemRoot:'C:\\Windows',WINDIR:'C:\\Windows'}}])});
test('Windows timeout taskkill exit 0 without child exit rejects recovery-required stop-uncertain',async()=>{const child=maintenance();await assert.rejects(run('maintenance',[],{},()=>child,1,{platform:'win32',systemEnv,killSpawn:()=>killer(0)}),error=>error.code==='DATABASE_MAINTENANCE_STOP_UNCERTAIN'&&error.recoveryRequired===true&&error.stage==='maintenance-stop-uncertain'&&error.cause.errors[0].message==='database maintenance timed out')});
test('Windows timeout taskkill nonzero fails closed and preserves timeout cause',async()=>{const child=maintenance();await assert.rejects(run('maintenance',[],{},()=>child,1,{platform:'win32',systemEnv,killSpawn:()=>killer(1)}),error=>error.code==='DATABASE_MAINTENANCE_STOP_UNCERTAIN'&&error.recoveryRequired===true&&error.cause.errors[0].message==='database maintenance timed out'&&error.cause.errors[1].message==='taskkill failed (1)')});
test('Windows timeout fails closed when trusted SystemRoot is unavailable',async()=>{const child=maintenance();await assert.rejects(run('maintenance',[],{},()=>child,1,{platform:'win32',systemEnv:{PATH:'hostile'},killSpawn:()=>assert.fail('must not spawn')}),error=>error.code==='DATABASE_MAINTENANCE_STOP_UNCERTAIN'&&error.recoveryRequired===true)});

test('committed cleanup deadline waits for restart action to settle and confirmed stop, then rejects without reload or rollback continuation',async()=>{const controller=new AbortController(),events=[],journal={phase:'committed'};let releaseStart,releaseStop;const startReady=new Promise(resolve=>releaseStart=resolve),stopConfirmed=new Promise(resolve=>releaseStop=resolve);const pending=committedCleanup({platform:'win32',signal:controller.signal,report:x=>events.push(x),cleanup:async()=>events.push('cleanup'),startSidecar:async()=>{events.push('restart-entered');await startReady;events.push('restart-ready')},stopSidecar:async()=>{events.push('stop-entered');if(events.filter(x=>x==='stop-entered').length===2){await stopConfirmed;events.push('stop-confirmed')}},reload:async()=>events.push('reload')});await new Promise(resolve=>setImmediate(resolve));const timeout=Object.assign(Error('deadline'),{code:'DATABASE_OPERATION_TIMEOUT',recoveryRequired:true});controller.abort(timeout);let settled=false;pending.finally(()=>settled=true).catch(()=>{});assert.equal(settled,false);releaseStart();await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);releaseStop();await assert.rejects(pending,error=>error===timeout);assert.equal(journal.phase,'committed');assert.deepEqual(events,['before-replacement-cleanup-stop','stop-entered','after-replacement-cleanup-stop','cleanup','before-replacement-cleanup-restart','restart-entered','restart-ready','after-replacement-cleanup-restart','stop-entered','stop-confirmed']);assert.equal(events.includes('reload'),false)});
test('committed cleanup deadline confirmed-stop failure is recovery-required and leaves committed journal exact',async()=>{const controller=new AbortController(),journal={phase:'committed',transitionId:'exact'},events=[];let releaseStart;const pending=committedCleanup({platform:'win32',signal:controller.signal,stopSidecar:async()=>{events.push('stop');if(events.length===2)throw Error('unconfirmed')},cleanup:async()=>{},startSidecar:()=>new Promise(resolve=>releaseStart=resolve),reload:async()=>events.push('reload')});await new Promise(resolve=>setImmediate(resolve));const timeout=Object.assign(Error('deadline'),{code:'DATABASE_OPERATION_TIMEOUT',recoveryRequired:true});controller.abort(timeout);releaseStart();await assert.rejects(pending,error=>error.recoveryRequired===true&&error.stage==='sidecar-abort-stop'&&error.cause.errors[0]===timeout);assert.deepEqual(journal,{phase:'committed',transitionId:'exact'});assert.equal(events.includes('reload'),false)});
