'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {committedCleanup}=require('../database-manager');

test('Windows committed cleanup stops, consumes cleanup, restarts, then reloads ordinary sidecar',async()=>{const events=[];const cause=await committedCleanup({platform:'win32',stopSidecar:async()=>events.push('stop'),cleanup:async()=>events.push('cleanup'),startSidecar:async()=>events.push('start'),reload:async()=>events.push('reload'),report:x=>events.push(x)});assert.equal(cause,null);assert.deepEqual(events,['before-replacement-cleanup-stop','stop','after-replacement-cleanup-stop','cleanup','before-replacement-cleanup-restart','start','after-replacement-cleanup-restart','before-replacement-cleanup-reload','reload','after-replacement-cleanup-reload'])});

test('ordinary committed restart port fallback reloads and probes only the new origin',async()=>{let origin='http://127.0.0.1:4100',loaded=null,healthy=null,marker=false;await committedCleanup({platform:'win32',stopSidecar:async()=>{},cleanup:async()=>{},startSidecar:async()=>{origin='http://127.0.0.1:4200'},reload:async()=>{loaded=origin;healthy=`${origin}/api/health/deep`;marker=true}});assert.equal(loaded,'http://127.0.0.1:4200');assert.equal(healthy,'http://127.0.0.1:4200/api/health/deep');assert.equal(marker,true);assert.notEqual(loaded,'http://127.0.0.1:4100')});

test('Windows committed cleanup stop failure does not run cleanup or report success',async()=>{const events=[],journal={phase:'committed'};await assert.rejects(committedCleanup({platform:'win32',stopSidecar:async()=>{events.push('stop');throw Error('stop failed')},cleanup:async()=>{journal.phase='consumed';events.push('cleanup')},startSidecar:async()=>events.push('start')}),error=>error.recoveryRequired===true&&error.stage==='sidecar-stop'&&error.cause?.message==='stop failed');assert.deepEqual(events,['stop']);assert.equal(journal.phase,'committed')});

test('Windows committed cleanup failure preserves cause and reliably restarts/reloads',async()=>{const events=[],expected=Error('cleanup failed'),cause=await committedCleanup({platform:'win32',stopSidecar:async()=>events.push('stop'),cleanup:async()=>{events.push('cleanup');throw expected},startSidecar:async()=>events.push('start'),reload:async()=>events.push('reload')});assert.equal(cause,expected);assert.deepEqual(events,['stop','cleanup','start','reload'])});

test('abort after start entered confirms restarted sidecar stop and never reloads',async()=>{const controller=new AbortController(),events=[];let releaseStart;const startReady=new Promise(resolve=>releaseStart=resolve),run=committedCleanup({platform:'win32',signal:controller.signal,stopSidecar:async()=>events.push('stop'),cleanup:async()=>events.push('cleanup'),startSidecar:async()=>{events.push('start-enter');await startReady;events.push('start-ready')},reload:async()=>events.push('reload')});await new Promise(resolve=>setImmediate(resolve));controller.abort(Object.assign(Error('deadline'),{code:'DATABASE_OPERATION_TIMEOUT',recoveryRequired:true}));releaseStart();await assert.rejects(run,error=>error.code==='DATABASE_OPERATION_TIMEOUT');assert.deepEqual(events,['stop','cleanup','start-enter','start-ready','stop']);assert.equal(events.includes('reload'),false)});

test('abort stop failure aggregates timeout and confirmed-stop failure',async()=>{const controller=new AbortController();let stops=0,releaseStart;const run=committedCleanup({platform:'win32',signal:controller.signal,stopSidecar:async()=>{if(++stops===2)throw Error('stop failed')},cleanup:async()=>{},startSidecar:()=>new Promise(resolve=>releaseStart=resolve),reload:async()=>assert.fail('must not reload')});await new Promise(resolve=>setImmediate(resolve));const timeout=Object.assign(Error('deadline'),{code:'DATABASE_OPERATION_TIMEOUT',recoveryRequired:true});controller.abort(timeout);releaseStart();await assert.rejects(run,error=>error.recoveryRequired===true&&error.stage==='sidecar-abort-stop'&&error.cause instanceof AggregateError&&error.cause.errors[0]===timeout&&error.cause.errors[1].message==='stop failed')});

test('Windows committed cleanup restart failure is recovery-required, including cleanup cause',async()=>{const cleanup=Error('cleanup failed'),restart=Error('restart failed');await assert.rejects(committedCleanup({platform:'win32',stopSidecar:async()=>{},cleanup:async()=>{throw cleanup},startSidecar:async()=>{throw restart}}),error=>error.recoveryRequired===true&&error.stage==='sidecar-restart'&&error.cause instanceof AggregateError&&error.cause.errors[0]===cleanup&&error.cause.errors[1]===restart)});

test('post-commit reload failure is recovery-required and does not undo committed cleanup',async()=>{let cleaned=false;await assert.rejects(committedCleanup({platform:'win32',stopSidecar:async()=>{},cleanup:async()=>{cleaned=true},startSidecar:async()=>{},reload:async()=>{throw Error('marker missing')}}),error=>error.recoveryRequired===true&&error.stage==='renderer-reload'&&error.cause.message==='marker missing');assert.equal(cleaned,true)});
