'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');const {refreshGate,refreshIfEligible,installActivatedCertificate}=require('../license-refresh-orchestrator');const {createActivationProvenanceStore}=require('../activation-provenance-store');const {verifyInstalledCertificateIdentity}=require('../activation-refresh');
const {offlineGrace}=require('../license-refresh-policy');
const {verifyRefreshedCertificate}=require('../activation-refresh');
const A={license_id:'A',activation_id:'gma_'+'a'.repeat(32),issued_at:'2026-08-01T00:00:00Z',next_check_in_at:'2026-08-13T00:00:00Z',expires_at:null,revoked_at:null},B={license_id:'B',activation_id:'gma_'+'b'.repeat(32)},enc=v=>Buffer.from(v),dec=b=>b.toString();
test('failed initial backend import preserves exact installed and committed certificate, discarding pending',async()=>{const b=fixture(),source=b.installed,dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-orch-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(A)+'\n');p.begin(A,'payment');p.promote(A);const certBytes=fs.readFileSync(file),provBytes=fs.readFileSync(p.paths.committed);await assert.rejects(()=>installActivatedCertificate({certificate:source,flowKind:'gift',provenance:p,verify:c=>verifyInitial(b,c),importCertificate:async()=>{throw Error('backend import failed');},readInstalled:async()=>JSON.parse(fs.readFileSync(file))}));assert.deepEqual(fs.readFileSync(file),certBytes);assert.deepEqual(fs.readFileSync(p.paths.committed),provBytes);assert.equal(fs.existsSync(p.paths.pending),false);});
test('crash cut points reconcile pending before import and import before promote',()=>{for(const imported of [false,true]){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-crash-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(A));p.begin(A,'payment');p.promote(A);p.begin(B,'gift');if(imported)fs.writeFileSync(file,JSON.stringify(B));const installed=JSON.parse(fs.readFileSync(file));assert.equal(p.reconcile(installed).state,imported?'promoted':'discarded');assert.equal(p.read(installed),imported?'gift':'payment');}});
function verifyInitial(base,source){return verifyRefreshedCertificate({candidate:source,deviceIdentity:base.deviceIdentity,authorityPublicKeyPem:base.authorityPublicKeyPem,now:new Date('2026-08-12T00:00:00Z')});}
function fixture(){const devicePair=crypto.generateKeyPairSync('ed25519'),authorityPair=crypto.generateKeyPairSync('ed25519'),publicKey=devicePair.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('base64'),deviceIdentity={publicKey,privateKeyPem:devicePair.privateKey.export({format:'pem',type:'pkcs8'}).toString()},installed={schema_version:2,certificate_type:'growthmap_device_activation',product:'growthmap',edition:'pro',license_id:'A',activation_id:'gma_'+'a'.repeat(32),major_version:1,device_allowance:1,device_id:'gmdev_'+crypto.createHash('sha256').update(Buffer.from(publicKey,'base64')).digest('hex'),device_public_key:publicKey,issued_at:'2026-08-01T00:00:00Z',expires_at:null,revoked_at:null,max_active_projects:null,next_check_in_at:'2026-08-13T00:00:00Z',signature:''};const payload=Object.fromEntries(Object.entries(installed).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));installed.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),authorityPair.privateKey).toString('base64');const entitlement={state:'paid',reason:'valid',license_id:'A',edition:'pro',major_version:1,device_allowance:1,max_active_projects:null},authorityPublicKeyPem=authorityPair.publicKey.export({format:'pem',type:'spki'}),installedCapability=verifyInstalledCertificateIdentity({certificate:installed,entitlement,deviceIdentity,authorityPublicKeyPem,currentMajor:1,now:new Date('2026-08-12T00:00:00Z')});const signCandidate=(overrides={})=>{const c={...installed,issued_at:'2026-08-13T00:00:00Z',next_check_in_at:'2026-08-20T00:00:00Z',...overrides,signature:''},payload=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='signature').sort(([a],[b])=>a<b?-1:a>b?1:0));c.signature=crypto.sign(null,Buffer.concat([Buffer.from('growthmap-activation-certificate-v2\0'),Buffer.from(JSON.stringify(payload))]),authorityPair.privateKey).toString('base64');return c;};return {entitlement,installed,installedCapability,deviceIdentity,authorityPublicKeyPem,revocationState:'none',freshnessState:{licenseId:'A'},flowKind:'payment',activationApiOrigin:'https://activation.test',now:new Date('2026-08-13T01:00:00Z'),signCandidate};}
test('gate requires unforgeable verifier capability and exact bound references',()=>{const base=fixture();assert(refreshGate(base));for(const patch of [{installedCapability:{}},{installed:{...base.installed}},{entitlement:{...base.entitlement}},{freshnessState:null},{freshnessState:{invalid:true,licenseId:'A'}},{revocationState:'accepted'},{flowKind:null}])assert.equal(refreshGate({...base,...patch}),false);});
test('same-license swaps have zero fetch and import opportunity',async()=>{const base=fixture();for(const patch of [{signature:Buffer.alloc(64).toString('base64')},{product:'other'},{major_version:2},{edition:'personal'},{device_allowance:2},{expires_at:'2026-08-11T00:00:00Z'},{revoked_at:'2026-08-11T00:00:00Z'}]){let fetches=0,imports=0;const result=await refreshIfEligible({...base,installed:{...base.installed,...patch},fetchImpl:async()=>{fetches++;},importCertificate:async()=>{imports++;}});assert.equal(result.state,'skipped');assert.equal(fetches,0);assert.equal(imports,0);}});
test('same-object certificate and authoritative entitlement mutation invalidates verified capability',()=>{
 const now=new Date('2026-08-13T01:00:00Z');
 function limitedFixture(){const base=fixture(),entitlement={state:'extraction',reason:'check_in_required',license_id:'A',major_version:1,edition:'pro',device_allowance:1,max_active_projects:null};base.entitlement=entitlement;base.freshnessState={licenseId:'A',lastSeenAt:'2026-08-13T00:30:00Z'};base.installedCapability=verifyInstalledCertificateIdentity({certificate:base.installed,entitlement,deviceIdentity:base.deviceIdentity,authorityPublicKeyPem:base.authorityPublicKeyPem,currentMajor:1,now:new Date('2026-08-12T00:00:00Z')});return base;}
 function assertInvalidated(mutate){const base=limitedFixture();assert.equal(refreshGate(base),true,'overdue certificate is refresh eligible before mutation');assert(offlineGrace({entitlement:base.entitlement,certificate:base.installed,installedCapability:base.installedCapability,freshnessState:base.freshnessState,revocationState:'none',now}));mutate(base);assert.equal(refreshGate(base),false);assert.equal(offlineGrace({entitlement:base.entitlement,certificate:base.installed,installedCapability:base.installedCapability,freshnessState:base.freshnessState,revocationState:'none',now}),null);}
 const certificateMutations=[
  b=>{b.installed.signature='INVALID';},b=>{b.installed.major_version=999;},b=>{b.installed.device_public_key='changed';},b=>{b.installed.device_id='gmdev_changed';},b=>{b.installed.license_id='changed';},
  b=>{b.installed.issued_at='2026-08-01T00:00:01Z';},b=>{b.installed.next_check_in_at='2026-08-13T00:00:01Z';},b=>{b.installed.expires_at='2027-01-01T00:00:00Z';},b=>{b.installed.revoked_at='2027-01-01T00:00:00Z';},
  b=>{b.installed.product='other';},b=>{b.installed.edition='personal';},b=>{b.installed.device_allowance=2;},b=>{b.installed.max_active_projects=1;},b=>{b.installed.extra_field=true;}
 ];
 const entitlementMutations=[
  b=>{b.entitlement.license_id='changed';},b=>{b.entitlement.major_version=2;},b=>{b.entitlement.reason='valid';},b=>{b.entitlement.state='paid';},b=>{b.entitlement.edition='personal';},b=>{b.entitlement.device_allowance=2;},b=>{b.entitlement.max_active_projects=1;},b=>{b.entitlement.extra_field=true;}
 ];
 for(const mutate of [...certificateMutations,...entitlementMutations])assertInvalidated(mutate);
});

function wireRefresh(base,{mutate,importCertificate,provenance,readInstalled}={}){let calls=0;const candidate=base.signCandidate();return {...base,receivedCandidate:candidate,provenance:provenance||{begin(){},promote(){},reconcile(){}},readInstalled:readInstalled||(async()=>base.installed),importCertificate:importCertificate||(async()=>{}),fetchImpl:async()=>{calls++;if(mutate)mutate(calls,base);return calls===1?{ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({state:'challenge_issued',challenge:{challenge_id:'gmr_'+ 'a'.repeat(32),nonce:'0123456789abcdef',activation_id:base.installed.license_id==='A'?base.installed.activation_id:'gma_'+ 'a'.repeat(32),license_id:'A',device_public_key:base.deviceIdentity.publicKey}})}:{ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({state:'activated',certificate:candidate})};}};}
test('post-gate same-object mutation at asynchronous cutpoints fails closed with zero import',async()=>{const cases=[
 [1,b=>{b.installed.edition='personal';}], [1,b=>{b.installed.signature='bad';}], [2,b=>{b.installed.license_id='other';}], [2,b=>{b.installed.activation_id='gma_'+ 'b'.repeat(32);}],
 [1,b=>{b.installed.major_version=2;}], [2,b=>{b.installed.device_id='gmdev_bad';}], [1,b=>{b.installed.product='other';}], [2,b=>{b.installed.issued_at='2026-08-01T00:00:01Z';}],
 [1,b=>{b.installed.next_check_in_at='2026-08-13T00:00:01Z';}], [2,b=>{b.entitlement.edition='personal';}], [1,b=>{b.entitlement.license_id='other';}], [2,b=>{Object.defineProperty(b.installed,'edition',{get(){return 'pro';},configurable:true});}],
 [1,b=>{b.installed[Symbol('x')]=1;}], [2,b=>{b.entitlement.extra={};b.entitlement.extra.self=b.entitlement.extra;}]
 ];for(const [phase,change] of cases){const b=fixture();let imports=0;await assert.rejects(()=>refreshIfEligible(wireRefresh(b,{mutate:(call,x)=>{if(call===phase)change(x);},importCertificate:async()=>{imports++;}})));assert.equal(imports,0);}});
test('mutation immediately before import is rejected and pending reconciles to exact old provenance',async()=>{const b=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-race-')),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});p.begin(b.installed,'payment');p.promote(b.installed);const bytes=fs.readFileSync(p.paths.committed);const begin=p.begin.bind(p);p.begin=(c,f)=>{const r=begin(c,f);b.entitlement.device_allowance=2;return r;};let imports=0;await assert.rejects(()=>refreshIfEligible(wireRefresh(b,{provenance:p,readInstalled:async()=>b.installed,importCertificate:async()=>{imports++;}})));assert.equal(imports,0);assert.deepEqual(fs.readFileSync(p.paths.committed),bytes);assert.equal(p.inspect().pending.state,'none');});
test('refresh durable transaction reconciles reject-before-mutation and landed-then-reject',async()=>{for(const landed of [false,true]){const b=fixture(),candidate=b.signCandidate(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-refresh-tx-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(b.installed)+'\n');p.begin(b.installed,'payment');p.promote(b.installed);const certBytes=fs.readFileSync(file),provBytes=fs.readFileSync(p.paths.committed);await assert.rejects(()=>refreshIfEligible({...wireRefresh(b),provenance:p,readInstalled:async()=>JSON.parse(fs.readFileSync(file)),importCertificate:async()=>{if(landed)fs.writeFileSync(file,JSON.stringify(candidate));throw Error('ambiguous import');}}));if(landed){assert.equal(p.inspect().pending.state,'none');assert.equal(p.read(candidate),'payment');}else{assert.deepEqual(fs.readFileSync(file),certBytes);assert.deepEqual(fs.readFileSync(p.paths.committed),provBytes);assert.equal(p.inspect().pending.state,'none');}}});
test('refresh promote failure after candidate landing reconciles candidate before returning failure',async()=>{const b=fixture(),candidate=b.signCandidate(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-promote-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(b.installed));p.begin(b.installed,'payment');p.promote(b.installed);const promote=p.promote.bind(p);let once=true;p.promote=c=>{if(once){once=false;throw Error('durable write failed');}return promote(c);};await assert.rejects(()=>refreshIfEligible({...wireRefresh(b),provenance:p,readInstalled:async()=>JSON.parse(fs.readFileSync(file)),importCertificate:async()=>fs.writeFileSync(file,JSON.stringify(candidate))}),/durable write failed/);assert.equal(p.read(candidate),'payment');assert.equal(p.inspect().pending.state,'none');});
test('restart reconciliation preserves pending evidence for neither/malformed actual',()=>{for(const actual of [null,{license_id:'neither',activation_id:'gma_'+ 'c'.repeat(32)}]){const b=fixture(),candidate=b.signCandidate(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-restart-')),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});p.begin(b.installed,'payment');p.promote(b.installed);const committed=fs.readFileSync(p.paths.committed);p.begin(candidate,'payment');assert.equal(p.reconcile(actual).state,'invalid');assert.deepEqual(fs.readFileSync(p.paths.committed),committed);assert.equal(p.inspect().pending.state,'valid');}});
test('hostile provenance begin cannot mutate private candidate and import receives the same frozen snapshot',async()=>{
 const b=fixture();let provenanceCandidate,imported,imports=0;
 const provenance={begin(candidate){provenanceCandidate=candidate;assert(Object.isFrozen(candidate));assert.throws(()=>{candidate.edition='personal';},TypeError);assert.throws(()=>Object.defineProperty(candidate,'hidden',{value:true}),TypeError);},promote(candidate){assert.strictEqual(candidate,provenanceCandidate);},reconcile(){}};
 const result=await refreshIfEligible(wireRefresh(b,{provenance,importCertificate:async candidate=>{imports++;imported=candidate;assert(Object.isFrozen(candidate));}}));
 assert.equal(imports,1);assert.strictEqual(imported,provenanceCandidate);assert.strictEqual(result.certificate,provenanceCandidate);assert.equal(imported.edition,'pro');
});
test('hostile provenance mutation attempt that aborts begin has zero import',async()=>{
 const b=fixture();let imports=0;const provenance={begin(candidate){assert.equal(Reflect.set(candidate,'edition','personal'),false);throw Error('hostile begin aborted');},promote(){},reconcile(){}};
 await assert.rejects(()=>refreshIfEligible(wireRefresh(b,{provenance,importCertificate:async()=>{imports++;}})),/hostile begin aborted/);assert.equal(imports,0);
});
test('provenance begin mutations of every complete candidate dimension fail closed before import and preserve exact old provenance',async()=>{
 const mutations=[
  c=>{c.signature='attacker';},c=>{c.license_id='other';},c=>{c.activation_id='gma_'+ 'b'.repeat(32);},c=>{c.device_id='gmdev_other';},c=>{c.device_public_key='other';},c=>{c.edition='personal';},c=>{c.major_version=2;},c=>{c.device_allowance=2;},c=>{c.certificate_type='other';},c=>{c.product='other';},c=>{c.schema_version=3;},c=>{c.issued_at='2026-08-14T00:00:00Z';},c=>{c.next_check_in_at='2026-08-21T00:00:00Z';},c=>{c.expires_at='2027-01-01T00:00:00Z';},c=>{c.revoked_at='2026-08-14T00:00:00Z';},c=>{c.max_active_projects=1;},
  c=>{c.extra=true;},c=>{delete c.product;},c=>{c.major_version='1';},c=>Object.defineProperty(c,'edition',{get(){return 'pro';},configurable:true}),c=>{c[Symbol('hidden')]=true;},c=>Object.defineProperty(c,'hidden',{value:true,enumerable:false}),c=>{c.extra={};c.extra.self=c.extra;}
 ];
 for(const mutate of mutations){const b=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-candidate-race-')),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});p.begin(b.installed,'payment');p.promote(b.installed);const committed=fs.readFileSync(p.paths.committed),wired=wireRefresh(b),begin=p.begin.bind(p);p.begin=(snapshot,flow)=>{begin(snapshot,flow);mutate(snapshot);};let imports=0;await assert.rejects(()=>refreshIfEligible({...wired,provenance:p,readInstalled:async()=>b.installed,importCertificate:async()=>{imports++;}}),TypeError);assert.equal(imports,0);assert.deepEqual(fs.readFileSync(p.paths.committed),committed);assert.equal(p.inspect().pending.state,'none');}
});
test('candidate source mutation after import is detected before promote and reconciles landed snapshot',async()=>{
 const b=fixture(),wired=wireRefresh(b),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-candidate-post-import-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(b.installed));p.begin(b.installed,'payment');p.promote(b.installed);await assert.rejects(()=>refreshIfEligible({...wired,provenance:p,readInstalled:async()=>JSON.parse(fs.readFileSync(file)),importCertificate:async snapshot=>{fs.writeFileSync(file,JSON.stringify(snapshot));assert.equal(Reflect.set(snapshot,'signature','attacker'),false);throw Error('hostile post-import callback');}}),/hostile post-import callback/);assert.equal(p.inspect().pending.state,'none');assert.equal(p.read(JSON.parse(fs.readFileSync(file))),'payment');
});

test('initial activation uses one frozen verifier capability snapshot for payment and Gift flows',async()=>{
 for(const flowKind of ['payment','gift']){const b=fixture(),source={...b.installed};let begun,imported,promoted;
  const provenance={begin(snapshot,flow){assert.equal(flow,flowKind);begun=snapshot;assert(Object.isFrozen(snapshot));assert.equal(Reflect.set(snapshot,'edition','personal'),false);},promote(snapshot){promoted=snapshot;},reconcile(){}};
  const result=await installActivatedCertificate({certificate:source,flowKind,provenance,verify:c=>verifyInitial(b,c),importCertificate:async snapshot=>{imported=snapshot;assert.equal(Reflect.set(snapshot,'signature','attacker'),false);},readInstalled:async()=>source});
  assert.strictEqual(begun,imported);assert.strictEqual(imported,promoted);assert.strictEqual(promoted,result);assert(Object.isFrozen(result));assert.equal(result.edition,'pro');
 }
});
test('Security R6 hostile begin mutation of original source fails closed for payment and Gift without affecting the verified snapshot',async()=>{
 for(const flowKind of ['payment','gift']){const b=fixture(),source={...b.installed},dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-initial-r6-')),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});p.begin(A,'payment');p.promote(A);const committed=fs.readFileSync(p.paths.committed),begin=p.begin.bind(p);let begun,imports=0,promotes=0;p.begin=(snapshot,flow)=>{begin(snapshot,flow);begun=snapshot;assert.equal(flow,flowKind);source.edition='attacker';assert.equal(snapshot.edition,'pro');};p.promote=()=>{promotes++;};
  await assert.rejects(()=>installActivatedCertificate({certificate:source,flowKind,provenance:p,verify:c=>verifyInitial(b,c),importCertificate:async()=>{imports++;},readInstalled:async()=>A}),/changed during the transaction/);
  assert(Object.isFrozen(begun));assert.equal(begun.edition,'pro');assert.equal(imports,0);assert.equal(promotes,0);assert.deepEqual(fs.readFileSync(p.paths.committed),committed);assert.equal(p.inspect().pending.state,'none');
 }
});
test('initial activation rejects forged, missing, mutable, foreign, and source-mutated verifier returns with zero import',async()=>{
 const factories=[
  (b,s)=>({...s}),(b,s)=>s,(b,s)=>{s.edition='personal';return verifyInitial(b,s);},()=>undefined,()=>7,(b,s)=>Object.freeze({...s}),
  (b,s)=>{const foreign={...s};return verifyInitial(b,foreign);}
 ];
 for(const make of factories){const b=fixture(),source={...b.installed};let imports=0,begins=0;await assert.rejects(()=>installActivatedCertificate({certificate:source,flowKind:'payment',provenance:{begin(){begins++;},promote(){},reconcile(){}},verify:s=>make(b,s),importCertificate:async()=>{imports++;},readInstalled:async()=>A}));assert.equal(imports,0);assert.equal(begins,0);}
});
test('initial source mutation after exact snapshot landing reconciles and promotes landed snapshot',async()=>{
 const b=fixture(),source={...b.installed},dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-initial-landed-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(A));p.begin(A,'payment');p.promote(A);let landed;
 await assert.rejects(()=>installActivatedCertificate({certificate:source,flowKind:'gift',provenance:p,verify:c=>verifyInitial(b,c),importCertificate:async snapshot=>{landed=snapshot;fs.writeFileSync(file,JSON.stringify(snapshot));source.edition='attacker';},readInstalled:async()=>JSON.parse(fs.readFileSync(file))}),/changed during the transaction/);
 assert(Object.isFrozen(landed));assert.equal(p.read(JSON.parse(fs.readFileSync(file))),'gift');assert.equal(p.inspect().pending.state,'none');
});
test('initial ambiguous import and promote failures reconcile only exact stable landing and preserve neither evidence',async()=>{
 for(const mode of ['before','after','promote','neither']){const b=fixture(),source={...b.installed},dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-initial-ambiguous-')),file=path.join(dir,'license.json'),p=createActivationProvenanceStore({userData:dir,encrypt:enc,decrypt:dec});fs.writeFileSync(file,JSON.stringify(A));p.begin(A,'payment');p.promote(A);const committed=fs.readFileSync(p.paths.committed);let verified;const promote=p.promote.bind(p);if(mode==='promote')p.promote=()=>{throw Error('promote failed');};
  await assert.rejects(()=>installActivatedCertificate({certificate:source,flowKind:'gift',provenance:p,verify:c=>(verified=verifyInitial(b,c)),importCertificate:async snapshot=>{if(mode!=='before')fs.writeFileSync(file,JSON.stringify(mode==='neither'?B:snapshot));if(mode!=='promote')throw Error('ambiguous import');},readInstalled:async()=>JSON.parse(fs.readFileSync(file))}));
  if(mode==='after'||mode==='promote'){assert.equal(p.read(verified),'gift');assert.equal(p.inspect().pending.state,'none');}else if(mode==='before'){assert.deepEqual(fs.readFileSync(p.paths.committed),committed);assert.equal(p.inspect().pending.state,'none');}else{assert.deepEqual(fs.readFileSync(p.paths.committed),committed);assert.equal(p.inspect().pending.state,'valid');}
  p.promote=promote;
 }
});
