const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{createReplacementJournal}=require('../replacement-journal'),{recoverReplacement}=require('../replacement-recovery'),{listing}=require('./replacement-oracle');
const id='11111111-1111-4111-8111-111111111111',crypt={encrypt:s=>Buffer.from(s).toString('base64'),decrypt:b=>Buffer.from(String(b),'base64').toString()},ev=b=>({sha256:crypto.createHash('sha256').update(b).digest('hex'),size:b.length}),a0={schemaVersion:1,bindings:{}},a1={schemaVersion:1,bindings:{'/db':{identity:{platform:'posix',path:'/db',device:'1',inode:'2'},lineage:id,legacyAdopted:false}}};
function auth(state){return {matches:v=>JSON.stringify(v)===JSON.stringify(state),restore(){}}}
function capture(file){const s=fs.lstatSync(file),base={type:s.isFile()?'file':s.isSymbolicLink()?'symlink':'other',isSymbolicLink:s.isSymbolicLink(),nlink:s.nlink,dev:String(s.dev),ino:String(s.ino)};if(s.isSymbolicLink())return {...base,link:fs.readlinkSync(file)};const bytes=fs.readFileSync(file);return {...base,bytes,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}}
for(const kind of ['failed-wrong','failed-symlink','failed-hardlink','quarantine-wrong','quarantine-symlink','quarantine-hardlink'])test(`pre-existing malicious ${kind} fails closed with byte- and identity-stable directory`,async()=>{const user=fs.mkdtempSync(path.join(os.tmpdir(),'gm-malicious-')),db=path.join(user,'growthmap.db'),j=createReplacementJournal({userData:user,...crypt});fs.writeFileSync(db,'NEW');let i=j.begin({transitionId:id,mode:'foreign-import',databasePath:db,oldEvidence:ev(Buffer.from('OLD')),newEvidence:ev(Buffer.from('NEW')),authorityPre:a0});i=j.update(i,{authorityNew:a1,phase:kind.startsWith('quarantine')?'committed':'db-installed'});fs.writeFileSync(i.oldPath,'OLD');const target=kind.startsWith('failed')?i.failedPath:i.quarantinePath;if(kind.endsWith('wrong'))fs.writeFileSync(target,'EVIL');else if(kind.endsWith('symlink'))fs.symlinkSync(i.oldPath,target);else fs.linkSync(i.oldPath,target);
 const journalPath=path.join(user,'secrets','replacement-intent.bin'),before={listing:listing(db),db:capture(db),old:capture(i.oldPath),target:capture(target),journal:fs.readFileSync(journalPath)};
 if(kind.endsWith('hardlink')){assert.equal(before.target.ino,before.old.ino);assert.equal(before.target.dev,before.old.dev);assert.equal(before.target.nlink,2);assert.equal(before.old.nlink,2)}if(kind.endsWith('symlink'))assert.equal(before.target.link,i.oldPath);
 await assert.rejects(recoverReplacement({platform:'linux',journal:j,authority:auth(kind.startsWith('failed')?a0:a1),validate:async f=>ev(fs.readFileSync(f)),databasePath:db,fsyncDir:async()=>{}}));
 const after={listing:listing(db),db:capture(db),old:capture(i.oldPath),target:capture(target),journal:fs.readFileSync(journalPath)};assert.deepEqual(after,before);assert.deepEqual(after.listing,before.listing);assert.equal(fs.existsSync(i.stagingPath),false);assert.equal(fs.existsSync(i.capturePath),false);
});
