const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createReplacementJournal}=require('../replacement-journal'),{recoverReplacement}=require('../replacement-recovery');
const root=()=>fs.mkdtempSync(path.join(os.tmpdir(),'gm-journal-')),crypt={encrypt:s=>Buffer.from(s).toString('base64'),decrypt:b=>Buffer.from(String(b),'base64').toString()};
function journal(user){return createReplacementJournal({userData:user,...crypt})}function evidence(file){const b=fs.readFileSync(file);return {sha256:require('node:crypto').createHash('sha256').update(b).digest('hex'),size:b.length}}
function authority(initial){let state=structuredClone(initial);return {load:()=>structuredClone(state),matches:v=>JSON.stringify(v)===JSON.stringify(state),restore:v=>state=structuredClone(v),set:v=>state=structuredClone(v)}}
async function fixture(authorityNew=false){const user=root(),live=path.join(user,'growthmap.db'),old=`${live}.gm-old-11111111-1111-4111-8111-111111111111`,a0={schemaVersion:1,bindings:{'/db':{identity:{platform:'posix',path:'/db',device:'1',inode:'1'},lineage:'11111111-1111-4111-8111-111111111111',legacyAdopted:false}}},a1={schemaVersion:1,bindings:{'/db':{identity:{platform:'posix',path:'/db',device:'1',inode:'2'},lineage:'11111111-1111-4111-8111-111111111111',legacyAdopted:false}}};fs.writeFileSync(old,'OLD');fs.writeFileSync(live,'NEW');const j=journal(user);let i=j.begin({transitionId:'11111111-1111-4111-8111-111111111111',mode:'managed-restore',databasePath:live,oldPath:old,oldEvidence:evidence(old),newEvidence:evidence(live),authorityPre:a0});i=j.update(i,{newEvidence:evidence(live),authorityNew:a1,phase:authorityNew?'committed':'db-installed'});const a=authority(authorityNew?a1:a0);return {user,live,old,j,i,a,a0,a1}}
const validate=async file=>evidence(file),sync=async()=>{};
test('durable intent before install aborts cleanly when live is still exact old DB',async()=>{const user=root(),live=path.join(user,'growthmap.db'),old=`${live}.gm-old-11111111-1111-4111-8111-111111111111`,a0={schemaVersion:1,bindings:{'/db':{identity:{platform:'posix',path:'/db',device:'1',inode:'1'},lineage:'11111111-1111-4111-8111-111111111111',legacyAdopted:false}}},j=journal(user);fs.writeFileSync(live,'OLD');j.begin({transitionId:'11111111-1111-4111-8111-111111111111',mode:'managed-restore',databasePath:live,oldPath:old,oldEvidence:evidence(live),newEvidence:evidence(live),authorityPre:a0});const r=await recoverReplacement({platform:'linux',journal:j,authority:authority(a0),validate,databasePath:live,fsyncDir:sync});assert.equal(r.outcome,'aborted-before-install');assert.equal(fs.readFileSync(live,'utf8'),'OLD');assert.equal(j.read().phase,'aborted-durable')});
test('cross-process-style restart with old authority durably rolls DB and authority back',async()=>{const f=await fixture(false),r=await recoverReplacement({platform:'linux',journal:f.j,authority:f.a,validate,databasePath:f.live,fsyncDir:sync});assert.equal(r.outcome,'rolled-back');assert.equal(fs.readFileSync(f.live,'utf8'),'OLD');assert(['rollback-durable','aborted-durable'].includes(f.j.read()?.phase));assert(f.a.matches(f.a0))});
test('restart with new authority accepts exact new DB and quarantines old',async()=>{const f=await fixture(true),r=await recoverReplacement({platform:'linux',journal:f.j,authority:f.a,validate,databasePath:f.live,fsyncDir:sync});assert.equal(r.outcome,'committed');assert.equal(fs.readFileSync(f.live,'utf8'),'NEW');assert.equal(f.j.read().phase,'cleanup-durable');assert(fs.readdirSync(f.user).some(x=>x.includes('gm-old-')&&x.includes('quarantine')))});
test('tamper, missing evidence, and authority disagreement fail closed retaining evidence',async()=>{for(const kind of ['old-tamper','old-missing','authority']){const f=await fixture(false);if(kind==='old-tamper')fs.writeFileSync(f.old,'EVIL');if(kind==='old-missing')fs.unlinkSync(f.old);if(kind==='authority')f.a.set({bad:true});await assert.rejects(recoverReplacement({platform:'linux',journal:f.j,authority:f.a,validate,databasePath:f.live,fsyncDir:sync}));assert(f.j.read());assert.equal(fs.readFileSync(f.live,'utf8'),'NEW')}});
test('journal exact keys are insertion-order independent while missing and extra keys fail closed',()=>{const user=root(),j=journal(user),live=path.join(user,'growthmap.db'),old=`${live}.gm-old-11111111-1111-4111-8111-111111111111`;fs.writeFileSync(live,'NEW');fs.writeFileSync(old,'OLD');const i=j.begin({transitionId:'11111111-1111-4111-8111-111111111111',mode:'foreign-import',databasePath:live,oldEvidence:evidence(old),newEvidence:evidence(live),authorityPre:{schemaVersion:1,bindings:{}}});const p=path.join(user,'secrets','replacement-intent.bin'),shuffled=Object.fromEntries(Object.entries(i).reverse());fs.writeFileSync(p,Buffer.from(crypt.encrypt(JSON.stringify(shuffled))));assert.deepEqual(j.read(),shuffled);for(const bad of [Object.fromEntries(Object.entries(i).slice(1)),{...i,extra:true}]){fs.writeFileSync(p,Buffer.from(crypt.encrypt(JSON.stringify(bad))));assert.throws(()=>j.read(),/invalid/)}});
test('authenticated bounded journal rejects ciphertext corruption without mutation',async()=>{const user=root(),j=journal(user),live=path.join(user,'growthmap.db'),old=`${live}.gm-old-11111111-1111-4111-8111-111111111111`;fs.writeFileSync(live,'x');fs.writeFileSync(old,'o');j.begin({transitionId:'11111111-1111-4111-8111-111111111111',mode:'foreign-import',databasePath:live,oldPath:old,oldEvidence:evidence(old),newEvidence:evidence(live),authorityPre:{schemaVersion:1,bindings:{}}});const p=path.join(user,'secrets','replacement-intent.bin'),before=Buffer.from('not ciphertext');fs.writeFileSync(p,before);assert.throws(()=>j.read(),/invalid/);assert.deepEqual(fs.readFileSync(p),before)});
test('authority payload validates identity paths with their declared platform semantics',()=>{const {validateAuthorityPayload}=require('../authority-schema'),lineage='11111111-1111-4111-8111-111111111111',windows='C:\\Users\\test\\growthmap.db',posix='/var/lib/growthmap.db';assert.doesNotThrow(()=>validateAuthorityPayload({schemaVersion:1,bindings:{[windows]:{identity:{platform:'win32',path:windows,volumeSerial:'1234ABCD',fileIndex:'0000000000000001'},lineage,legacyAdopted:false}}}));assert.doesNotThrow(()=>validateAuthorityPayload({schemaVersion:1,bindings:{[posix]:{identity:{platform:'posix',path:posix,device:'1',inode:'2'},lineage,legacyAdopted:false}}}));});
test('explicit non-Windows recovery platform is honored even when the host differs',async()=>{const f=await fixture(true),r=await recoverReplacement({platform:'linux',journal:f.j,authority:f.a,validate,databasePath:f.live,fsyncDir:sync});assert.equal(r.outcome,'committed');});
