const {createHostNeutralTestFiles,createHostNeutralTestFilesFactory}=require('./helpers/host-neutral-test-files');
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{createReplacementJournal}=require('../replacement-journal'),{recoverReplacement}=require('../replacement-recovery');
const id='11111111-1111-4111-8111-111111111111',crypt={encrypt:s=>Buffer.from(s).toString('base64'),decrypt:b=>Buffer.from(String(b),'base64').toString()},ev=b=>({sha256:crypto.createHash('sha256').update(b).digest('hex'),size:b.length}),a0={schemaVersion:1,bindings:{}},a1={schemaVersion:1,bindings:{'/db':{identity:{platform:'posix',path:'/db',device:'1',inode:'2'},lineage:id,legacyAdopted:false}}};
function fixture(phase='committed'){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-win-barrier-')),live=path.join(root,'growthmap.db'),j=createReplacementJournal({platform:'linux',userData:root,files:createHostNeutralTestFiles(path.join(root,'secrets')),...crypt});fs.writeFileSync(live,'NEW');let i=j.begin({transitionId:id,mode:'foreign-import',databasePath:live,oldEvidence:ev(Buffer.from('OLD')),newEvidence:ev(Buffer.from('NEW')),authorityPre:a0});i=j.update(i,{authorityNew:a1,phase});fs.writeFileSync(i.oldPath,'OLD');return {root,live,j,i}}
function harness(f,{closeFailure=false,staleTransaction=false}={}){let active=0,serial=0,transaction=staleTransaction;const events=[];const nativeOpen=async file=>{const bytes=fs.readFileSync(file),evidence=ev(bytes),token=++serial;active++;events.push(`open:${path.basename(file)}:${token}`);let closed=false;return {evidence,identity:{token},async assertExact(expected){events.push(`assert:${path.basename(file)}:${token}`);assert.deepEqual(evidence,expected);assert.equal(fs.readFileSync(file,'utf8'),bytes.toString())},async assertPath(){},async close(){if(closed)return;if(closeFailure&&token===2)throw Error('injected close failure');closed=true;active--;events.push(`close:${path.basename(file)}:${token}`)}}};const owner={async prepareRecovery({transitionId}){events.push(`prepare-recovery:${transitionId}:transaction=${transaction}`);transaction=false},async renameExact({action}){events.push(`rename:${action}:active=${active}:transaction=${transaction}`);assert.equal(transaction,false,'rename attempted while install transaction remained active');assert.equal(active,0,'rename attempted while evidence handles remained active');if(action==='cleanup-old-to-quarantine')fs.renameSync(f.i.oldPath,f.i.quarantinePath);else if(action==='rollback-live-to-failed')fs.renameSync(f.live,f.i.failedPath);else if(action==='rollback-old-to-live')fs.renameSync(f.i.oldPath,f.live);return {evidence:f.i.oldEvidence}}};return {nativeOpen,owner,events,active:()=>active}}
const authority={matches:v=>JSON.stringify(v)===JSON.stringify(a1),restore(){}};
test('Win32 committed cleanup closes every validated handle before rename and reopens deterministic paths',async()=>{const f=fixture(),h=harness(f),r=await recoverReplacement({journal:f.j,authority,validate:async()=>{},databasePath:f.live,fsyncDir:async()=>h.events.push('flush'),nativeOpen:h.nativeOpen,platform:'win32',windowsReplacementOwner:h.owner});assert.equal(r.outcome,'committed');const rename=h.events.indexOf('rename:cleanup-old-to-quarantine:active=0:transaction=false'),flush=h.events.indexOf('flush');assert(rename>=0&&flush>rename);assert(h.events.slice(rename+1).some(x=>x.startsWith('open:growthmap.db:')));assert(h.events.slice(rename+1).some(x=>x.includes('.quarantine:')));assert.equal(h.active(),0);assert.equal(f.j.read(),null)});
test('Win32 committed cleanup deterministically releases its matching installed broker transaction before evidence opens',async()=>{const f=fixture(),h=harness(f,{staleTransaction:true}),r=await recoverReplacement({journal:f.j,authority,validate:async()=>{},databasePath:f.live,fsyncDir:async()=>{},nativeOpen:h.nativeOpen,platform:'win32',windowsReplacementOwner:h.owner});assert.equal(r.outcome,'committed');assert.match(h.events[0],/^prepare-recovery:.*:transaction=true$/);assert(h.events.some(x=>x.startsWith('rename:cleanup-old-to-quarantine:active=0:transaction=false')));assert.equal(f.j.read(),null)});
test('Win32 close failure blocks rename and durable journal progression',async()=>{const f=fixture(),h=harness(f,{closeFailure:true});await assert.rejects(recoverReplacement({journal:f.j,authority,validate:async()=>{},databasePath:f.live,fsyncDir:async()=>{},nativeOpen:h.nativeOpen,platform:'win32',windowsReplacementOwner:h.owner}),/injected close failure/);assert(!h.events.some(x=>x.startsWith('rename:')));assert.equal(f.j.read().phase,'committed');assert(fs.existsSync(f.i.oldPath))});
test('Win32 committed cleanup recovery is idempotent after durable quarantine',async()=>{const f=fixture(),h1=harness(f);await recoverReplacement({journal:f.j,authority,validate:async()=>{},databasePath:f.live,fsyncDir:async()=>{},nativeOpen:h1.nativeOpen,platform:'win32',windowsReplacementOwner:h1.owner});const h2=harness(f),r=await recoverReplacement({journal:f.j,authority,validate:async()=>{},databasePath:f.live,fsyncDir:async()=>{},nativeOpen:h2.nativeOpen,platform:'win32',windowsReplacementOwner:h2.owner});assert.equal(r.recovered,false);assert(!h2.events.some(x=>x.startsWith('rename:')));assert.equal(h2.active(),0)});
