'use strict';
const {createHostNeutralTestFiles}=require('./helpers/host-neutral-test-files');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');const {createSecretStore}=require('../secret-store');
const key=Buffer.alloc(32,7),secret='sk-production-secret-never-plaintext';
function encrypt(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return Buffer.concat([Buffer.from('GM1'),iv,cipher.getAuthTag(),body])}
function decrypt(data){if(!Buffer.isBuffer(data)||data.subarray(0,3).toString()!=='GM1')throw Error('format');const decipher=crypto.createDecipheriv('aes-256-gcm',key,data.subarray(3,15));decipher.setAuthTag(data.subarray(15,31));return Buffer.concat([decipher.update(data.subarray(31)),decipher.final()]).toString()}
function fixture(remote={},dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-secret-')),files){const warnings=[];return{dir,warnings,store:createSecretStore({platform:'linux',directory:dir,files:createHostNeutralTestFiles(dir),encrypt,decrypt,putRemote:remote.put||(()=>{}),deleteRemote:remote.del||(()=>{}),recoverRemote:remote.recover||(()=>{}),recoverStatus:remote.status||(()=>({revision:2,credential_status:'ready',secret_change_pending:false})),warn:w=>warnings.push(w),...(files?{files}: {})})}}
function noPlaintext(dir){for(const name of fs.readdirSync(dir))assert.equal(fs.readFileSync(path.join(dir,name)).includes(Buffer.from(secret)),false,name)}
test('AES-256-GCM set persists only authenticated ciphertext and restart hydrates',async()=>{const f=fixture(),loaded=[];await f.store.set('p',secret);noPlaintext(f.dir);await fixture({put:(id,v)=>loaded.push([id,v])},f.dir).store.hydrate();assert.deepEqual(loaded,[['p',secret]])});
test('ciphertext bitflip and metadata tamper reject without warning leakage',async()=>{for(const offset of [0,20,35]){const f=fixture();await f.store.set('p',secret);const name=path.join(f.dir,'p.bin'),data=fs.readFileSync(name);data[offset]^=1;fs.writeFileSync(name,data);await f.store.hydrate();assert.equal(f.warnings.length,1);assert.doesNotMatch(f.warnings.join(' '),/sk-production|remote raw/)}});
test('hydrate remote failure is a hard barrier and never leaks plaintext',async()=>{const f=fixture();await f.store.set('p',secret);const restarted=fixture({put:async()=>{throw Object.assign(Error(`remote raw ${secret}`),{statusCode:409,code:'PROVIDER_SECRET_CHANGE_PENDING'})}},f.dir);await assert.rejects(restarted.store.hydrate(),/could not be loaded securely/);assert.equal(restarted.warnings.length,0);assert.doesNotMatch(String((await restarted.store.hydrate().catch(e=>e)).message),/sk-production|remote raw/)});
test('credential bounds reject empty NUL oversized chars and bytes without echo',async()=>{const f=fixture();for(const value of ['',`x\0y`,'x'.repeat(16385),'密'.repeat(11000)]){const e=await f.store.set('p',value).catch(e=>e);assert.equal(e.message,'INVALID_PROVIDER_CREDENTIAL');assert.doesNotMatch(e.message,/x{10}|密/)}});
test('remote set failure leaves no final artifact or plaintext',async()=>{const f=fixture({put:async()=>{throw Error(`remote raw ${secret}`)}});await assert.rejects(f.store.set('p',secret),/could not be dispatched securely/);assert.deepEqual(fs.readdirSync(f.dir),['p.recover']);noPlaintext(f.dir);assert.doesNotMatch(f.warnings.join(' '),/sk-production|remote raw/)});
test('remote delete failure retains encrypted key across restart',async()=>{const f=fixture();await f.store.set('p',secret);await assert.rejects(fixture({del:async()=>{throw Error('raw')}},f.dir).store.delete('p'));assert(fs.existsSync(path.join(f.dir,'p.bin')));noPlaintext(f.dir)});
test('successful delete survives restart',async()=>{const f=fixture();await f.store.set('p',secret);await f.store.delete('p');assert.equal(f.store.has('p'),false);await fixture({},f.dir).store.reconcile()});
test('pending set journal replays then promotes ready on fresh store',async()=>{const f=fixture({recover:async()=>{throw Error('down')}});await assert.rejects(f.store.recover('p',2,'set',secret));noPlaintext(f.dir);let calls=0;const restarted=fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:true}),recover:()=>calls++},f.dir);await restarted.store.reconcile();assert.equal(calls,1);assert.equal(decrypt(fs.readFileSync(path.join(f.dir,'p.bin'))),secret);assert(!fs.existsSync(path.join(f.dir,'p.recover')))});
test('pending delete journal replays and removes target',async()=>{const f=fixture();await f.store.set('p',secret);const failing=fixture({recover:async()=>{throw Error('down')}},f.dir);await assert.rejects(failing.store.recover('p',2,'delete'));await fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:true})},f.dir).store.reconcile();assert.deepEqual(fs.readdirSync(f.dir),[])});
test('ready state promotes retained journal without duplicate remote call',async()=>{const f=fixture({recover:async()=>{throw Error('cut')}});await assert.rejects(f.store.recover('p',2,'set',secret));let calls=0;await fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:false}),recover:()=>calls++},f.dir).store.reconcile();assert.equal(calls,0);assert.equal(decrypt(fs.readFileSync(path.join(f.dir,'p.bin'))),secret)});
test('stale revision and ambiguous state fail closed retaining journal',async()=>{for(const status of [{revision:3,credential_status:'ready',secret_change_pending:true},{revision:2,credential_status:'missing',secret_change_pending:false}]){const f=fixture({recover:async()=>{throw Error('cut')}});await assert.rejects(f.store.recover('p',2,'set',secret));await assert.rejects(fixture({status:()=>status},f.dir).store.reconcile());assert(fs.existsSync(path.join(f.dir,'p.recover')))}});
test('malformed journal, auth tamper, and filename mismatch fail closed',async()=>{for(const bytes of [Buffer.from('bad'),encrypt(JSON.stringify({v:1,id:'other',revision:2,operation:'delete'}))]){const f=fixture();fs.writeFileSync(path.join(f.dir,'p.recover'),bytes,{mode:0o600});await assert.rejects(f.store.reconcile(),/invalid/i)}const f=fixture();fs.writeFileSync(path.join(f.dir,'p.recover'),encrypt('{}'),{mode:0o600});const d=fs.readFileSync(path.join(f.dir,'p.recover'));d[d.length-1]^=1;fs.writeFileSync(path.join(f.dir,'p.recover'),d);await assert.rejects(f.store.reconcile(),/invalid/i)});
test('unknown tmp, unknown recover, quarantine, and multiple-artifact directories fail closed',async()=>{for(const name of ['p.tmp','p.tmp-1','p.bin.quarantine-1']){const f=fixture();fs.writeFileSync(path.join(f.dir,name),'x',{mode:0o600});await assert.rejects(f.store.reconcile(),/invalid/i)}const f=fixture();fs.writeFileSync(path.join(f.dir,'unknown.recover'),encrypt(JSON.stringify({v:1,id:'different',revision:2,operation:'delete'})),{mode:0o600});await assert.rejects(f.store.reconcile(),/invalid/i)});
test('journal target promote failure retains journal for restart',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-cut-')),base=createHostNeutralTestFiles(dir);let fail=true;const files={...base,write:(n,d)=>{if(fail&&n.endsWith('.bin')){fail=false;throw Error('rename cut')}return base.write(n,d)}};const f=fixture({},dir,files);await assert.rejects(f.store.recover('p',2,'set',secret));assert(base.exists('p.recover'));await fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:false})},dir).store.reconcile();assert.equal(decrypt(base.read('p.bin')),secret)});
test('target unlink failure retains delete journal and target',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-cut-')),base=createHostNeutralTestFiles(dir);base.write('p.bin',encrypt(secret));let fail=true;const files={...base,remove:n=>{if(fail&&n==='p.bin'){fail=false;throw Error('unlink')}return base.remove(n)}};await assert.rejects(fixture({},dir,files).store.recover('p',2,'delete'));assert(base.exists('p.recover')&&base.exists('p.bin'))});
test('journal unlink failure leaves promoted target plus journal and restart completes',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-cut-')),base=createHostNeutralTestFiles(dir);let fail=true;const files={...base,remove:n=>{if(fail&&n.endsWith('.recover')){fail=false;throw Error('journal unlink')}return base.remove(n)}};await assert.rejects(fixture({},dir,files).store.recover('p',2,'set',secret));assert(base.exists('p.bin')&&base.exists('p.recover'));await fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:false})},dir).store.reconcile();assert.equal(decrypt(base.read('p.bin')),secret)});
test('directory symlink and entry symlink/hardlink are rejected POSIX',{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},async()=>{const {secureFiles}=require('../secure-files'),root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-fs-')),real=path.join(root,'real');fs.mkdirSync(real,{mode:0o700});const link=path.join(root,'link');fs.symlinkSync(real,link);assert.throws(()=>fixture({},link,secureFiles(link,link,fs,{platform:'linux'})).store.has('p'),/Unsafe/);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-secret-posix-')),f=fixture({},dir,secureFiles(dir,dir,fs,{platform:'linux'}));fs.writeFileSync(path.join(f.dir,'outside'),encrypt(secret),{mode:0o600});fs.symlinkSync(path.join(f.dir,'outside'),path.join(f.dir,'p.bin'));assert.throws(()=>f.store.has('p'));fs.unlinkSync(path.join(f.dir,'p.bin'));fs.linkSync(path.join(f.dir,'outside'),path.join(f.dir,'p.bin'));assert.throws(()=>f.store.has('p'))});
test('wrong directory and entry mode are rejected POSIX',{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},async()=>{const {secureFiles}=require('../secure-files'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-mode-')),f=fixture({},dir,secureFiles(dir,dir,fs,{platform:'linux'}));fs.chmodSync(f.dir,0o755);assert.throws(()=>f.store.has('p'));fs.chmodSync(f.dir,0o700);fs.writeFileSync(path.join(f.dir,'p.bin'),encrypt(secret),{mode:0o644});assert.throws(()=>f.store.has('p'))});
test('O_NOFOLLOW read detects injectable fstat identity TOCTOU mismatch',{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},()=>{const {secureFiles}=require('../secure-files'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-toctou-'));fs.writeFileSync(path.join(dir,'p.bin'),encrypt(secret),{mode:0o600});let calls=0;const io={...fs,constants:fs.constants};io.fstatSync=fd=>{const s=fs.fstatSync(fd);calls++;return calls===2?new Proxy(s,{get:(t,p)=>p==='ino'?Number(t.ino)+1:t[p]}):s};assert.throws(()=>secureFiles(dir,dir,io,{platform:'linux'}).read('p.bin'),/Unstable/)});
test('ordinary v2 set journals before CAS dispatch and promotes target',async()=>{const events=[],f=fixture({status:()=>({revision:7,credential_status:'ready',secret_change_pending:false}),put:async(id,value,revision)=>{events.push([id,value,revision]);assert(fs.existsSync(path.join(f.dir,'p.recover')))}});await f.store.set('p',secret);assert.deepEqual(events,[['p',secret,7]]);assert.equal(decrypt(fs.readFileSync(path.join(f.dir,'p.bin'))),secret);assert(!fs.existsSync(path.join(f.dir,'p.recover')))});
test('ordinary v2 delete journals before CAS dispatch',async()=>{const f=fixture({status:()=>({revision:4,credential_status:'ready',secret_change_pending:false}),del:async(id,revision)=>{assert.equal(revision,4);assert(fs.existsSync(path.join(f.dir,'p.recover')))}});fs.writeFileSync(path.join(f.dir,'p.bin'),encrypt(secret),{mode:0o600});await f.store.delete('p');assert.deepEqual(fs.readdirSync(f.dir),[])});
test('v2 reconcile handles exact base, pending target, and completed target states',async()=>{for(const [state,kind] of [[{revision:5,credential_status:'ready',secret_change_pending:false},'ordinary'],[{revision:6,credential_status:'recovery_required',secret_change_pending:true,secret_change_operation_id:'a'.repeat(48)},'recover'],[{revision:6,credential_status:'ready',secret_change_pending:false,secret_change_operation_id:'a'.repeat(48)},'promote']]){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-v2-')),base=createHostNeutralTestFiles(dir),j={v:2,id:'p',operationId:'a'.repeat(48),baseRevision:5,revision:6,operation:'set',value:secret};base.write('p.recover',encrypt(JSON.stringify(j)));let ordinary=0,recover=0;await fixture({status:()=>state,put:(id,v,n)=>{ordinary++;assert.equal(n,5)},recover:()=>recover++},dir).store.reconcile();assert.equal(ordinary,kind==='ordinary'?1:0);assert.equal(recover,kind==='recover'?1:0);assert.equal(decrypt(base.read('p.bin')),secret)}});
test('v2 stale or ambiguous authority retains encrypted journal',async()=>{for(const state of [{revision:4,credential_status:'ready',secret_change_pending:false},{revision:5,credential_status:'recovery_required',secret_change_pending:true},{revision:7,credential_status:'ready',secret_change_pending:false}]){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-v2-stale-')),base=createHostNeutralTestFiles(dir);base.write('p.recover',encrypt(JSON.stringify({v:2,id:'p',operationId:'a'.repeat(48),baseRevision:5,revision:6,operation:'set',value:secret})));await assert.rejects(fixture({status:()=>state},dir).store.reconcile());assert(base.exists('p.recover'));noPlaintext(dir)}});
test('same-provider ordinary operations are serialized',async()=>{let revision=1,active=0,max=0;const f=fixture({status:()=>({revision,credential_status:'ready',secret_change_pending:false}),put:async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,20));revision++;active--}});await Promise.all([f.store.set('p',secret),f.store.set('p',secret+'2')]);assert.equal(max,1);assert.equal(revision,3)});
test('ordinary operation rejects pending or exhausted authority before journal',async()=>{for(const state of [{revision:2,credential_status:'recovery_required',secret_change_pending:true},{revision:Number.MAX_SAFE_INTEGER,credential_status:'ready',secret_change_pending:false}]){const f=fixture({status:()=>state});await assert.rejects(f.store.set('p',secret));assert.deepEqual(fs.readdirSync(f.dir),[])}});
test('terminal operation mismatch retains v2 journal for set and delete',async()=>{for(const operation of ['set','delete']){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gm-op-mismatch-')),base=createHostNeutralTestFiles(dir),j={v:2,id:'p',operationId:'a'.repeat(48),baseRevision:5,revision:6,operation,...(operation==='set'?{value:secret}:{})};if(operation==='delete')base.write('p.bin',encrypt(secret));base.write('p.recover',encrypt(JSON.stringify(j)));await assert.rejects(fixture({status:()=>({revision:6,credential_status:operation==='set'?'unavailable':'ready',secret_change_pending:false,secret_change_operation_id:'b'.repeat(48)})},dir).store.reconcile(),e=>e.credentialStage==='authority-ambiguous');assert(base.exists('p.recover'));assert.equal(base.exists('p.bin'),operation==='delete')}});
test('v1 finalized delete requires unavailable and response-loss cut promotes',async()=>{const f=fixture({recover:async()=>{throw Error('response lost')}});await assert.rejects(f.store.recover('p',2,'delete'));await assert.rejects(fixture({status:()=>({revision:2,credential_status:'ready',secret_change_pending:false})},f.dir).store.reconcile(),e=>e.credentialStage==='authority-ambiguous');assert(fs.existsSync(path.join(f.dir,'p.recover')));await fixture({status:()=>({revision:2,credential_status:'unavailable',secret_change_pending:false})},f.dir).store.reconcile();assert.deepEqual(fs.readdirSync(f.dir),[])});
test('diagnostic stages are fixed and hostile nested errors are redacted',async()=>{const hostile=`secret=${secret} path=/private/provider revision=99`;const f=fixture({put:async()=>{throw Error(hostile)}}),e=await f.store.set('p',secret).catch(e=>e);assert.equal(e.credentialStage,'remote-dispatch-failed');assert.doesNotMatch(e.message,/private|provider|99/);assert.match(e.message,/could not be dispatched securely/)});
test('v2 journal operation id is random and schema validated',async()=>{const ids=[];for(let i=0;i<2;i++){const f=fixture({status:()=>({revision:1,credential_status:'ready',secret_change_pending:false}),put:async()=>{const j=JSON.parse(decrypt(fs.readFileSync(path.join(f.dir,'p.recover'))));ids.push(j.operationId);throw Error('cut')}});await assert.rejects(f.store.set('p',secret));assert.match(ids[i],/^[0-9a-f]{48}$/)}assert.notEqual(ids[0],ids[1]);const f=fixture(),bad={v:2,id:'p',operationId:'bad',baseRevision:1,revision:2,operation:'delete'};fs.writeFileSync(path.join(f.dir,'p.recover'),encrypt(JSON.stringify(bad)),{mode:0o600});await assert.rejects(f.store.reconcile(),e=>e.credentialStage==='journal-invalid')});
