'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {secureFiles,nativeWindowsPolicy,WINDOWS_POLICY}=require('../secure-files');
function roots(){const trusted=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trusted-'));fs.chmodSync(trusted,0o700);return{trusted,directory:path.join(trusted,'controlled','secrets')}}
test('walk creates one component at a time and rejects an intermediate symlink escape',()=>{if(process.platform==='win32')return;const {trusted,directory}=roots(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'gm-outside-'));fs.chmodSync(outside,0o700);fs.symlinkSync(outside,path.join(trusted,'controlled'));assert.throws(()=>secureFiles(trusted,directory).verifyDir(),/Unsafe|escapes/);assert.equal(fs.existsSync(path.join(outside,'secrets')),false)});
test('directory must remain bounded beneath explicit trusted root',()=>{const {trusted}=roots();assert.throws(()=>secureFiles(trusted,path.join(trusted,'..','escape')).verifyDir(),/escapes trusted root/)});
test('walk rejects a permissive intermediate component',()=>{if(process.platform==='win32')return;const {trusted,directory}=roots();fs.mkdirSync(path.join(trusted,'controlled'),{mode:0o755});assert.throws(()=>secureFiles(trusted,directory).verifyDir(),/Unsafe secret dir/)});
for(const [operation,hook,invoke] of [
 ['mkdir','afterMkdir',f=>f.verifyDir()],
 ['read','beforeReadReturn',f=>f.read('p.bin')],
 ['write rename','beforeRename',f=>f.write('p.bin',Buffer.from('new'))],
 ['unlink','beforeUnlink',f=>f.remove('p.bin')],
])test(`parent replacement during ${operation} fails closed`,()=>{if(process.platform==='win32')return;const {trusted,directory}=roots();let fired=false,armed=operation==='mkdir';const replace=()=>{if(!armed||fired||!fs.existsSync(directory))return;fired=true;const moved=`${directory}.moved`;fs.renameSync(directory,moved);fs.mkdirSync(directory,{mode:0o700})};const hooks={[hook]:replace};const f=secureFiles(trusted,directory,fs,{hooks});if(operation!=='mkdir'){f.verifyDir();f.write('p.bin',Buffer.from('old'));fired=false;armed=true}assert.throws(()=>invoke(f),/parent replaced/)});
test('native runner passes only fixed encoded policy and structured stdin and requires stable identity output',()=>{let call;const runner=(exe,args,options)=>{call={exe,args,options};return{status:0,stdout:JSON.stringify({identities:[{path:'C:\\safe\\root',identity:'1234ABCD:0000000000000042'}]})}};assert.deepEqual(nativeWindowsPolicy(['C:\\safe\\root'],runner),['1234ABCD:0000000000000042']);assert.equal(call.exe,'powershell.exe');assert.equal(call.args.includes('C:\\safe\\root'),false);assert.deepEqual(JSON.parse(call.options.input),{paths:['C:\\safe\\root']});assert.equal(call.args.includes('-EncodedCommand'),true);for(const bad of [{status:1,stdout:''},{status:0,stdout:'{}'},{status:0,stdout:JSON.stringify({identities:[{path:'wrong',identity:'1234ABCD:0000000000000042'}]})},{status:0,stdout:JSON.stringify({identities:[{path:'C:\\safe\\root',identity:'0:0'}]})}])assert.throws(()=>nativeWindowsPolicy(['C:\\safe\\root'],()=>bad),/unavailable/)});
test('container-only native query is structured and retains ACL/owner enforcement source',()=>{let input;const runner=(exe,args,options)=>{input=JSON.parse(options.input);return{status:0,stdout:JSON.stringify({identities:[{path:'C:\\container',identity:'1234ABCD:0000000000000042'}]})}};assert.deepEqual(nativeWindowsPolicy(['C:\\container'],runner,true),['1234ABCD:0000000000000042']);assert.deepEqual(input,{paths:['C:\\container'],containerOnly:true});assert.match(WINDOWS_POLICY,/\$a=Get-Acl[\s\S]*\$q\.containerOnly[\s\S]*ownerSid -notin \$trusted/);assert.doesNotMatch(WINDOWS_POLICY,/if\(!\$q\.containerOnly\)\{\s*\$a=Get-Acl/)});
test('injected Windows policy identity is mandatory and distinguishes parent replacement',()=>{const {trusted,directory}=roots();let identity='VOL:ONE';const policy=()=>[identity];const f=secureFiles(trusted,directory,fs,{platform:'win32',windowsPolicy:policy});f.verifyDir();const raced=secureFiles(trusted,directory,fs,{platform:'win32',windowsPolicy:()=>[identity],hooks:{beforeReadReturn:()=>identity='VOL:TWO'}});f.write('p.bin',Buffer.from('x'));assert.throws(()=>raced.read('p.bin'),/parent replaced/);assert.throws(()=>secureFiles(trusted,directory,fs,{platform:'win32',windowsPolicy:()=>[]}).verifyDir(),/identity unavailable/)});
test('fixed native policy executes explicit trusted SID and complete dangerous-right model',()=>{for(const token of ['S-1-5-18','S-1-5-32-544','WriteData','CreateFiles','CreateDirectories','AppendData','Write','Modify','FullControl','Delete','DeleteSubdirectoriesAndFiles','ChangePermissions','TakeOwnership','0x40000000','0x10000000','IsInherited']){if(token==='IsInherited')continue;assert.equal(WINDOWS_POLICY.includes(token),true,token)}assert.equal(WINDOWS_POLICY.includes('S-1-1-0'),false)});
test('Windows-native dangerous ACL, owner, reparse and operation matrix', {skip:process.platform!=='win32'&&'requires native Windows NTFS/PowerShell'},()=>{
 const cp=require('node:child_process'),container=fs.mkdtempSync(path.join(os.tmpdir(),'gm-win-container-')),directory=path.join(container,'secrets'),outside=fs.mkdtempSync(path.join(os.tmpdir(),'gm-win-outside-'));
 fs.symlinkSync(outside,directory,'junction');assert.throws(()=>secureFiles(directory,directory).verifyDir(),/Unsafe|policy/);fs.unlinkSync(directory);
 const rejectedParent=fs.mkdtempSync(path.join(os.tmpdir(),'gm-win-parent-reject-')),rejectedChild=path.join(rejectedParent,'secrets'),parentAcl=String.raw`$q=[Console]::In.ReadToEnd()|ConvertFrom-Json;$a=Get-Acl -LiteralPath $q.path;$s=[Security.Principal.SecurityIdentifier]::new('S-1-5-32-546');$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($s,[Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles,[Security.AccessControl.AccessControlType]::Allow));Set-Acl -LiteralPath $q.path -AclObject $a`;cp.execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',parentAcl],{input:JSON.stringify({path:rejectedParent})});assert.throws(()=>secureFiles(rejectedChild,rejectedChild).verifyDir(),/policy/);assert.equal(fs.existsSync(rejectedChild),false);
 const f=secureFiles(directory,directory);f.write('p.bin',Buffer.from('safe'));assert.deepEqual(f.read('p.bin'),Buffer.from('safe'));f.remove('p.bin');assert.equal(f.exists('p.bin'),false);f.write('p.bin',Buffer.from('safe'));
 const sid='S-1-5-32-546',aclScript=String.raw`$q=[Console]::In.ReadToEnd()|ConvertFrom-Json;$a=Get-Acl -LiteralPath $q.path;$s=[Security.Principal.SecurityIdentifier]::new($q.sid);if($q.remove){$a.PurgeAccessRules($s)}else{$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($s,[Security.AccessControl.FileSystemRights]$q.right,[Security.AccessControl.AccessControlType]::Allow))};Set-Acl -LiteralPath $q.path -AclObject $a`,acl=(right,remove=false)=>cp.execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',aclScript],{input:JSON.stringify({path:directory,sid,right,remove})});for(const right of ['WriteData','AppendData','CreateDirectories','Delete','ChangePermissions','TakeOwnership','Modify','FullControl']){acl(right);for(const operation of [()=>f.verifyDir(),()=>f.read('p.bin'),()=>f.write('q.bin',Buffer.from('x')),()=>f.remove('p.bin')])assert.throws(operation,/policy/);acl('',true)}
 const inheritedScript=String.raw`$q=[Console]::In.ReadToEnd()|ConvertFrom-Json;$a=Get-Acl -LiteralPath $q.path;$s=[Security.Principal.SecurityIdentifier]::new($q.sid);$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($s,[Security.AccessControl.FileSystemRights]::Delete,[Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit',[Security.AccessControl.PropagationFlags]::InheritOnly,[Security.AccessControl.AccessControlType]::Allow));Set-Acl -LiteralPath $q.path -AclObject $a`;cp.execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',inheritedScript],{input:JSON.stringify({path:directory,sid})});assert.throws(()=>f.verifyDir(),/policy/);acl('',true);
 const ownerScript='$p=[Console]::In.ReadToEnd();$a=Get-Acl -LiteralPath $p;$a.SetOwner([Security.Principal.SecurityIdentifier]::new("S-1-5-32-545"));Set-Acl -LiteralPath $p -AclObject $a';const changed=cp.spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',ownerScript],{input:directory,encoding:'utf8'});if(changed.status===0)assert.throws(()=>f.verifyDir(),/policy/);
});
test('Windows directory fsync ignores only documented unsupported errors and revalidates parent',()=>{
 const {trusted,directory}=roots();fs.mkdirSync(directory,{recursive:true,mode:0o700});let policyIdentity='VOL:ONE',syncs=0;
 const io={...fs,constants:fs.constants,fsyncSync:fd=>{syncs++;if(syncs===2){const e=Error('unsupported directory fsync');e.code='EPERM';throw e}return fs.fsyncSync(fd)}};
 const f=secureFiles(trusted,directory,io,{platform:'win32',windowsPolicy:()=>[policyIdentity]});f.write('p.bin',Buffer.from('x'));assert.deepEqual(f.read('p.bin'),Buffer.from('x'));f.remove('p.bin');assert.equal(f.exists('p.bin'),false);
 for(const code of ['EINVAL','ENOTSUP','EOPNOTSUPP']){let calls=0;const injected={...fs,constants:fs.constants,fsyncSync:fd=>{calls++;if(calls===2){const e=Error(code);e.code=code;throw e}return fs.fsyncSync(fd)}};secureFiles(trusted,directory,injected,{platform:'win32',windowsPolicy:()=>['VOL:ONE']}).write('p.bin',Buffer.from(code));}
 let calls=0;const broken={...fs,constants:fs.constants,fsyncSync:fd=>{calls++;if(calls===2){const e=Error('I/O failure');e.code='EIO';throw e}return fs.fsyncSync(fd)}};assert.throws(()=>secureFiles(trusted,directory,broken,{platform:'win32',windowsPolicy:()=>['VOL:ONE']}).write('q.bin',Buffer.from('x')),e=>e.code==='EIO');
});
