'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {secureFiles,nativeWindowsPolicy,WINDOWS_POLICY,WINDOWS_NATIVE_POLICY_TIMEOUT_MS}=require('../secure-files');
function roots(){const trusted=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trusted-'));fs.chmodSync(trusted,0o700);return{trusted,directory:path.join(trusted,'controlled','secrets')}}
test('walk creates one component at a time and rejects an intermediate symlink escape',{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},()=>{const {trusted,directory}=roots(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'gm-outside-'));fs.chmodSync(outside,0o700);fs.symlinkSync(outside,path.join(trusted,'controlled'));assert.throws(()=>secureFiles(trusted,directory).verifyDir(),/Unsafe|escapes/);assert.equal(fs.existsSync(path.join(outside,'secrets')),false)});
test('directory must remain bounded beneath explicit trusted root',()=>{const {trusted}=roots();assert.throws(()=>secureFiles(trusted,path.join(trusted,'..','escape')).verifyDir(),/escapes trusted root/)});
test('walk rejects a permissive intermediate component',{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},()=>{const {trusted,directory}=roots();fs.mkdirSync(path.join(trusted,'controlled'),{mode:0o755});assert.throws(()=>secureFiles(trusted,directory).verifyDir(),/Unsafe secret dir/)});
for(const [operation,hook,invoke] of [
 ['mkdir','afterMkdir',f=>f.verifyDir()],
 ['read','beforeReadReturn',f=>f.read('p.bin')],
 ['write rename','beforeRename',f=>f.write('p.bin',Buffer.from('new'))],
 ['unlink','beforeUnlink',f=>f.remove('p.bin')],
])test(`parent replacement during ${operation} fails closed`,{skip:process.platform==='win32'?'POSIX filesystem semantics unavailable on win32':false},()=>{const {trusted,directory}=roots();let fired=false,armed=operation==='mkdir';const replace=()=>{if(!armed||fired||!fs.existsSync(directory))return;fired=true;const moved=`${directory}.moved`;fs.renameSync(directory,moved);fs.mkdirSync(directory,{mode:0o700})};const hooks={[hook]:replace};const f=secureFiles(trusted,directory,fs,{hooks});if(operation!=='mkdir'){f.verifyDir();f.write('p.bin',Buffer.from('old'));fired=false;armed=true}assert.throws(()=>invoke(f),/parent replaced/)});
test('async adapter validates exact payload/result and fails closed on malformed response',async()=>{
 const {createWindowsSecureFilesAdapter}=require('../secure-files');let seen;
 const good=createWindowsSecureFilesAdapter({broker:{request:async(c,p)=>{seen={c,p};return{identities:[{path:p.targets[0].path,identity:'1234ABCD:0000000000000042'}]}}}});
 assert.equal((await good.policy('C:\\safe',[{path:'C:\\safe\\key.bin',kind:'file'}]))[0].identity,'1234ABCD:0000000000000042');assert.deepEqual(seen,{c:'secure-path-policy',p:{root:'C:\\safe',targets:[{path:'C:\\safe\\key.bin',kind:'file',containerPolicy:'private'}]}});
 for(const result of [{}, {identities:[]},{identities:[{path:'C:\\wrong',identity:'1234ABCD:0000000000000042'}]}]){const a=createWindowsSecureFilesAdapter({broker:{request:async()=>result}});await assert.rejects(a.policy('C:\\safe',[{path:'C:\\safe\\key.bin',kind:'file'}]),/unavailable|schema/)}
 await assert.rejects(good.policy('C:\\safe',[{path:'C:\\escape\key.bin',kind:'file'}]),/unavailable|schema/);
});
test('adapter queue progresses event loop, serializes, survives rejection, and queued abort has no broker side effect',async()=>{
 const {createWindowsSecureFilesAdapter}=require('../secure-files');let active=0,max=0,calls=0,release;const gate=new Promise(r=>release=r),broker={request:async(_c,p)=>{calls++;active++;max=Math.max(max,active);if(calls===1)await gate;active--;if(calls===1)throw Error('remote');return{identities:p.targets.map(t=>({path:t.path,identity:'1234ABCD:0000000000000042'}))}}},a=createWindowsSecureFilesAdapter({broker}),ac=new AbortController();let tick=false;
 setImmediate(()=>tick=true);const first=a.policy('C:\\safe',[{path:'C:\\safe\\a.bin',kind:'file'}]);const aborted=a.policy('C:\\safe',[{path:'C:\\safe\\b.bin',kind:'file'}],ac.signal);const third=a.policy('C:\\safe',[{path:'C:\\safe\\c.bin',kind:'file'}]);ac.abort();await new Promise(r=>setImmediate(r));assert(tick);release();await assert.rejects(first,/remote/);await assert.rejects(aborted,/abort/i);assert.equal((await third)[0].path,'C:\\safe\\c.bin');assert.equal(max,1);assert.equal(calls,2);
});
test('ACL initialize is exact and mandatory same-broker policy revalidation',async()=>{
 const {createWindowsSecureFilesAdapter}=require('../secure-files');const calls=[],broker={request:async(c,p)=>{calls.push([c,p]);if(c==='initialize-private-acl')return{path:p.path,identity:'1234ABCD:0000000000000042',initialized:true};return{identities:[{path:p.targets[0].path,identity:'1234ABCD:0000000000000042'}]}}},a=createWindowsSecureFilesAdapter({broker});await a.initializePrivateAcl('C:\\safe','C:\\safe\\new.bin','file');assert.deepEqual(calls.map(x=>x[0]),['initialize-private-acl','secure-path-policy']);assert.deepEqual(calls[0][1],{root:'C:\\safe',path:'C:\\safe\\new.bin',kind:'file',containerPolicy:'private'});const bad=createWindowsSecureFilesAdapter({broker:{request:async c=>c==='initialize-private-acl'?{path:'C:\\safe\\new.bin',identity:'1234ABCD:0000000000000042',initialized:true}:{identities:[]}}});await assert.rejects(bad.initializePrivateAcl('C:\\safe','C:\\safe\\new.bin','file'),/unavailable|schema/);
});
test('helper ACL command has strict contract, protected owner-only DACL, root boundary, and no second native type',()=>{const src=fs.readFileSync(require.resolve('../windows-native-broker-helper.ps1'),'utf8');assert.match(src,/'initialize-private-acl' \{Exact-Keys \$q\.payload 'containerPolicy\|kind\|path\|root'/);assert.match(src,/Assert-UnderRoot \$root \$p/);assert.match(src,/SetAccessRuleProtection\(\$true,\$false\)/);for(const sid of ['S-1-5-18','S-1-5-32-544'])assert.match(src,new RegExp(sid));assert.match(src,/Initialize-PrivateAcl[\s\S]*Response \$writer/);assert.equal((src.match(/Add-Type/g)||[]).length,1)});
test('async Windows secure-files detects parent and file identity races for read/write/unlink',async()=>{const {trusted,directory}=roots();fs.mkdirSync(directory,{recursive:true,mode:0o700});let seq=0,armed=false;const adapter={policy:async(_r,targets)=>targets.map(t=>({path:t.path,identity:armed&&t.path===directory?`D:${++seq}`:'D:stable'})),initializePrivateAcl:async()=>({}),readFile:async(_r,p)=>({path:p,identity:'D:file',size:3,data:Buffer.from('old')})};const f=secureFiles(trusted,directory,fs,{platform:'win32',windowsAdapter:adapter});await f.write('p.bin',Buffer.from('old'));armed=true;await assert.rejects(f.read('p.bin'),/parent replaced|Unstable/);seq=0;await assert.rejects(f.write('q.bin',Buffer.from('new')),/parent replaced/);seq=0;await assert.rejects(f.remove('p.bin'),/parent replaced|Unstable/)});
test('Windows directory fsync ignores only allowlisted unsupported errors and revalidates parent',async()=>{const {trusted,directory}=roots();fs.mkdirSync(directory,{recursive:true,mode:0o700});let n=0;const adapter={policy:async(_r,ts)=>ts.map(t=>({path:t.path,identity:'D:stable'})),initializePrivateAcl:async()=>({})};for(const code of ['EPERM','EINVAL','ENOTSUP','EOPNOTSUPP']){let calls=0;const io={...fs,constants:fs.constants,fsyncSync:fd=>{calls++;if(calls===2){const e=Error(code);e.code=code;throw e}return fs.fsyncSync(fd)}};await secureFiles(trusted,directory,io,{platform:'win32',windowsAdapter:adapter}).write(`p-${n++}.bin`,Buffer.from(code))}let calls=0;const broken={...fs,constants:fs.constants,fsyncSync:fd=>{calls++;if(calls===2){const e=Error('bad');e.code='EIO';throw e}return fs.fsyncSync(fd)}};await assert.rejects(secureFiles(trusted,directory,broken,{platform:'win32',windowsAdapter:adapter}).write('bad.bin',Buffer.from('x')),e=>e.code==='EIO')});
test('Windows secure read bytes come only from broker and strict result rejects malformed encoding/size/path',async()=>{const {createWindowsSecureFilesAdapter}=require('../secure-files');let nodeReads=0;const io={...fs,readFileSync(){nodeReads++;throw Error('Node must not read secret bytes')}};const {trusted,directory}=roots();fs.mkdirSync(directory,{recursive:true,mode:0o700});const target=path.join(directory,'p.bin');fs.writeFileSync(target,'NODE');const ids=new Map([[trusted,'D:root'],[directory,'D:dir']]),adapter={policy:async(_r,ts)=>ts.map(t=>({path:t.path,identity:ids.get(t.path)||'D:file'})),initializePrivateAcl:async()=>({}),readFile:async()=>({path:target,identity:'D:file',size:6,data:Buffer.from('BROKER')})};assert.equal((await secureFiles(trusted,directory,io,{platform:'win32',windowsAdapter:adapter}).read('p.bin')).toString(),'BROKER');assert.equal(nodeReads,0);const payloads=[];for(const result of [{path:target,identity:'1234ABCD:0000000000000042',size:2,dataBase64:'YQ=='},{path:target,identity:'1234ABCD:0000000000000042',size:1,dataBase64:'YR=='},{path:'C:\\wrong',identity:'1234ABCD:0000000000000042',size:1,dataBase64:'YQ=='}]){const a=createWindowsSecureFilesAdapter({broker:{request:async(c,p)=>{payloads.push([c,p]);return result}}});await assert.rejects(a.readFile('C:\\safe','C:\\safe\\p.bin',8),/unavailable/)}assert.deepEqual(payloads[0][1],{root:'C:\\safe',path:'C:\\safe\\p.bin',maxBytes:8,containerPolicy:'private'})});
test('helper secure read and ACL are retained-handle transactions with named identity checks',()=>{const src=fs.readFileSync(require.resolve('../windows-native-broker-helper.ps1'),'utf8');assert.match(src,/'secure-read-file' \{Exact-Keys \$q\.payload 'containerPolicy\|maxBytes\|path\|root'/);assert.match(src,/secure-read-file[\s\S]*OpenOwner\(\$p\)[\s\S]*Same \$before \$after[\s\S]*OpenIdentity\(\$p\)[\s\S]*Same \$before \$fi/);assert.match(src,/SetKernelObjectSecurity/);assert.match(src,/Initialize-PrivateAcl[\s\S]*OpenSecurity\(\$p\)[\s\S]*SetOwnerAndDacl\(\$h[\s\S]*Assert-ExactPrivateAcl[\s\S]*OpenIdentity\(\$p\)/)});
