'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {waitForSidecarReady,DEFAULT_SIDECAR_READY_TIMEOUT_MS}=require('../sidecar-readiness');
function child(){const value=new EventEmitter();value.growthmapStderr='';return value;}
function clock(){let now=0,id=0;const jobs=new Map();return {now:()=>now,setTimer:(fn,ms)=>{const key=++id;jobs.set(key,{at:now+ms,fn});return key;},clearTimer:key=>jobs.delete(key),async advance(ms){const end=now+ms;for(;;){const due=[...jobs].filter(([,job])=>job.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;now=due[1].at;jobs.delete(due[0]);due[1].fn();await Promise.resolve();await Promise.resolve();}now=end;await Promise.resolve();await Promise.resolve();},pending:()=>jobs.size};}
function options(c,t,probe,extra={}){return {child:c,probe,now:t.now,setTimer:t.setTimer,clearTimer:t.clearTimer,pollIntervalMs:150,...extra};}
test('immediate deep health success settles and removes fail-fast listeners',async()=>{const c=child(),t=clock();await waitForSidecarReady(options(c,t,async()=>{}));assert.equal(t.pending(),0);assert.equal(c.listenerCount('exit'),0);assert.equal(c.listenerCount('error'),0);});
test('transient failures may recover after the former 15 second ceiling',async()=>{const c=child(),t=clock();let calls=0;const ready=waitForSidecarReady(options(c,t,async()=>{calls++;if(t.now()<35000)throw Error('not ready');}));for(let elapsed=0;elapsed<36000;elapsed+=150)await t.advance(150);await ready;assert(t.now()>15000);assert(calls>100);});
test('deadline is explicit, bounded, and exact',async()=>{assert.equal(DEFAULT_SIDECAR_READY_TIMEOUT_MS,60000);const c=child(),t=clock();const ready=waitForSidecarReady(options(c,t,async()=>{throw Error('not ready');},{timeoutMs:1000}));await t.advance(999);let settled=false;ready.catch(()=>{settled=true;});await Promise.resolve();assert.equal(settled,false);await t.advance(1);await assert.rejects(ready,/readiness timed out/);assert.equal(t.pending(),0);});
test('child exit and error fail fast',async()=>{for(const kind of ['exit','error']){const c=child(),t=clock(),ready=waitForSidecarReady(options(c,t,()=>new Promise(()=>{})));kind==='exit'?c.emit('exit',7,'SIGTERM'):c.emit('error',Error('spawn'));await assert.rejects(ready,kind==='exit'?/code=7, signal=SIGTERM/:/could not be started/);assert.equal(t.pending(),0);}});
test('already exited or signal-only child rejects immediately with zero probes',async()=>{for(const state of [{exitCode:3,signalCode:null},{exitCode:null,signalCode:'SIGKILL'}]){const c=child(),t=clock();Object.assign(c,state);let probes=0;const ready=waitForSidecarReady(options(c,t,async()=>{probes++;}));await assert.rejects(ready,state.signalCode?/signal=SIGKILL/:/code=3/);assert.equal(probes,0);assert.equal(t.pending(),0);assert.equal(c.listenerCount('exit'),0);assert.equal(c.listenerCount('error'),0);}});
test('late probe completion cannot double-settle after child exit',async()=>{const c=child(),t=clock();let resolveProbe;const ready=waitForSidecarReady(options(c,t,()=>new Promise(resolve=>{resolveProbe=resolve;})));c.emit('exit',9,null);await assert.rejects(ready,/code=9/);resolveProbe();await Promise.resolve();await t.advance(60000);assert.equal(t.pending(),0);assert.equal(c.listenerCount('exit'),0);});
