'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{createTrialStore,hasPriorUse}=require('../trial-store');
const enc=x=>Buffer.from(x),dec=x=>x.toString();
function initializeExisting(root){const store=createTrialStore({userData:root,encrypt:enc,decrypt:dec,now:()=>new Date('2026-01-01Z')}),fresh=store.prepare();fs.writeFileSync(store.paths.state,JSON.stringify({schema_version:1,installation_id:fresh.marker.installationId,started_at:fresh.marker.startedAt,last_seen_at:fresh.marker.startedAt}));store.commit(fresh.marker);assert.equal(store.prepare().mode,'existing');return store;}
test('fresh initialization commits protected marker only after sidecar JSON exists',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=createTrialStore({userData:root,encrypt:enc,decrypt:dec,now:()=>new Date('2026-01-01Z')});const fresh=store.prepare();assert.equal(fresh.mode,'fresh');assert.equal(fs.existsSync(store.paths.secure),false);fs.writeFileSync(store.paths.state,JSON.stringify({schema_version:1,installation_id:fresh.marker.installationId,started_at:fresh.marker.startedAt,last_seen_at:fresh.marker.startedAt}));store.commit(fresh.marker);assert.equal(store.prepare().mode,'existing');});
test('deletion, tamper, or disagreement fails closed and never creates marker',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=createTrialStore({userData:root,encrypt:enc,decrypt:dec,now:()=>new Date('2026-01-01Z')}),fresh=store.prepare();fs.writeFileSync(store.paths.state,JSON.stringify({schema_version:1,installation_id:fresh.marker.installationId,started_at:fresh.marker.startedAt,last_seen_at:fresh.marker.startedAt}));store.commit(fresh.marker);fs.unlinkSync(store.paths.state);assert.equal(store.prepare().mode,'extraction');assert.throws(()=>store.commit(fresh.marker));fs.writeFileSync(store.paths.state,'{}');assert.equal(store.prepare().mode,'extraction');fs.writeFileSync(store.paths.secure,'tampered');assert.equal(store.prepare().mode,'extraction');});
test('deleting both Free artifacts cannot reset Free when durable prior-use evidence exists',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=createTrialStore({userData:root,encrypt:enc,decrypt:dec}),fresh=store.prepare();fs.writeFileSync(store.paths.state,JSON.stringify({schema_version:1,installation_id:fresh.marker.installationId,started_at:fresh.marker.startedAt,last_seen_at:fresh.marker.startedAt}));store.commit(fresh.marker);for(const target of [store.paths.secure,store.paths.state])fs.rmSync(target);assert.equal(store.prepare().mode,'extraction');});
test('independent protected installation identity survives both trial-file deletion',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=createTrialStore({userData:root,encrypt:enc,decrypt:dec}),fresh=store.prepare();fs.writeFileSync(store.paths.state,JSON.stringify({schema_version:1,installation_id:fresh.marker.installationId,started_at:fresh.marker.startedAt,last_seen_at:fresh.marker.startedAt}));store.commit(fresh.marker);fs.rmSync(store.paths.secure);fs.rmSync(store.paths.state);assert.equal(store.prepare().mode,'extraction');});
test('copied JSON without OS-protected marker is extraction, not reinstall',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-'));fs.writeFileSync(path.join(root,'trial-state.json'),JSON.stringify({schema_version:1,installation_id:'copied-installation',started_at:'2026-01-01T00:00:00Z'}));const store=createTrialStore({userData:root,encrypt:enc,decrypt:dec});assert.equal(store.prepare().mode,'extraction');assert.equal(fs.existsSync(store.paths.secure),false);});
test('unrelated junk and invalid spoof evidence do not brick a clean install',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-'));fs.writeFileSync(path.join(root,'notes.txt'),'junk');fs.writeFileSync(path.join(root,'growthmap.db'),'not sqlite');fs.mkdirSync(path.join(root,'backups'));fs.writeFileSync(path.join(root,'backups','backup-fake.db'),'x');assert.equal(createTrialStore({userData:root,encrypt:enc,decrypt:dec}).prepare().mode,'fresh');});
test('external import fixture is not prior-use evidence, while the managed database is',()=>{const header=Buffer.concat([Buffer.from('SQLite format 3\0','binary'),Buffer.alloc(128)]),userData=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-profile-')),input=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-input-'));fs.writeFileSync(path.join(input,'fixture.sqlite'),header);assert.equal(hasPriorUse(userData,{decrypt:dec}),false);assert.equal(createTrialStore({userData,encrypt:enc,decrypt:dec}).prepare().mode,'fresh');fs.writeFileSync(path.join(userData,'growthmap.db'),header);assert.equal(hasPriorUse(userData,{decrypt:dec}),true);assert.equal(createTrialStore({userData,encrypt:enc,decrypt:dec}).prepare().mode,'extraction');});
test('valid sqlite database and valid managed backup independently prove prior use',()=>{const header=Buffer.concat([Buffer.from('SQLite format 3\0','binary'),Buffer.alloc(128)]);for(const kind of ['database','backup']){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-'));if(kind==='database')fs.writeFileSync(path.join(root,'growthmap.db'),header);else{const dir=path.join(root,'backups'),name='backup-2026-07-28T00-00-00-000Z-11111111-1111-4111-8111-111111111111.db';fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,name),header);fs.writeFileSync(path.join(dir,`${name}.json`),JSON.stringify({format:'growthmap-backup-v1',createdAt:'2026-07-28T00:00:00Z',file:name,size:header.length,projects:0,sha256:crypto.createHash('sha256').update(header).digest('hex'),durability:{fileFsync:true,directoryFsync:true}}));}assert.equal(createTrialStore({userData:root,encrypt:enc,decrypt:dec}).prepare().mode,'extraction');}});
test('protected Free marker rejects raw duplicate keys',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=initializeExisting(root);const raw=fs.readFileSync(store.paths.secure,'utf8').replace('{','{"schemaVersion":999,');fs.writeFileSync(store.paths.secure,raw);assert.equal(store.prepare().mode,'extraction');});
test('existing identity with a last-key-valid duplicate fails closed after primary Free deletion',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=initializeExisting(root),valid=fs.readFileSync(store.paths.identity,'utf8');fs.rmSync(store.paths.secure);fs.rmSync(store.paths.state);fs.writeFileSync(store.paths.identity,valid.replace('{','{"schemaVersion":999,'));assert.deepEqual(store.prepare(),{mode:'extraction',reason:'prior_installation_evidence_invalid'});});
test('existing identity with a nested casefold collision fails closed after primary Free deletion',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),store=initializeExisting(root),identity=JSON.parse(fs.readFileSync(store.paths.identity,'utf8'));fs.rmSync(store.paths.secure);fs.rmSync(store.paths.state);fs.writeFileSync(store.paths.identity,`{"schemaVersion":1,"kind":"growthmap-installation-receipt","installationId":"${identity.installationId}","createdAt":"${identity.createdAt}","metadata":{"Key":1,"key":2}}`);assert.deepEqual(store.prepare(),{mode:'extraction',reason:'prior_installation_evidence_invalid'});});
test('identity decrypt failure and wrong exact shape fail closed after primary Free deletion',async t=>{for(const kind of ['decrypt failure','wrong shape'])await t.test(kind,()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),initialized=initializeExisting(root);fs.rmSync(initialized.paths.secure);fs.rmSync(initialized.paths.state);let store;if(kind==='decrypt failure')store=createTrialStore({userData:root,encrypt:enc,decrypt:()=>{throw Error('decrypt failed');}});else{fs.writeFileSync(initialized.paths.identity,'{"schemaVersion":1,"kind":"growthmap-installation-receipt","installationId":"11111111-1111-4111-8111-111111111111"}');store=createTrialStore({userData:root,encrypt:enc,decrypt:dec});}assert.deepEqual(store.prepare(),{mode:'extraction',reason:'prior_installation_evidence_invalid'});});});
test('true identity ENOENT stays fresh while a valid identity proves prior use',()=>{const freshRoot=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-'));assert.equal(createTrialStore({userData:freshRoot,encrypt:enc,decrypt:dec}).prepare().mode,'fresh');const usedRoot=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-')),used=initializeExisting(usedRoot);fs.rmSync(used.paths.secure);fs.rmSync(used.paths.state);assert.deepEqual(used.prepare(),{mode:'extraction',reason:'prior_installation_evidence'});});
test('exact observed DB-only legacy profile remains extraction and creates no Free artifacts',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-trial-observed-')),db=path.join(root,'growthmap.db'),header=Buffer.from('SQLite format 3\0','binary');fs.writeFileSync(db,Buffer.concat([header,Buffer.alloc(2711552-header.length)]));const before=fs.readdirSync(root).sort(),store=createTrialStore({userData:root,encrypt:enc,decrypt:dec}),result=store.prepare();assert.deepEqual(result,{mode:'extraction',reason:'prior_installation_evidence'});assert.deepEqual(fs.readdirSync(root).sort(),before);assert.equal(fs.statSync(db).size,2711552);for(const artifact of [store.paths.state,store.paths.secure,store.paths.identity])assert.equal(fs.existsSync(artifact),false);});
