'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const {createUpdater}=require('../updater'),{readMarker,writeMarker,promoteInstallReady,verifyPending}=require('../update-recovery');
const id='backup-2026-07-28T00-00-00-000Z-11111111-1111-4111-8111-111111111111.db',durability={fileFsync:true,directoryFsync:true};
function fixture({backup,responses=[0,0],download}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-update-')),u=new EventEmitter(),bytes=Buffer.alloc(4096,7),evidence={backupId:id,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),size:bytes.length,verifiedManaged:true};u.setFeedURL=value=>u.feed=value;u.checkForUpdates=async()=>({ok:true});u.downloadUpdate=download||(async()=>{u.downloaded=true});u.quitAndInstall=()=>u.installed=true;const errors=[],dialog={showMessageBox:async()=>({response:responses.shift()??0}),showErrorBox:()=>{}};createUpdater({autoUpdater:u,dialog,backup:backup||(async()=>{evidenceFiles({root,evidence,bytes});return evidence;}),userData:root,currentVersion:'1.0.0',feedUrl:'https://updates.growthmap.test/base',channel:'stable',isPackaged:true,onError:e=>errors.push(e.message)});return{root,u,errors,evidence,bytes};}
const tick=()=>new Promise(r=>setImmediate(r));
async function waitFor(predicate,message='async updater event timed out'){for(let i=0;i<100;i++){if(predicate())return;await tick();}assert.fail(message);}
function evidenceFiles(f,{createdAt='2026-07-28T00:00:00Z',dur=durability}={}){const dir=path.join(f.root,'backups');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id),f.bytes);fs.writeFileSync(path.join(dir,`${id}.json`),JSON.stringify({format:'growthmap-backup-v1',createdAt,file:id,size:f.evidence.size,projects:0,sha256:f.evidence.sha256,durability:dur}));}
function pending(phase='install-ready'){const f=fixture();evidenceFiles(f);writeMarker(f.root,{kind:'update',phase,createdAt:'2026-07-28T00:00:00Z',fromVersion:'1.0.0',toVersion:'1.1.0',backupId:id,sha256:f.evidence.sha256,size:f.evidence.size});return f;}
test('stable feed appends channel exactly once',()=>{const f=fixture();assert.equal(f.u.feed.url,'https://updates.growthmap.test/base/stable');});
test('backup failure or incomplete evidence prevents marker and download',async()=>{for(const backup of [async()=>{throw Error('bad')},async()=>({backupId:'x'}),async()=>({verifiedManaged:false})]){const f=fixture({backup});f.u.emit('update-available',{version:'1.1.0'});await tick();assert.equal(f.u.downloaded,undefined);assert.equal(readMarker(f.root),null);}});
test('download marker phases promote only on update-downloaded',async()=>{const f=fixture();f.u.emit('update-available',{version:'1.1.0'});await tick();assert.equal(readMarker(f.root).phase,'download-started');evidenceFiles(f);f.u.emit('update-downloaded');await tick();assert.equal(readMarker(f.root).phase,'install-ready');assert(f.u.installed);});
test('marker is durable before download begins',async()=>{let f,phase;f=fixture({download:async()=>{phase=readMarker(f.root)?.phase;}});f.u.emit('update-available',{version:'1.1.0'});await waitFor(()=>phase!==undefined);assert.equal(phase,'download-started');});
test('download rejection durably clears interrupted marker',async()=>{const f=fixture({download:async()=>{throw Error('rejected')}});f.u.emit('update-available',{version:'1.1.0'});await waitFor(()=>f.errors.includes('rejected'));assert.equal(readMarker(f.root),null);});
test('updater error event clears download-started marker on source version',async()=>{const f=pending('download-started');f.u.emit('error',Error('transport'));assert.equal(readMarker(f.root),null);assert(f.errors.includes('transport'));});
test('crash during download clears safely on source launch',async()=>{const f=pending('download-started'),r=await verifyPending({userData:f.root,runningVersion:'1.0.0',deepHealth:async()=>{throw Error('must not run')}});assert(r.interruptedDownload&&r.cleared);assert.equal(readMarker(f.root),null);});
test('install-ready on source clears deferred install without health or DB mutation',async()=>{const f=pending(),r=await verifyPending({userData:f.root,runningVersion:'1.0.0',deepHealth:async()=>{throw Error('must not run')}});assert(r.installDeferred&&r.cleared);});
test('after install on exact target requires strict evidence and deep health then clears',async()=>{const f=pending();let health=0;assert((await verifyPending({userData:f.root,runningVersion:'1.1.0',deepHealth:async()=>{health++;}})).installed);assert.equal(health,1);assert.equal(readMarker(f.root),null);});
const verifyRejectedEvidence=async(kind,mutate)=>{const f=pending(),file=path.join(f.root,'backups',id),manifest=path.join(f.root,'backups',`${id}.json`),m=JSON.parse(fs.readFileSync(manifest));if(kind==='createdAt')m.createdAt=17;if(kind==='durability')m.durability=null;if(kind==='extra')m.extra=true;if(kind==='missing')delete m.projects;if(kind==='hash')m.sha256='0'.repeat(64);if(kind==='size')m.size++;if(['createdAt','durability','extra','missing','hash','size'].includes(kind))fs.writeFileSync(manifest,JSON.stringify(m));if(mutate)mutate(file);const r=await verifyPending({userData:f.root,runningVersion:'1.1.0',deepHealth:async()=>{assert.fail('health must not run')}});assert.equal(r.recovery,true,kind);};
for(const kind of ['createdAt','durability','extra','missing','hash','size'])test(`exact managed evidence rejects ${kind}`,async()=>verifyRejectedEvidence(kind));
test('exact managed evidence rejects symlink',{skip:process.platform==='win32'?'POSIX link semantics unavailable on win32':false},async()=>verifyRejectedEvidence('symlink',file=>{const copy=`${file}.copy`;fs.renameSync(file,copy);fs.symlinkSync(copy,file);}));
test('exact managed evidence rejects hardlink',{skip:process.platform==='win32'?'POSIX link semantics unavailable on win32':false},async()=>verifyRejectedEvidence('hardlink',file=>fs.linkSync(file,`${file}.link`)));
test('impossible version, malformed evidence, malformed durability and health retain lock',async()=>{for(const kind of ['version','createdAt','durability','health']){const f=pending(),manifest=path.join(f.root,'backups',`${id}.json`);if(kind==='createdAt'){const m=JSON.parse(fs.readFileSync(manifest));m.createdAt=17;fs.writeFileSync(manifest,JSON.stringify(m));}if(kind==='durability'){const m=JSON.parse(fs.readFileSync(manifest));m.durability=null;fs.writeFileSync(manifest,JSON.stringify(m));}const r=await verifyPending({userData:f.root,runningVersion:kind==='version'?'1.2.0':'1.1.0',deepHealth:async()=>{if(kind==='health')throw Error('bad');}});assert.equal(r.recovery,true,kind);assert(fs.existsSync(path.join(f.root,'update-pending.json')));}});
test('path replacement during stable-handle validation fails',()=>{const f=pending(),file=path.join(f.root,'backups',id),realFstat=fs.fstatSync;let calls=0;fs.fstatSync=function(fd){const stat=realFstat(fd);if(++calls===2)fs.writeFileSync(file,Buffer.alloc(4096,9));return stat;};try{assert.throws(()=>promoteInstallReady(f.root));}finally{fs.fstatSync=realFstat;}});
