'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),{createWindowsNativeBroker,BOOTSTRAP}=require('../windows-native-broker');
function fixture(options={}){const child=new EventEmitter();child.pid=42;child.stdin=new PassThrough();child.stderr=new PassThrough();const socket=new EventEmitter();socket.setEncoding=()=>{};socket.destroy=()=>{};let nonce,challenge;socket.write=(line,cb)=>{const q=JSON.parse(line);if(q.command==='hello'){challenge=q.payload.challenge;queueMicrotask(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:q.id,ok:true,result:{protocolVersion:1,challenge,serverNonce:nonce,ownerSid:'S-1-5-21-1',acl:[{sid:'S-1-5-21-1',rights:7,type:'Allow'}]}})+'\n'))}else queueMicrotask(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:q.id,ok:true,result:{value:7}})+'\n'));cb?.()};const spawn=(exe)=>{if(exe.endsWith('taskkill.exe')){const k=new EventEmitter();queueMicrotask(()=>k.emit('exit',0));return k}queueMicrotask(()=>child.stderr.write('BOOT_START\nSOURCE_READ\nSOURCE_HASH_OK\nSOURCE_EXEC\nHELPER_START\nNATIVE_TYPE_READY\nENV_READY\nIDENTITY_READY\nPIPE_SECURITY_READY\nSERVER_CREATED\nWAIT_CLIENT\n'));return child};const connect=()=>{nonce=options.wrongNonce?'0'.repeat(64):lastEnv.GROWTHMAP_BROKER_NONCE;queueMicrotask(()=>{socket.emit('connect');setImmediate(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:0,command:'hello',nonce})+'\n'))});return socket};let lastEnv;const spawnWrapped=(exe,args,opts)=>{if(!exe.endsWith('taskkill.exe'))lastEnv=opts.env;return spawn(exe,args,opts)};return {options:{helperPath:'helper.ps1',readFile:()=>('x'.repeat(101)),env:{SystemRoot:'C:\Windows'},executable:'fake-powershell.exe',spawnImpl:spawnWrapped,connect,timeout:100},child,socket}}
test('PowerShell owns random pipe; bootstrap is fixed, short, hash-pinned stdin',async()=>{assert(Buffer.byteLength(Buffer.from(BOOTSTRAP,'utf16le').toString('base64'))<8192);const f=fixture(),b=createWindowsNativeBroker(f.options),started=await b.start();assert.match(started.pipeName,/^\\\\\.\\pipe\\[0-9a-f]{32}$/);assert.equal(started.ownerSid,'S-1-5-21-1');assert.deepEqual(await b.request('probe',{}),{value:7});assert.equal(f.child.stdin.read()?.toString(),'x'.repeat(101));await b.close()});
test('wrong server nonce fails closed',async()=>{const f=fixture({wrongNonce:true});await assert.rejects(createWindowsNativeBroker(f.options).start(),{code:'WINDOWS_NATIVE_BROKER_UNAVAILABLE',stage:'auth'})});
test('helper missing fails before spawn',async()=>{let spawned=false;const b=createWindowsNativeBroker({helperPath:'missing',readFile:()=>{throw Error()},spawnImpl:()=>{spawned=true},env:{SystemRoot:'C:\Windows'}});await assert.rejects(b.start(),{stage:'helper'});assert.equal(spawned,false)});
test('real helper bootstrap timeout exposes only last allowlisted fixed stage',async()=>{const f=fixture();f.options.serverTimeout=20;f.options.spawnImpl=(exe,args,opts)=>{if(exe.endsWith('taskkill.exe')){const k=new EventEmitter();queueMicrotask(()=>k.emit('exit',0));return k}queueMicrotask(()=>f.child.stderr.write('BOOT_START\nSOURCE_READ\nSOURCE_HASH_OK\nSOURCE_EXEC\nHELPER_START\nNATIVE_TYPE_READY\n'));return f.child};await assert.rejects(createWindowsNativeBroker(f.options).start(),{code:'WINDOWS_NATIVE_BROKER_UNAVAILABLE',stage:'server-timeout-NATIVE_TYPE_READY'})});
test('native intermediate crash seam is unavailable outside test',()=>{assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'production',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'C:\\x'}),{stage:'test-crash-phase'})});
test('native intermediate crash seam accepts only fixed enum and absolute sentinel',()=>{assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'arbitrary',testCrashSentinel:'C:\\x'}),{stage:'test-crash-phase'});assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'relative'}),{stage:'test-crash-sentinel'});assert.doesNotThrow(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'C:\\x'}));assert.doesNotThrow(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-quarantine-directory-flush',testCrashSentinel:'C:\\x'}))});
