'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),{createWindowsNativeBroker,BOOTSTRAP,validateSecurePath,validateSecurePathPolicyPayload,validateSecurePathPolicyResult,validateSecureRemoveFilePayload,validateSecureRemoveFileResult,DEFAULT_SERVER_TIMEOUT_MS}=require('../windows-native-broker');
function fixture(options={}){const child=new EventEmitter();child.pid=42;child.stdin=new PassThrough();child.stderr=new PassThrough();const socket=new EventEmitter();socket.setEncoding=()=>{};socket.destroy=()=>{};let nonce,challenge;socket.write=(line,cb)=>{const q=JSON.parse(line);if(q.command==='hello'){challenge=q.payload.challenge;queueMicrotask(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:q.id,ok:true,result:{protocolVersion:1,challenge,serverNonce:nonce,ownerSid:'S-1-5-21-1',acl:[{sid:'S-1-5-21-1',rights:7,type:'Allow'}]}})+'\n'))}else if(options.noResponse||options.writeError){}else if(options.malformed)queueMicrotask(()=>socket.emit('data','not-json\n'));else queueMicrotask(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:q.id,ok:true,result:{value:7}})+'\n'));if(options.writeError&&q.command!=='hello')queueMicrotask(()=>cb?.(Error('write')));else cb?.()};const spawn=(exe)=>{if(exe.endsWith('taskkill.exe')){options.onKill?.();const k=new EventEmitter();setTimeout(()=>{k.emit('exit',options.killCode??0);if(options.childExit!==false){child.exitCode=0;child.emit('exit',0)}},options.killDelay||0);return k}queueMicrotask(()=>child.stderr.write('BOOT_START\nSOURCE_READ\nSOURCE_HASH_OK\nSOURCE_EXEC\nHELPER_START\nNATIVE_TYPE_READY\nENV_READY\nIDENTITY_READY\nPIPE_SECURITY_READY\nSERVER_CREATED\nWAIT_CLIENT\n'));return child};const connect=()=>{nonce=options.wrongNonce?'0'.repeat(64):lastEnv.GROWTHMAP_BROKER_NONCE;queueMicrotask(()=>{socket.emit('connect');setImmediate(()=>socket.emit('data',JSON.stringify({protocolVersion:1,id:0,command:'hello',nonce})+'\n'))});return socket};let lastEnv;const spawnWrapped=(exe,args,opts)=>{if(!exe.endsWith('taskkill.exe'))lastEnv=opts.env;return spawn(exe,args,opts)};return {options:{helperPath:'helper.ps1',readFile:()=>('x'.repeat(101)),env:{SystemRoot:'C:\Windows'},executable:'fake-powershell.exe',spawnImpl:spawnWrapped,connect,timeout:100},child,socket}}
test('PowerShell owns random pipe; bootstrap is fixed, short, hash-pinned stdin',async()=>{assert(Buffer.byteLength(Buffer.from(BOOTSTRAP,'utf16le').toString('base64'))<8192);const f=fixture(),b=createWindowsNativeBroker(f.options),started=await b.start();assert.match(started.pipeName,/^\\\\\.\\pipe\\[0-9a-f]{32}$/);assert.equal(started.ownerSid,'S-1-5-21-1');assert.deepEqual(await b.request('probe',{}),{value:7});assert.equal(f.child.stdin.read()?.toString(),'x'.repeat(101));await b.close()});
test('PowerShell receives bounded Windows compiler discovery environment only',async()=>{const f=fixture();f.options.env={SystemRoot:'C:\\Windows',WINDIR:'C:\\Windows',TEMP:'C:\\Temp',TMP:'C:\\Tmp',PATH:'C:\\Windows\\System32',PATHEXT:'.COM;.EXE',ComSpec:'C:\\Windows\\System32\\cmd.exe',SECRET:'must-not-pass'};let childEnv;const spawn=f.options.spawnImpl;f.options.spawnImpl=(exe,args,opts)=>{if(!exe.endsWith('taskkill.exe'))childEnv=opts.env;return spawn(exe,args,opts)};const b=createWindowsNativeBroker(f.options);await b.start();assert.equal(childEnv.PATH,f.options.env.PATH);assert.equal(childEnv.PATHEXT,f.options.env.PATHEXT);assert.equal(childEnv.ComSpec,f.options.env.ComSpec);assert.equal(childEnv.SECRET,undefined);await b.close()});
test('wrong server nonce fails closed',async()=>{const f=fixture({wrongNonce:true});await assert.rejects(createWindowsNativeBroker(f.options).start(),{code:'WINDOWS_NATIVE_BROKER_UNAVAILABLE',stage:'auth'})});
test('helper missing fails before spawn',async()=>{let spawned=false;const b=createWindowsNativeBroker({helperPath:'missing',readFile:()=>{throw Error()},spawnImpl:()=>{spawned=true},env:{SystemRoot:'C:\Windows'}});await assert.rejects(b.start(),{stage:'helper'});assert.equal(spawned,false)});
test('real helper bootstrap timeout exposes only last allowlisted fixed stage',async()=>{const f=fixture();f.options.serverTimeout=20;f.options.spawnImpl=(exe,args,opts)=>{if(exe.endsWith('taskkill.exe')){const k=new EventEmitter();queueMicrotask(()=>{k.emit('exit',0);f.child.exitCode=0;f.child.emit('exit',0)});return k}queueMicrotask(()=>f.child.stderr.write('BOOT_START\nSOURCE_READ\nSOURCE_HASH_OK\nSOURCE_EXEC\nHELPER_START\nNATIVE_TYPE_READY\n'));return f.child};await assert.rejects(createWindowsNativeBroker(f.options).start(),{code:'WINDOWS_NATIVE_BROKER_UNAVAILABLE',stage:'server-timeout-NATIVE_TYPE_READY'})});
test('hosted helper cold-start default remains bounded beyond observed 30-second compilation',()=>{assert.equal(DEFAULT_SERVER_TIMEOUT_MS,60000);assert.ok(DEFAULT_SERVER_TIMEOUT_MS>30000&&DEFAULT_SERVER_TIMEOUT_MS<=60000)});
test('native intermediate crash seam is unavailable outside test',()=>{assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'production',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'C:\\x'}),{stage:'test-crash-phase'})});
test('native intermediate crash seam accepts only fixed enum and absolute sentinel',()=>{assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'arbitrary',testCrashSentinel:'C:\\x'}),{stage:'test-crash-phase'});assert.throws(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'relative'}),{stage:'test-crash-sentinel'});assert.doesNotThrow(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-rename-directory-flush',testCrashSentinel:'C:\\x'}));assert.doesNotThrow(()=>createWindowsNativeBroker({env:{NODE_ENV:'test',SystemRoot:'C:\\Windows'},testCrashPhase:'after-old-quarantine-directory-flush',testCrashSentinel:'C:\\x'}))});

test('cold and warm requests share exactly one broker process',async()=>{let spawns=0;const f=fixture();const base=f.options.spawnImpl;f.options.spawnImpl=(exe,args,opts)=>{if(!exe.endsWith('taskkill.exe'))spawns++;return base(exe,args,opts)};const b=createWindowsNativeBroker(f.options);assert.deepEqual(await b.request('one',{}),{value:7});assert.deepEqual(await b.request('two',{}),{value:7});assert.equal(spawns,1);await b.close()});
test('command timeout rejects only after taskkill completes',async()=>{let killed=false;const f=fixture({noResponse:true,killDelay:30});const base=f.options.spawnImpl;f.options.spawnImpl=(exe,args,opts)=>{const r=base(exe,args,opts);if(exe.endsWith('taskkill.exe'))r.once('exit',()=>{killed=true});return r};f.options.timeout=10;const b=createWindowsNativeBroker(f.options);await b.start();await assert.rejects(b.request('hang',{}),{stage:'timeout'});assert.equal(killed,true)});
test('malformed protocol follows one terminal kill path',async()=>{let kills=0;const f=fixture({malformed:true,onKill:()=>kills++});const b=createWindowsNativeBroker(f.options);await b.start();await assert.rejects(b.request('bad',{}),{stage:'protocol'});assert.equal(kills,1);await b.close();assert.equal(kills,1)});
test('socket write failure follows terminal cleanup',async()=>{let kills=0;const f=fixture({writeError:true,onKill:()=>kills++});const b=createWindowsNativeBroker(f.options);await b.start();await assert.rejects(b.request('bad',{}),{stage:'socket'});assert.equal(kills,1)});
test('abort waits for owned process tree cleanup and removes abort listener',async()=>{let killed=false,adds=0,removes=0;const f=fixture({noResponse:true,killDelay:20});const base=f.options.spawnImpl;f.options.spawnImpl=(exe,args,opts)=>{const r=base(exe,args,opts);if(exe.endsWith('taskkill.exe'))r.once('exit',()=>{killed=true});return r};const ac=new AbortController(),add=ac.signal.addEventListener.bind(ac.signal),remove=ac.signal.removeEventListener.bind(ac.signal);ac.signal.addEventListener=(...a)=>{adds++;return add(...a)};ac.signal.removeEventListener=(...a)=>{removes++;return remove(...a)};const b=createWindowsNativeBroker(f.options);await b.start();const p=b.request('hang',{},1000,ac.signal);ac.abort();await assert.rejects(p,{stage:'aborted'});assert.equal(killed,true);assert.ok(adds<=1);assert.ok(removes<=1)});
test('secure remove contract binds exact digest and handle-owned durable deletion',()=>{const fs=require('node:fs'),helper=fs.readFileSync(require('node:path').join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8'),payload={root:'C:\\safe',path:'C:\\safe\\terminal.bin',expectedSha256:'a'.repeat(64),expectedSize:42,containerPolicy:'private'};assert.deepEqual(validateSecureRemoveFilePayload(payload),payload);assert.deepEqual(validateSecureRemoveFileResult(payload,{identity:'1234ABCD:1234567890ABCDEF',deleted:true}),{path:payload.path,identity:'1234ABCD:1234567890ABCDEF',deleted:true});for(const bad of [{...payload,expectedSha256:'bad'},{...payload,expectedSize:-1},{...payload,extra:true}])assert.throws(()=>validateSecureRemoveFilePayload(bad));assert.match(helper,/'secure-remove-file' \{Exact-Keys \$q\.payload 'containerPolicy\|expectedSha256\|expectedSize\|path\|root'/);assert.match(helper,/secure-remove-file[\s\S]*OpenOwner\(\$p\)[\s\S]*Evidence \$s[\s\S]*OpenIdentity\(\$p\)[\s\S]*Delete\(\$h\)[\s\S]*NFlush/);assert.match(helper,/SetFileInformationByHandle\(h,4,p,1\)/)});
test('helper secure-path-policy contract is strict, bounded, ordered and identity-backed',()=>{const fs=require('node:fs'),helper=fs.readFileSync(require('node:path').join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');assert.match(helper,/Exact-Keys \$q\.payload 'root\|targets'/);assert.match(helper,/targets\.Count-lt1-or\$targets\.Count-gt64/);assert.match(helper,/Exact-Keys \$t 'containerPolicy\|kind\|path'/);assert.match(helper,/containerPolicy-ne'private'/);assert.match(helper,/kind-notin@\('file','directory'\)/);assert.match(helper,/VolumeSerial-eq0/);assert.match(helper,/FileIndexHigh-eq0-and\$i\.FileIndexLow-eq0/);assert.match(helper,/for\(\$n=0;\$n-lt\$targets\.Count;\$n\+\+\)/);assert.match(helper,/\$out\+=@\(@\{index=\$n;identity=\$record\.identity\}\)/)});
test('helper accepts only fixed local drive roots after canonicalization',()=>{const fs=require('node:fs'),helper=fs.readFileSync(require('node:path').join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');assert.match(helper,/GetDriveTypeW\(string rootPathName\)/);assert.match(helper,/\$p=Canon \$raw;\$root=\[IO\.Path\]::GetPathRoot\(\$p\)/);assert.match(helper,/GetDriveTypeW\(\$root\)-ne3\)\{throw 'network'\}/);assert.doesNotMatch(helper,/\$p-ine\$raw\)\{throw 'path'\}/);for(const blocked of ["raw-notmatch'^[A-Za-z]:\\\\'","$raw.Contains('/')","$raw.Substring(2).Contains(':')","$raw.IndexOfAny([char[]]'?*')"])assert.ok(helper.includes(blocked),blocked)});
test('helper combines ACL flags through explicit integral values before enum reconstruction',()=>{const fs=require('node:fs'),helper=fs.readFileSync(require('node:path').join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');assert.match(helper,/\[Security\.AccessControl\.AceFlags\]\(\[int\]\[Security\.AccessControl\.AceFlags\]::ContainerInherit-bor\[int\]\[Security\.AccessControl\.AceFlags\]::ObjectInherit\)/);assert.match(helper,/\[Security\.AccessControl\.InheritanceFlags\]\(\[int\]\[Security\.AccessControl\.InheritanceFlags\]::ContainerInherit-bor\[int\]\[Security\.AccessControl\.InheritanceFlags\]::ObjectInherit\)/);assert.doesNotMatch(helper,/::ContainerInherit-bor\[Security\.AccessControl\.(?:AceFlags|InheritanceFlags)\]::ObjectInherit/)});
test('secure-read helper accepts JSON Int32 bounds and maps only native not-found errors to missing',()=>{const fs=require('node:fs'),helper=fs.readFileSync(require('node:path').join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');assert.match(helper,/maxBytes-isnot\[int\]/);assert.doesNotMatch(helper,/maxBytes-isnot\[int64\]/);assert.match(helper,/GetFileAttributesW\(string fileName\)/);assert.match(helper,/if\(\$e-in@\(2,3\)\)\{throw 'missing'\};throw 'state'/);assert.match(helper,/FileAttributes\]::Directory\)-ne0\)\{throw 'target'/);assert.doesNotMatch(helper,/\[IO\.File\]::Exists\(\$p\)/);assert.match(helper,/Public-Stage[\s\S]{0,300}'missing'/)});

test('aggregate overflow is fatal and event loop remains responsive',async()=>{let kills=0,ticked=false;const f=fixture({noResponse:true,onKill:()=>kills++});const b=createWindowsNativeBroker(f.options);await b.start();const pending=b.request('large',{},1000);await new Promise(r=>setImmediate(r));const turn=new Promise(resolve=>setImmediate(()=>{ticked=true;resolve()}));f.socket.emit('data','x'.repeat(1024*1024+1));await Promise.all([assert.rejects(pending,{stage:'bounds'}),turn]);assert.equal(ticked,true);assert.equal(kills,1)});
test('helper source hash is recomputed and pinned into child environment',async()=>{const f=fixture();let hash;const base=f.options.spawnImpl;f.options.readFile=()=>('a'.repeat(101));f.options.spawnImpl=(exe,args,opts)=>{if(!exe.endsWith('taskkill.exe'))hash=opts.env.GROWTHMAP_BROKER_SOURCE_SHA256;return base(exe,args,opts)};const b=createWindowsNativeBroker(f.options);await b.start();assert.equal(hash,require('node:crypto').createHash('sha256').update('a'.repeat(101)).digest('hex'));await b.close()});
test('remote missing maps to ENOENT while other remote rejects remain opaque',()=>{const source=require('node:fs').readFileSync(require.resolve('../windows-native-broker.js'),'utf8');assert.match(source,/if\(value==='missing'\)error\.code='ENOENT'/);assert.match(source,/m\.ok===true\?p\.resolve\(m\.result\):p\.reject\(remoteError\(m\?\.error\?\.stage\)\)/);assert.doesNotMatch(source,/error\.code=m\?\.error/)});

test('secure path validators enforce drive absolute grammar, roots, order and exact results',()=>{assert.equal(validateSecurePath('C:\\'),'C:\\');for(const bad of ['\\foo','C:foo','\\\\server\\x','\\\\?\\C:\\x','\\\\.\\C:\\x','C:\\x:ads','C:\\x*','C:/x','C:\\safe\\.\\x','C:\\safe\\a\\..\\x','C:\\safe\\\\x','C:\\safe\\'])assert.throws(()=>validateSecurePath(bad),{code:'WINDOWS_NATIVE_BROKER_UNAVAILABLE'});const q=validateSecurePathPolicyPayload({root:'C:\\safe',targets:[{path:'C:\\safe\\A',kind:'directory',containerPolicy:'private'},{path:'c:\\safe\\A\\x',kind:'file',containerPolicy:'private'}]});assert.equal(q.targets.length,2);for(const p of [{root:'C:\\safe',targets:[{path:'C:\\safely\\x',kind:'file',containerPolicy:'private'}]},{root:'C:\\safe',targets:[{path:'D:\\safe\\x',kind:'file',containerPolicy:'private'}]}])assert.throws(()=>validateSecurePathPolicyPayload(p),{stage:'request-boundary'});const raw=[{index:0,identity:'00000001:0000000000000001'},{index:1,identity:'00000001:0000000000000002'}],ids=validateSecurePathPolicyResult(q,{identities:raw});assert.equal(ids[1].path,'c:\\safe\\A\\x');assert.throws(()=>validateSecurePathPolicyResult(q,{identities:raw.slice(0,1)}),{stage:'response-schema-policy-container'});for(const malformed of [[{...raw[0],extra:true},raw[1]],[{...raw[0],index:1},raw[1]],[raw[0],{...raw[1],index:0}]])assert.throws(()=>validateSecurePathPolicyResult(q,{identities:malformed}),{stage:'response-schema-policy-item'});assert.throws(()=>validateSecurePathPolicyResult(q,{identities:[{...raw[0],identity:'bad'},raw[1]]}),{stage:'response-schema-policy-identity'})});
test('taskkill nonzero or unconfirmed child reports cleanup-unconfirmed after bounded attempt',async()=>{for(const options of [{noResponse:true,killCode:1},{noResponse:true,childExit:false}]){const f=fixture(options);f.options.timeout=5;f.options.cleanupTimeout=15;const b=createWindowsNativeBroker(f.options);await b.start();await assert.rejects(b.request('hang',{}),{stage:'cleanup-unconfirmed'})}});

test('connect retry is cancelled by unexpected child exit and late connect cannot win',async()=>{const f=fixture({onKill:()=>{}});let attempts=0,destroys=0,last;f.options.connectTimeout=500;f.options.connect=()=>{attempts++;const s=new EventEmitter();s.destroy=()=>{destroys++};s.setEncoding=()=>{};last=s;queueMicrotask(()=>s.emit('error',Object.assign(Error('retry'),{code:'ENOENT'})));return s};const b=createWindowsNativeBroker(f.options),start=b.start();await new Promise(r=>setTimeout(r,10));f.child.emit('exit',1);await assert.rejects(start,{stage:/^(exit-nonzero|cleanup-unconfirmed)$/});const before=attempts;last.emit('connect');await new Promise(r=>setTimeout(r,60));assert.equal(attempts,before);assert.ok(destroys>=1)});
test('connect timeout waits for owned-tree cleanup before rejecting',async()=>{const f=fixture({killDelay:25});let killed=false;const spawn=f.options.spawnImpl;f.options.spawnImpl=(exe,args,opts)=>{const x=spawn(exe,args,opts);if(exe.endsWith('taskkill.exe'))x.once('exit',()=>{killed=true});return x};f.options.connectTimeout=10;f.options.connect=()=>{const s=new EventEmitter();s.destroy=()=>{};return s};const b=createWindowsNativeBroker(f.options);await assert.rejects(b.start(),{stage:'connect-timeout'});assert.equal(killed,true)});
test('partial child pipes are cleaned before pipes rejection',async()=>{for(const missing of ['stdin','stderr']){let kills=0,cleaned=false;const child=new EventEmitter();child.pid=77;child.stdin=missing==='stdin'?null:new PassThrough();child.stderr=missing==='stderr'?null:new PassThrough();const spawn=(exe)=>{if(exe.endsWith('taskkill.exe')){kills++;const k=new EventEmitter();setTimeout(()=>{k.emit('exit',0);child.exitCode=0;child.emit('exit',0);cleaned=true},15);return k}return child};const b=createWindowsNativeBroker({helperPath:'x',readFile:()=>('x'.repeat(101)),env:{SystemRoot:'C:\\Windows'},executable:'fake',spawnImpl:spawn,cleanupTimeout:50});await assert.rejects(b.start(),{stage:'pipes'});assert.equal(kills,1);assert.equal(cleaned,true)}});
test('partial child cleanup failure is cleanup-unconfirmed',async()=>{for(const mode of ['nonzero','no-child','no-pid']){const child=new EventEmitter();if(mode!=='no-pid')child.pid=78;child.stdin=null;child.stderr=new PassThrough();const spawn=(exe)=>{if(exe.endsWith('taskkill.exe')){const k=new EventEmitter();setTimeout(()=>{k.emit('exit',mode==='nonzero'?1:0);if(mode==='nonzero'){child.exitCode=0;child.emit('exit',0)}},1);return k}return child};const b=createWindowsNativeBroker({helperPath:'x',readFile:()=>('x'.repeat(101)),env:{SystemRoot:'C:\\Windows'},executable:'fake',spawnImpl:spawn,cleanupTimeout:10});await assert.rejects(b.start(),{stage:'cleanup-unconfirmed'})}});

test('ACL initialization preflight permits only the exact target to need ACL convergence',()=>{
 const {validateAclInitializationPreflight}=require('../windows-native-broker');
 const item=(kind,extra={})=>({exists:true,reparse:false,identity:true,finalPath:true,ownerTrusted:true,kind,nlink:kind==='file'?1:undefined,...extra});
 assert.equal(validateAclInitializationPreflight({rootBootstrap:true,kind:'directory',target:item('directory',{policySafe:false}),parent:item('directory',{policySafe:true,retainedStable:true})}),true);
 assert.throws(()=>validateAclInitializationPreflight({rootBootstrap:true,kind:'directory',target:item('directory',{policySafe:false}),parent:item('directory',{policySafe:false,retainedStable:true})}));
 assert.equal(validateAclInitializationPreflight({rootBootstrap:false,kind:'file',target:item('file',{policySafe:false}),ancestors:[item('directory',{policySafe:true})]}),true);
 for(const target of [item('file',{ownerTrusted:false}),item('file',{reparse:true}),item('file',{nlink:2})])assert.throws(()=>validateAclInitializationPreflight({rootBootstrap:false,kind:'file',target,ancestors:[item('directory',{policySafe:true})]}));
});
test('exact private ACL descriptor rejects every shape deviation',()=>{
 const {validatePrivateAclDescriptor}=require('../windows-native-broker'),sids=['ME','SYSTEM','ADMINS'],ace=(sid,extra={})=>({sid,type:'AccessAllowed',mask:'FullControl',flags:'None',inherited:false,...extra}),good={ownerSid:'ME',protected:true,aces:sids.map(ace)};
 assert.equal(validatePrivateAclDescriptor(good,'file',sids),true);
 const bad=[{...good,ownerSid:'SYSTEM'},{...good,aces:good.aces.slice(0,2)},{...good,aces:[...good.aces,ace('EXTRA')]},{...good,aces:[ace('ME'),ace('ME'),ace('ADMINS')]},{...good,aces:[ace('ME',{mask:'Modify'}),...good.aces.slice(1)]},{...good,aces:[ace('ME',{flags:'ContainerInherit|ObjectInherit'}),...good.aces.slice(1)]},{...good,aces:[ace('ME',{type:'AccessDenied'}),...good.aces.slice(1)]}];
 for(const descriptor of bad)assert.throws(()=>validatePrivateAclDescriptor(descriptor,'file',sids));
 const directory={ownerSid:'ME',protected:true,aces:sids.map(s=>ace(s,{flags:'ContainerInherit|ObjectInherit'}))};assert.equal(validatePrivateAclDescriptor(directory,'directory',sids),true);
});
test('replacement recovery barrier releases only the journal-matching installed transaction and otherwise fails closed',()=>{const fs=require('node:fs'),path=require('node:path'),helper=fs.readFileSync(path.join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');assert.match(helper,/'prepare-recovery' \{Exact-Keys \$q\.payload 'transactionId'/);assert.match(helper,/if\(\$script:tx\)\{if\(\$script:tx\.id-ne\$tid-or-not\$script:tx\.installed\)\{throw 'busy-transaction'\};Close-TxStrict\}/);assert.match(helper,/function Close-TxStrict\(\)\{[\s\S]*if\(\$x\.closeFailed\)\{throw 'busy-transaction'\}[\s\S]*\.Dispose\(\)[\s\S]*catch\{\$x\.closeFailed=\$true;throw\}[\s\S]*\$script:tx=\$null\}/);assert.match(helper,/if\(\$evidenceHandles\.Count-or\$script:tx\)\{throw 'state'\}/)});
test('native Owner+DACL helper contract uses current owner, exact access and fails closed',()=>{
 const fs=require('node:fs'),path=require('node:path'),{validateNativeAclOwnerDaclContract}=require('../windows-native-broker'),source=fs.readFileSync(path.join(__dirname,'..','windows-native-broker-helper.ps1'),'utf8');
 assert.deepEqual(validateNativeAclOwnerDaclContract(source),{openSecurityAccess:0xE0000,securityInformation:0x5,owner:'current-user',sacl:false});
 for(const bad of [source.replace('OWNER_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,sd','DACL_SECURITY_INFORMATION,sd'),source.replace('$a.SetOwner($me)','$a.SetOwner($preRaw.Owner)'),source.replace('Assert-ExactPrivateAcl $raw $isDir $me.Value','Assert-ExactPrivateAcl $raw $isDir \'S-1-5-18\''),source.replace('READ_CONTROL|WRITE_DAC|WRITE_OWNER','READ_CONTROL|WRITE_DAC')])assert.throws(()=>validateNativeAclOwnerDaclContract(bad),{stage:'acl-native-contract'});
});
