'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{createWindowsNativeOpen}=require('../windows-native-evidence');
function fake(handler){return ()=>{const child=new EventEmitter(),stdin=new EventEmitter(),stdout=new EventEmitter(),stderr=new EventEmitter();stdout.setEncoding=stderr.setEncoding=()=>{};child.stdin=stdin;child.stdout=stdout;child.stderr=stderr;child.kill=()=>{child.emit('exit',1)};stdin.write=(line,callback)=>{queueMicrotask(()=>handler(JSON.parse(line),value=>stdout.emit('data',JSON.stringify(value)+'\n'),child));callback?.()};stdin.destroy=()=>{};return child}}
const p='C:\\safe\\db.db',identity={platform:'win32',volumeSerial:'1234ABCD',fileIndex:'0000000100000002'},evidence={sha256:'a'.repeat(64),size:3};
const opts=handler=>({spawnImpl:fake(handler),readFile:()=>('x'.repeat(101)),executable:'powershell.exe',startupTimeout:50,commandTimeout:50});
test('strict ready/assert/close protocol',async()=>{const open=createWindowsNativeOpen(opts((q,send)=>q.path?send({protocolVersion:1,ready:true,identity,evidence}):q.command==='assert'?send({protocolVersion:1,ok:true,identity,evidence}):send({protocolVersion:1,closed:true})));const h=await open(p);assert.deepEqual(h.evidence,evidence);assert.equal(h.identity.path,p);await h.assertExact(evidence);await h.assertPath();await h.close();await h.close()});
test('response-supplied identity path is rejected and request path is reconstructed',async()=>{const open=createWindowsNativeOpen(opts((_q,send)=>send({protocolVersion:1,ready:true,identity:{...identity,path:'C:\\wrong'},evidence})));await assert.rejects(open(p),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'})});
test('malformed ready fails closed',async()=>{const open=createWindowsNativeOpen(opts((_q,send)=>send({ready:true})));await assert.rejects(open(p),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'})});
test('identity mismatch fails closed',async()=>{let n=0;const open=createWindowsNativeOpen(opts((q,send)=>q.path?send({protocolVersion:1,ready:true,identity,evidence}):send({protocolVersion:1,ok:true,identity:{...identity,fileIndex:'0000000100000003'},evidence})));const h=await open(p);await assert.rejects(h.assertPath(),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'})});
test('timeout and child exit fail closed',async()=>{await assert.rejects(createWindowsNativeOpen(opts(()=>{}))(p),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'});await assert.rejects(createWindowsNativeOpen(opts((_q,_s,c)=>c.emit('exit',2)))(p),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'})});
test('caller evidence mismatch fails closed',async()=>{const open=createWindowsNativeOpen(opts((q,send)=>q.path?send({protocolVersion:1,ready:true,identity,evidence}):send({protocolVersion:1,ok:true,identity,evidence})));const h=await open(p);await assert.rejects(h.assertExact({...evidence,size:4}),{code:'REPLACEMENT_EVIDENCE_UNAVAILABLE'})});
