'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {createReplacementJournal}=require('../replacement-journal'),{dbIdentity}=require('../credential-lineage');
const authority=(p,id)=>{p=path.win32.normalize(path.win32.resolve(p)).toLowerCase();return ({schemaVersion:1,bindings:{[p]:{identity:{platform:'win32',path:p,volumeSerial:id.slice(0,8),fileIndex:id.slice(9)},lineage:crypto.randomUUID(),legacyAdopted:false}}})};
function asyncFiles(){const values=new Map(),events=[];return {events,async exists(n){events.push('exists');await Promise.resolve();return values.has(n)},async read(n){events.push('read');await Promise.resolve();if(!values.has(n)){const e=Error('missing');e.code='ENOENT';throw e}return values.get(n)},async write(n,v){events.push('write');await Promise.resolve();values.set(n,Buffer.from(v))},async remove(n){events.push('remove');await Promise.resolve();values.delete(n)}}}
test('win32 dispatch requires explicit shared adapter or async files seam',()=>{assert.throws(()=>createReplacementJournal({platform:'win32',userData:'C:\\u',encrypt:x=>x,decrypt:x=>x}),/requires shared/);assert.throws(()=>dbIdentity('C:\\x.db',{platform:'win32'}),/requires shared/)});
test('async Windows journal awaits begin/update/read/terminal/clear and terminal supersession',async()=>{const files=asyncFiles(),crypt={encrypt:x=>Buffer.from(x),decrypt:x=>Buffer.from(x).toString()},db='C:\\data\\growthmap.db',a0=authority(db,'12345678:1234567890ABCDEF'),j=createReplacementJournal({platform:'win32',userData:'C:\\u',files,...crypt}),id=crypto.randomUUID(),ev={sha256:'a'.repeat(64),size:1};let i=await j.begin({transitionId:id,mode:'foreign-import',databasePath:db,oldEvidence:ev,newEvidence:null,authorityPre:a0});assert.equal((await j.read()).phase,'intent');i=await j.update(i,{newEvidence:ev,authorityNew:a0,phase:'cleanup-durable'});await j.markTerminalVerified(i);const id2=crypto.randomUUID();i=await j.begin({transitionId:id2,mode:'foreign-import',databasePath:db,oldEvidence:ev,newEvidence:null,authorityPre:a0});await j.clear(i);assert.equal(await j.read(),null);assert(files.events.includes('write')&&files.events.includes('read')&&files.events.includes('remove'))});
test('async db identity awaits adapter and rejects unstable or malformed identity',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'gm-async-id-')),p=path.join(root,'x.db');fs.writeFileSync(p,'x');let n=0;const unstable={policy:async()=>[{path:p,identity:++n===1?'12345678:1234567890ABCDEF':'12345678:1234567890ABCDE0'}]};await assert.rejects(dbIdentity(p,{platform:'win32',windowsAdapter:unstable}),/Unstable/);await assert.rejects(dbIdentity(p,{platform:'win32',windowsAdapter:{policy:async()=>[]}}),/invalid/)});
test('async journal FIFO makes concurrent begin/update atomic and recovers after rejection',async()=>{const files=asyncFiles(),crypt={encrypt:x=>Buffer.from(x),decrypt:x=>Buffer.from(x).toString()},db='C:\\data\\growthmap.db',a0=authority(db,'12345678:1234567890ABCDEF'),j=createReplacementJournal({platform:'win32',userData:'C:\\u',files,...crypt}),ev={sha256:'a'.repeat(64),size:1},make=()=>({transitionId:crypto.randomUUID(),mode:'foreign-import',databasePath:db,oldEvidence:ev,newEvidence:null,authorityPre:a0});const settled=await Promise.allSettled([j.begin(make()),j.begin(make())]);assert.equal(settled.filter(x=>x.status==='fulfilled').length,1);const i=settled.find(x=>x.status==='fulfilled').value,[u1,u2]=await Promise.allSettled([j.update(i,{phase:'db-installed'}),j.update(i,{phase:'committed'})]);assert.equal([u1,u2].filter(x=>x.status==='fulfilled').length,1);assert.equal((await j.read()).phase,'db-installed')});
test('terminal verification binds checked bytes and stale clear cannot delete a newer generation',async()=>{const files=asyncFiles(),crypt={encrypt:x=>Buffer.from(x),decrypt:x=>Buffer.from(x).toString()},db='C:\\data\\growthmap.db',a0=authority(db,'12345678:1234567890ABCDEF'),j=createReplacementJournal({platform:'win32',userData:'C:\\u',files,...crypt}),ev={sha256:'a'.repeat(64),size:1};let i=await j.begin({transitionId:crypto.randomUUID(),mode:'foreign-import',databasePath:db,oldEvidence:ev,newEvidence:null,authorityPre:a0});await assert.rejects(j.markTerminalVerified({...i,phase:'cleanup-durable'}),/proof changed/);i=await j.update(i,{newEvidence:ev,authorityNew:a0,phase:'cleanup-durable'});await j.markTerminalVerified(i);const bytes=Buffer.from(await files.read('replacement-intent.bin')),parsed=JSON.parse(bytes);parsed.phase='rollback-durable';await files.write('replacement-intent.bin',Buffer.from(JSON.stringify(parsed)));await assert.rejects(j.begin({transitionId:crypto.randomUUID(),mode:'foreign-import',databasePath:db,oldEvidence:ev,newEvidence:null,authorityPre:a0}),/verified atomic supersession/);await assert.rejects(j.clear(i),/changed unexpectedly/);assert.equal((await j.read()).phase,'rollback-durable')});
test('R39 A3/A4 source cuts bind native install before commit marker and NEW recovery after marker',()=>{const source=fs.readFileSync(path.join(__dirname,'windows-r39-acceptance.js'),'utf8'),commit=source.indexOf('await s.commit()'),a3=source.indexOf("if(cut==='A3')process.exit(86)"),update=source.indexOf("await j.update(i,{authorityNew:a.load(),phase:'committed'})"),a4=source.indexOf("if(cut==='A4')process.exit(86)");assert(commit<a3&&a3<update&&update<a4);assert.match(source,/\['A4','A5'\]\.includes\(cut\)\?'NEW':'OLD'/)});
