'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),script=fs.readFileSync(path.join(root,'.github/workflows/scripts/test-windows-mcp.py'),'utf8'),workflow=fs.readFileSync(path.join(root,'.github/workflows/desktop-windows.yml'),'utf8');
test('Windows MCP harness executes every required integration transition, not keyword placeholders',()=>{
 for(const call of ['bounded_run(exe,["provision"]','bounded_run(exe,["read"]','mcp_exchange(exe,env)','os.symlink(ordinary,discovery)','bounded_run(exe,["rebind"]','direct_project(endpoint2,token,401)','bounded_run(exe,["delete"]','assert_no_leak(evidence,token,ports,root)'])assert.match(script,new RegExp(call.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
 for(const reached of ['ordinary_discovery_and_mcp','reparse_rejected_by_executable','restart_rebind_persistence','revoke_blocks_bearer_and_mcp','credential_deleted','secret_evidence_checked'])assert.match(script,new RegExp(`reached\\.add\\(["']${reached}["']\\)`));
 assert.match(script,/required<=reached/);assert.match(script,/if os\.name!="nt":raise SystemExit\("genuine Windows required"\)/);
});
test('workflow runs exact harness after MCP build and before package build',()=>{const build=workflow.indexOf('./packaging/build-mcp.ps1'),harness=workflow.indexOf('./.github/workflows/scripts/test-windows-mcp.ps1'),pack=workflow.indexOf('npm run dist:win:e2e');assert(build>=0&&harness>build&&pack>harness)});
test('PyInstaller spec resolves tracked MCP sources from repository root',()=>{const spec=fs.readFileSync(path.resolve(__dirname,'../../src/backend/packaging/growthmap-mcp.spec'),'utf8');assert.match(spec,/Path\(SPECPATH\)\.resolve\(\)\.parents\[2\]/);for(const file of ['growthmap_mcp.py','growthmap_mcp_schemas.json','growthmap_credential.py'])assert.match(spec,new RegExp(file.replace('.','\\.')));assert.doesNotMatch(spec,/Analysis\(\['\.\.\/\.\.\/scripts\//)});
test('read check is status-only and harness forbids secret and endpoint ports in captured process evidence',()=>{const adapter=fs.readFileSync(path.join(root,'scripts/growthmap_mcp.py'),'utf8');assert.match(adapter,/read\(q\["target"\]\);return/);assert.match(script,/"argv":INVOCATIONS/);assert.match(script,/"env":env/);assert.match(script,/"stdout"/);assert.match(script,/"stderr"/);assert.match(script,/for port in port_strings/)});
test('Windows fixture preserves runtime environment case-insensitively and emits bounded startup diagnostics',()=>{assert.match(script,/k\.casefold\(\) in runtime_keys/);assert.match(script,/"path"/);assert.match(script,/def _sidecar_failure/);assert.match(script,/diagnostic output exceeded bound/);assert.match(script,/detail\[:4096\]/)});
test('MCP outcomes are transition-specific and diagnostics redact secret, port, and temp path',()=>{assert.match(script,/def assert_call_result/);assert.match(script,/replace\(secret,"<redacted-secret>"\)/);assert.match(script,/replace\(port,"<port>"\)/);assert.match(script,/"unsafe discovery descriptor"/);assert.match(script,/"GRANT_INACTIVE"/);assert.match(script,/"ordinary discovery"/);assert.match(script,/"restart rebind"/);assert.doesNotMatch(script,/expect_call_error/)});
test('frozen adapter dispatches credential argv and harness verifies secret-free status',()=>{const adapter=fs.readFileSync(path.join(root,'scripts/growthmap_mcp.py'),'utf8');assert.match(adapter,/def dispatch_credential_argv/);assert.match(adapter,/if dispatch_credential_argv\(\):raise SystemExit\(0\)/);for(const status of ['provisioned','available','deleted','rebound']){assert.match(adapter,new RegExp(`"status":"${status}"`));assert.match(script,new RegExp(`expected_status="${status}"`))}assert.match(script,/value!=\{"status":expected_status\}/)});
