param([switch]$SelfTestOnly,[string]$ProvenancePath,[string]$ProvenanceSha256)

$ErrorActionPreference = 'Stop'

$fixturePath = Join-Path $PSScriptRoot 'fixtures/production-package-layout.json'
$layout = Get-Content $fixturePath -Raw | ConvertFrom-Json
$requiredAsarEntries = @($layout.requiredAsarEntries)
$requiredResourceEntries = @($layout.requiredResourceEntries)
$forbiddenEntries = @('e2e-main.js', 'e2e-commercial-config.js', 'e2e-license-public-key.pem', 'E2E_ONLY', 'create-e2e-fixture', 'e2e-config-support', 'renderer-e2e', 'test-windows-', 'recovery-matrix', 'growthmap_payments', 'services/payments', 'admin_secret', 'signing_key')

function ConvertTo-NormalizedPackageEntry {
  param([Parameter(Mandatory)][string]$Entry)
  # @electron/asar emits root entries with a leading slash on Windows too. Trim
  # captured CRLF/whitespace, canonicalize separators, then remove all roots.
  return ((($Entry.Trim()) -replace '\\', '/') -replace '^/+', '')
}

function Assert-NoProductionTestEntries {
  param(
    [Parameter(Mandatory)][string[]]$Entries,
    [Parameter(Mandatory)][string]$Location
  )
  foreach ($entry in $Entries) {
    $normalized = ConvertTo-NormalizedPackageEntry $entry
    foreach ($needle in $forbiddenEntries) {
      if ($normalized.IndexOf($needle, [StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Production $Location contains forbidden E2E/test entry: $normalized"
      }
    }
    if ($normalized -match '(?i)(^|/|[-_])e2e([/_-]|$)' -or $normalized -match '(?i)(^|/)(tests?|test[-_]?helpers?)(/|$)') {
      throw "Production $Location contains a test path: $normalized"
    }
    $isApprovedPublicKey = $normalized -ceq 'commercial/license_public_key.pem'
    if ($normalized -match '(?i)\.py[co]?$' -or
        ((-not $isApprovedPublicKey) -and $normalized -match '(?i)\.pem(-|$|\.)') -or
        $normalized -match '(?i)\.(key|p12|pfx|sqlite|sqlite3|db)(-|$|\.)' -or
        $normalized -match '(?i)(^|/)migrations?(/|$)') {
      throw "Production $Location contains a forbidden server/key/database artifact: $normalized"
    }
  }
}

function Assert-NoForbiddenContent {
  param([Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$Location,[switch]$AllowInventoriedNodeModules)
  $rootPath = (Resolve-Path $Root).Path
  foreach ($file in Get-ChildItem $rootPath -File -Recurse) {
    $relative = [IO.Path]::GetRelativePath($rootPath, $file.FullName) -replace '\\','/'
    # App-owned files are scanned completely, regardless of size or extension.
    # node_modules is verified separately against the lock-installed byte inventory.
    if ($relative -match '(?i)(^|/)node_modules/') {
      if ($AllowInventoriedNodeModules) { continue }
      throw "Production $Location contains unowned node_modules subtree: $relative"
    }
    if ($relative -ceq 'app.asar') { continue }
    $bytes = [IO.File]::ReadAllBytes($file.FullName)
    $ascii = [Text.Encoding]::ASCII.GetString($bytes)
    # Search the full byte-derived string, not just file headers: renamed DBs or
    # payloads appended beyond a large benign prefix remain detectable.
    $hasSqlite = $ascii.Contains("SQLite format 3$([char]0)")
    $pythonBytecode = $bytes.Length -ge 4 -and $bytes[2] -eq 13 -and $bytes[3] -eq 10
    if ($ascii -match '-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----' -or $hasSqlite -or $pythonBytecode -or
        $ascii -match '(?i)(growthmap_payments|Ed25519PrivateKey|CREATE TABLE settlement_intents|quoted_amount_minor.*payment_proofs)') {
      throw "Production $Location contains forbidden server/key/database content: $relative"
    }
  }
}

function Assert-ThirdPartyInventory {
  param([Parameter(Mandatory)][string]$ExtractedRoot,[Parameter(Mandatory)][string]$InstalledRoot,[string]$LockPath='desktop/package-lock.json',[string]$PackagePath='desktop/package.json',[string]$ProvenancePath,[string]$ProvenanceSha256)
  if (-not $ProvenancePath -or -not $ProvenanceSha256 -or -not (Test-Path $ProvenancePath -PathType Leaf)) { throw 'Frozen clean-install provenance is required and must not be regenerated by verifier' }
  if ((Get-FileHash $ProvenancePath -Algorithm SHA256).Hash.ToLowerInvariant() -cne $ProvenanceSha256.ToLowerInvariant()) { throw 'Frozen clean-install provenance digest changed after capture' }
  $provenance=Get-Content $ProvenancePath -Raw|ConvertFrom-Json -Depth 10
  if ($provenance.version -ne 1 -or $provenance.lockSha256 -cne (Get-FileHash $LockPath -Algorithm SHA256).Hash.ToLowerInvariant() -or $provenance.packageSha256 -cne (Get-FileHash $PackagePath -Algorithm SHA256).Hash.ToLowerInvariant()) { throw 'Frozen provenance does not bind current lockfile/package.json' }
  $manifestFiles=@{};foreach($entry in $provenance.files){if($manifestFiles.ContainsKey($entry.path)){throw "Duplicate provenance path: $($entry.path)"};$manifestFiles[$entry.path]=$entry.sha256}
  $packaged = Join-Path $ExtractedRoot 'node_modules';$source=(Resolve-Path $InstalledRoot).Path
  foreach($file in Get-ChildItem $source -File -Force -Recurse){$rel=[IO.Path]::GetRelativePath($source,$file.FullName)-replace '\\','/';if(-not $manifestFiles.ContainsKey($rel)-or (Get-FileHash $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant() -cne $manifestFiles[$rel]){throw "Installed third-party file differs from frozen clean-install provenance: node_modules/$rel"}}
  if (@(Get-ChildItem $source -File -Force -Recurse).Count -ne $manifestFiles.Count) { throw 'Installed node_modules file set differs from frozen clean-install provenance' }
  # npm lockfile v3 intentionally uses packages[""] for root metadata. PowerShell 7
  # rejects that valid empty-string JSON key when producing a PSCustomObject, so
  # parse the lock as a hashtable and use explicit dictionary access throughout.
  $lock=Get-Content (Resolve-Path $LockPath) -Raw | ConvertFrom-Json -Depth 100 -AsHashtable
  $rootPackage=Get-Content (Resolve-Path $PackagePath) -Raw | ConvertFrom-Json -Depth 100
  if ($lock['lockfileVersion'] -ne 3 -or -not $lock.ContainsKey('packages') -or -not $lock['packages'].ContainsKey('')) { throw 'Third-party package lock must be npm lockfile v3 with root metadata' }
  foreach ($tree in @($ExtractedRoot,$source)) {
    $treeRoot=(Resolve-Path $tree).Path;$treeFolded=@{}
    foreach ($item in Get-ChildItem $treeRoot -Force -Recurse) {
      if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "Third-party inventory contains symlink/reparse point: $($item.FullName)" }
      $rel=[IO.Path]::GetRelativePath($treeRoot,$item.FullName) -replace '\\','/'
      if ($rel -match '(^|/)\.\.(/|$)' -or $rel.StartsWith('/')) { throw "Third-party inventory path escapes root: $rel" }
      $lower=$rel.ToLowerInvariant();if ($treeFolded.ContainsKey($lower) -and $treeFolded[$lower] -cne $rel) { throw "Third-party inventory contains case-colliding paths: $rel" };$treeFolded[$lower]=$rel
    }
  }
  $allowed=@{};$folded=@{}
  foreach ($prop in $lock['packages'].GetEnumerator()) {
    $key=([string]$prop.Key -replace '\\','/').TrimEnd('/')
    if (-not $key.StartsWith('node_modules/')) { continue }
    if ($key -match '(^|/)\.\.(/|$)') { throw "Invalid node_modules lock path: $key" }
    $relative=$key.Substring(13);$lower=$relative.ToLowerInvariant()
    if ($folded.ContainsKey($lower) -and $folded[$lower] -cne $relative) { throw "Case-colliding lock package paths: $relative" }
    $folded[$lower]=$relative;$meta=$prop.Value
    if (-not $meta['version'] -or (($meta['resolved'] -or $meta['integrity']) -and (-not $meta['resolved'] -or -not $meta['integrity']))) { throw "Incomplete lock identity/integrity metadata: $key" }
    $allowed[$relative]=$meta
  }
  $rootDeps=@{};foreach ($kind in @('dependencies','optionalDependencies')) { foreach ($p in $rootPackage.$kind.psobject.Properties) {$rootDeps[$p.Name]=[string]$p.Value} }
  $lockRootDeps=@{};foreach ($kind in @('dependencies','optionalDependencies')) { if ($lock['packages'][''].ContainsKey($kind)) { foreach ($p in $lock['packages'][''][$kind].GetEnumerator()) {$lockRootDeps[[string]$p.Key]=[string]$p.Value} } }
  $rootDependencyNames = (($rootDeps.Keys | Sort-Object) -join "`n")
  $lockRootDependencyNames = (($lockRootDeps.Keys | Sort-Object) -join "`n")
  if ($rootDependencyNames -cne $lockRootDependencyNames) { throw 'desktop package.json dependencies differ from package-lock root entry' }
  foreach ($name in $rootDeps.Keys) { if ($rootDeps[$name] -cne $lockRootDeps[$name] -or -not $allowed.ContainsKey($name)) { throw "Root dependency is not identically represented in lock: $name" } }
  function Get-PackageRoots([string]$Root) {
    if (-not (Test-Path $Root -PathType Container)) { return @() }
    $resolved=(Resolve-Path $Root).Path
    return @(Get-ChildItem $resolved -Directory -Force -Recurse | Where-Object {
      ($_.Parent.Name -eq 'node_modules' -and -not $_.Name.StartsWith('@')) -or
      ($_.Parent.Parent -and $_.Parent.Parent.Name -eq 'node_modules' -and $_.Parent.Name.StartsWith('@'))
    } | ForEach-Object { [IO.Path]::GetRelativePath($resolved,$_.FullName) -replace '\\','/' })
  }
  $installedRoots=@(Get-PackageRoots $source);$packagedRoots=@(Get-PackageRoots $packaged)
  foreach ($root in @($installedRoots+$packagedRoots)) { if (-not $allowed.ContainsKey($root)) { throw "Package root absent from lock inventory: node_modules/$root" } }
  # Electron may prune optional/platform packages, so packaged roots are a byte-identical
  # subset of the exact lock-installed roots; installed roots themselves may not exceed lock.
  foreach ($file in Get-ChildItem $packaged -File -Recurse) {
    $relative=[IO.Path]::GetRelativePath($packaged,$file.FullName);$expected=Join-Path $source $relative
    if (-not (Test-Path $expected -PathType Leaf)) { throw "Packaged third-party file absent from lock-installed inventory: node_modules/$($relative -replace '\\','/')" }
    if ((Get-FileHash $file.FullName -Algorithm SHA256).Hash -cne (Get-FileHash $expected -Algorithm SHA256).Hash) { throw "Packaged third-party file differs from lock-installed inventory: node_modules/$($relative -replace '\\','/')" }
  }
}

function Assert-RequiredEntries {
  param(
    [Parameter(Mandatory)][string[]]$Entries,
    [Parameter(Mandatory)][string[]]$Required,
    [Parameter(Mandatory)][string]$Location
  )
  $normalized = @($Entries | ForEach-Object { ConvertTo-NormalizedPackageEntry $_ })
  foreach ($requiredEntry in $Required) {
    # Archive/resource manifests use canonical casing even though Windows file
    # lookup is normally insensitive. Exact ordinal equality catches drift.
    if (-not ($normalized | Where-Object { $_ -ceq $requiredEntry })) {
      $name = [IO.Path]::GetFileName($requiredEntry)
      $nearby = @($normalized | Where-Object { $_.IndexOf($name, [StringComparison]::OrdinalIgnoreCase) -ge 0 } | Select-Object -First 20)
      if (-not $nearby.Count) {
        $nearby = @($normalized | Where-Object { $_ -notmatch '/' -or $_ -match '(?i)(commercial|identity|update|backup|startup)' } | Select-Object -First 40)
      }
      $detail = if ($nearby.Count) { $nearby -join "`n  " } else { '<empty manifest>' }
      throw "Production $Location is missing required trust-boundary entry: $requiredEntry`nNormalized entries near '$name' (or relevant roots):`n  $detail"
    }
  }
}

function Assert-ProductionPackageLayout {
  param(
    [Parameter(Mandatory)][string[]]$AsarEntries,
    [Parameter(Mandatory)][string[]]$ResourceEntries
  )
  Assert-NoProductionTestEntries $AsarEntries 'ASAR'
  Assert-NoProductionTestEntries $ResourceEntries 'resources'
  Assert-RequiredEntries $AsarEntries $requiredAsarEntries 'ASAR'
  Assert-RequiredEntries $ResourceEntries $requiredResourceEntries 'resources'
}

function Invoke-ProductionPackageLayoutSelfTest {
  $asarFixture = @($layout.asarListLines)
  $resourceFixture = @($layout.requiredResourceEntries | ForEach-Object { "\\$_`r" })
  Assert-ProductionPackageLayout $asarFixture $resourceFixture

  $missing = @($asarFixture | Where-Object { (ConvertTo-NormalizedPackageEntry $_) -cne 'updater.js' }) + @('/nested/updater.js')
  try {
    Assert-ProductionPackageLayout $missing $resourceFixture
    throw 'Package verifier self-test accepted a nested required updater module'
  } catch {
    if ($_.Exception.Message -notmatch 'missing required trust-boundary entry: updater\.js') { throw }
  }

  $contentRoot = Join-Path ([IO.Path]::GetTempPath()) ("growthmap-content-selftest-{0}" -f [guid]::NewGuid())
  New-Item -ItemType Directory $contentRoot | Out-Null
  try {
    foreach ($case in @(
      @{ Name='blob.dat'; Bytes=[Text.Encoding]::ASCII.GetBytes('-----BEGIN PRIVATE KEY-----') },
      @{ Name='cache.bin'; Bytes=[Text.Encoding]::ASCII.GetBytes("SQLite format 3`0payload") },
      @{ Name='worker.dat'; Bytes=[Text.Encoding]::ASCII.GetBytes('from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey') },
      @{ Name='schema.dat'; Bytes=[Text.Encoding]::ASCII.GetBytes('CREATE TABLE settlement_intents(secret TEXT)') },
      @{ Name='native.node'; Bytes=[Text.Encoding]::ASCII.GetBytes('-----BEGIN PRIVATE KEY-----') },
      @{ Name='suffix.bin'; Bytes=([byte[]](New-Object byte[] 2097153) + [Text.Encoding]::ASCII.GetBytes('SQLite format 3' + [char]0)) }
    )) {
      Get-ChildItem $contentRoot -File | Remove-Item -Force
      [IO.File]::WriteAllBytes((Join-Path $contentRoot $case.Name),$case.Bytes)
      try { Assert-NoForbiddenContent $contentRoot 'self-test'; throw 'Content verifier accepted adversarial generic payload' }
      catch { if ($_.Exception.Message -notmatch 'forbidden server/key/database content') { throw } }
    }
    $installed = Join-Path $contentRoot 'installed';$extracted = Join-Path $contentRoot 'extracted'
    New-Item -ItemType Directory (Join-Path $installed 'safe-package') -Force | Out-Null
    New-Item -ItemType Directory (Join-Path $extracted 'node_modules/safe-package') -Force | Out-Null
    [IO.File]::WriteAllText((Join-Path $installed 'safe-package/index.js'),'module.exports=1')
    [IO.File]::WriteAllText((Join-Path $extracted 'node_modules/safe-package/index.js'),'-----BEGIN PRIVATE KEY-----')
    $testLock=Join-Path $contentRoot 'package-lock.json';$testPackage=Join-Path $contentRoot 'package.json'
    [IO.File]::WriteAllText($testPackage,'{"dependencies":{"safe-package":"1.0.0"}}')
    [IO.File]::WriteAllText($testLock,'{"lockfileVersion":3,"packages":{"":{"dependencies":{"safe-package":"1.0.0"}},"node_modules/safe-package":{"version":"1.0.0","resolved":"https://registry.invalid/safe-package.tgz","integrity":"sha512-test"}}}')
    $testProvenance=Join-Path $contentRoot 'provenance.json';$testDigest=& (Join-Path $PSScriptRoot 'new-node-provenance.ps1') -NodeModules $installed -LockPath $testLock -PackagePath $testPackage -OutputPath $testProvenance
    try { Assert-ThirdPartyInventory $extracted $installed $testLock $testPackage $testProvenance $testDigest;throw 'Third-party inventory accepted a hidden node_modules payload' }
    catch { if ($_.Exception.Message -notmatch 'differs from lock-installed inventory') { throw } }
    # An extra package present in both installed and ASAR trees must still be rejected
    # because the lock, not either mutable tree, is the trust inventory. Refresh the
    # synthetic frozen provenance after each deliberate fixture mutation so the test
    # reaches the intended lock-inventory gate instead of failing at the earlier byte gate.
    foreach ($root in @($installed,(Join-Path $extracted 'node_modules'))) { New-Item -ItemType Directory (Join-Path $root 'smuggled') -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'smuggled/index.js'),'same') }
    $testDigest=& (Join-Path $PSScriptRoot 'new-node-provenance.ps1') -NodeModules $installed -LockPath $testLock -PackagePath $testPackage -OutputPath $testProvenance
    try { Assert-ThirdPartyInventory $extracted $installed $testLock $testPackage $testProvenance $testDigest;throw 'Inventory accepted package smuggled into installed and packaged trees' }
    catch { if ($_.Exception.Message -notmatch 'Package root absent from lock') { throw } }
    Remove-Item (Join-Path $installed 'smuggled'),(Join-Path $extracted 'node_modules/smuggled') -Recurse -Force
    foreach ($root in @($installed,(Join-Path $extracted 'node_modules'))) { New-Item -ItemType Directory (Join-Path $root 'safe-package/node_modules/nested-smuggled') -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $root 'safe-package/node_modules/nested-smuggled/index.js'),'same') }
    $testDigest=& (Join-Path $PSScriptRoot 'new-node-provenance.ps1') -NodeModules $installed -LockPath $testLock -PackagePath $testPackage -OutputPath $testProvenance
    try { Assert-ThirdPartyInventory $extracted $installed $testLock $testPackage $testProvenance $testDigest;throw 'Inventory accepted nested package absent from lock' }
    catch { if ($_.Exception.Message -notmatch 'Package root absent from lock') { throw } }
    Remove-Item (Join-Path $installed 'safe-package/node_modules'),(Join-Path $extracted 'node_modules/safe-package/node_modules') -Recurse -Force
    [IO.File]::WriteAllText($testPackage,'{"dependencies":{"other":"1.0.0"}}')
    $testDigest=& (Join-Path $PSScriptRoot 'new-node-provenance.ps1') -NodeModules $installed -LockPath $testLock -PackagePath $testPackage -OutputPath $testProvenance
    try { Assert-ThirdPartyInventory $extracted $installed $testLock $testPackage $testProvenance $testDigest;throw 'Inventory accepted lock/root dependency mismatch' }
    catch { if ($_.Exception.Message -notmatch 'dependencies differ') { throw } }
  } finally { Remove-Item $contentRoot -Recurse -Force }

  foreach ($case in @(
    @{ Asar = @($asarFixture + '\fixtures\E2E-MAIN.js'); Resources = $resourceFixture; Expected = 'Production ASAR contains forbidden' },
    @{ Asar = $asarFixture; Resources = @($resourceFixture + '\commercial\e2e-license-public-key.pem'); Expected = 'Production resources contains forbidden' },
    @{ Asar = @($asarFixture + '\services\payments\growthmap_payments\api.py'); Resources = $resourceFixture; Expected = 'Production ASAR contains forbidden' },
    @{ Asar = @($asarFixture + '\assets\renamed-worker.py'); Resources = $resourceFixture; Expected = 'Production ASAR contains a forbidden server/key/database artifact' },
    @{ Asar = $asarFixture; Resources = @($resourceFixture + '\assets\renamed-trust.pem'); Expected = 'Production resources contains a forbidden server/key/database artifact' },
    @{ Asar = $asarFixture; Resources = @($resourceFixture + '\assets\renamed-ledger.sqlite3'); Expected = 'Production resources contains a forbidden server/key/database artifact' },
    @{ Asar = @($asarFixture + '\assets\migrations\002.sql'); Resources = $resourceFixture; Expected = 'Production ASAR contains a forbidden server/key/database artifact' }
  )) {
    try {
      Assert-ProductionPackageLayout $case.Asar $case.Resources
      throw 'Package verifier self-test accepted forbidden E2E material'
    } catch {
      if (-not $_.Exception.Message.StartsWith($case.Expected, [StringComparison]::Ordinal)) { throw }
    }
  }
}

Invoke-ProductionPackageLayoutSelfTest
if ($SelfTestOnly) {
  Write-Host 'Production package layout fixture self-test passed.'
  return
}

$dist = (Resolve-Path 'desktop/dist').Path
$resources = Join-Path $dist 'win-unpacked/resources'
$asar = Join-Path $resources 'app.asar'
if (-not (Test-Path $asar -PathType Leaf)) { throw 'Final production app.asar is missing' }
if (-not (Get-ChildItem $dist -Filter 'GrowthMap-Setup-*.exe' | Select-Object -First 1)) {
  throw 'Final production installer is missing; refusing to inspect a stale unpacked dist'
}

# Use the maintained package explicitly; its output is one path per line and may
# contain leading separators/CRLF depending on capture and platform.
$list = @(npx --yes '@electron/asar' list $asar)
if ($LASTEXITCODE -ne 0) { throw '@electron/asar list failed' }
$resourceList = @(Get-ChildItem $resources -File -Recurse | ForEach-Object {
  [IO.Path]::GetRelativePath($resources, $_.FullName)
})
Assert-ProductionPackageLayout $list $resourceList

$tmp = Join-Path $env:RUNNER_TEMP ("growthmap-production-asar-{0}" -f [guid]::NewGuid())
New-Item -ItemType Directory -Path $tmp | Out-Null
Push-Location $tmp
try {
  npx --yes '@electron/asar' extract-file $asar main.js
  if ($LASTEXITCODE -ne 0) { throw 'Could not extract packaged main.js' }
  npx --yes '@electron/asar' extract-file $asar package.json
  if ($LASTEXITCODE -ne 0) { throw 'Could not extract packaged package.json' }
  $allPath = Join-Path $tmp 'all'
  npx --yes '@electron/asar' extract $asar $allPath
  if ($LASTEXITCODE -ne 0) { throw 'Could not extract production ASAR for content inspection' }
} finally {
  Pop-Location
}

Assert-NoForbiddenContent (Join-Path $tmp 'all') 'ASAR' -AllowInventoriedNodeModules
Assert-ThirdPartyInventory (Join-Path $tmp 'all') (Resolve-Path 'desktop/node_modules') 'desktop/package-lock.json' 'desktop/package.json' $ProvenancePath $ProvenanceSha256
Assert-NoForbiddenContent $resources 'resources'

$mainPath = Join-Path $tmp 'main.js'
$packagePath = Join-Path $tmp 'package.json'
if (-not (Test-Path $mainPath) -or -not (Test-Path $packagePath)) {
  throw 'ASAR extract-file did not produce main.js and package.json'
}
$main = Get-Content $mainPath -Raw
$packageText = Get-Content $packagePath -Raw
foreach ($needle in @('GROWTHMAP_DESKTOP_E2E', 'E2E_IMPORT', 'E2E_ONLY', 'remote-debugging-port', 'e2e-main')) {
  if ($main.Contains($needle) -or $packageText.Contains($needle)) {
    throw "Production ASAR contains forbidden E2E marker: $needle"
  }
}
$package = $packageText | ConvertFrom-Json
if ($package.main -cne 'main.js') { throw "Production package main must be main.js, got '$($package.main)'" }

# commercial-config.json is intentionally an extraResource because packaged
# runtime loads it from process.resourcesPath. Verify that exact resource,
# rather than falsely requiring/extracting an ASAR copy.
$commercialPath = Join-Path $resources 'commercial-config.json'
$sourceCommercialPath = (Resolve-Path 'desktop/commercial-config.json').Path
if ((Get-FileHash $commercialPath -Algorithm SHA256).Hash -cne (Get-FileHash $sourceCommercialPath -Algorithm SHA256).Hash) {
  throw 'Packaged commercial-config.json hash differs from the production source resource'
}
$commercialText = Get-Content $commercialPath -Raw
$commercial = $commercialText | ConvertFrom-Json
$expectedCommercial = @('schemaVersion','productMajor','licensePublicKeyResource','licensePublicKeySha256','paymentApiOrigin','purchasePortalOrigin','purchasePortalUrl','baseNetwork','baseUsdc','basePayee','earlyLimit','earlyPriceMicros','regularPriceMicros','paypalUrl','updateUrl','updateOrigin','publisher','publisherStatus') | Sort-Object
$actualCommercial = @($commercial.psobject.Properties.Name) | Sort-Object
if (Compare-Object $expectedCommercial $actualCommercial) { throw 'Commercial config schema mismatch' }
if ($env:GROWTHMAP_COMMERCIAL_RELEASE -eq '1' -and ($commercialText -match 'REPLACE|EXAMPLE|TBD|UNAPPROVED')) { throw 'Commercial resource contains placeholder trust configuration' }

Write-Host "Production ASAR and resources verified from final installer dist: $asar"
Remove-Item $tmp -Recurse -Force
