import assert from "node:assert/strict";
import test from "node:test";
import { reorderBlockAuthoritatively, type OwnerToken } from "./block-reorder";
const rows = [{ id: "a", node_id: "n", order_index: 0 }, { id: "b", node_id: "n", order_index: 1 }];
const token: OwnerToken = { projectId: "p", nodeId: "n", generation: 1 };
const owner = { project: { id: "p" }, node: { id: "n", project_id: "p" }, blocks: [...rows].reverse() };
const deferred = <T>() => { let resolve!: (v:T)=>void; let reject!: (error:Error)=>void; const promise=new Promise<T>((r,j)=>{resolve=r;reject=j}); return {promise,resolve,reject}; };

test("one PATCH and coherent owner publication", async()=>{const calls:string[]=[];const result=await reorderBlockAuthoritatively(rows,0,1,token,{current:()=>true},async()=>{calls.push("PATCH")},async()=>{calls.push("GET");return owner},()=>calls.push("PUBLISH"),()=>calls.push("INVALIDATE"));assert.deepEqual(calls,["PATCH","GET","PUBLISH"]);assert.deepEqual(result,{moved:true})});
test("boundary no-op has zero PATCH GET publish invalidate",async()=>{let calls=0;const result=await reorderBlockAuthoritatively(rows,0,-1,token,{current:()=>true},async()=>{calls++},async()=>{calls++;return owner},()=>{calls++},()=>{calls++});assert.equal(calls,0);assert.deepEqual(result,{moved:false})});
test("A to B supersession is silent and cannot refresh or mutate new owner",async()=>{const d=deferred<typeof owner>();let current=true,published=0,invalidated=0,refresh=0,patches=0;const pending=reorderBlockAuthoritatively(rows,0,1,token,{current:()=>current},async()=>{patches++},()=>d.promise,()=>published++,()=>invalidated++);current=false;d.resolve(owner);const result=await pending;if(result.moved)refresh++;assert.deepEqual(result,{moved:false,superseded:true});assert.deepEqual({published,invalidated,refresh,patches},{published:0,invalidated:1,refresh:0,patches:1})});
test("readback rejection after A to B switch silently invalidates A once",async()=>{let current=true,invalidated=0,published=0;const d=deferred<typeof owner>();const pending=reorderBlockAuthoritatively(rows,0,1,token,{current:()=>current},async()=>{},()=>d.promise,()=>published++,()=>invalidated++);current=false;d.reject(new Error("failed"));assert.deepEqual(await pending,{moved:false,superseded:true});assert.equal(invalidated,1);assert.equal(published,0)});
for(const [name,bad] of [["project",{...owner,project:{id:"x"}}],["node",{...owner,node:{id:"x",project_id:"p"}}],["block",{...owner,blocks:[{id:"a",node_id:"x",order_index:0}]}]] as const)test(`mismatched ${name} fails closed`,async()=>{let invalidated=0,published=0;await assert.rejects(()=>reorderBlockAuthoritatively(rows,0,1,token,{current:()=>true},async()=>{},async()=>bad,()=>published++,()=>invalidated++),/CONTENT_REORDER_SAVED_REFRESH_FAILED/);assert.equal(published,0);assert.equal(invalidated,1)});
