"use client";
import { useI18n } from "@/i18n/provider";
import { msg } from "@/i18n/ui";
import {useCallback,useEffect,useState} from "react";
import {type AgentPortActivity} from "@/lib/api";
import {useAgentPortDesktopControl} from "@/lib/agent-port-control";
import type {GNode} from "@/lib/types";
export function AgentPortPanel({projectId,rootNode,onClose}:{projectId:string;rootNode:GNode;onClose:()=>void}){
  const { locale } = useI18n();
  const u = (tw: string, cn: string, en: string) => msg(locale, {"zh-TW":tw,"zh-CN":cn,en});
 const desktopControl=useAgentPortDesktopControl();
 const [access,setAccess]=useState<Record<string,unknown>|null>(null),[lifetime,setLifetime]=useState("unlimited"),[grants,setGrants]=useState<Record<string,unknown>[]>([]),[activity,setActivity]=useState<AgentPortActivity>({proposals:[],events:[],readbacks:[]}),[token,setToken]=useState(""),[label,setLabel]=useState("Local agent"),[identity,setIdentity]=useState("agent"),[permission,setPermission]=useState("propose"),[hours,setHours]=useState(24),[message,setMessage]=useState("");
 const reload=useCallback(async()=>{if(!desktopControl)return;const d=window.growthmapDesktop!;const[g,a,x]=await Promise.all([d.agentPort.list(projectId),d.agentPort.activity(projectId),d.agentAccess.status()]);setGrants(g);setActivity(a);setAccess(x);},[desktopControl,projectId]);useEffect(()=>{if(desktopControl)void reload().catch(e=>setMessage(String(e)));},[desktopControl,reload]);
 const create=async()=>{if(!desktopControl)return;try{const row=await window.growthmapDesktop!.agentPort.create({project_id:projectId,permission,label,agent_identity:identity,expires_at:new Date(Date.now()+hours*3600000).toISOString()});setToken(String(row.token));setMessage(u("權杖只顯示這一次。請立即複製並安全保存。", "令牌仅显示一次。请立即复制并安全保存。", "The token is shown only once. Copy it now and store it securely."));await reload();}catch(e){setMessage((e as Error).message||String(e));}};
 const review=async(id:string,decision:"approve"|"reject")=>{if(!desktopControl)return;try{await window.growthmapDesktop!.agentPort.review(id,decision);await reload();}catch(e){setMessage(u(`審核失敗（可能是 revision conflict）：${String(e)}`,`审核失败（可能是 revision conflict）：${String(e)}`,`Review failed (possible revision conflict): ${String(e)}`))}};
 if(!desktopControl)return <div data-testid="agent-port-unavailable" role="dialog" aria-modal="true" className="fixed inset-0 z-[130] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><div className="w-full max-w-md rounded-xl border border-gray-700 bg-gray-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><h2 className="font-semibold text-gray-100">Agent Port control unavailable</h2><p className="mt-2 text-sm text-gray-400">Human grant, activity, and proposal review controls require the trusted GrowthMap desktop preload.</p></div><button type="button" aria-label="Close" onClick={onClose}>×</button></div></div></div>;
 return <div data-testid="agent-port-panel" className="fixed inset-0 z-[130] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><div className="max-h-[88vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-gray-700 bg-gray-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="font-semibold text-gray-100">🔌 Agent Port v1</h2><p className="text-xs text-gray-500">{u('Provider-neutral REST 協作。只授予 GrowthMap graph 權限，不授予檔案、repo 或模型權限。','Provider-neutral REST 协作。仅授予 GrowthMap graph 权限，不授予文件、repo 或模型权限。','Provider-neutral REST collaboration. Grants GrowthMap graph access only—never file, repository, or model access.')}</p></div><button onClick={onClose}>×</button></div>
 <section className="mt-4 rounded border border-emerald-900 p-3"><div className="flex justify-between"><div><b>{u('允許本機代理','允许本地代理','Allow local agents')}</b><p className="text-xs text-gray-400">{u('允許同一 Windows 使用者的 MCP 相容本機程序。','允许同一 Windows 用户的 MCP 兼容本地进程。','Allows MCP-compatible local processes running as this Windows user.')}</p></div><button data-testid="agent-access-master" onClick={()=>void (async()=>{try{if(access?.enabled)await window.growthmapDesktop!.agentAccess.disable();else await window.growthmapDesktop!.agentAccess.enable({projectId,permission,lifetime});await reload();}catch(e){setMessage((e as Error).message||String(e));}})()} className="rounded bg-emerald-700 px-3 text-xs">{access?.enabled?u('停用並撤銷','停用并撤销','Disable and revoke'):u('啟用','启用','Enable')}</button></div><div className="mt-2 flex gap-2"><select aria-label="agent access lifetime" value={lifetime} onChange={e=>setLifetime(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"><option value="session">{u("工作階段期間","会话期间","Session")}</option><option value="24h">{u("24 小時","24 小时","24 hours")}</option><option value="7d">{u("7 天","7 天","7 days")}</option><option value="30d">{u("30 天","30 天","30 days")}</option><option value="unlimited">{u("直到手動停用","直到手动停用","Until manually disabled")}</option></select><button onClick={()=>void window.growthmapDesktop!.agentAccess.copy().then(()=>setMessage(u('已複製設定。','已复制配置。','Configuration copied.')))} className="rounded border px-2 text-xs">{u('複製通用 MCP 設定','复制通用 MCP 配置','Copy generic MCP config')}</button><button onClick={()=>void window.growthmapDesktop!.agentAccess.download().then(r=>r.saved&&setMessage(u('已儲存設定。','已保存配置。','Configuration saved.')))} className="rounded border px-2 text-xs">{u('下載 JSON','下载 JSON','Download JSON')}</button><button onClick={()=>void window.growthmapDesktop!.agentAccess.test().then(r=>setMessage(r.ok?u('連線測試成功。','连接测试成功。','Connection test passed.'):u('連線測試失敗。','连接测试失败。','Connection test failed.')))} className="rounded border px-2 text-xs">{u('測試連線','测试连接','Test connection')}</button>{Boolean(access?.enabled)&&<button onClick={()=>void window.growthmapDesktop!.agentAccess.regenerate().then(reload).catch(e=>setMessage(String(e)))} className="rounded border border-amber-700 px-2 text-xs">{u('重新產生存取權','重新生成访问权','Regenerate access')}</button>}</div></section>
 <div className="mt-4 grid gap-2 rounded border border-gray-800 p-3 sm:grid-cols-4"><input aria-label="grant label" value={label} onChange={e=>setLabel(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><input aria-label="agent identity" value={identity} onChange={e=>setIdentity(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><select value={permission} onChange={e=>setPermission(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"><option>read</option><option>propose</option><option>write</option></select><input aria-label="expiry hours (hours)" type="number" min={1} max={2160} value={hours} onChange={e=>setHours(Number(e.target.value))} className="rounded bg-gray-800 p-2 text-xs"/><button onClick={()=>void create()} className="rounded bg-blue-600 p-2 text-xs sm:col-span-4">{u('建立 project-wide 有限期 grant','创建 project-wide 限时 grant','Create project-wide expiring grant')}</button></div>
 {token&&<div className="mt-3 rounded border border-amber-700 bg-amber-950/20 p-3"><b className="text-xs text-amber-300">{u('⚠️ 只顯示一次；關閉後無法找回','⚠️ 仅显示一次；关闭后无法找回','⚠️ Shown once; it cannot be recovered after closing')}</b><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-auto rounded bg-black p-2 text-xs">{token}</code><button onClick={()=>void navigator.clipboard.writeText(token)} className="rounded border border-amber-700 px-2 text-xs">{u('複製','复制','Copy')}</button></div></div>}{message&&<p className="mt-2 text-xs text-amber-300">{message}</p>}
 <h3 className="mt-5 text-sm font-medium">Access grants</h3><div className="space-y-2">{grants.map(g=><div key={String(g.id)} className="rounded border border-gray-800 p-2 text-xs"><div className="flex justify-between"><span>{String(g.label)} · {String(g.agent_identity)} · {String(g.permission)} · {g.node_scope_id?"node":g.branch_root_id?"branch":"project-wide"}</span><span>{String(g.status)}</span></div><div className="text-gray-500">prefix {String(g.token_prefix)} · {u('到期','到期','expires')} {g.persistent?u('直到手動停用','直到手动停用','until manually disabled'):new Date(String(g.expires_at)).toLocaleString(locale)} · last use {g.last_used_at?new Date(String(g.last_used_at)).toLocaleString():"never"}</div>{g.status==="active"&&<button onClick={()=>void window.growthmapDesktop!.agentPort.revoke(String(g.id)).then(reload)} className="mt-1 text-red-300">{u('撤銷','撤销','Revoke')}</button>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Proposal bundles / revision diff</h3><div className="space-y-2">{activity.proposals.map(p=><div key={String(p.id)} className="rounded border border-purple-900 p-2 text-xs"><div>{String(p.title)} · expected project r{String(p.expected_project_revision)} · {String(p.status)}</div><pre className="mt-1 max-h-36 overflow-auto whitespace-pre-wrap text-[11px] text-gray-400">{JSON.stringify(p.operations,null,2)}</pre>{p.status==="pending"&&<div className="flex gap-2"><button onClick={()=>void review(String(p.id),"approve")} className="text-emerald-300">{u('核准套用','批准并应用','Approve and apply')}</button><button onClick={()=>void review(String(p.id),"reject")} className="text-red-300">{u('拒絕','拒绝','Reject')}</button></div>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Events / implementation readback</h3>{activity.events.map(e=><div key={String(e.id)} className="text-xs text-gray-400">{String(e.event_type)} · {String(e.message)}</div>)}{activity.readbacks.map(r=><div key={String(r.id)} className="mt-2 rounded border border-gray-800 p-2 text-xs"><b>{String(r.summary||"Implementation readback")}</b><div className="text-gray-500">node {String(r.target_node_id||rootNode.id)} · commits {JSON.stringify(r.commit_refs)} · files {JSON.stringify(r.files)} · tests {JSON.stringify(r.tests)} · risks {JSON.stringify(r.risks)} · todos {JSON.stringify(r.todos)}</div></div>)}</div></div>
}
