"use client";
import {useCallback,useEffect,useState} from "react";
import {api} from "@/lib/api";
import type {AgentPortActivity,AgentPortReadback} from "@/lib/api";
import {useAgentPortDesktopControl} from "@/lib/agent-port-control";
import type {GNode} from "@/lib/types";
export function AgentPortPanel({projectId,rootNode,onClose,onSelectNode}:{projectId:string;rootNode:GNode;onClose:()=>void;onSelectNode?:(nodeId:string)=>void}){
 const desktopControl=useAgentPortDesktopControl();
 const [grants,setGrants]=useState<Record<string,unknown>[]>([]),[activity,setActivity]=useState<AgentPortActivity>({proposals:[],events:[],readbacks:[]}),[token,setToken]=useState(""),[label,setLabel]=useState("Local agent"),[identity,setIdentity]=useState("agent"),[permission,setPermission]=useState("propose"),[hours,setHours]=useState(24),[message,setMessage]=useState("");
 const reload=useCallback(async()=>{if(!desktopControl)return;setGrants(await api.listAgentGrants(projectId));setActivity(await api.getAgentPortActivity(projectId));},[desktopControl,projectId]);useEffect(()=>{if(desktopControl)void reload().catch(e=>setMessage(String(e)));},[desktopControl,reload]);
 const create=async()=>{if(!desktopControl)return;const row=await api.createAgentGrant({project_id:projectId,permission,label,agent_identity:identity,expires_at:new Date(Date.now()+hours*3600000).toISOString()});setToken(String(row.token));setMessage("權杖只顯示這一次。請立即複製並安全保存。");await reload();};
 const review=async(id:string,decision:"approve"|"reject")=>{if(!desktopControl)return;try{await api.reviewAgentProposal(id,decision);await reload();}catch(e){setMessage(`審核失敗（可能是 revision conflict）：${String(e)}`)}};
 if(!desktopControl)return <div data-testid="agent-port-unavailable" role="dialog" aria-modal="true" className="fixed inset-0 z-[130] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><div className="w-full max-w-md rounded-xl border border-gray-700 bg-gray-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><h2 className="font-semibold text-gray-100">Agent Port control unavailable</h2><p className="mt-2 text-sm text-gray-400">Human grant, activity, and proposal review controls require the trusted GrowthMap desktop preload.</p></div><button type="button" aria-label="Close" onClick={onClose}>×</button></div></div></div>;
 return <div data-testid="agent-port-panel" className="fixed inset-0 z-[130] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><div className="max-h-[88vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-gray-700 bg-gray-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="font-semibold text-gray-100">🔌 Agent Port v1</h2><p className="text-xs text-gray-500">Provider-neutral REST 協作。只授予 GrowthMap graph 權限，不授予檔案、repo 或模型權限。</p></div><button onClick={onClose}>×</button></div>
 <div className="mt-4 grid gap-2 rounded border border-gray-800 p-3 sm:grid-cols-4"><input aria-label="grant label" value={label} onChange={e=>setLabel(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><input aria-label="agent identity" value={identity} onChange={e=>setIdentity(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><select value={permission} onChange={e=>setPermission(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"><option>read</option><option>propose</option><option>write</option></select><input aria-label="expiry hours" type="number" min={1} max={2160} value={hours} onChange={e=>setHours(Number(e.target.value))} className="rounded bg-gray-800 p-2 text-xs"/><button onClick={()=>void create()} className="rounded bg-blue-600 p-2 text-xs sm:col-span-4">建立 project-wide 有限期 grant</button></div>
 {token&&<div className="mt-3 rounded border border-amber-700 bg-amber-950/20 p-3"><b className="text-xs text-amber-300">⚠️ 只顯示一次；關閉後無法找回</b><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-auto rounded bg-black p-2 text-xs">{token}</code><button onClick={()=>void navigator.clipboard.writeText(token)} className="rounded border border-amber-700 px-2 text-xs">複製</button></div></div>}{message&&<p className="mt-2 text-xs text-amber-300">{message}</p>}
 <h3 className="mt-5 text-sm font-medium">Access grants</h3><div className="space-y-2">{grants.map(g=><div key={String(g.id)} className="rounded border border-gray-800 p-2 text-xs"><div className="flex justify-between"><span>{String(g.label)} · {String(g.agent_identity)} · {String(g.permission)} · {g.node_scope_id?"node":g.branch_root_id?"branch":"project-wide"}</span><span>{String(g.status)}</span></div><div className="text-gray-500">prefix {String(g.token_prefix)} · 到期 {new Date(String(g.expires_at)).toLocaleString()} · last use {g.last_used_at?new Date(String(g.last_used_at)).toLocaleString():"never"}</div>{g.status==="active"&&<button onClick={()=>void api.revokeAgentGrant(String(g.id)).then(reload)} className="mt-1 text-red-300">撤銷</button>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Proposal bundles / revision diff</h3><div className="space-y-2">{activity.proposals.map(p=><div key={String(p.id)} className="rounded border border-purple-900 p-2 text-xs"><div>{String(p.title)} · expected project r{String(p.expected_project_revision)} · {String(p.status)}</div><pre className="mt-1 max-h-36 overflow-auto whitespace-pre-wrap text-[11px] text-gray-400">{JSON.stringify(p.operations,null,2)}</pre>{p.status==="pending"&&<div className="flex gap-2"><button onClick={()=>void review(String(p.id),"approve")} className="text-emerald-300">核准套用</button><button onClick={()=>void review(String(p.id),"reject")} className="text-red-300">拒絕</button></div>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Events / implementation readback</h3>{activity.events.map(e=><div key={String(e.id)} className="text-xs text-gray-400">{String(e.event_type)} · {String(e.message)}</div>)}{activity.readbacks.map(r=><ReadbackCard key={r.id} readback={r} fallbackNodeId={rootNode.id} onSelectNode={onSelectNode}/>)}</div></div>
}

function ReadbackCard({readback:r,fallbackNodeId,onSelectNode}:{readback:AgentPortReadback;fallbackNodeId:string;onSelectNode?:(nodeId:string)=>void}){
 const target=r.target_node_id||fallbackNodeId;
 const list=(label:string,items:unknown[])=><div><span className="text-gray-400">{label}:</span> {items.length?JSON.stringify(items):"—"}</div>;
 return <div data-testid="agent-readback-card" className="mt-2 rounded border border-gray-800 p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><b>{r.summary||"Implementation readback"}</b><span>based on project r{r.based_on_project_revision}</span><span className={r.context_stale?"rounded bg-amber-900 px-2 py-0.5 text-amber-200":"rounded bg-emerald-900 px-2 py-0.5 text-emerald-200"}>{r.context_stale?`stale · current r${r.current_project_revision}`:`current r${r.current_project_revision}`}</span><code title={r.context_snapshot_digest}>digest {r.context_snapshot_digest.slice(0,12)}</code></div><div className="mt-1 text-gray-500">target {onSelectNode?<button type="button" className="underline" onClick={()=>onSelectNode(target)}>{target}</button>:target}</div><div className="mt-2 space-y-1 text-gray-300">{list("commits",r.commit_refs)}{list("files",r.files)}{list("tests",r.tests)}{list("decisions",r.decisions)}{list("risks",r.risks)}{list("todos",r.todos)}{list("evidence",r.evidence)}</div></div>;
}
