"use client";
import {useCallback,useEffect,useState} from "react";
import {api} from "@/lib/api";
import type {GNode} from "@/lib/types";
export function AgentPortPanel({projectId,rootNode,onClose}:{projectId:string;rootNode:GNode;onClose:()=>void}){
 const [grants,setGrants]=useState<Record<string,unknown>[]>([]),[activity,setActivity]=useState<{proposals:Record<string,unknown>[];events:Record<string,unknown>[];readbacks:Record<string,unknown>[]}>({proposals:[],events:[],readbacks:[]}),[token,setToken]=useState(""),[label,setLabel]=useState("Local agent"),[identity,setIdentity]=useState("agent"),[permission,setPermission]=useState("propose"),[hours,setHours]=useState(24),[message,setMessage]=useState("");
 const reload=useCallback(async()=>{setGrants(await api.listAgentGrants(projectId));setActivity(await api.getAgentPortActivity(projectId));},[projectId]);useEffect(()=>{void reload().catch(e=>setMessage(String(e)));},[reload]);
 const create=async()=>{const row=await api.createAgentGrant({project_id:projectId,permission,label,agent_identity:identity,expires_at:new Date(Date.now()+hours*3600000).toISOString()});setToken(String(row.token));setMessage("權杖只顯示這一次。請立即複製並安全保存。");await reload();};
 const review=async(id:string,decision:"approve"|"reject")=>{try{await api.reviewAgentProposal(id,decision);await reload();}catch(e){setMessage(`審核失敗（可能是 revision conflict）：${String(e)}`)}};
 return <div className="fixed inset-0 z-[130] flex items-center justify-center bg-black/70 p-4" onClick={onClose}><div className="max-h-[88vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-gray-700 bg-gray-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="font-semibold text-gray-100">🔌 Agent Port v1</h2><p className="text-xs text-gray-500">Provider-neutral REST 協作。只授予 GrowthMap graph 權限，不授予檔案、repo 或模型權限。</p></div><button onClick={onClose}>×</button></div>
 <div className="mt-4 grid gap-2 rounded border border-gray-800 p-3 sm:grid-cols-4"><input aria-label="grant label" value={label} onChange={e=>setLabel(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><input aria-label="agent identity" value={identity} onChange={e=>setIdentity(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"/><select value={permission} onChange={e=>setPermission(e.target.value)} className="rounded bg-gray-800 p-2 text-xs"><option>read</option><option>propose</option><option>write</option></select><input aria-label="expiry hours" type="number" min={1} max={2160} value={hours} onChange={e=>setHours(Number(e.target.value))} className="rounded bg-gray-800 p-2 text-xs"/><button onClick={()=>void create()} className="rounded bg-blue-600 p-2 text-xs sm:col-span-4">建立 project-wide 有限期 grant</button></div>
 {token&&<div className="mt-3 rounded border border-amber-700 bg-amber-950/20 p-3"><b className="text-xs text-amber-300">⚠️ 只顯示一次；關閉後無法找回</b><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-auto rounded bg-black p-2 text-xs">{token}</code><button onClick={()=>void navigator.clipboard.writeText(token)} className="rounded border border-amber-700 px-2 text-xs">複製</button></div></div>}{message&&<p className="mt-2 text-xs text-amber-300">{message}</p>}
 <h3 className="mt-5 text-sm font-medium">Access grants</h3><div className="space-y-2">{grants.map(g=><div key={String(g.id)} className="rounded border border-gray-800 p-2 text-xs"><div className="flex justify-between"><span>{String(g.label)} · {String(g.agent_identity)} · {String(g.permission)} · {g.node_scope_id?"node":g.branch_root_id?"branch":"project-wide"}</span><span>{String(g.status)}</span></div><div className="text-gray-500">prefix {String(g.token_prefix)} · 到期 {new Date(String(g.expires_at)).toLocaleString()} · last use {g.last_used_at?new Date(String(g.last_used_at)).toLocaleString():"never"}</div>{g.status==="active"&&<button onClick={()=>void api.revokeAgentGrant(String(g.id)).then(reload)} className="mt-1 text-red-300">撤銷</button>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Proposal bundles / revision diff</h3><div className="space-y-2">{activity.proposals.map(p=><div key={String(p.id)} className="rounded border border-purple-900 p-2 text-xs"><div>{String(p.title)} · expected project r{String(p.expected_project_revision)} · {String(p.status)}</div><pre className="mt-1 max-h-36 overflow-auto whitespace-pre-wrap text-[11px] text-gray-400">{JSON.stringify(p.operations,null,2)}</pre>{p.status==="pending"&&<div className="flex gap-2"><button onClick={()=>void review(String(p.id),"approve")} className="text-emerald-300">核准套用</button><button onClick={()=>void review(String(p.id),"reject")} className="text-red-300">拒絕</button></div>}</div>)}</div>
 <h3 className="mt-5 text-sm font-medium">Events / implementation readback</h3>{activity.events.map(e=><div key={String(e.id)} className="text-xs text-gray-400">{String(e.event_type)} · {String(e.message)}</div>)}{activity.readbacks.map(r=><div key={String(r.id)} className="mt-2 rounded border border-gray-800 p-2 text-xs"><b>{String(r.summary||"Implementation readback")}</b><div className="text-gray-500">node {String(r.target_node_id||rootNode.id)} · commits {JSON.stringify(r.commit_refs)} · files {JSON.stringify(r.files)} · tests {JSON.stringify(r.tests)} · risks {JSON.stringify(r.risks)} · todos {JSON.stringify(r.todos)}</div></div>)}</div></div>
}
