"use client";
import {useEffect,useState} from "react";
import type {DesktopBackup,DesktopDatabaseStatus} from "@/desktop";
export function DatabaseWorkspace({onClose}:{onClose:()=>void}){
 const [database,setDatabase]=useState<DesktopDatabaseStatus|null>(null),[backups,setBackups]=useState<DesktopBackup[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const refresh=async()=>{const d=window.growthmapDesktop;if(!d)return;const [status,rows]=await Promise.all([d.database.status(),d.database.listBackups()]);setDatabase(status);setBackups(rows);};
 useEffect(()=>{refresh().catch(()=>setMessage("無法讀取資料庫工作區狀態。"));},[]);
 const action=async(kind:"backup"|"import"|"restore"|"workspace",backup?:DesktopBackup)=>{const d=window.growthmapDesktop;if(!d)return;if(kind==="import"&&!confirm("匯入會先備份，再以選取的資料庫取代目前工作區資料。確定繼續？"))return;if(kind==="restore"&&!confirm(`還原會先備份目前資料（${backup?.projects??0} 個專案）。確定繼續？`))return;setBusy(true);setMessage("");try{const result=kind==="backup"?await d.database.backup():kind==="import"?await d.database.import():kind==="restore"?await d.database.restore(backup!.id):await d.database.chooseWorkspace();if(result)setMessage(kind==="workspace"?"正在切換工作區並重新啟動…":kind==="backup"?"✅ 備份完成。":"✅ 資料庫已安全替換。");await refresh();}catch(e){setMessage(`操作失敗：${(e as Error).message}`);}finally{setBusy(false);}};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 backdrop-blur-sm"><div data-testid="database-workspace" className="max-h-[90vh] w-full max-w-2xl space-y-4 overflow-y-auto rounded-xl border border-blue-800/60 bg-gray-900 p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-semibold text-blue-100">🗄️ 資料庫工作區</h2><p className="mt-1 text-xs text-gray-500">GrowthMap 專案資料、備份與工作區位置；與 LLM Provider 設定分開管理。</p></div><button onClick={onClose} className="text-lg text-gray-500">×</button></div>{database&&<section className="space-y-2 rounded-lg border border-blue-900/50 bg-blue-950/20 p-4 text-xs text-gray-300"><div className="break-all"><span className="text-gray-500">目前資料庫：</span><span data-testid="database-path" className="font-mono">{database.databasePath}</span></div><div className="grid grid-cols-2 gap-2"><span>{database.projects} 個專案</span><span>{(database.size/1024).toFixed(1)} KB</span><span>SHA-256 {database.sha256.slice(0,16)}…</span><span>最近備份：{database.lastBackup?new Date(database.lastBackup).toLocaleString():"尚無"}</span></div></section>}<div className="rounded border border-amber-900/50 bg-amber-950/20 p-3 text-xs leading-5 text-amber-200/80">工作區必須位於 Windows 本機磁碟。為保護 SQLite，不能直接使用 WSL、UNC、網路磁碟或雲端同步資料夾；WSL Agent 請透過 Agent Port/API 存取。</div><div className="flex flex-wrap gap-2"><button data-testid="database-choose-workspace" disabled={busy} onClick={()=>action("workspace")} className="rounded bg-blue-700 px-3 py-2 text-xs text-white disabled:opacity-50">選擇既有工作區</button><button data-testid="database-backup" disabled={busy} onClick={()=>action("backup")} className="rounded border border-blue-700 px-3 py-2 text-xs text-blue-200">立即備份</button><button data-testid="database-import" disabled={busy} onClick={()=>action("import")} className="rounded border border-amber-700 px-3 py-2 text-xs text-amber-200">匯入既有 DB</button><button disabled={busy} onClick={()=>window.growthmapDesktop?.database.revealFolder()} className="rounded border border-gray-600 px-3 py-2 text-xs text-gray-300">開啟備份資料夾</button></div><div className="max-h-40 space-y-2 overflow-y-auto">{backups.length===0?<p className="text-xs text-gray-500">尚無此工作區的管理備份。</p>:backups.map(item=><div key={item.id} className="flex items-center justify-between rounded border border-gray-800 p-2 text-xs"><span>{new Date(item.createdAt).toLocaleString()} · {item.projects} 個專案</span><button disabled={busy} onClick={()=>action("restore",item)} className="rounded border border-red-800 px-2 py-1 text-red-300">還原</button></div>)}</div>{busy&&<p className="text-xs text-blue-200">處理中，請勿關閉應用程式…</p>}{message&&<div className="rounded border border-gray-700 bg-gray-800 p-2 text-xs">{message}</div>}</div></div>;
}
