#!/usr/bin/env python3
"""Validate reviewed canonical public config and generate deterministic artifacts."""
import argparse,hashlib,json,pathlib,re,sys,unicodedata
ROOT=pathlib.Path(__file__).resolve().parents[1]
SOURCE=ROOT/'config/commercial-public-config.json'
REVIEWED_PIN=ROOT/'config/commercial-public-config.sha256'
DESKTOP=ROOT/'desktop/commercial-config.json'
PAYMENTS=ROOT/'services/payments/public-config.json'
DIGEST=ROOT/'services/payments/growthmap_payments/_public_config_digest.py'
DESKTOP_CONSTANTS=ROOT/'desktop/generated/public-config.js'
SCHEMA={
 'schemaVersion':int,'productMajor':int,'licenseIssuer':str,'supportEmail':str,'supportUrl':str,
 'licensePublicKeyResource':str,'licensePublicKeySha256':str,'paymentApiOrigin':str,
 'purchasePortalOrigin':str,'purchasePortalUrl':str,'baseNetwork':str,'baseUsdc':str,
 'basePayee':str,'earlyLimit':int,'earlyPriceMicros':int,'regularPriceMicros':int,
 'paypalUrl':str,'updateUrl':str,'updateOrigin':str,'publisher':str,'publisherStatus':str,
}
APPROVED={
 'schemaVersion':3,'productMajor':1,'licenseIssuer':'Growthmap','baseNetwork':'eip155:8453',
 'baseUsdc':'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
 'basePayee':'0x81d30e175a22c1c2f78b3db6fc0600a6e1cb3591','earlyLimit':50,
 'earlyPriceMicros':10000000,'regularPriceMicros':29000000,
 'paypalUrl':'https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA','publisherStatus':'UNAPPROVED',
}
def _pairs(pairs):
 out={};normalized={}
 for key,value in pairs:
  if key in out:raise ValueError(f'duplicate JSON key: {key}')
  folded=unicodedata.normalize('NFKC',key).casefold()
  if folded in normalized:raise ValueError(f'NFKC/casefold JSON key collision: {normalized[folded]} / {key}')
  normalized[folded]=key;out[key]=value
 return out
def load_and_validate(raw):
 try:doc=json.loads(raw.decode('utf-8'),object_pairs_hook=_pairs)
 except (UnicodeDecodeError,json.JSONDecodeError,ValueError) as e:raise ValueError(f'invalid strict canonical JSON: {e}') from e
 if not isinstance(doc,dict) or set(doc)!=set(SCHEMA):raise ValueError('canonical JSON keys do not exactly match schema')
 for key,kind in SCHEMA.items():
  if type(doc[key]) is not kind:raise ValueError(f'canonical value has wrong type: {key}')
 for key,value in APPROVED.items():
  if doc[key]!=value:raise ValueError(f'canonical value is not approved: {key}')
 if not re.fullmatch(r'[^@\s]+@[^@\s]+\.[^@\s]+',doc['supportEmail']):raise ValueError('invalid supportEmail')
 if doc['supportUrl']!='https://x.com/nerv00kaworu':raise ValueError('supportUrl is not approved')
 if doc['publisher']!='月影塵（nerv00kaworu）':raise ValueError('publisher is not approved')
 placeholders=('licensePublicKeyResource','licensePublicKeySha256','paymentApiOrigin','purchasePortalOrigin','purchasePortalUrl','updateUrl','updateOrigin')
 if any(not doc[k] or not isinstance(doc[k],str) for k in placeholders):raise ValueError('required public production boundary value missing')
 return doc
def reviewed_digest():
 try:text=REVIEWED_PIN.read_text(encoding='ascii')
 except OSError as e:raise ValueError('independent reviewed canonical SHA-256 pin missing') from e
 if not re.fullmatch(r'[0-9a-f]{64}\n?',text):raise ValueError('independent reviewed canonical SHA-256 pin invalid')
 return text.strip()
def encoded(value):return (json.dumps(value,ensure_ascii=False,indent=2)+"\n").encode()
def outputs(doc):
 server={'baseNetwork':doc['baseNetwork'],'basePayee':doc['basePayee']};payload=encoded(server)
 constants=("'use strict';\n// Generated by tools/generate-public-config.py; do not edit.\n"+f"module.exports=Object.freeze({json.dumps(server,separators=(',',':'))});\n").encode()
 return {DESKTOP:encoded(doc),PAYMENTS:payload,DIGEST:(f'"""Generated by tools/generate-public-config.py; do not edit."""\nPUBLIC_CONFIG_SHA256="{hashlib.sha256(payload).hexdigest()}"\n').encode(),DESKTOP_CONSTANTS:constants}
def evaluate(check):
 raw=SOURCE.read_bytes();doc=load_and_validate(raw)
 # Generation never edits the independent review pin. --check is the required
 # approval/drift gate, so tamper + regenerate still cannot become accepted.
 if check and hashlib.sha256(raw).hexdigest()!=reviewed_digest():raise ValueError('canonical config does not match independent reviewed SHA-256 pin')
 bad=[]
 for path,data in outputs(doc).items():
  if check:
   if not path.is_file() or path.read_bytes()!=data:bad.append(str(path.relative_to(ROOT)))
  else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
 if bad:raise ValueError('public config drift: '+', '.join(bad))
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
 try:evaluate(a.check)
 except (OSError,ValueError) as e:print(f'public config validation failed: {e}',file=sys.stderr);return 1
 return 0
if __name__=='__main__':raise SystemExit(main())
