'use strict';
const crypto=require('node:crypto');
const {strictCanonicalPublicHttpsOrigin}=require('./purchase-portal');
const PAYMENT_KEY=/^GM1\.([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})\.([A-Za-z0-9_-]{32})$/;
const GIFT_KEY=/^GMG1\.([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})\.([A-Za-z0-9_-]{32})$/;
const MAX_RESPONSE=65536;
function parseActivationKey(value){if(typeof value!=='string'||value.length>128||value!==value.trim())throw Error('Invalid activation-key format');let match=PAYMENT_KEY.exec(value);if(match)return {orderId:match[1],recoveryCode:match[2]};match=GIFT_KEY.exec(value);if(match)return {kind:'gift',giftId:match[1],claimSecret:match[2]};throw Error('Invalid activation-key format');}
function endpoint(origin,path){const canonical=strictCanonicalPublicHttpsOrigin(origin),url=new URL(path,canonical);if(url.origin!==canonical||url.search||url.hash)return null;return url.href;}
function exactObject(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('|')===keys.slice().sort().join('|');}
async function post(fetchImpl,url,body){let response;try{response=await fetchImpl(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body),redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});}catch{throw Error('Unable to connect to the activation service');}const length=response.headers?.get?.('content-length');if(length&&(!/^\d+$/.test(length)||Number(length)>MAX_RESPONSE))throw Error('The activation service returned an invalid response');const text=await response.text();if(text.length>MAX_RESPONSE||!response.ok)throw Error(response.status===404?'The activation key is invalid or payment is pending':'The activation service cannot complete activation right now');try{return JSON.parse(text);}catch{throw Error('The activation service returned an invalid response');}}
async function activateLicenseKey({activationKey,activationApiOrigin,deviceIdentity,fetchImpl=globalThis.fetch}){const key=parseActivationKey(activationKey),gift=key.kind==='gift',challengeUrl=endpoint(activationApiOrigin,gift?'/v1/gifts/claim/challenge':'/v1/activation/challenge'),completeUrl=endpoint(activationApiOrigin,gift?'/v1/gifts/claim/complete':'/v1/activation/complete');if(!challengeUrl||!completeUrl||typeof fetchImpl!=='function')throw Error('The activation service is not configured');const first=await post(fetchImpl,challengeUrl,gift?{claim_key:activationKey,device_public_key:deviceIdentity.publicKey}:{order_id:key.orderId,recovery_code:key.recoveryCode,device_public_key:deviceIdentity.publicKey});if(!exactObject(first,['state','challenge'])||first.state!=='challenge_issued'||!exactObject(first.challenge,['challenge_id','nonce','license_id','device_public_key'])||first.challenge.device_public_key!==deviceIdentity.publicKey)throw Error('The activation service returned an invalid response');const challenge=Buffer.concat([Buffer.from('growthmap-activation-request-v1\0'),Buffer.from(JSON.stringify({device_public_key:deviceIdentity.publicKey,license_id:first.challenge.license_id,nonce:first.challenge.nonce}))]);let proof;try{proof=crypto.sign(null,challenge,crypto.createPrivateKey(deviceIdentity.privateKeyPem)).toString('base64');}catch{throw Error('The device identity could not sign the activation request');}const second=await post(fetchImpl,completeUrl,{challenge_id:first.challenge.challenge_id,proof});if(!exactObject(second,['state','certificate'])||second.state!=='activated'||typeof second.certificate!=='object')throw Error('The activation service returned an invalid response');return second.certificate;}
module.exports={parseActivationKey,activateLicenseKey};
