'use strict';
const crypto=require('node:crypto');
const {strictCanonicalPublicHttpsOrigin}=require('./purchase-portal');
const {parseStrictJson}=require('./strict-json');
const CERT_FIELDS=['schema_version','certificate_type','product','edition','license_id','activation_id','major_version','device_allowance','device_id','device_public_key','issued_at','expires_at','revoked_at','max_active_projects','next_check_in_at','signature'];
const DOMAIN=Buffer.from('growthmap-license-refresh-request-v1\0'),CERT_DOMAIN=Buffer.from('growthmap-activation-certificate-v2\0'),MAX_RESPONSE=65536,REFRESH_WINDOW_MS=24*60*60*1000;
const verifiedCapabilities=new WeakMap(),verifiedCandidates=new WeakMap();
function plainRecord(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;const prototype=Object.getPrototypeOf(value);return prototype===Object.prototype||prototype===null;}
function exactOwn(value,fields){
 if(!plainRecord(value))return false;const keys=Reflect.ownKeys(value);if(keys.length!==fields.length||keys.some(key=>typeof key!=='string'||!fields.includes(key)))return false;
 return fields.every(key=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);return descriptor&&Object.hasOwn(descriptor,'value')&&descriptor.enumerable;});
}
function validatedCopy(value,seen=new Set()){
 if(value===null||typeof value==='string'||typeof value==='boolean')return value;
 if(typeof value==='number'){if(!Number.isFinite(value))throw Error('unsupported verified content');return value;}
 if(typeof value!=='object'||seen.has(value))throw Error('unsupported verified content');
 if(!Array.isArray(value)&&!plainRecord(value))throw Error('unsupported verified content');
 seen.add(value);const keys=Reflect.ownKeys(value);if(keys.some(key=>typeof key!=='string'))throw Error('unsupported verified content');
 const out=Array.isArray(value)?[]:{};
 for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!Object.hasOwn(descriptor,'value')||!descriptor.enumerable)throw Error('unsupported verified content');const copied=validatedCopy(descriptor.value,seen);Object.defineProperty(out,key,{value:copied,enumerable:true,writable:false,configurable:false});}
 seen.delete(value);return Object.freeze(out);
}
function certificateSnapshot(value){if(!exactOwn(value,CERT_FIELDS))throw Error('The refreshed certificate structure is invalid');try{return validatedCopy(value);}catch{throw Error('The refreshed certificate structure is invalid');}}
function canonicalValue(value){
 if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number')return value;
 if(Array.isArray(value))return value.map(canonicalValue);
 return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalValue(value[key])]));
}
function canonical(value){return Buffer.from(JSON.stringify(canonicalValue(value)));}
function contentDigest(value){return crypto.createHash('sha256').update(canonical(validatedCopy(value))).digest('base64');}
function strictBase64(value,bytes){if(typeof value!=='string'||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)$/.test(value))return null;const raw=Buffer.from(value,'base64');return raw.length===bytes&&raw.toString('base64')===value?raw:null;}
function validDeviceKey(value){return Boolean(strictBase64(value,32));}
function canonicalUtc(value){const m=typeof value==='string'&&/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{6}))?Z$/.exec(value);if(!m)throw Error('The refreshed certificate timestamp is invalid');const base=`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`,ms=Date.parse(base);if(!Number.isFinite(ms)||new Date(ms).toISOString().replace('.000Z','Z')!==base)throw Error('The refreshed certificate timestamp is invalid');return BigInt(ms)*1000n+BigInt(m[7]||'0');}
function validateCertificateTimes(c){const issued=canonicalUtc(c.issued_at),check=canonicalUtc(c.next_check_in_at),expiry=c.expires_at===null?null:canonicalUtc(c.expires_at),revoked=c.revoked_at===null?null:canonicalUtc(c.revoked_at);if(issued>=check||(expiry!==null&&(expiry<=issued||expiry<check))||(revoked!==null&&revoked<issued))throw Error('The refreshed certificate time order is invalid');return {issued,check,expiry,revoked};}
function endpoint(origin,p){const o=strictCanonicalPublicHttpsOrigin(origin),u=new URL(p,o);if(u.origin!==o||u.search||u.hash)throw Error('The activation service is not configured');return u.href;}
async function post(fetchImpl,url,body,checkpoint=()=>{}){let r;try{r=await fetchImpl(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body),redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});}catch{throw Error('Unable to connect to the activation service');}checkpoint();const length=r.headers?.get?.('content-length');if(length&&(!/^\d+$/.test(length)||+length>MAX_RESPONSE))throw Error('The activation service returned an invalid response');const text=await r.text();checkpoint();if(!r.ok||text.length>MAX_RESPONSE)throw Error('The activation service cannot complete refresh right now');try{return parseStrictJson(text);}catch{throw Error('The activation service returned an invalid response');}}
function assertInstalled(certificate,deviceIdentity){const snapshot=certificateSnapshot(certificate);if(snapshot.schema_version!==2||!validDeviceKey(deviceIdentity.publicKey)||snapshot.device_public_key!==deviceIdentity.publicKey)throw Error('The current certificate cannot be refreshed safely');return snapshot;}
async function refreshActivationCertificate({certificate,entitlement=null,installedCapability=null,checkpoint=()=>{},flowKind,activationApiOrigin,deviceIdentity,fetchImpl=globalThis.fetch}){const bound=installedCapability&&verifiedCapabilities.get(installedCapability),source=bound&&bound.certificate===certificate&&bound.entitlement===entitlement?bound.certificateSnapshot:certificate;checkpoint();assertInstalled(source,deviceIdentity);if(!['payment','gift'].includes(flowKind)||typeof fetchImpl!=='function')throw Error('A trusted activation source is missing');const root=flowKind==='gift'?'/v1/gifts/refresh':'/v1/activation/refresh';checkpoint();const triple={activation_id:source.activation_id,license_id:source.license_id,device_public_key:deviceIdentity.publicKey};const first=await post(fetchImpl,endpoint(activationApiOrigin,root+'/challenge'),triple,checkpoint);checkpoint();if(!exactOwn(first,['state','challenge'])||first.state!=='challenge_issued'||!exactOwn(first.challenge,['challenge_id','nonce','activation_id','license_id','device_public_key']))throw Error('The activation service returned an invalid response');const c=first.challenge;if(typeof c.challenge_id!=='string'||!/^gmr_[a-f0-9]{32}$/.test(c.challenge_id)||typeof c.nonce!=='string'||c.nonce.length<16||c.nonce.length>256||c.activation_id!==triple.activation_id||c.license_id!==triple.license_id||c.device_public_key!==triple.device_public_key||!validDeviceKey(c.device_public_key))throw Error('The activation service returned an invalid response');const payload={activation_id:c.activation_id,device_public_key:c.device_public_key,license_id:c.license_id,nonce:c.nonce};let proof;try{proof=crypto.sign(null,Buffer.concat([DOMAIN,canonical(payload)]),crypto.createPrivateKey(deviceIdentity.privateKeyPem)).toString('base64');}catch{throw Error('The device identity could not sign the refresh request');}checkpoint();const second=await post(fetchImpl,endpoint(activationApiOrigin,root+'/complete'),{challenge_id:c.challenge_id,proof},checkpoint);checkpoint();if(!exactOwn(second,['state','certificate'])||second.state!=='activated'||!exactOwn(second.certificate,CERT_FIELDS))throw Error('The activation service returned an invalid response');return second.certificate;}
function canonicalCertificate(c){return canonical(Object.fromEntries(CERT_FIELDS.filter(k=>k!=='signature').map(k=>[k,c[k]])));}
function verifyInstalledCertificateIdentity({certificate,entitlement,deviceIdentity,authorityPublicKeyPem,currentMajor,now=new Date()}){
 const certificateReference=certificate;
 try{
  certificate=assertInstalled(certificate,deviceIdentity);
  if(certificate.certificate_type!=='growthmap_device_activation'||certificate.product!=='growthmap'||!['personal','pro','studio'].includes(certificate.edition)||typeof certificate.license_id!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(certificate.license_id)||typeof certificate.activation_id!=='string'||!/^gma_[a-f0-9]{32}$/.test(certificate.activation_id)||!Number.isInteger(certificate.major_version)||certificate.major_version!==currentMajor||![1,2].includes(certificate.device_allowance)||certificate.max_active_projects!==null)throw Error();
  const rawKey=strictBase64(certificate.device_public_key,32),expectedDeviceId=rawKey&&'gmdev_'+crypto.createHash('sha256').update(rawKey).digest('hex');if(!expectedDeviceId||certificate.device_id!==expectedDeviceId)throw Error();
  const sig=strictBase64(certificate.signature,64);if(!sig||!crypto.verify(null,Buffer.concat([CERT_DOMAIN,canonicalCertificate(certificate)]),crypto.createPublicKey(authorityPublicKeyPem),sig))throw Error();
  const times=validateCertificateTimes(certificate),nowUs=BigInt(now.getTime())*1000n;if(!Number.isFinite(now.getTime())||(times.expiry!==null&&times.expiry<=nowUs)||(times.revoked!==null&&times.revoked<=nowUs))throw Error();
  if(!entitlement||certificate.license_id!==entitlement.license_id||certificate.major_version!==entitlement.major_version)throw Error();if(entitlement.state==='paid'){for(const field of ['edition','device_allowance','max_active_projects'])if(certificate[field]!==entitlement[field])throw Error();}else if(entitlement.reason!=='check_in_required')throw Error();
  const certificateDigest=contentDigest(certificateReference),entitlementDigest=contentDigest(entitlement),certificateSnapshot=certificate,entitlementSnapshot=validatedCopy(entitlement),capability=Object.freeze(Object.create(null));verifiedCapabilities.set(capability,{certificate:certificateReference,entitlement,certificateDigest,entitlementDigest,certificateSnapshot,entitlementSnapshot});return capability;
 }catch{throw Error('Current certificate identity verification failed');}
}
function hasInstalledCertificateCapability(capability,certificate,entitlement){const bound=capability&&verifiedCapabilities.get(capability);if(!bound||bound.certificate!==certificate||bound.entitlement!==entitlement)return false;try{return bound.certificateDigest===contentDigest(certificate)&&bound.entitlementDigest===contentDigest(entitlement);}catch{return false;}}
function verifyRefreshedCertificate({previous=null,installedCapability=null,certificate=null,entitlement=null,candidate,deviceIdentity,authorityPublicKeyPem,now=new Date()}){const source=candidate,bound=installedCapability&&verifiedCapabilities.get(installedCapability);if(bound){if(bound.certificate!==certificate||bound.entitlement!==entitlement||!hasInstalledCertificateCapability(installedCapability,certificate,entitlement))throw Error('The current certificate changed during refresh');previous=bound.certificateSnapshot;}if(previous)previous=assertInstalled(previous,deviceIdentity);candidate=assertInstalled(candidate,deviceIdentity);const sig=strictBase64(candidate.signature,64);if(!sig)throw Error('The refreshed certificate signature is invalid');try{if(!crypto.verify(null,Buffer.concat([CERT_DOMAIN,canonicalCertificate(candidate)]),crypto.createPublicKey(authorityPublicKeyPem),sig))throw Error();}catch{throw Error('The refreshed certificate signature is invalid');}if(previous)for(const k of ['license_id','activation_id','device_id','device_public_key','edition','major_version','device_allowance','max_active_projects','certificate_type','product'])if(candidate[k]!==previous[k])throw Error('The refreshed certificate identity does not match');const current=validateCertificateTimes(candidate),old=previous?validateCertificateTimes(previous):null,nowUs=BigInt(now.getTime())*1000n;if((old&&(current.issued<=old.issued||current.check<=old.check))||current.check<=nowUs||(current.expiry!==null&&current.expiry<=nowUs)||(current.revoked!==null&&current.revoked<=nowUs))throw Error('The refreshed certificate is not a newer valid certificate');const sourceDigest=contentDigest(source);verifiedCandidates.set(candidate,{source,sourceDigest});return candidate;}
function hasVerifiedCandidateCapability(candidate,source){const bound=candidate&&verifiedCandidates.get(candidate);if(!bound||bound.source!==source)return false;try{return bound.sourceDigest===contentDigest(source)&&contentDigest(candidate)===bound.sourceDigest;}catch{return false;}}
function matchesCertificateSnapshot(value,snapshot){try{return contentDigest(certificateSnapshot(value))===contentDigest(snapshot);}catch{return false;}}
function shouldRefresh(certificate,now=new Date()){try{return BigInt(now.getTime())*1000n>=canonicalUtc(certificate?.next_check_in_at)-BigInt(REFRESH_WINDOW_MS)*1000n;}catch{return false;}}
module.exports={CERT_FIELDS,DOMAIN,REFRESH_WINDOW_MS,refreshActivationCertificate,verifyRefreshedCertificate,verifyInstalledCertificateIdentity,hasInstalledCertificateCapability,hasVerifiedCandidateCapability,matchesCertificateSnapshot,shouldRefresh,canonical,canonicalUtc,validateCertificateTimes,strictBase64};
