'use strict';
const crypto=require('node:crypto');
const {strictCanonicalPublicHttpsOrigin}=require('./purchase-portal');
const KEY=/^GM1\.([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})\.([A-Za-z0-9_-]{32})$/;
const MAX_RESPONSE=65536;
function parseActivationKey(value){if(typeof value!=='string'||value.length>128||value!==value.trim())throw Error('授權碼格式錯誤');const match=KEY.exec(value);if(!match)throw Error('授權碼格式錯誤');return {orderId:match[1],recoveryCode:match[2]};}
function endpoint(origin,path){const canonical=strictCanonicalPublicHttpsOrigin(origin),url=new URL(path,canonical);if(url.origin!==canonical||url.search||url.hash)return null;return url.href;}
function exactObject(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('|')===keys.slice().sort().join('|');}
async function post(fetchImpl,url,body){let response;try{response=await fetchImpl(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body),redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(15000)});}catch{throw Error('授權服務暫時無法連線');}const length=response.headers?.get?.('content-length');if(length&&(!/^\d+$/.test(length)||Number(length)>MAX_RESPONSE))throw Error('授權服務回覆異常');const text=await response.text();if(text.length>MAX_RESPONSE||!response.ok)throw Error(response.status===404?'授權碼無效或尚未付款':'授權服務暫時無法完成啟用');try{return JSON.parse(text);}catch{throw Error('授權服務回覆異常');}}
async function activateLicenseKey({activationKey,activationApiOrigin,deviceIdentity,fetchImpl=globalThis.fetch}){const key=parseActivationKey(activationKey),challengeUrl=endpoint(activationApiOrigin,'/v1/activation/challenge'),completeUrl=endpoint(activationApiOrigin,'/v1/activation/complete');if(!challengeUrl||!completeUrl||typeof fetchImpl!=='function')throw Error('授權服務未設定');const first=await post(fetchImpl,challengeUrl,{order_id:key.orderId,recovery_code:key.recoveryCode,device_public_key:deviceIdentity.publicKey});if(!exactObject(first,['state','challenge'])||first.state!=='challenge_issued'||!exactObject(first.challenge,['challenge_id','nonce','license_id','device_public_key'])||first.challenge.device_public_key!==deviceIdentity.publicKey)throw Error('授權服務回覆異常');const challenge=Buffer.concat([Buffer.from('growthmap-activation-request-v1\0'),Buffer.from(JSON.stringify({device_public_key:deviceIdentity.publicKey,license_id:first.challenge.license_id,nonce:first.challenge.nonce}))]);let proof;try{proof=crypto.sign(null,challenge,crypto.createPrivateKey(deviceIdentity.privateKeyPem)).toString('base64');}catch{throw Error('裝置身分無法簽署啟用要求');}const second=await post(fetchImpl,completeUrl,{challenge_id:first.challenge.challenge_id,proof});if(!exactObject(second,['state','certificate'])||second.state!=='activated'||typeof second.certificate!=='object')throw Error('授權服務回覆異常');return second.certificate;}
module.exports={parseActivationKey,activateLicenseKey};
