'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const MAX_HELPER_ERROR=4096,MAX_TEST_OUTPUT=262144,MAX_ID=128,MAX_TOKEN=1024,MAX_PROFILE_BYTES=65536,MAX_STATUS_BYTES=262144,MAX_STATUS_ROWS=256,MAX_CLEANUP=8;
const PROFILE_KEYS=new Set(['schema','status','grantId','projectId','permission','mode','lifetime','credentialTarget','cleanup']);
const GRANT_KEYS=new Set(['id','token','token_prefix','project_id','workspace_scope','mode','permission','node_scope_id','branch_root_id','label','agent_identity','status','expires_at','persistent','revoked_at','last_used_at','created_at','warning']);
function regular(file){try{const s=fs.lstatSync(file);if(s.isSymbolicLink()||!s.isFile())throw Error('unsafe Agent Access file');}catch(e){if(e.code!=='ENOENT')throw e;}}
function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});regular(file);const t=file+'.tmp-'+crypto.randomBytes(8).toString('hex');try{fs.writeFileSync(t,JSON.stringify(value)+'\n',{flag:'wx',mode:0o600});fs.renameSync(t,file);}finally{try{fs.unlinkSync(t)}catch{}}}
function atomicText(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});regular(file);const t=file+'.tmp-'+crypto.randomBytes(8).toString('hex');try{fs.writeFileSync(t,value,{flag:'wx',mode:0o600});fs.renameSync(t,file);}finally{try{fs.unlinkSync(t)}catch{}}}
function remove(file){try{regular(file);fs.unlinkSync(file);}catch(e){if(e.code!=='ENOENT')throw e;}}
function unlinkEntry(file){try{fs.lstatSync(file);fs.unlinkSync(file);}catch(e){if(e.code!=='ENOENT')throw e;}}
function boundedStableRead(file,max=MAX_PROFILE_BYTES){const before=fs.lstatSync(file);if(before.isSymbolicLink()||!before.isFile()||before.size<1||before.size>max)throw Error('unsafe Agent Access file');const fd=fs.openSync(file,'r');try{const opened=fs.fstatSync(fd);if(!opened.isFile()||opened.size!==before.size||opened.dev!==before.dev||opened.ino!==before.ino)throw Error('unstable Agent Access file');const data=Buffer.alloc(opened.size);let offset=0;while(offset<data.length){const count=fs.readSync(fd,data,offset,data.length-offset,offset);if(!count)throw Error('short Agent Access profile read');offset+=count;}const after=fs.fstatSync(fd),pathAfter=fs.lstatSync(file);if(after.size!==opened.size||after.mtimeMs!==opened.mtimeMs||pathAfter.dev!==opened.dev||pathAfter.ino!==opened.ino||pathAfter.size!==opened.size)throw Error('unstable Agent Access file');return data.toString('utf8');}finally{fs.closeSync(fd);}}

function helper(exe,command,payload){return new Promise((ok,no)=>{const p=spawn(exe,[command],{stdio:['pipe','ignore','pipe'],windowsHide:true,env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}}),chunks=[];let size=0,settled=false;const fail=e=>{if(!settled){settled=true;no(e)}};p.stderr.on('data',x=>{if(size<MAX_HELPER_ERROR){chunks.push(x.subarray(0,MAX_HELPER_ERROR-size));size+=x.length}});p.once('error',fail);p.once('exit',c=>{if(settled)return;settled=true;c===0?ok():no(Error(`Credential helper failed (${c}): ${Buffer.concat(chunks).toString().slice(0,300)}`))});p.stdin.on('error',fail);p.stdin.end(JSON.stringify(payload));});}
function config(command){return {mcpServers:{growthmap:{command}}};}
function target(major,installation,suffix='primary'){if(!Number.isInteger(major)||major<1||!/^[A-Za-z0-9_-]{16,128}$/.test(installation)||!/^[A-Za-z0-9_-]{1,64}$/.test(suffix))throw Error('invalid installation identity');return `GrowthMap/AgentPort/v1/product-${major}/installation-${installation}/${suffix}`;}
function testConnection(exe,{timeoutMs=8000}={}){return new Promise(resolve=>{const child=spawn(exe,[],{stdio:['pipe','pipe','pipe'],windowsHide:true,env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,LOCALAPPDATA:process.env.LOCALAPPDATA}});let out='',total=0,done=false,initialized=false,listed=false;const finish=(ok,code)=>{if(done)return;done=true;clearTimeout(timer);try{child.stdin.destroy()}catch{}try{child.kill()}catch{}resolve(Object.freeze({ok,status:ok?'connected':code}))};const consume=chunk=>{total+=chunk.length;if(total>MAX_TEST_OUTPUT)return finish(false,'output_limit');out+=chunk.toString('utf8');let index;while((index=out.indexOf('\n'))>=0){const line=out.slice(0,index);out=out.slice(index+1);if(!line)continue;let value;try{value=JSON.parse(line)}catch{return finish(false,'invalid_response')}if(value.id===1&&value.result)initialized=true;if(value.id===2&&value.result&&Array.isArray(value.result.tools))listed=true;if(initialized&&listed)return finish(true,'connected')}};child.stdout.on('data',consume);child.stderr.on('data',x=>{total+=x.length;if(total>MAX_TEST_OUTPUT)finish(false,'output_limit')});child.once('error',()=>finish(false,'spawn_failed'));child.once('exit',()=>finish(false,'exited'));const timer=setTimeout(()=>finish(false,'timeout'),timeoutMs);child.stdin.end(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'connection-test',version:'1'}}})+'\n'+JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/list',params:{}})+'\n');});}
function plain(x){return x!==null&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;}
function bounded(value,max=MAX_ID){return typeof value==='string'&&value.length>0&&value.length<=max&&!/[\0-\x1f\x7f]/.test(value);}
function exactKeys(value,allowed){return plain(value)&&Object.keys(value).every(k=>allowed.has(k));}
function validInput(o){return plain(o)&&['session','24h','7d','30d','unlimited'].includes(o.lifetime)&&((Object.keys(o).length===2&&['read_only','direct_collaboration','review_first'].includes(o.mode))||(Object.keys(o).length===3&&bounded(o.projectId)&&['read','propose','write'].includes(o.permission)));}
function uuidId(value){return typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value);}
function grantCreated(text,expectedId){let row;try{row=JSON.parse(text)}catch{}if(!exactKeys(row,GRANT_KEYS)||!bounded(row.id)||row.id!==expectedId||!bounded(row.token,MAX_TOKEN))throw Error('Agent Access service returned an invalid grant response');return {id:row.id,token:row.token};}
function statusProjection(value,wanted,lifetime,now=Date.now()){
 if(!Array.isArray(value))return {kind:'unknown',reason:'invalid_response'};
 const allowed=new Set(['id','status','persistent','expires_at','token_prefix','project_id','workspace_scope','mode','permission','node_scope_id','branch_root_id','label','agent_identity','revoked_at','last_used_at','created_at']),matches=[];
 for(const row of value){const nullableString=k=>row[k]===undefined||row[k]===null||bounded(row[k],512),optionalString=k=>row[k]===undefined||bounded(row[k],512);if(!exactKeys(row,allowed)||!bounded(row.id)||!['active','revoked'].includes(row.status)||typeof row.persistent!=='boolean'||!(row.expires_at===null||typeof row.expires_at==='string')||(row.persistent&&row.expires_at!==null)||(!row.persistent&&!Number.isFinite(Date.parse(row.expires_at)))||!optionalString('token_prefix')||(row.permission!==undefined&&!['read','propose','write'].includes(row.permission))||!nullableString('node_scope_id')||!nullableString('branch_root_id')||!nullableString('label')||!nullableString('agent_identity')||!nullableString('revoked_at')||!nullableString('last_used_at')||!nullableString('created_at'))return {kind:'unknown',reason:'invalid_response'};const expectedPermission={read_only:'read',review_first:'propose',direct_collaboration:'write'}[row.mode];if(row.workspace_scope==='workspace'){if(row.project_id!==null||expectedPermission===undefined||row.permission!==expectedPermission)return {kind:'unknown',reason:'invalid_response'};}else if(row.workspace_scope==='legacy_project'){if(!bounded(row.project_id,512)||expectedPermission===undefined||row.permission!==expectedPermission)return {kind:'unknown',reason:'invalid_response'};}else return {kind:'unknown',reason:'invalid_response'};if(row.id===wanted)matches.push(row);}
 if(matches.length>1)return {kind:'unknown',reason:'ambiguous_response'};if(matches.length===0)return {kind:'repair',reason:'grant_missing'};
 const row=matches[0];if(row.status!=='active')return {kind:'repair',reason:'grant_inactive'};
 if(row.persistent){if(lifetime!=='unlimited')return {kind:'unknown',reason:'invalid_response'};}
 else {const expires=Date.parse(row.expires_at);if(expires<=now||lifetime==='unlimited')return expires<=now?{kind:'repair',reason:'grant_expired'}:{kind:'unknown',reason:'invalid_response'};}
 return {kind:'enabled',reason:'backend_confirmed'};
}
function manager({userData,localAppData,exe,major,installation,api,endpoint,sidecarPid,instanceNonce,clipboard,saveDialog,runHelper=helper,runTest=testConnection}){
 const descriptor=path.join(localAppData,'GrowthMap','agent-access.json'),profile=path.join(userData,'agent-access.json'),targetPrefix=`GrowthMap/AgentPort/v1/product-${major}/installation-${installation}/`;let state=null,tail=Promise.resolve(),statusLatch=null;
 const enqueue=operation=>{const result=tail.then(operation,operation);tail=result.catch(()=>{});return result;};
 const status=()=>{if(statusLatch)return statusLatch;const result=enqueue(statusImpl);statusLatch=result.finally(()=>{if(statusLatch===latched)statusLatch=null});const latched=statusLatch;return statusLatch;};
 const persist=l=>l==='unlimited'?'unlimited':l==='session'?'session':'finite',validTarget=x=>bounded(x,512)&&x.startsWith(targetPrefix)&&/^[A-Za-z0-9_-]{1,64}$/.test(x.slice(targetPrefix.length));
 const grantBody=(o,grantId)=>({id:grantId,...(o.mode?{workspace_scope:'workspace',mode:o.mode}:{workspace_scope:'legacy_project',project_id:o.projectId,permission:o.permission}),persistent:o.lifetime==='unlimited',expires_at:o.lifetime==='unlimited'?null:new Date(Date.now()+({session:12,'24h':24,'7d':168,'30d':720}[o.lifetime])*3600000).toISOString(),label:'Universal local MCP',agent_identity:'local-mcp'});
 const validCleanup=x=>plain(x)&&Object.keys(x).length===4&&bounded(x.grantId)&&validTarget(x.credentialTarget)&&typeof x.revokePending==='boolean'&&typeof x.deletePending==='boolean'&&(x.revokePending||x.deletePending);
 const validIntent=x=>x===null||(plain(x)&&((Object.keys(x).length===3&&x.stage==='pre-create'&&uuidId(x.grantId)&&validTarget(x.credentialTarget))||(Object.keys(x).length===5&&x.stage==='pre-rotate'&&uuidId(x.grantId)&&validTarget(x.credentialTarget)&&bounded(x.oldGrantId)&&validTarget(x.oldCredentialTarget))));
 const intentDisjoint=x=>x.intent===null||((!x.grantId||x.intent.stage==='pre-rotate'&&x.intent.oldGrantId===x.grantId&&x.intent.oldCredentialTarget===x.credentialTarget||x.intent.grantId!==x.grantId&&x.intent.credentialTarget!==x.credentialTarget)&&!x.cleanup.some(c=>c.grantId===x.intent.grantId||c.credentialTarget===x.intent.credentialTarget||x.intent.stage==='pre-rotate'&&(c.grantId===x.intent.oldGrantId||c.credentialTarget===x.intent.oldCredentialTarget)));
 const validProfile=x=>exactKeys(x,new Set([...PROFILE_KEYS,'intent']))&&x.schema==='growthmap.agent-profile.v1'&&['enabled','repair'].includes(x.status)&&bounded(x.projectId)&&['read','propose','write'].includes(x.permission)&&(x.mode===undefined||['read_only','review_first','direct_collaboration'].includes(x.mode))&&['session','24h','7d','30d','unlimited'].includes(x.lifetime)&&(x.grantId===null||bounded(x.grantId))&&(x.credentialTarget===null||validTarget(x.credentialTarget))&&((x.grantId===null)===(x.credentialTarget===null))&&Array.isArray(x.cleanup)&&x.cleanup.length<=MAX_CLEANUP&&x.cleanup.every(validCleanup)&&new Set(x.cleanup.map(c=>c.grantId)).size===x.cleanup.length&&(!x.grantId||!x.cleanup.some(c=>c.grantId===x.grantId||c.credentialTarget===x.credentialTarget))&&validIntent(x.intent)&&intentDisjoint(x)&&(!x.intent||x.cleanup.length<MAX_CLEANUP)&&(x.status==='enabled'?x.grantId!==null&&x.cleanup.length===0&&x.intent===null:true);
 const normalizeLegacy=x=>{if(!plain(x))return x;const permission=['read','propose','write'].includes(x.permission)?x.permission:'propose';const mode=x.mode||({read:'read_only',propose:'review_first',write:'direct_collaboration'}[permission]);return {...x,permission,mode,cleanup:x.cleanup||[],intent:x.intent===undefined?null:x.intent};};
 const save=()=>atomic(profile,state),view=(kind,reason)=>Object.freeze({state:kind,reason,permission:state?.permission||'propose',lifetime:state?.lifetime||'unlimited',config:config(exe)});
 async function statusImpl(){if(!state)return view('disabled','no_profile');if(state.blocked===true)return view('repair',state.recovery?'recovery_capacity':'profile_invalid');if(state.status!=='enabled'||state.cleanup.length||state.intent)return view('repair','local_repair');let text;try{text=await api('GET',state.projectId==='workspace'?'/api/agent-port/grants':`/api/agent-port/grants?project_id=${encodeURIComponent(state.projectId)}`,undefined,undefined,{maxSuccessBytes:MAX_STATUS_BYTES});if(typeof text!=='string'||Buffer.byteLength(text)>MAX_STATUS_BYTES)return view('unknown','response_too_large');const value=JSON.parse(text);if(!Array.isArray(value)||value.length>MAX_STATUS_ROWS)return view('unknown','invalid_response');const x=statusProjection(value,state.grantId,state.lifetime);return view(x.kind,x.reason);}catch{return view('unknown','backend_unavailable')}}
 async function authorize(){const checked=await statusImpl();if(checked.state!=='enabled')throw Error('Agent Access is not backend-confirmed enabled');}
 async function compensate(item){let revoke=false,del=false;try{await api('POST',`/api/agent-port/grants/${encodeURIComponent(item.grantId)}/revoke`);revoke=true}catch(e){if(e?.statusCode===404)revoke=true}try{await runHelper(exe,'delete',{target:item.credentialTarget});del=true}catch{}return {revoke,del};}
 function materializeIntent(){if(!state.intent)return false;if(!intentDisjoint(state))throw Error('Agent Access recovery identity conflict');const intent=state.intent,needed=intent.stage==='pre-rotate'?2:1;if(state.cleanup.length+needed>MAX_CLEANUP)throw Error('Agent Access recovery capacity invariant violated');if(intent.stage==='pre-rotate'){state.grantId=null;state.credentialTarget=null;state.cleanup.push({grantId:intent.oldGrantId,credentialTarget:intent.oldCredentialTarget,revokePending:true,deletePending:true});}state.cleanup.push({grantId:intent.grantId,credentialTarget:intent.credentialTarget,revokePending:true,deletePending:true});state.intent=null;state.status='repair';save();return true;}
 function persistRecovery(item,primary){state.status='repair';const isCurrent=state.grantId===item.grantId&&state.credentialTarget===item.credentialTarget;if(isCurrent){state.grantId=null;state.credentialTarget=null;}else if(state.grantId===item.grantId||state.credentialTarget===item.credentialTarget)throw Error('Agent Access recovery identity conflict');const existing=state.cleanup.find(x=>x.grantId===item.grantId);if(existing){if(existing.credentialTarget!==item.credentialTarget)throw Error('Agent Access recovery identity conflict');existing.revokePending||=item.revokePending;existing.deletePending||=item.deletePending;}else state.cleanup.push(item);try{save()}catch{}throw primary;}
 async function createRecoverable(o,newTarget){const grantId=crypto.randomUUID();state.intent={stage:'pre-create',grantId,credentialTarget:newTarget};save();let text;try{text=await api('POST','/api/agent-port/grants',grantBody(o,grantId),undefined,{maxSuccessBytes:16384});}catch(e){if(e?.statusCode===403){state.intent=null;save()}else{state.status='repair';try{save()}catch{}}throw e}let created;try{created=grantCreated(text,grantId)}catch(e){state.status='repair';try{save()}catch{}throw e}const item={grantId,credentialTarget:newTarget,revokePending:true,deletePending:true};state.intent=null;state.cleanup.push(item);try{save()}catch(e){const done=await compensate(item);if(done.revoke&&done.del)throw e;persistRecovery({...item,revokePending:!done.revoke,deletePending:!done.del},e)}try{await runHelper(exe,'provision',{target:newTarget,persist:persist(o.lifetime),credential:{schema:'growthmap.agent-credential.v1',endpoint,token:created.token,instance_nonce:instanceNonce,product_major:major}});}catch(e){const done=await compensate(item);item.revokePending=!done.revoke;item.deletePending=!done.del;if(!item.revokePending&&!item.deletePending)state.cleanup=state.cleanup.filter(x=>x!==item);try{save()}catch{}throw e}return {created,item};}
 async function publish(){if(!state||!validTarget(state.credentialTarget))throw Error('Agent Access profile is incomplete');atomic(descriptor,{schema:'growthmap.agent-discovery.v1',protocol:'1.0',endpoint,sidecar_pid:sidecarPid(),desktop_pid:process.pid,instance_nonce:instanceNonce,product_major:major,created_at:new Date().toISOString(),credential_target:state.credentialTarget,mcp_executable:exe});}
 async function restoreImpl(){let parsed;try{parsed=normalizeLegacy(JSON.parse(boundedStableRead(profile)));}catch(e){if(e.code==='ENOENT')return null;remove(descriptor);state={blocked:true};return state}if(!validProfile(parsed)){remove(descriptor);const safe=plain(parsed)&&parsed.schema==='growthmap.agent-profile.v1'&&Array.isArray(parsed.cleanup)&&parsed.cleanup.length===MAX_CLEANUP&&parsed.cleanup.every(validCleanup)&&validIntent(parsed.intent)&&parsed.intent!==null&&intentDisjoint(parsed);state=safe?{blocked:true,recovery:parsed}:{blocked:true};return state}state=parsed;materializeIntent();if(state.status==='enabled'){try{await runHelper(exe,'rebind',{target:state.credentialTarget,endpoint,instance_nonce:instanceNonce,product_major:major,persist:persist(state.lifetime)});await publish();}catch{state.status='repair';save();remove(descriptor)}}else remove(descriptor);return state;}
 async function enableImpl(o){if(state?.status==='enabled')return statusImpl();if(state)throw Error('Agent Access requires repair before it can be enabled');if(!validInput(o))throw Error('Invalid Agent Access request');const credentialTarget=target(major,installation);state={schema:'growthmap.agent-profile.v1',status:'repair',grantId:null,projectId:o.mode?'workspace':o.projectId,permission:o.mode?({read_only:'read',review_first:'propose',direct_collaboration:'write'}[o.mode]):o.permission,mode:o.mode||({read:'read_only',propose:'review_first',write:'direct_collaboration'}[o.permission]),lifetime:o.lifetime,credentialTarget:null,cleanup:[],intent:null};save();let made;try{made=await createRecoverable(o,credentialTarget)}catch(e){if(state.cleanup.length===0&&state.intent===null){unlinkEntry(profile);state=null}throw e}state.cleanup=state.cleanup.filter(x=>x!==made.item);state.grantId=made.created.id;state.credentialTarget=credentialTarget;state.status='repair';try{save();await publish();state.status='enabled';save();return statusImpl()}catch(e){remove(descriptor);const item={grantId:made.created.id,credentialTarget,revokePending:true,deletePending:true},done=await compensate(item);item.revokePending=!done.revoke;item.deletePending=!done.del;if(item.revokePending||item.deletePending)persistRecovery(item,e);unlinkEntry(profile);state=null;throw e}}
 async function cleanupPending(){let failed=false;for(const item of [...state.cleanup]){if(item.revokePending){try{await api('POST',`/api/agent-port/grants/${encodeURIComponent(item.grantId)}/revoke`);item.revokePending=false;save()}catch(e){if(e?.statusCode===404){item.revokePending=false;save()}else failed=true}}if(item.deletePending){try{await runHelper(exe,'delete',{target:item.credentialTarget});item.deletePending=false;save()}catch{failed=true}}if(!item.revokePending&&!item.deletePending){state.cleanup=state.cleanup.filter(x=>x!==item);save()}}return !failed&&state.cleanup.length===0;}
 async function regenerateImpl(){await authorize();if(state.cleanup.length+2>MAX_CLEANUP)throw Error('Agent Access cleanup capacity is exhausted; repair before regenerating');const old={grantId:state.grantId,credentialTarget:state.credentialTarget,revokePending:true,deletePending:true},credentialTarget=target(major,installation,crypto.randomBytes(12).toString('hex')),grantId=crypto.randomUUID();state.status='repair';state.intent={stage:'pre-rotate',grantId,credentialTarget,oldGrantId:old.grantId,oldCredentialTarget:old.credentialTarget};save();let text;try{text=await api('POST',`/api/agent-port/grants/${encodeURIComponent(old.grantId)}/rotate`,grantBody({mode:state.mode,lifetime:state.lifetime},grantId),undefined,{maxSuccessBytes:16384});}catch(e){if(e?.statusCode===409&&e?.code==='WORKSPACE_GRANT_STALE'){state.intent=null;state.status='repair';save()}else{state.status='repair';try{save()}catch{}}throw e}let created;try{created=grantCreated(text,grantId)}catch(e){state.status='repair';try{save()}catch{}throw e}state.intent=null;state.grantId=created.id;state.credentialTarget=credentialTarget;state.cleanup.push(old);save();try{await runHelper(exe,'provision',{target:credentialTarget,persist:persist(state.lifetime),credential:{schema:'growthmap.agent-credential.v1',endpoint,token:created.token,instance_nonce:instanceNonce,product_major:major}});await publish();}catch(e){remove(descriptor);const replacement={grantId:created.id,credentialTarget,revokePending:true,deletePending:true};state.grantId=null;state.credentialTarget=null;state.cleanup.push(replacement);try{save()}catch{}throw e}if(!await cleanupPending())throw Error('New access is active, but old access cleanup requires repair.');state.status='enabled';save();return statusImpl();}
 async function disableImpl(){remove(descriptor);if(!state)return statusImpl();if(state.blocked===true){if(state.recovery)throw Error('Agent Access recovery capacity is exhausted; metadata was preserved');unlinkEntry(profile);state=null;return statusImpl()}state.status='repair';materializeIntent();if(state.grantId&&!state.cleanup.some(x=>x.grantId===state.grantId)){if(state.cleanup.length>=MAX_CLEANUP)throw Error('Agent Access recovery capacity invariant violated');state.cleanup.push({grantId:state.grantId,credentialTarget:state.credentialTarget,revokePending:true,deletePending:true});state.grantId=null;state.credentialTarget=null}save();if(!await cleanupPending())throw Error('Access is blocked locally, but cleanup failed. Retry repair.');unlinkEntry(profile);state=null;return statusImpl();}
 return {restore:()=>enqueue(restoreImpl),status,enable:o=>enqueue(()=>enableImpl(o)),regenerate:()=>enqueue(regenerateImpl),disable:()=>enqueue(disableImpl),copyConfig:()=>enqueue(async()=>{await authorize();if(!clipboard)throw Error('Clipboard is unavailable');clipboard.writeText(JSON.stringify(config(exe),null,2));return true;}),downloadConfig:()=>enqueue(async()=>{await authorize();if(!saveDialog)throw Error('Save dialog is unavailable');const choice=await saveDialog({title:'Save generic MCP configuration',defaultPath:'mcp.json',filters:[{name:'JSON',extensions:['json']}],properties:['showOverwriteConfirmation']});if(choice.canceled||!choice.filePath)return {saved:false};atomicText(choice.filePath,JSON.stringify(config(exe),null,2)+'\n');return {saved:true};}),test:()=>enqueue(async()=>{await authorize();return runTest(exe)}),publish};
}
module.exports={regular,atomic,atomicText,remove,unlinkEntry,boundedStableRead,helper,config,target,testConnection,statusProjection,manager};
