'use strict';
const crypto=require('node:crypto'),path=require('node:path');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,canonical=JSON.stringify;
const exactKeys=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&keys.length===Object.keys(v).length&&keys.every(k=>Object.prototype.hasOwnProperty.call(v,k));
function namespace(lineage){return crypto.createHash('sha256').update(`growthmap-credential-lineage\0${lineage}`).digest('hex')}
function canonicalBindingKey(platform,value){if(platform!=='win32')return path.posix.resolve(value);if(typeof value!=='string'||!(/^[A-Za-z]:[\\/]/).test(value)||/^(?:\\\\|[\\/]|[A-Za-z]:[^\\/])/.test(value))throw Error('Credential authority path is invalid');const resolved=path.win32.resolve(value);if(!/^[A-Za-z]:\\/.test(resolved)||resolved.startsWith('\\\\')||resolved.startsWith('\\\\?\\')||resolved.startsWith('\\\\.\\'))throw Error('Credential authority path is invalid');return path.win32.normalize(resolved).toLowerCase()}
function validateAuthorityPayload(value,fail=()=>{throw Error('Credential authority is invalid')}){if(!exactKeys(value,['schemaVersion','bindings'])||value.schemaVersion!==1||!value.bindings||Array.isArray(value.bindings)||typeof value.bindings!=='object')return fail();const lineages=new Set(),namespaceSet=new Set(),bindingKeys=new Set();for(const [key,b] of Object.entries(value.bindings)){if(!exactKeys(b,['identity','lineage','legacyAdopted'])||!b.identity||typeof b.legacyAdopted!=='boolean'||!UUID.test(b.lineage))return fail();const identity=b.identity,keys=identity.platform==='win32'?['platform','path','volumeSerial','fileIndex']:identity.platform==='posix'?['platform','path','device','inode']:null;if(!keys||!exactKeys(identity,keys)||key!==identity.path)return fail();let bindingKey;try{bindingKey=canonicalBindingKey(identity.platform,key)}catch{return fail()}if(bindingKey!==key||bindingKeys.has(bindingKey))return fail();bindingKeys.add(bindingKey);if(identity.platform==='win32'){if(!/^[0-9A-F]{8}$/.test(identity.volumeSerial)||!/^[0-9A-F]{16}$/.test(identity.fileIndex))return fail()}else if(!/^\d+$/.test(identity.device)||!/^\d+$/.test(identity.inode)||(identity.device==='0'&&identity.inode==='0'))return fail();const ns=namespace(b.lineage);if(lineages.has(b.lineage)||namespaceSet.has(ns))return fail();lineages.add(b.lineage);namespaceSet.add(ns)}return value}
function migrateLegacyWindowsAuthority(value,fail=()=>{throw Error('Credential authority is invalid')}){if(!exactKeys(value,['schemaVersion','bindings'])||value.schemaVersion!==1||!value.bindings||Array.isArray(value.bindings)||typeof value.bindings!=='object')return fail();const migrated={schemaVersion:value.schemaVersion,bindings:{}},lineages=new Set(),namespaceSet=new Set(),canonicalKeys=new Set();for(const [key,b] of Object.entries(value.bindings)){if(!exactKeys(b,['identity','lineage','legacyAdopted'])||!b.identity||typeof b.legacyAdopted!=='boolean'||!UUID.test(b.lineage))return fail();const identity=b.identity;if(!exactKeys(identity,['platform','path','volumeSerial','fileIndex'])||identity.platform!=='win32'||key!==identity.path||typeof key!=='string'||key.includes('\0')||!/^[A-Za-z]:\\/.test(key)||key.includes('/')||path.win32.normalize(key)!==key||key.startsWith('\\\\')||key.startsWith('\\\\?\\')||key.startsWith('\\\\.\\')||!/^[0-9A-F]{8}$/.test(identity.volumeSerial)||!/^[0-9A-F]{16}$/.test(identity.fileIndex))return fail();let bindingKey;try{bindingKey=canonicalBindingKey('win32',key)}catch{return fail()}if(canonicalKeys.has(bindingKey))return fail();canonicalKeys.add(bindingKey);const ns=namespace(b.lineage);if(lineages.has(b.lineage)||namespaceSet.has(ns))return fail();lineages.add(b.lineage);namespaceSet.add(ns);migrated.bindings[bindingKey]={identity:{...identity,path:bindingKey},lineage:b.lineage,legacyAdopted:b.legacyAdopted}}return validateAuthorityPayload(migrated,fail)}
module.exports={validateAuthorityPayload,migrateLegacyWindowsAuthority,namespace,canonical,canonicalBindingKey,UUID,exactKeys};
