'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {validateUpdateUrl,canonicalOrigin,checkoutAllowed,PLACEHOLDER}=require('./update-policy');
const EXACT=['schemaVersion','productMajor','licensePublicKeyResource','licensePublicKeySha256','paymentApiOrigin','purchasePortalOrigin','purchasePortalUrl','baseNetwork','baseUsdc','basePayee','earlyLimit','earlyPriceMicros','regularPriceMicros','paypalUrl','updateUrl','updateOrigin','publisher','publisherStatus'];
function placeholder(value){return PLACEHOLDER.test(String(value))||/REPLACE|TBD|REQUIRES_APPROVED|UNAPPROVED/i.test(String(value));}
function loadCommercialConfig({isPackaged,resourcesPath,env=process.env,appDir=__dirname}){if(!isPackaged)return {schemaVersion:2,productMajor:1,publisher:'development',publisherStatus:'DEVELOPMENT',licensePublicKeyPath:env.GROWTHMAP_LICENSE_PUBLIC_KEY||path.join(appDir,'../src/backend/desktop/license_public_key.pem'),paymentApiOrigin:env.GROWTHMAP_PAYMENT_API_ORIGIN||'',purchasePortalOrigin:env.GROWTHMAP_PURCHASE_PORTAL_ORIGIN||'',purchasePortalUrl:env.GROWTHMAP_PURCHASE_PORTAL_URL||'',paypalUrl:env.GROWTHMAP_PAYPAL_URL||'',updateUrl:env.GROWTHMAP_UPDATE_URL||'',developmentOverride:true};
 const file=path.join(resourcesPath,'commercial-config.json'),doc=JSON.parse(fs.readFileSync(file,'utf8'));if(Object.keys(doc).sort().join('\0')!==EXACT.slice().sort().join('\0')||doc.schemaVersion!==2||doc.productMajor!==1||doc.publisherStatus!=='APPROVED'||EXACT.some(k=>placeholder(doc[k])))throw Error('Packaged commercial configuration is invalid');
 const publicKey=path.resolve(resourcesPath,doc.licensePublicKeyResource);if(!publicKey.startsWith(`${path.resolve(resourcesPath)}${path.sep}`)||!doc.licensePublicKeyResource.endsWith('.pem')||!/^[0-9a-f]{64}$/.test(doc.licensePublicKeySha256)||crypto.createHash('sha256').update(fs.readFileSync(publicKey)).digest('hex')!==doc.licensePublicKeySha256)throw Error('Packaged license public key hash mismatch');
 const purchasePortalOrigin=canonicalOrigin(doc.purchasePortalOrigin);if(!checkoutAllowed(doc.purchasePortalUrl,purchasePortalOrigin)||canonicalOrigin(doc.paymentApiOrigin)!==doc.paymentApiOrigin||!checkoutAllowed(doc.paypalUrl,new URL(doc.paypalUrl).origin)||doc.baseNetwork!=='eip155:8453'||doc.baseUsdc!=='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'||!/^0x[0-9a-fA-F]{40}$/.test(doc.basePayee)||doc.earlyLimit!==50||doc.earlyPriceMicros!==10000000||doc.regularPriceMicros!==29000000)throw Error('Packaged payment trust mismatch');const updateUrl=validateUpdateUrl(doc.updateUrl,{production:true}),updateOrigin=canonicalOrigin(doc.updateOrigin);if(new URL(updateUrl).origin!==updateOrigin)throw Error('Packaged update trust mismatch');return {...doc,purchasePortalOrigin,updateUrl,updateOrigin,licensePublicKeyPath:publicKey};}
module.exports={loadCommercialConfig,EXACT};
