'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {validateUpdateUrl,canonicalOrigin,PLACEHOLDER}=require('./update-policy');
const {strictCanonicalPublicHttpsOrigin,validatePurchasePortalUrl}=require('./purchase-portal');
const {parseStrictJson}=require('./strict-json');
const EXACT=['schemaVersion','productMajor','licenseIssuer','supportEmail','supportUrl','licensePublicKeyResource','licensePublicKeySha256','activationApiOrigin','purchasePortalOrigin','purchasePortalUrl','updateUrl','updateOrigin','publisher','publisherStatus'];
function placeholder(value){return PLACEHOLDER.test(String(value))||/REPLACE|TBD|REQUIRES_APPROVED|UNAPPROVED/i.test(String(value));}
function validText(value,max){return typeof value==='string'&&value.length>0&&value.length<=max&&!/[\u0000-\u001f\u007f]/.test(value)&&!placeholder(value);}
function validEmail(value){return typeof value==='string'&&value.length<=254&&/^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$/.test(value)&&!placeholder(value);}
function validSupportUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&u.origin==='https://x.com'&&u.username===''&&u.password===''&&u.search===''&&u.hash===''&&/^\/[A-Za-z0-9_]{1,15}$/.test(u.pathname)&&u.href===value;}catch{return false;}}
function validatePublic(doc){if(!validText(doc.licenseIssuer,80)||!validEmail(doc.supportEmail)||!validSupportUrl(doc.supportUrl))throw Error('Packaged commercial public identity is invalid');}
function loadCommercialConfig({isPackaged,resourcesPath,env=process.env,appDir=__dirname,releaseMode='signed-commercial'}){if(!isPackaged)return {schemaVersion:4,productMajor:1,licenseIssuer:env.GROWTHMAP_LICENSE_ISSUER||'',supportEmail:env.GROWTHMAP_SUPPORT_EMAIL||'',supportUrl:env.GROWTHMAP_SUPPORT_URL||'',publisher:'development',publisherStatus:'DEVELOPMENT',licensePublicKeyPath:env.GROWTHMAP_LICENSE_PUBLIC_KEY||path.join(appDir,'../src/backend/desktop/license_public_key.pem'),activationApiOrigin:env.GROWTHMAP_ACTIVATION_API_ORIGIN||'',purchasePortalOrigin:env.GROWTHMAP_PURCHASE_PORTAL_ORIGIN||'',purchasePortalUrl:env.GROWTHMAP_PURCHASE_PORTAL_URL||'',updateUrl:env.GROWTHMAP_UPDATE_URL||'',developmentOverride:true};
 const file=path.join(resourcesPath,'commercial-config.json'),doc=parseStrictJson(fs.readFileSync(file,'utf8'));if(Object.keys(doc).sort().join('\0')!==EXACT.slice().sort().join('\0')||doc.schemaVersion!==4||doc.productMajor!==1)throw Error('Packaged commercial configuration is invalid');validatePublic(doc);
 const publicKey=path.resolve(resourcesPath,doc.licensePublicKeyResource);if(!publicKey.startsWith(`${path.resolve(resourcesPath)}${path.sep}`)||!doc.licensePublicKeyResource.endsWith('.pem')||!/^[0-9a-f]{64}$/.test(doc.licensePublicKeySha256)||crypto.createHash('sha256').update(fs.readFileSync(publicKey)).digest('hex')!==doc.licensePublicKeySha256)throw Error('Packaged license public key hash mismatch');
 if(releaseMode==='unsigned-manual'){if(doc.publisherStatus!=='NONCOMMERCIAL_UNSIGNED'||doc.activationApiOrigin!==''||doc.purchasePortalOrigin!==''||doc.purchasePortalUrl!==''||doc.updateUrl!==''||doc.updateOrigin!==''||placeholder(doc.publisher)||placeholder(doc.licensePublicKeyResource)||placeholder(doc.licensePublicKeySha256))throw Error('Packaged noncommercial configuration is invalid');return {...doc,licensePublicKeyPath:publicKey,noncommercialUnsigned:true};}
 if(releaseMode!=='signed-commercial'||doc.publisherStatus!=='APPROVED'||EXACT.some(k=>placeholder(doc[k])))throw Error('Packaged commercial configuration is invalid');
 let purchasePortalOrigin,purchasePortalUrl,activationApiOrigin;try{purchasePortalOrigin=strictCanonicalPublicHttpsOrigin(doc.purchasePortalOrigin);activationApiOrigin=strictCanonicalPublicHttpsOrigin(doc.activationApiOrigin);purchasePortalUrl=validatePurchasePortalUrl(doc.purchasePortalUrl,purchasePortalOrigin);}catch{throw Error('Packaged activation trust mismatch');}if(activationApiOrigin===purchasePortalOrigin)throw Error('Packaged activation trust mismatch');const updateUrl=validateUpdateUrl(doc.updateUrl,{production:true}),updateOrigin=canonicalOrigin(doc.updateOrigin);if(new URL(updateUrl).origin!==updateOrigin)throw Error('Packaged update trust mismatch');return {...doc,activationApiOrigin,purchasePortalOrigin,purchasePortalUrl,updateUrl,updateOrigin,licensePublicKeyPath:publicKey};}
module.exports={loadCommercialConfig,EXACT,validatePublic,validEmail,validSupportUrl};
