'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {validateUpdateUrl,canonicalOrigin,PLACEHOLDER}=require('./update-policy');
const {strictCanonicalPublicHttpsOrigin,validatePurchasePortalUrl}=require('./purchase-portal');
const {parseStrictJson}=require('./strict-json');
const APPROVED_PAYPAL_URL='https://www.paypal.com/ncp/payment/R2M3YAQJNNCZA';
const PUBLIC_CONFIG=require('./generated/public-config');
const APPROVED_BASE_PAYEE=PUBLIC_CONFIG.basePayee;
const EXACT=['schemaVersion','productMajor','licenseIssuer','supportEmail','supportUrl','licensePublicKeyResource','licensePublicKeySha256','paymentApiOrigin','purchasePortalOrigin','purchasePortalUrl','baseNetwork','baseUsdc','basePayee','earlyLimit','earlyPriceMicros','regularPriceMicros','paypalUrl','updateUrl','updateOrigin','publisher','publisherStatus'];
function placeholder(value){return PLACEHOLDER.test(String(value))||/REPLACE|TBD|REQUIRES_APPROVED|UNAPPROVED/i.test(String(value));}
function validText(value,max){return typeof value==='string'&&value.length>0&&value.length<=max&&!/[\u0000-\u001f\u007f]/.test(value)&&!placeholder(value);}
function validEmail(value){return typeof value==='string'&&value.length<=254&&/^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$/.test(value)&&!placeholder(value);}
function validSupportUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&u.origin==='https://x.com'&&u.username===''&&u.password===''&&u.search===''&&u.hash===''&&/^\/[A-Za-z0-9_]{1,15}$/.test(u.pathname)&&u.href===value;}catch{return false;}}
function validatePublic(doc){if(!validText(doc.licenseIssuer,80)||!validEmail(doc.supportEmail)||!validSupportUrl(doc.supportUrl))throw Error('Packaged commercial public identity is invalid');}
function validPaypalUrl(value){return typeof value==='string'&&value===APPROVED_PAYPAL_URL;}
function loadCommercialConfig({isPackaged,resourcesPath,env=process.env,appDir=__dirname}){if(!isPackaged)return {schemaVersion:3,productMajor:1,licenseIssuer:env.GROWTHMAP_LICENSE_ISSUER||'',supportEmail:env.GROWTHMAP_SUPPORT_EMAIL||'',supportUrl:env.GROWTHMAP_SUPPORT_URL||'',publisher:'development',publisherStatus:'DEVELOPMENT',licensePublicKeyPath:env.GROWTHMAP_LICENSE_PUBLIC_KEY||path.join(appDir,'../src/backend/desktop/license_public_key.pem'),paymentApiOrigin:env.GROWTHMAP_PAYMENT_API_ORIGIN||'',purchasePortalOrigin:env.GROWTHMAP_PURCHASE_PORTAL_ORIGIN||'',purchasePortalUrl:env.GROWTHMAP_PURCHASE_PORTAL_URL||'',basePayee:env.GROWTHMAP_BASE_PAYEE||'',paypalUrl:env.GROWTHMAP_PAYPAL_URL||'',updateUrl:env.GROWTHMAP_UPDATE_URL||'',developmentOverride:true};
 const file=path.join(resourcesPath,'commercial-config.json'),doc=parseStrictJson(fs.readFileSync(file,'utf8'));if(Object.keys(doc).sort().join('\0')!==EXACT.slice().sort().join('\0')||doc.schemaVersion!==3||doc.productMajor!==1||doc.publisherStatus!=='APPROVED'||EXACT.some(k=>placeholder(doc[k])))throw Error('Packaged commercial configuration is invalid');validatePublic(doc);
 const publicKey=path.resolve(resourcesPath,doc.licensePublicKeyResource);if(!publicKey.startsWith(`${path.resolve(resourcesPath)}${path.sep}`)||!doc.licensePublicKeyResource.endsWith('.pem')||!/^[0-9a-f]{64}$/.test(doc.licensePublicKeySha256)||crypto.createHash('sha256').update(fs.readFileSync(publicKey)).digest('hex')!==doc.licensePublicKeySha256)throw Error('Packaged license public key hash mismatch');
 let purchasePortalOrigin,purchasePortalUrl,paymentApiOrigin;try{purchasePortalOrigin=strictCanonicalPublicHttpsOrigin(doc.purchasePortalOrigin);paymentApiOrigin=strictCanonicalPublicHttpsOrigin(doc.paymentApiOrigin);purchasePortalUrl=validatePurchasePortalUrl(doc.purchasePortalUrl,purchasePortalOrigin);}catch{throw Error('Packaged payment trust mismatch');}if(paymentApiOrigin===purchasePortalOrigin||!validPaypalUrl(doc.paypalUrl)||doc.baseNetwork!==PUBLIC_CONFIG.baseNetwork||doc.baseUsdc!=='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'||doc.basePayee!==APPROVED_BASE_PAYEE||doc.earlyLimit!==50||doc.earlyPriceMicros!==10000000||doc.regularPriceMicros!==29000000)throw Error('Packaged payment trust mismatch');const updateUrl=validateUpdateUrl(doc.updateUrl,{production:true}),updateOrigin=canonicalOrigin(doc.updateOrigin);if(new URL(updateUrl).origin!==updateOrigin)throw Error('Packaged update trust mismatch');return {...doc,paymentApiOrigin,purchasePortalOrigin,purchasePortalUrl,updateUrl,updateOrigin,licensePublicKeyPath:publicKey};}
module.exports={loadCommercialConfig,EXACT,validatePublic,validEmail,validSupportUrl,validPaypalUrl,APPROVED_PAYPAL_URL,APPROVED_BASE_PAYEE};
