'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{secureFiles}=require('./secure-files'),{validateAuthorityPayload,namespace,canonical}=require('./authority-schema');
const AUTH='lineage-authority.bin',KEY='lineage-authority-key.bin',MAX=64*1024,SECRET=/^[0-9a-f-]{36}\.(?:bin|recover)$/;
const fail=()=>{throw Error('Credential authority is invalid')};
function dbIdentity(databasePath,{io=fs,platform=process.platform,windowsPolicy,windowsRunner}={}){
 const real=io.realpathSync(databasePath),before=io.lstatSync(real);if(before.isSymbolicLink()||!before.isFile()||before.nlink!==1)throw Error('Unsafe database identity');
 if(platform==='win32'){const ids=windowsPolicy([real],windowsRunner);if(!Array.isArray(ids)||ids.length!==1||!/^[0-9A-F]{8}:[0-9A-F]{16}$/.test(ids[0]))throw Error('Windows native database identity unavailable');const after=io.lstatSync(real),again=windowsPolicy([real],windowsRunner);if(after.isSymbolicLink()||!after.isFile()||after.nlink!==1||again[0]!==ids[0])throw Error('Unstable database identity');const [volumeSerial,fileIndex]=ids[0].split(':');return {platform:'win32',path:real,volumeSerial,fileIndex};}
 const after=io.lstatSync(real);if(before.dev!==after.dev||before.ino!==after.ino||!before.dev&&!before.ino)throw Error('Unstable database identity');return {platform:'posix',path:real,device:String(before.dev),inode:String(before.ino)};
}
function same(a,b){return canonical(a)===canonical(b)}
function createLineageAuthority({userData,io=fs,hooks={},platform=process.platform,windowsPolicy,windowsRunner,filesFactory,protectKey,unprotectKey}={}){
 if(typeof protectKey!=='function'||typeof unprotectKey!=='function')throw Error('Credential authority key protection unavailable');
 const root=path.join(userData,'secrets'),makeFiles=filesFactory||((trusted,directory,options)=>secureFiles(trusted,directory,io,options)),files=makeFiles(root,root,{hooks,maxReadBytes:MAX,platform,windowsPolicy,windowsRunner});files.verifyDir();
 function pair(){const authority=files.exists(AUTH),keyFile=files.exists(KEY);if(authority!==keyFile)return fail();return {authority,keyFile}}
 function key(){const present=pair();if(!present.keyFile){const raw=crypto.randomBytes(32);files.write(KEY,Buffer.from(protectKey(raw)));return raw}let raw;try{raw=Buffer.from(unprotectKey(files.read(KEY)))}catch{return fail()}if(raw.length!==32)return fail();return raw}
 const empty=()=>({schemaVersion:1,bindings:{}});
 function mac(payload){return crypto.createHmac('sha256',crypto.createHmac('sha256',key()).update('growthmap-lineage-authority-mac\0').digest()).update(canonical(payload)).digest('hex')}
 function validatePayload(value){return validateAuthorityPayload(value,fail)}
 function load(){const present=pair();if(!present.authority)return empty();const raw=files.read(AUTH);if(raw.length>MAX)return fail();let env;try{env=JSON.parse(raw.toString('utf8'))}catch{return fail()}if(canonical(env)!==raw.toString('utf8')||!env||Object.keys(env).join(',')!=='schemaVersion,payload,mac'||env.schemaVersion!==1||typeof env.mac!=='string'||!/^[0-9a-f]{64}$/.test(env.mac))return fail();const expected=mac(env.payload);if(!crypto.timingSafeEqual(Buffer.from(env.mac,'hex'),Buffer.from(expected,'hex')))return fail();return validatePayload(env.payload)}
 function save(value){validatePayload(value);files.write(AUTH,Buffer.from(canonical({schemaVersion:1,payload:value,mac:mac(value)})))}
 const identify=p=>dbIdentity(p,{io,platform,windowsPolicy,windowsRunner});
 function binding(databasePath){const identity=identify(databasePath),state=load(),found=state.bindings[identity.path];if(found&&!same(found.identity,identity))throw Error('Database identity changed without an authorized replacement');return {identity,state,found}}
 function prepare(databasePath,{mode='existing'}={}){const identity=identify(databasePath),before=load(),state=structuredClone(before);let found=state.bindings[identity.path];if(mode==='existing'){if(found&&!same(found.identity,identity))throw Error('Database identity changed without an authorized replacement');if(!found){found={identity,lineage:crypto.randomUUID(),legacyAdopted:false};state.bindings[identity.path]=found}}else if(mode==='managed-restore'){if(!found)throw Error('Managed restore has no credential lineage');found.identity=identity}else if(mode==='foreign-import'){found={identity,lineage:crypto.randomUUID(),legacyAdopted:true};state.bindings[identity.path]=found}else throw Error('Invalid credential lineage transition');let applied=false,open=true;return {lineage:found.lineage,before:structuredClone(before),after:structuredClone(state),apply(){if(applied)return;save(state);applied=true},commit(){if(!applied)throw Error('Credential lineage transition was not applied');open=false},rollback(){if(!open)throw Error('Credential lineage transition is already committed');if(applied)save(before);open=false}}}
 function activate(databasePath,options={}){const transition=prepare(databasePath,options);transition.apply();return transition}
 function adoptLegacyOnce(databasePath){const {identity,state,found}=binding(databasePath);if(!found)throw Error('Credential lineage is not active');const all=files.list().filter(n=>![AUTH,KEY].includes(n)&&!(/^[0-9a-f]{64}$/.test(n)&&io.lstatSync(path.join(root,n)).isDirectory()));for(const name of all)if(!SECRET.test(name))throw Error('Unexpected legacy credential artifact');const target=path.join(root,namespace(found.lineage)),destination=makeFiles(root,target,{maxReadBytes:MAX,platform,windowsPolicy,windowsRunner});if(found.legacyAdopted)return target;for(const name of all){const data=files.read(name);if(destination.exists(name)){if(!destination.read(name).equals(data))throw Error('Credential legacy adoption conflict')}else destination.write(name,data);hooks.afterLegacyCopy?.()}for(const name of all){files.remove(name);hooks.afterLegacyRemove?.()}found.legacyAdopted=true;state.bindings[identity.path]=found;save(state);hooks.afterLegacySave?.();return target}
 function directory(databasePath){const {found}=binding(databasePath);if(!found)throw Error('Credential lineage is not active');return path.join(root,namespace(found.lineage))}
 function ownsIdentity(candidatePath,authorityPath){const candidate=identify(candidatePath),state=load(),authority=state.bindings[path.resolve(authorityPath)];if(!authority)return false;const expected={...authority.identity,path:candidate.path};return same(expected,candidate)}
 function matches(value){try{return same(load(),value)}catch{return false}}
 function restore(value){save(structuredClone(value));if(!matches(value))throw Error('Credential authority restore verification failed')}
 return {activate,prepare,restore,adoptLegacyOnce,directory,ownsIdentity,matches,load,root};
}
const syncCreateLineageAuthority=createLineageAuthority,syncDbIdentity=dbIdentity;
const asyncImpl=()=>require('./credential-lineage-async');
function createLineageAuthorityDispatch(options={}){if((options.platform||process.platform)==='win32'){if(!options.windowsAdapter)throw Error('Windows credential authority requires shared native broker adapter');return asyncImpl().createLineageAuthorityAsync(options)}return syncCreateLineageAuthority(options)}
function dbIdentityDispatch(databasePath,options={}){if((options.platform||process.platform)==='win32'){if(!options.windowsAdapter)throw Error('Windows database identity requires shared native broker adapter');return asyncImpl().dbIdentityAsync(databasePath,options)}return syncDbIdentity(databasePath,options)}
module.exports={createLineageAuthority:createLineageAuthorityDispatch,dbIdentity:dbIdentityDispatch,namespace};
