'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{spawn:defaultSpawn}=require('node:child_process');
const {listManagedBackups}=require('./managed-backup');
const EXTENSIONS=new Set(['.db','.sqlite','.sqlite3']),UUID='[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}',OWNED_OLD=new RegExp(`^growthmap\\.db\\.gm-old-${UUID}$`,'i'),OWNED_NEW=new RegExp(`^growthmap\\.db\\.gm-new-${UUID}$`,'i'),OWNED_BACKUP=new RegExp(`^(backup|rollback)-\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-\\d{3}Z-${UUID}\\.db$`,'i');
class RecoveryRequiredError extends Error{constructor(cause,stage){super('database recovery required',{cause});this.name='RecoveryRequiredError';this.recoveryRequired=true;this.stage=stage||null;}}
function safeMessage(error){return error?.recoveryRequired?'資料庫需要復原；請重新啟動應用程式。':'資料庫操作失敗；目前資料已保留。';}
function replacementQuota({entitlement,recoveryEntitlement,updateRecovery=false}){const source=updateRecovery?recoveryEntitlement:entitlement;return Number.isInteger(source?.max_active_projects)?source.max_active_projects:null;}
function decimalIdentity(value){try{return BigInt(value).toString();}catch{return null;}}
function identityMatches(stat,evidence){return !evidence?.meaningful||(decimalIdentity(stat.dev)===decimalIdentity(evidence.device)&&decimalIdentity(stat.ino)===decimalIdentity(evidence.inode));}
function run(executable,args,env={},spawn=defaultSpawn,timeoutMs=30000){return new Promise((resolve,reject)=>{const clean={...process.env};delete clean.GROWTHMAP_MAINTENANCE_TEST_HOOK;const child=spawn(executable,args,{env:{...clean,...env,GROWTHMAP_DESKTOP_MODE:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']});let out='',err='',settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);error?reject(error):resolve(value);};const timer=setTimeout(()=>{try{child.kill();}catch{}if(process.platform==='win32'&&child.pid)defaultSpawn('taskkill',['/PID',String(child.pid),'/T','/F'],{stdio:'ignore',windowsHide:true}).once('error',()=>{});finish(new Error('database maintenance timed out'));},timeoutMs);child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.once('error',error=>finish(error));child.once('exit',code=>{if(code!==0)return finish(new Error(`database maintenance failed (${code}): ${err.slice(-300)}`));try{finish(null,JSON.parse(out));}catch{finish(new Error('database maintenance returned invalid output'));}});});}
function createDatabaseManager({userData,databasePath,executable,stopSidecar,startSidecar,reload,showOpenDialog,reveal,selectWorkspace=null,switchWorkspace=null,spawn=defaultSpawn,retention=20,fault=()=>{},reportStage=()=>{}}){
 const liveDir=path.dirname(databasePath),backupsDir=path.join(liveDir,'backups');let operation=null,recoveryRequired=false;
 const stage=name=>{reportStage(name);fault(name);};
 const maintenance=(flag,file,env)=>run(executable,[flag,file],env,spawn),hit=stage;
 async function schemaStatus(){return maintenance('--schema-status',databasePath);}
 async function startupEvidence(maxActiveProjects){const meta=await maintenance('--stable-validate-db',databasePath);if(Number.isInteger(maxActiveProjects)&&meta.counts.activeProjects>maxActiveProjects)throw new Error(`database exceeds active project limit (${meta.counts.activeProjects}/${maxActiveProjects})`);return {...meta,identity:{device:meta.device,inode:meta.inode,meaningful:decimalIdentity(meta.device)!=='0'||decimalIdentity(meta.inode)!=='0'},maxActiveProjects:Number.isInteger(maxActiveProjects)?maxActiveProjects:null};}
 async function gate(file,maxActiveProjects=null){if(/^\\\\/.test(file))throw new Error('network database paths are not allowed');if(!EXTENSIONS.has(path.extname(file).toLowerCase()))throw new Error('unsupported database extension');const stat=await fs.promises.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1)throw new Error('database must be a single-link regular file');const real=await fs.promises.realpath(file),liveReal=await fs.promises.realpath(databasePath).catch(()=>path.resolve(databasePath)),live=await fs.promises.stat(databasePath).catch(()=>null);if(real===liveReal||(live&&stat.dev===live.dev&&stat.ino===live.ino))throw new Error('source is active database');const meta=await maintenance('--validate-db',real);if(Number.isInteger(maxActiveProjects)&&meta.counts.activeProjects>maxActiveProjects)throw new Error(`database exceeds active project limit (${meta.counts.activeProjects}/${maxActiveProjects})`);return {source:real,expected:{sha256:meta.sha256,size:meta.size}};}
 async function fsyncDir(dir){if(process.platform==='win32')return {directoryFsync:'unsupported-windows-best-effort'};const h=await fs.promises.open(dir,'r');try{hit('before-directory-fsync');await h.sync();hit('after-directory-fsync');}finally{await h.close();}return {directoryFsync:true};}
 function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}
 async function snapshot(source,destination,label='source-snapshot'){hit(`before-${label}`);const meta=await maintenance('--validated-snapshot-db',source,{GROWTHMAP_MAINTENANCE_DESTINATION:destination});hit(`after-${label}`);return meta;}
 async function writeManifest(dbFile,meta){const manifest={format:'growthmap-backup-v1',createdAt:new Date().toISOString(),file:path.basename(dbFile),size:meta.size,projects:meta.counts.projects,sha256:meta.sha256,durability:meta.durability};const target=`${dbFile}.json`;try{hit('before-manifest');const handle=await fs.promises.open(target,'wx',0o600);try{await handle.writeFile(JSON.stringify(manifest,null,2));hit('before-manifest-fsync');await handle.sync();hit('after-manifest-fsync');}finally{await handle.close();}await fsyncDir(backupsDir);hit('after-manifest');}catch(error){let cleanupFailed=false;for(const file of [target,dbFile])try{await fs.promises.unlink(file);}catch(unlinkError){if(unlinkError.code!=='ENOENT')cleanupFailed=true;}try{await fsyncDir(backupsDir);}catch{cleanupFailed=true;}if(cleanupFailed){recoveryRequired=true;throw new RecoveryRequiredError();}throw error;}return manifest;}
 async function validManaged(){await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const rows=[];for(const manifest of listManagedBackups(liveDir)){try{const meta=await maintenance('--validate-db',path.join(backupsDir,manifest.file));if(meta.counts.projects===manifest.projects&&meta.sha256===manifest.sha256&&meta.size===manifest.size)rows.push(manifest);}catch{}}return rows;}
 async function prune(){for(const row of (await validManaged()).slice(retention)){await fs.promises.unlink(path.join(backupsDir,row.file)).catch(()=>{});await fs.promises.unlink(path.join(backupsDir,`${row.file}.json`)).catch(()=>{});}}
 async function backupInternal(prefix='backup'){await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const file=path.join(backupsDir,`${prefix}-${stamp()}-${crypto.randomUUID()}.db`);const meta=await snapshot(databasePath,file,'live-backup');await writeManifest(file,meta);await prune();return {...meta,backupId:path.basename(file)};}
 async function recoverStartup(){await fs.promises.mkdir(liveDir,{recursive:true});const names=await fs.promises.readdir(liveDir),olds=names.filter(x=>OWNED_OLD.test(x)).map(x=>path.join(liveDir,x)),news=names.filter(x=>OWNED_NEW.test(x)).map(x=>path.join(liveDir,x)),validOld=[];for(const file of olds){try{await maintenance('--validate-db',file);validOld.push(file);}catch{}}let liveValid=false,recovered=false;if(fs.existsSync(databasePath)){try{await maintenance('--validate-db',databasePath);liveValid=true;}catch{liveValid=false;}if(!liveValid){if(validOld.length!==1)throw new RecoveryRequiredError();const corrupt=`${databasePath}.gm-corrupt-${crypto.randomUUID()}`;await fs.promises.rename(databasePath,corrupt);try{await fs.promises.rename(validOld[0],databasePath);await fsyncDir(liveDir);await maintenance('--validate-db',databasePath);}catch{recoveryRequired=true;throw new RecoveryRequiredError();}return {recovered:true,evidenceRetained:true};}}else if(validOld.length===1){await fs.promises.rename(validOld[0],databasePath);await fsyncDir(liveDir);await maintenance('--validate-db',databasePath);liveValid=true;recovered=true;}else if(olds.length||news.length)throw new RecoveryRequiredError();else return {recovered:false};if(liveValid){for(const file of [...olds,...news].filter(x=>fs.existsSync(x))){const suffix=`.quarantine-${Date.now()}-${crypto.randomUUID()}`;await fs.promises.rename(file,`${file}${suffix}`);}if(olds.length||news.length)await fsyncDir(liveDir);return {recovered,residuesQuarantined:olds.length+news.length};}throw new RecoveryRequiredError();}
 async function offline(action,reloadAfter=false,restartAfter=true){if(operation)throw new Error('database operation already in progress');if(recoveryRequired)throw new RecoveryRequiredError();operation=(async()=>{let stopped=false,success=false,result,primaryError=null;try{stage('before-stop');await stopSidecar();stopped=true;stage('after-stop');result=await action();success=true;}catch(error){primaryError=error;}if(stopped&&restartAfter){try{stage('before-sidecar-restart');await startSidecar();stage('after-sidecar-restart');}catch(error){recoveryRequired=true;throw new RecoveryRequiredError(error,'sidecar-restart');}}if(primaryError)throw primaryError;if(success&&reloadAfter){stage('before-reload');await reload();stage('after-reload');}return result;})().finally(()=>{operation=null;});return operation;}
 async function replaceFrom(source,{maxActiveProjects=null,expected=null}={}){let installed=null;try{return await offline(async()=>{await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const rollback=path.join(backupsDir,`rollback-${stamp()}-${crypto.randomUUID()}.db`),id=crypto.randomUUID(),old=path.join(liveDir,`${path.basename(databasePath)}.gm-old-${id}`),staging=path.join(liveDir,`${path.basename(databasePath)}.gm-new-${id}`),capture=`${staging}.capture`;const previous=await snapshot(databasePath,rollback,'rollback-snapshot');await writeManifest(rollback,previous);const captured=await snapshot(source,staging,'source-snapshot');if(expected&&(captured.sourceSha256!==expected.sha256||captured.sourceSize!==expected.size))throw new Error('database source changed after validation');hit('before-old-rename');installed=await maintenance('--install-db',staging,{GROWTHMAP_MAINTENANCE_DESTINATION:databasePath,GROWTHMAP_MAINTENANCE_OLD:old,GROWTHMAP_MAINTENANCE_CAPTURE:capture,GROWTHMAP_EXPECTED_SHA256:captured.sha256,GROWTHMAP_EXPECTED_SIZE:String(captured.size),GROWTHMAP_EXPECTED_DEVICE:String(captured.device),GROWTHMAP_EXPECTED_INODE:String(captured.inode),GROWTHMAP_MAX_ACTIVE_PROJECTS:Number.isInteger(maxActiveProjects)?String(maxActiveProjects):''});installed.installed.maxActiveProjects=Number.isInteger(maxActiveProjects)?maxActiveProjects:null;await fs.promises.unlink(staging).catch(()=>{});return installed;},false,false).then(async result=>{try{hit('after-staging-rename');hit('before-final-validate');const liveStat=await fs.promises.lstat(databasePath,{bigint:true});if(!liveStat.isFile()||liveStat.isSymbolicLink()||liveStat.nlink!==1n||!identityMatches(liveStat,result.installed.identity))throw new Error('installed database identity changed before startup');await startSidecar(result.installed);hit('after-final-validate');await fs.promises.unlink(result.old);await fsyncDir(liveDir);if(reload)await reload();return {ok:true,installed:result.installed};}catch(error){await stopSidecar().catch(()=>{});const failed=`${databasePath}.failed-${Date.now()}`;try{await fs.promises.rename(databasePath,failed);hit('before-rollback-rename');await fs.promises.rename(result.old,databasePath);hit('after-rollback-rename');await fsyncDir(liveDir);}catch{recoveryRequired=true;throw new RecoveryRequiredError();}throw error;}});}finally{if(installed?.old&&fs.existsSync(installed.old))recoveryRequired=true;}}
 async function status(){const meta=await maintenance('--validate-db',databasePath),list=await validManaged();return {basename:path.basename(databasePath),directory:liveDir,databasePath,size:meta.size,projects:meta.counts.projects,sha256:meta.sha256,lastBackup:list[0]?.createdAt||null,busy:Boolean(operation)};}
 async function importDatabase(maxActiveProjects=null){if(operation)throw new Error('database operation already in progress');let picked;picked=await showOpenDialog({properties:['openFile'],filters:[{name:'SQLite database',extensions:['db','sqlite','sqlite3']}]});if(picked.canceled)return null;const checked=await gate(picked.filePaths[0],maxActiveProjects);return replaceFrom(checked.source,{maxActiveProjects,expected:checked.expected});}
 async function backupEvidence(meta){const managed=(await validManaged()).find(item=>item.id===meta.backupId);if(!managed)throw new Error('managed backup verification failed');return {ok:true,verifiedManaged:true,projects:meta.counts.projects,backupId:meta.backupId,sha256:managed.sha256,size:managed.size};}
 async function backup(){return offline(async()=>backupEvidence(await backupInternal()));}
 async function migrationBackup(){return backupEvidence(await backupInternal('backup'));}
 async function restore(id,maxActiveProjects=null){if(operation)throw new Error('database operation already in progress');if(typeof id!=='string'||!OWNED_BACKUP.test(id))throw new Error('invalid backup id');const item=(await validManaged()).find(x=>x.id===id);if(!item)throw new Error('backup is not app-managed or has changed');const source=path.join(backupsDir,item.file),meta=await maintenance('--validate-db',source);if(Number.isInteger(maxActiveProjects)&&meta.counts.activeProjects>maxActiveProjects)throw new Error(`backup exceeds active project limit (${meta.counts.activeProjects}/${maxActiveProjects})`);return replaceFrom(source,{maxActiveProjects,expected:{sha256:item.sha256,size:item.size}});}
 async function list(){return (await validManaged()).map(({id,createdAt,size,projects,sha256})=>({id,createdAt,size,projects,sha256}));}
 async function awaitIdle(){if(operation)await operation.catch(()=>{});}
 async function chooseWorkspace(){if(!selectWorkspace||!switchWorkspace)throw new Error('database workspace selection is unavailable');if(operation)throw new Error('database operation already in progress');const chosen=await selectWorkspace();if(!chosen)return null;return switchWorkspace(chosen);}
 return {status,schemaStatus,startupEvidence,importDatabase,backup,migrationBackup,restore,list,recoverStartup,awaitIdle,chooseWorkspace,get busy(){return Boolean(operation);},reveal:()=>reveal(backupsDir),safeMessage:error=>safeMessage(error)};
}
module.exports={createDatabaseManager,run,safeMessage,replacementQuota,identityMatches,RecoveryRequiredError};
