'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{spawn:defaultSpawn}=require('node:child_process');
const EXTENSIONS=new Set(['.db','.sqlite','.sqlite3']),UUID='[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}',OWNED_OLD=new RegExp(`^growthmap\\.db\\.gm-old-${UUID}$`,'i'),OWNED_NEW=new RegExp(`^growthmap\\.db\\.gm-new-${UUID}$`,'i'),OWNED_BACKUP=new RegExp(`^(backup|rollback)-\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-\\d{3}Z-${UUID}\\.db$`,'i');
class RecoveryRequiredError extends Error{constructor(){super('database recovery required');this.recoveryRequired=true;}}
function safeMessage(error){return error?.recoveryRequired?'資料庫需要復原；請重新啟動應用程式。':'資料庫操作失敗；目前資料已保留。';}
function run(executable,args,env={},spawn=defaultSpawn,timeoutMs=30000){return new Promise((resolve,reject)=>{const child=spawn(executable,args,{env:{...process.env,...env,GROWTHMAP_DESKTOP_MODE:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']});let out='',err='',settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);error?reject(error):resolve(value);};const timer=setTimeout(()=>{try{child.kill();}catch{}if(process.platform==='win32'&&child.pid)defaultSpawn('taskkill',['/PID',String(child.pid),'/T','/F'],{stdio:'ignore',windowsHide:true}).once('error',()=>{});finish(new Error('database maintenance timed out'));},timeoutMs);child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.once('error',error=>finish(error));child.once('exit',code=>{if(code!==0)return finish(new Error(`database maintenance failed (${code}): ${err.slice(-300)}`));try{finish(null,JSON.parse(out));}catch{finish(new Error('database maintenance returned invalid output'));}});});}
function createDatabaseManager({userData,databasePath,executable,stopSidecar,startSidecar,reload,showOpenDialog,reveal,spawn=defaultSpawn,retention=20,fault=()=>{},reportStage=()=>{}}){
 const backupsDir=path.join(userData,'backups'),liveDir=path.dirname(databasePath);let operation=null,recoveryRequired=false;
 const stage=name=>{reportStage(name);fault(name);};
 const maintenance=(flag,file,env)=>run(executable,[flag,file],env,spawn),hit=stage;
 async function gate(file){if(/^\\\\/.test(file))throw new Error('network database paths are not allowed');if(!EXTENSIONS.has(path.extname(file).toLowerCase()))throw new Error('unsupported database extension');const stat=await fs.promises.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1)throw new Error('database must be a single-link regular file');const real=await fs.promises.realpath(file),liveReal=await fs.promises.realpath(databasePath).catch(()=>path.resolve(databasePath)),live=await fs.promises.stat(databasePath).catch(()=>null);if(real===liveReal||(live&&stat.dev===live.dev&&stat.ino===live.ino))throw new Error('source is active database');await maintenance('--validate-db',real);return real;}
 async function fsyncDir(dir){if(process.platform==='win32')return {directoryFsync:'unsupported-windows-best-effort'};const h=await fs.promises.open(dir,'r');try{hit('before-directory-fsync');await h.sync();hit('after-directory-fsync');}finally{await h.close();}return {directoryFsync:true};}
 function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}
 async function snapshot(source,destination,label='source-snapshot'){hit(`before-${label}`);const meta=await maintenance('--validated-snapshot-db',source,{GROWTHMAP_MAINTENANCE_DESTINATION:destination});hit(`after-${label}`);return meta;}
 async function writeManifest(dbFile,meta){const manifest={format:'growthmap-backup-v1',createdAt:new Date().toISOString(),file:path.basename(dbFile),size:meta.size,projects:meta.counts.projects,sha256:meta.sha256,durability:meta.durability};const target=`${dbFile}.json`;try{hit('before-manifest');const handle=await fs.promises.open(target,'wx',0o600);try{await handle.writeFile(JSON.stringify(manifest,null,2));hit('before-manifest-fsync');await handle.sync();hit('after-manifest-fsync');}finally{await handle.close();}await fsyncDir(backupsDir);hit('after-manifest');}catch(error){let cleanupFailed=false;for(const file of [target,dbFile])try{await fs.promises.unlink(file);}catch(unlinkError){if(unlinkError.code!=='ENOENT')cleanupFailed=true;}try{await fsyncDir(backupsDir);}catch{cleanupFailed=true;}if(cleanupFailed){recoveryRequired=true;throw new RecoveryRequiredError();}throw error;}return manifest;}
 async function validManaged(){await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const names=await fs.promises.readdir(backupsDir),rows=[];for(const name of names.filter(x=>x.endsWith('.db.json'))){try{if(name!==name.normalize('NFC'))continue;const raw=await fs.promises.readFile(path.join(backupsDir,name),'utf8'),manifest=JSON.parse(raw),keys=Object.keys(manifest).sort(),expected=['createdAt','durability','file','format','projects','sha256','size'].sort();if(JSON.stringify(keys)!==JSON.stringify(expected)||manifest.format!=='growthmap-backup-v1'||typeof manifest.createdAt!=='string'||!Number.isSafeInteger(manifest.size)||manifest.size<0||!Number.isSafeInteger(manifest.projects)||manifest.projects<0||typeof manifest.sha256!=='string'||!/^[0-9a-f]{64}$/.test(manifest.sha256))continue;if(typeof manifest.file!=='string'||manifest.file!==manifest.file.normalize('NFC')||manifest.file!==path.basename(manifest.file)||manifest.file.includes('/')||manifest.file.includes('\\\\')||!OWNED_BACKUP.test(manifest.file)||name!==`${manifest.file}.json`)continue;const file=path.resolve(backupsDir,manifest.file);if(path.dirname(file)!==path.resolve(backupsDir))continue;const stat=await fs.promises.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size!==manifest.size)continue;const meta=await maintenance('--validate-db',file);if(meta.counts.projects!==manifest.projects||meta.sha256!==manifest.sha256)continue;rows.push({...manifest,id:manifest.file});}catch{}}return rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
 async function prune(){for(const row of (await validManaged()).slice(retention)){await fs.promises.unlink(path.join(backupsDir,row.file)).catch(()=>{});await fs.promises.unlink(path.join(backupsDir,`${row.file}.json`)).catch(()=>{});}}
 async function backupInternal(prefix='backup'){await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const file=path.join(backupsDir,`${prefix}-${stamp()}-${crypto.randomUUID()}.db`);const meta=await snapshot(databasePath,file,'live-backup');await writeManifest(file,meta);await prune();return meta;}
 async function recoverStartup(){await fs.promises.mkdir(liveDir,{recursive:true});const names=await fs.promises.readdir(liveDir),olds=names.filter(x=>OWNED_OLD.test(x)).map(x=>path.join(liveDir,x)),news=names.filter(x=>OWNED_NEW.test(x)).map(x=>path.join(liveDir,x)),validOld=[];for(const file of olds){try{await maintenance('--validate-db',file);validOld.push(file);}catch{}}let liveValid=false,recovered=false;if(fs.existsSync(databasePath)){try{await maintenance('--validate-db',databasePath);liveValid=true;}catch{liveValid=false;}if(!liveValid){if(validOld.length!==1)throw new RecoveryRequiredError();const corrupt=`${databasePath}.gm-corrupt-${crypto.randomUUID()}`;await fs.promises.rename(databasePath,corrupt);try{await fs.promises.rename(validOld[0],databasePath);await fsyncDir(liveDir);await maintenance('--validate-db',databasePath);}catch{recoveryRequired=true;throw new RecoveryRequiredError();}return {recovered:true,evidenceRetained:true};}}else if(validOld.length===1){await fs.promises.rename(validOld[0],databasePath);await fsyncDir(liveDir);await maintenance('--validate-db',databasePath);liveValid=true;recovered=true;}else if(olds.length||news.length)throw new RecoveryRequiredError();else return {recovered:false};if(liveValid){for(const file of [...olds,...news].filter(x=>fs.existsSync(x))){const suffix=`.quarantine-${Date.now()}-${crypto.randomUUID()}`;await fs.promises.rename(file,`${file}${suffix}`);}if(olds.length||news.length)await fsyncDir(liveDir);return {recovered,residuesQuarantined:olds.length+news.length};}throw new RecoveryRequiredError();}
 async function offline(action,reloadAfter=false){if(operation)throw new Error('database operation already in progress');if(recoveryRequired)throw new RecoveryRequiredError();operation=(async()=>{let stopped=false,success=false,result,primaryError=null;try{stage('before-stop');await stopSidecar();stopped=true;stage('after-stop');result=await action();success=true;}catch(error){primaryError=error;}if(stopped){try{stage('before-sidecar-restart');await startSidecar();stage('after-sidecar-restart');}catch(error){recoveryRequired=true;throw new RecoveryRequiredError();}}if(primaryError)throw primaryError;if(success&&reloadAfter){stage('before-reload');await reload();stage('after-reload');}return result;})().finally(()=>{operation=null;});return operation;}
 async function replaceFrom(source){return offline(async()=>{await fs.promises.mkdir(backupsDir,{recursive:true,mode:0o700});const rollback=path.join(backupsDir,`rollback-${stamp()}-${crypto.randomUUID()}.db`),id=crypto.randomUUID(),old=path.join(liveDir,`${path.basename(databasePath)}.gm-old-${id}`),staging=path.join(liveDir,`${path.basename(databasePath)}.gm-new-${id}`);let oldMoved=false,newMoved=false;try{const previous=await snapshot(databasePath,rollback,'rollback-snapshot');await writeManifest(rollback,previous);await snapshot(source,staging,'source-snapshot');await maintenance('--validate-db',staging);hit('before-old-rename');await fs.promises.rename(databasePath,old);oldMoved=true;hit('after-old-rename');hit('before-staging-rename');await fs.promises.rename(staging,databasePath);newMoved=true;hit('after-staging-rename');await fsyncDir(liveDir);hit('before-final-validate');await maintenance('--validate-db',databasePath);hit('after-final-validate');await fs.promises.unlink(old);oldMoved=false;return {ok:true};}catch(error){if(oldMoved){try{if(newMoved)await fs.promises.rename(databasePath,`${staging}.failed-${Date.now()}`);hit('before-rollback-rename');await fs.promises.rename(old,databasePath);oldMoved=false;hit('after-rollback-rename');await fsyncDir(liveDir);}catch{recoveryRequired=true;throw new RecoveryRequiredError();}}throw error;}finally{if(!oldMoved)await fs.promises.unlink(staging).catch(()=>{});}},true);}
 async function status(){const meta=await maintenance('--validate-db',databasePath),list=await validManaged();return {basename:path.basename(databasePath),size:meta.size,projects:meta.counts.projects,lastBackup:list[0]?.createdAt||null,busy:Boolean(operation)};}
 async function importDatabase(){if(operation)throw new Error('database operation already in progress');let picked;picked=await showOpenDialog({properties:['openFile'],filters:[{name:'SQLite database',extensions:['db','sqlite','sqlite3']}]});if(picked.canceled)return null;return replaceFrom(await gate(picked.filePaths[0]));}
 async function backup(){return offline(async()=>{const meta=await backupInternal();return {ok:true,projects:meta.counts.projects};},true);}
 async function restore(id){if(operation)throw new Error('database operation already in progress');if(typeof id!=='string'||!OWNED_BACKUP.test(id))throw new Error('invalid backup id');const item=(await validManaged()).find(x=>x.id===id);if(!item)throw new Error('backup is not app-managed or has changed');return replaceFrom(path.join(backupsDir,item.file));}
 async function list(){return (await validManaged()).map(({id,createdAt,size,projects,sha256})=>({id,createdAt,size,projects,sha256}));}
 async function awaitIdle(){if(operation)await operation.catch(()=>{});}
 return {status,importDatabase,backup,restore,list,recoverStartup,awaitIdle,get busy(){return Boolean(operation);},reveal:()=>reveal(backupsDir),safeMessage:error=>safeMessage(error)};
}
module.exports={createDatabaseManager,run,safeMessage,RecoveryRequiredError};
