'use strict';
const fs=require('node:fs'),path=require('node:path');
function samePath(left,right,isWindows){const normalize=value=>{let raw=String(value).replaceAll('\\','/');if(isWindows){if(raw.toLowerCase().startsWith('//?/unc/'))raw=`//${raw.slice(8)}`;else if(raw.startsWith('//?/'))raw=raw.slice(4);return path.win32.resolve(raw).replaceAll('\\','/').toLowerCase();}return path.resolve(raw).replaceAll('\\','/');};return normalize(left)===normalize(right);}
function windowsStable(opened,linked){const comparable=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&a!==0&&b!==0;return opened.size===linked.size&&opened.mtimeMs===linked.mtimeMs&&opened.birthtimeMs===linked.birthtimeMs&&(!comparable(opened.dev,linked.dev)||opened.dev===linked.dev)&&(!comparable(opened.ino,linked.ino)||opened.ino===linked.ino);}
function readStableRegularFile(file,{maxBytes=65536,fsImpl=fs}={}){
 const hasNoFollow=Number.isInteger(fs.constants.O_NOFOLLOW)&&fs.constants.O_NOFOLLOW!==0,isWindows=process.platform==='win32';
 // Windows has no O_NOFOLLOW and may not expose matching nonzero inode/device
 // values for path and handle stats. Resolve before/after open and compare the
 // stable metadata it does expose. The signed license or safeStorage-encrypted
 // identity remains the content-authenticity boundary.
 if(!hasNoFollow){const before=fsImpl.lstatSync(file);if(before.isSymbolicLink()||!before.isFile()||(!isWindows&&before.nlink!==1))throw Error('unsafe file');const real=fsImpl.realpathSync.native?fsImpl.realpathSync.native(file):fsImpl.realpathSync(file);if(!samePath(real,file,isWindows))throw Error('unsafe file');}
 const fd=fsImpl.openSync(file,fs.constants.O_RDONLY|(hasNoFollow?fs.constants.O_NOFOLLOW:0));try{const st=fsImpl.fstatSync(fd);if(!st.isFile()||(!isWindows&&st.nlink!==1)||st.size<0||st.size>maxBytes)throw Error('unsafe file');const data=Buffer.alloc(st.size);let offset=0;while(offset<st.size){const count=fsImpl.readSync(fd,data,offset,st.size-offset,offset);if(count<=0)throw Error('short read');offset+=count;}const after=fsImpl.fstatSync(fd),linked=fsImpl.lstatSync(file),real=fsImpl.realpathSync.native?fsImpl.realpathSync.native(file):fsImpl.realpathSync(file);const stable=isWindows?windowsStable(after,linked):(after.dev===st.dev&&after.ino===st.ino&&after.size===st.size&&after.nlink===1&&linked.dev===after.dev&&linked.ino===after.ino&&linked.size===after.size&&linked.nlink===1);if(data.length!==st.size||!linked.isFile()||linked.isSymbolicLink()||!samePath(real,file,isWindows)||!stable)throw Error('unstable file');return data;}finally{fsImpl.closeSync(fd);}}
module.exports={readStableRegularFile,samePath,windowsStable};
