'use strict';
const {app,BrowserWindow,ipcMain,safeStorage,dialog,session}=require('electron');
const {spawn}=require('node:child_process'); const crypto=require('node:crypto'); const fs=require('node:fs'); const net=require('node:net'); const path=require('node:path'); const http=require('node:http');
const {createSecretStore}=require('./secret-store');
let sidecar=null,mainWindow=null,baseUrl='',shuttingDown=false; const token=crypto.randomBytes(32).toString('base64url');
if(!app.requestSingleInstanceLock()) app.quit();
app.on('second-instance',()=>{if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus();}});
function secure(){if(!safeStorage.isEncryptionAvailable())throw new Error('Secure key storage is unavailable. GrowthMap refuses to store an API key.');}
function api(method,route,body){return new Promise((resolve,reject)=>{const q=http.request(`${baseUrl}${route}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>{if(r.statusCode>=200&&r.statusCode<300)return resolve(d);const e=new Error(`Sidecar request failed (${r.statusCode})`);e.statusCode=r.statusCode;reject(e);});});q.on('error',()=>reject(new Error('Sidecar is unavailable')));if(body)q.write(JSON.stringify(body));q.end();});}
function guard(event){const expected=mainWindow&&mainWindow.webContents;if(!expected||event.sender!==expected||event.sender.id!==expected.id)throw new Error('Unauthorized desktop IPC sender');const frameUrl=event.senderFrame&&event.senderFrame.url;let origin;try{origin=new URL(frameUrl).origin;}catch{}if(origin!==baseUrl)throw new Error('Unauthorized desktop IPC origin');}
function makeStore(){secure();return createSecretStore({directory:path.join(app.getPath('userData'),'secrets'),encrypt:v=>safeStorage.encryptString(v),decrypt:b=>safeStorage.decryptString(b),putRemote:(id,v)=>api('PUT',`/api/desktop/secrets/${encodeURIComponent(id)}`,{api_key:v}),deleteRemote:id=>api('DELETE',`/api/desktop/secrets/${encodeURIComponent(id)}`),warn:m=>{if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send('desktop:warning',m);}});}
function ipc(store){ipcMain.handle('secrets:has',(e,id)=>{guard(e);return store.has(id);});ipcMain.handle('secrets:set',(e,id,value)=>{guard(e);return store.set(id,value);});ipcMain.handle('secrets:delete',(e,id)=>{guard(e);return store.delete(id);});ipcMain.handle('license:import',async e=>{guard(e);const c=await dialog.showOpenDialog(mainWindow,{properties:['openFile'],filters:[{name:'GrowthMap License',extensions:['json']}]});if(c.canceled)return null;let document;try{document=JSON.parse(fs.readFileSync(c.filePaths[0],'utf8'));}catch{throw new Error('The selected license file is not valid JSON');}return JSON.parse(await api('POST','/api/desktop/license/import',{document}));});}
function reservePort(){return new Promise((ok,no)=>{const s=net.createServer();s.on('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p));});});}
function executable(){if(app.isPackaged)return path.join(process.resourcesPath,'sidecar',process.platform==='win32'?'growthmap-sidecar.exe':'growthmap-sidecar');return process.env.GROWTHMAP_SIDECAR||path.join(__dirname,'..','src','backend','dist',process.platform==='win32'?'growthmap-sidecar.exe':'growthmap-sidecar');}
function waitReady(child){return new Promise((resolve,reject)=>{let done=false,attempts=0;const timer=setInterval(async()=>{if(done)return;try{await api('GET','/api/health/deep');done=true;clearInterval(timer);resolve();}catch{if(++attempts>=100){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar readiness timed out'));}}},150);child.once('exit',()=>{if(!done){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar exited before readiness'));}});child.once('error',()=>{if(!done){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar could not be started'));}});});}
async function startSidecar(){for(let attempt=1;attempt<=3;attempt++){const p=await reservePort();baseUrl=`http://127.0.0.1:${p}`;const env={...process.env,GROWTHMAP_DESKTOP_MODE:'1',GROWTHMAP_SESSION_TOKEN:token,GROWTHMAP_PORT:String(p),DATABASE_URL:`sqlite+aiosqlite:///${path.join(app.getPath('userData'),'growthmap.db')}`,GROWTHMAP_LICENSE_FILE:path.join(app.getPath('userData'),'license.json'),GROWTHMAP_STATIC_DIR:app.isPackaged?path.join(process.resourcesPath,'frontend'):path.join(__dirname,'..','src','frontend','out')};delete env.GROWTHMAP_ENV_FILE;const child=spawn(executable(),[],{env,stdio:['ignore','ignore','ignore'],windowsHide:true});sidecar=child;try{await waitReady(child);child.once('exit',()=>{if(!shuttingDown){dialog.showErrorBox('GrowthMap stopped','The local service stopped unexpectedly. GrowthMap will close to protect your data.');if(mainWindow&&!mainWindow.isDestroyed())mainWindow.destroy();app.quit();}});return;}catch{try{child.kill();}catch{}sidecar=null;if(attempt===3)throw new Error('GrowthMap local service could not start after 3 attempts');}}}
async function launch(){await startSidecar();session.defaultSession.webRequest.onBeforeSendHeaders({urls:[`${baseUrl}/*`]},(d,cb)=>{d.requestHeaders.Authorization=`Bearer ${token}`;cb({requestHeaders:d.requestHeaders});});session.defaultSession.webRequest.onHeadersReceived({urls:[`${baseUrl}/*`]},(d,cb)=>{const h=d.responseHeaders||{};h['Content-Security-Policy']=["default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"];cb({responseHeaders:h});});mainWindow=new BrowserWindow({width:1280,height:820,show:false,webPreferences:{preload:path.join(__dirname,'preload.js'),nodeIntegration:false,contextIsolation:true,sandbox:true}});mainWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));mainWindow.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith(`${baseUrl}/`))e.preventDefault();});const store=makeStore();await store.hydrate();ipc(store);await mainWindow.loadURL(baseUrl);mainWindow.show();}
app.whenReady().then(launch).catch(e=>{dialog.showErrorBox('GrowthMap could not start',e.message);app.quit();});app.on('window-all-closed',()=>app.quit());app.on('before-quit',()=>{shuttingDown=true;if(sidecar&&!sidecar.killed)sidecar.kill();});
module.exports={guard};
