'use strict';
const {app,BrowserWindow,ipcMain,safeStorage,dialog,session,Menu}=require('electron');
const {spawn}=require('node:child_process'); const crypto=require('node:crypto'); const fs=require('node:fs'); const net=require('node:net'); const path=require('node:path'); const http=require('node:http');
const {createSecretStore}=require('./secret-store'); const {loadManifest,policy}=require('./csp'); const {createLifecycle,spawnOptions}=require('./lifecycle'); const {createDatabaseManager}=require('./database-manager'); const {createRequestPolicy}=require('./request-policy');
let mainWindow=null,baseUrl='',rendererReady=false,databaseManager=null; const token=crypto.randomBytes(32).toString('base64url'); const lifecycle=createLifecycle();
if(!app.requestSingleInstanceLock()) app.quit();
app.on('second-instance',()=>{if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus();}});
function secure(){if(!safeStorage.isEncryptionAvailable())throw new Error('Secure key storage is unavailable. GrowthMap refuses to store an API key.');}
function api(method,route,body){return new Promise((resolve,reject)=>{const q=http.request(`${baseUrl}${route}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>{if(r.statusCode>=200&&r.statusCode<300)return resolve(d);const e=new Error(`Sidecar request failed (${r.statusCode})`);e.statusCode=r.statusCode;reject(e);});});q.on('error',()=>reject(new Error('Sidecar is unavailable')));if(body)q.write(JSON.stringify(body));q.end();});}
function guard(event){if(!lifecycle.acceptingIpc)throw new Error('Application is shutting down');const expected=mainWindow&&mainWindow.webContents;if(!expected||event.sender!==expected||event.sender.id!==expected.id)throw new Error('Unauthorized desktop IPC sender');const frameUrl=event.senderFrame&&event.senderFrame.url;let origin;try{origin=new URL(frameUrl).origin;}catch{}if(origin!==baseUrl)throw new Error('Unauthorized desktop IPC origin');}
function makeStore(){secure();return createSecretStore({directory:path.join(app.getPath('userData'),'secrets'),encrypt:v=>safeStorage.encryptString(v),decrypt:b=>safeStorage.decryptString(b),putRemote:(id,v)=>api('PUT',`/api/desktop/secrets/${encodeURIComponent(id)}`,{api_key:v}),deleteRemote:id=>api('DELETE',`/api/desktop/secrets/${encodeURIComponent(id)}`),warn:m=>{if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send('desktop:warning',m);}});}
function ipc(store){ipcMain.handle('secrets:has',(e,id)=>{guard(e);return store.has(id);});ipcMain.handle('secrets:set',(e,id,value)=>{guard(e);return store.set(id,value);});ipcMain.handle('secrets:delete',(e,id)=>{guard(e);return store.delete(id);});ipcMain.handle('license:import',async e=>{guard(e);const c=await dialog.showOpenDialog(mainWindow,{properties:['openFile'],filters:[{name:'GrowthMap License',extensions:['json']}]});if(c.canceled)return null;let document;try{document=JSON.parse(fs.readFileSync(c.filePaths[0],'utf8'));}catch{throw new Error('The selected license file is not valid JSON');}return JSON.parse(await api('POST','/api/desktop/license/import',{document}));});for(const [channel,method] of Object.entries({'database:status':'status','database:import':'importDatabase','database:backup':'backup','database:list-backups':'list','database:restore':'restore','database:reveal':'reveal'}))ipcMain.handle(channel,async(e,...args)=>{guard(e);if(databaseManager.busy&&method!=='status')throw new Error('資料庫操作進行中。');try{return await databaseManager[method](...args);}catch(error){diagnostic('database',error.message);throw new Error(databaseManager.safeMessage(error));}});}
function reservePort(){return new Promise((ok,no)=>{const s=net.createServer();s.on('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p));});});}
function executable(){if(app.isPackaged)return path.join(process.resourcesPath,'sidecar',process.platform==='win32'?'growthmap-sidecar.exe':'growthmap-sidecar');return process.env.GROWTHMAP_SIDECAR||path.join(__dirname,'..','src','backend','dist',process.platform==='win32'?'growthmap-sidecar.exe':'growthmap-sidecar');}
function waitReady(child){return new Promise((resolve,reject)=>{let done=false,attempts=0;const timer=setInterval(async()=>{if(done)return;try{await api('GET','/api/health/deep');done=true;clearInterval(timer);resolve();}catch{if(++attempts>=100){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar readiness timed out'));}}},150);child.once('exit',()=>{if(!done){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar exited before readiness'));}});child.once('error',()=>{if(!done){done=true;clearInterval(timer);reject(new Error('GrowthMap sidecar could not be started'));}});});}
async function startSidecar(){for(let attempt=1;attempt<=3;attempt++){const p=await reservePort();baseUrl=`http://127.0.0.1:${p}`;const env={...process.env,GROWTHMAP_DESKTOP_MODE:'1',GROWTHMAP_SESSION_TOKEN:token,GROWTHMAP_PORT:String(p),DATABASE_URL:`sqlite+aiosqlite:///${path.join(app.getPath('userData'),'growthmap.db')}`,GROWTHMAP_LICENSE_FILE:path.join(app.getPath('userData'),'license.json'),GROWTHMAP_STATIC_DIR:app.isPackaged?path.join(process.resourcesPath,'frontend'):path.join(__dirname,'..','src','frontend','out')};delete env.GROWTHMAP_ENV_FILE;delete env.GROWTHMAP_E2E_DEBUG_PORT;const child=lifecycle.attach(spawn(executable(),[],{env,...spawnOptions()}));try{await waitReady(child);child.once('exit',()=>{if(!lifecycle.shuttingDown&&!lifecycle.isExpectedExit(child)){dialog.showErrorBox('GrowthMap stopped','The local service stopped unexpectedly. GrowthMap will close to protect your data.');if(mainWindow&&!mainWindow.isDestroyed())mainWindow.destroy();app.quit();}});return;}catch{await lifecycle.cleanup(child);if(attempt===3)throw new Error('GrowthMap local service could not start after 3 attempts');}}}
function diagnostic(kind,detail){const clean=String(detail||'').replace(/(authorization|bearer|api[_-]?key|token|secret)[^\s,;]*/gi,'[redacted]').slice(0,1000);console.error(`[renderer:${kind}] ${clean}`);}
async function rendererError(message){if(!mainWindow||mainWindow.isDestroyed()||rendererReady)return;diagnostic('fatal',message);await mainWindow.webContents.executeJavaScript(`document.documentElement.innerHTML=${JSON.stringify('<head><title>GrowthMap — startup error</title><style>body{background:#0b1120;color:#e5e7eb;font:16px system-ui;padding:48px}main{max-width:720px;margin:auto}h1{color:#fca5a5}code{color:#93c5fd}</style></head><body><main><h1>GrowthMap could not display its interface</h1><p>The renderer failed to load. Close and reopen GrowthMap. If this continues, attach the desktop CI/log diagnostics to a support report.</p><code>Renderer startup failed</code></main></body>')}`).catch(()=>{});mainWindow.show();}
async function launch(){const userData=app.getPath('userData'),databasePath=path.join(userData,'growthmap.db');databaseManager=createDatabaseManager({userData,databasePath,executable:executable(),stopSidecar:()=>lifecycle.cleanup(),startSidecar,reload:async()=>{rendererReady=false;if(mainWindow&&!mainWindow.isDestroyed())await mainWindow.loadURL(baseUrl);},showOpenDialog:options=>dialog.showOpenDialog(mainWindow,options),reveal:folder=>require('electron').shell.openPath(folder),reportStage:name=>diagnostic('database-stage',name)});await databaseManager.recoverStartup();await startSidecar();const manifest=loadManifest(path.join(__dirname,'generated','csp-script-hashes.json')),csp=policy(manifest),requests=createRequestPolicy({getBaseUrl:()=>baseUrl,token,csp});session.defaultSession.webRequest.onBeforeSendHeaders(requests.filter,(d,cb)=>cb(requests.before(d)));session.defaultSession.webRequest.onHeadersReceived(requests.filter,(d,cb)=>cb(requests.headers(d)));Menu.setApplicationMenu(null);mainWindow=new BrowserWindow({title:'GrowthMap',width:1280,height:820,show:false,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),nodeIntegration:false,contextIsolation:true,sandbox:true}});mainWindow.setMenu(null);mainWindow.on('close',e=>{if(databaseManager?.busy&&!lifecycle.shuttingDown){e.preventDefault();mainWindow.webContents.send('desktop:warning','資料庫操作進行中，完成後即可關閉。');}});mainWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));mainWindow.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith(`${baseUrl}/`))e.preventDefault();});mainWindow.webContents.on('did-fail-load',(_e,code,description,url,isMainFrame)=>{if(isMainFrame){diagnostic('did-fail-load',`${code} ${description} ${new URL(url).pathname}`);rendererError('main frame load failed');}});mainWindow.webContents.on('render-process-gone',(_e,details)=>{diagnostic('render-process-gone',`${details.reason} ${details.exitCode}`);rendererError('render process exited');});mainWindow.webContents.on('console-message',(_e,level,message,line,source)=>{if(level>=2){const fingerprint=crypto.createHash('sha256').update(String(message)).digest('hex').slice(0,12);diagnostic('console',`level=${level} fingerprint=${fingerprint} at ${path.basename(source||'renderer')}:${line}`);}});mainWindow.webContents.on('did-finish-load',()=>{setTimeout(async()=>{try{rendererReady=await mainWindow.webContents.executeJavaScript(`Boolean(document.querySelector('[data-testid="growthmap-title"]')&&document.querySelector('[data-testid="new-project-button"]')&&document.querySelector('[data-testid="entitlement-status"]')&&document.querySelector('link[rel="stylesheet"]')&&getComputedStyle(document.body).display!=='none')`);if(rendererReady){mainWindow.show();}else await rendererError('required UI markers or stylesheet missing');}catch{await rendererError('renderer readiness probe failed');}},1500);});const store=makeStore();await store.hydrate();ipc(store);await mainWindow.loadURL(baseUrl);}
function orderlyShutdown(){if(databaseManager?.busy)return databaseManager.awaitIdle().then(orderlyShutdown);return lifecycle.shutdown(()=>{if(mainWindow&&!mainWindow.isDestroyed())mainWindow.destroy();}).finally(()=>app.quit());}
app.whenReady().then(launch).catch(e=>{diagnostic('startup',e.message);dialog.showErrorBox('GrowthMap could not start',e.message);orderlyShutdown();});app.on('window-all-closed',orderlyShutdown);app.on('before-quit',e=>{if(!lifecycle.shuttingDown){e.preventDefault();orderlyShutdown();}});app.on('will-quit',()=>{ipcMain.removeAllListeners();});
module.exports={guard,orderlyShutdown};
