'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const UUID='[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}';
const BACKUP=new RegExp(`^(backup|rollback)-\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-\\d{3}Z-${UUID}\\.db$`,'i');
const MANIFEST_KEYS=['format','createdAt','file','size','projects','sha256','durability'];
function exact(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('\0')===keys.slice().sort().join('\0');}
function validTimestamp(value){if(typeof value!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?(?:Z|[+-]\d\d:\d\d)$/.test(value))return false;const time=Date.parse(value);return Number.isFinite(time)&&new Date(time).toISOString().slice(0,19)===new Date(value).toISOString().slice(0,19);}
function validDurability(value){return exact(value,['fileFsync','directoryFsync'])&&value.fileFsync===true&&value.directoryFsync===true||exact(value,['fileFlush','directoryFlush'])&&value.fileFlush==='FlushFileBuffers'&&value.directoryFlush==='unsupported-windows-best-effort';}
function validateManifest(value,{expectedFile}={}){if(!exact(value,MANIFEST_KEYS)||value.format!=='growthmap-backup-v1'||!validTimestamp(value.createdAt)||typeof value.file!=='string'||value.file!==value.file.normalize('NFC')||value.file!==path.basename(value.file)||!BACKUP.test(value.file)||(expectedFile&&value.file!==expectedFile)||!Number.isSafeInteger(value.size)||value.size<100||!Number.isSafeInteger(value.projects)||value.projects<0||typeof value.sha256!=='string'||!/^[0-9a-f]{64}$/.test(value.sha256)||!validDurability(value.durability))throw Error('invalid managed backup manifest');return value;}
function identity(stat){return {dev:stat.dev,ino:stat.ino,size:stat.size,mtimeMs:stat.mtimeMs};}
function same(a,b){return a.dev===b.dev&&a.ino===b.ino&&a.size===b.size&&a.mtimeMs===b.mtimeMs;}
function openStable(file){const flags=fs.constants.O_RDONLY|(fs.constants.O_NOFOLLOW||0),fd=fs.openSync(file,flags),before=fs.fstatSync(fd);if(!before.isFile()||before.isSymbolicLink?.()||before.nlink!==1){fs.closeSync(fd);throw Error('managed evidence must be a single-link regular file');}return {fd,before};}
function readAll(fd,limit=1024*1024){const chunks=[],buffer=Buffer.alloc(65536);let total=0;for(let offset=0;;){const n=fs.readSync(fd,buffer,0,buffer.length,offset);if(!n)break;total+=n;if(total>limit)throw Error('managed evidence is too large');chunks.push(Buffer.from(buffer.subarray(0,n)));offset+=n;}return Buffer.concat(chunks);}
function verifyPathStable(file,opened){const after=fs.fstatSync(opened.fd),linked=fs.lstatSync(file);if(!same(identity(opened.before),identity(after))||!same(identity(after),identity(linked))||!linked.isFile()||linked.isSymbolicLink()||linked.nlink!==1)throw Error('managed evidence changed while validating');return after;}
function verifyManagedBackup(userData,backupId,{expected}={}){const dir=path.resolve(userData,'backups');if(typeof backupId!=='string'||!BACKUP.test(backupId))throw Error('invalid managed backup id');const file=path.resolve(dir,backupId),manifestFile=`${file}.json`;if(path.dirname(file)!==dir)throw Error('backup path escapes managed directory');const db=openStable(file),mf=openStable(manifestFile);try{const manifest=validateManifest(JSON.parse(readAll(mf.fd).toString('utf8')),{expectedFile:backupId});const hash=crypto.createHash('sha256'),buffer=Buffer.alloc(1024*1024);for(let offset=0;;){const n=fs.readSync(db.fd,buffer,0,buffer.length,offset);if(!n)break;hash.update(buffer.subarray(0,n));offset+=n;}const dbStat=verifyPathStable(file,db);verifyPathStable(manifestFile,mf);if(dbStat.size!==manifest.size||hash.digest('hex')!==manifest.sha256)throw Error('managed backup hash or size mismatch');if(expected&&(manifest.size!==expected.size||manifest.sha256!==expected.sha256))throw Error('managed backup does not match evidence');return {...manifest,id:backupId};}finally{fs.closeSync(db.fd);fs.closeSync(mf.fd);}}
function listManagedBackups(userData){const dir=path.join(userData,'backups');let names;try{names=fs.readdirSync(dir);}catch(error){if(error.code==='ENOENT')return [];throw error;}const rows=[];for(const name of names.filter(x=>x.endsWith('.db.json'))){try{rows.push(verifyManagedBackup(userData,name.slice(0,-5)));}catch{}}return rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
module.exports={BACKUP,validateManifest,verifyManagedBackup,listManagedBackups,validTimestamp,validDurability};
