'use strict';
const path=require('node:path'),crypto=require('node:crypto'),{secureFiles}=require('./secure-files'),{validateAuthorityPayload,exactKeys}=require('./authority-schema');
const NAME='replacement-intent.bin',MAX=64*1024,TERMINAL=new Set(['cleanup-durable','rollback-durable','aborted-durable']),PHASES=new Set(['intent','db-installed','authority-saved','committed','cleanup','rollback-live-moved','rollback-old-live','rollback-db-durable','rollback-authority-durable','cleanup-old-moved','cleanup-durable','rollback-durable','aborted-durable']);
const canonical=JSON.stringify,plain=v=>v&&typeof v==='object'&&!Array.isArray(v);
function validEvidence(v,nullable=false){if(nullable&&v===null)return true;return plain(v)&&Object.keys(v).length===2&&Object.prototype.hasOwnProperty.call(v,'sha256')&&Object.prototype.hasOwnProperty.call(v,'size')&&typeof v.sha256==='string'&&/^[0-9a-f]{64}$/.test(v.sha256)&&Number.isSafeInteger(v.size)&&v.size>=0}
function validAuthority(v,nullable=false){if(nullable&&v===null)return true;try{return validateAuthorityPayload(v)===v}catch{return false}}
function createReplacementJournal({userData,encrypt,decrypt,io,platform,windowsPolicy,windowsRunner}){
 let verifiedTerminal=null;const rawDigest=()=>crypto.createHash('sha256').update(files.read(NAME)).digest();const root=path.join(userData,'secrets'),files=secureFiles(root,root,io,{platform,windowsPolicy,windowsRunner,maxReadBytes:MAX});
 const validate=v=>{if(!exactKeys(v,['schemaVersion','transitionId','mode','databasePath','oldPath','failedPath','quarantinePath','stagingPath','capturePath','oldEvidence','newEvidence','authorityPre','authorityNew','phase'])||v.schemaVersion!==1||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v.transitionId)||!['managed-restore','foreign-import'].includes(v.mode)||!PHASES.has(v.phase)||!validEvidence(v.oldEvidence)||!validEvidence(v.newEvidence,true)||!validAuthority(v.authorityPre)||!validAuthority(v.authorityNew,true))throw Error('Replacement journal is invalid');const db=path.resolve(v.databasePath),expectedOld=`${db}.gm-old-${v.transitionId}`,expectedFailed=`${db}.gm-failed-${v.transitionId}`,expectedQuarantine=`${db}.gm-old-${v.transitionId}.quarantine`,expectedStaging=`${db}.gm-new-${v.transitionId}`,expectedCapture=`${expectedStaging}.capture`;if(v.databasePath!==db||v.oldPath!==expectedOld||v.failedPath!==expectedFailed||v.quarantinePath!==expectedQuarantine||v.stagingPath!==expectedStaging||v.capturePath!==expectedCapture)throw Error('Replacement journal path is invalid');return v};
 const read=()=>{if(!files.exists(NAME))return null;let value;try{const raw=decrypt(files.read(NAME));if(Buffer.byteLength(raw)>MAX)throw Error();value=JSON.parse(raw)}catch{throw Error('Replacement journal is invalid')}value=validate(value);return value};
 const write=value=>files.write(NAME,Buffer.from(encrypt(canonical(validate(value)))));
 const begin=value=>{const prior=read();if(prior&&!TERMINAL.has(prior.phase))throw Error('Replacement recovery is already pending');if(prior&&(!verifiedTerminal||verifiedTerminal.transitionId!==prior.transitionId||!crypto.timingSafeEqual(verifiedTerminal.digest,rawDigest())))throw Error('Completed replacement requires verified atomic supersession');const id=value.transitionId||crypto.randomUUID(),db=path.resolve(value.databasePath),intent={schemaVersion:1,transitionId:id,mode:value.mode,databasePath:db,oldPath:`${db}.gm-old-${id}`,failedPath:`${db}.gm-failed-${id}`,quarantinePath:`${db}.gm-old-${id}.quarantine`,stagingPath:`${db}.gm-new-${id}`,capturePath:`${db}.gm-new-${id}.capture`,oldEvidence:value.oldEvidence,newEvidence:value.newEvidence,authorityPre:value.authorityPre,authorityNew:null,phase:'intent'};write(intent);return intent};
 const update=(intent,patch)=>{const current=read();if(!current||current.transitionId!==intent.transitionId)throw Error('Replacement journal changed unexpectedly');const next={...current,...patch};write(next);return next};
 const markTerminalVerified=intent=>{if(!TERMINAL.has(intent.phase))throw Error('Replacement terminal proof is invalid');const current=read();if(current.transitionId!==intent.transitionId||current.phase!==intent.phase)throw Error('Replacement terminal proof changed');verifiedTerminal={transitionId:intent.transitionId,digest:rawDigest()}};
 const clear=intent=>{const current=read();if(!current||current.transitionId!==intent.transitionId)throw Error('Replacement journal changed unexpectedly');files.remove(NAME)};
 return {read,begin,update,clear,markTerminalVerified};
}
module.exports={createReplacementJournal};
