'use strict';
const {secureFiles}=require('./secure-files');
const crypto=require('node:crypto');
const MAX_SECRET_CHARS=16384,MAX_SECRET_BYTES=32768,MAX_REVISION=Number.MAX_SAFE_INTEGER;
function staged(message,stage){const error=new Error(message);error.credentialStage=stage;error.code=`CREDENTIAL_${stage.toUpperCase().replaceAll('-','_')}`;return error}
function validSecret(value){return typeof value==='string'&&value.length>0&&value.length<=MAX_SECRET_CHARS&&!value.includes('\0')&&Buffer.byteLength(value,'utf8')<=MAX_SECRET_BYTES}
function createSecretStore({trustedRoot,directory,encrypt,decrypt,putRemote,hydrateRemote=putRemote,deleteRemote,recoverRemote,recoverStatus,warn=()=>{},windowsAdapter=null,platform=process.platform,files=secureFiles(trustedRoot||directory,directory,undefined,{windowsAdapter,platform})}){
 const valid=id=>{if(!/^[A-Za-z0-9-]{1,80}$/.test(id))throw Error('Invalid provider id');return id};
 const bin=id=>`${valid(id)}.bin`,journal=id=>`${valid(id)}.recover`,locks=new Map();
 const serialized=(id,fn)=>{id=valid(id);const prior=locks.get(id)||Promise.resolve(),run=prior.catch(()=>{}).then(fn);locks.set(id,run);return run.finally(()=>{if(locks.get(id)===run)locks.delete(id)})};
 const decode=async(name,label)=>{let value;try{value=JSON.parse(decrypt(await files.read(name)))}catch{throw staged('Credential recovery data is invalid','journal-invalid')}return value};
 const readJournal=async name=>{const value=await decode(name,'journal'),shape=value&&typeof value==='object';if(!shape||![1,2].includes(value.v)||!['set','delete'].includes(value.operation)||typeof value.id!=='string'||journal(value.id)!==name||(value.operation==='set'&&!validSecret(value.value))||(value.operation==='delete'&&Object.hasOwn(value,'value')))throw staged('Credential recovery data is invalid','journal-invalid');if(value.v===1){if(Object.hasOwn(value,'operationId')&&!/^[0-9a-f]{48}$/.test(value.operationId))throw staged('Credential recovery data is invalid','journal-invalid');if(!Number.isSafeInteger(value.revision)||value.revision<1)throw staged('Credential recovery data is invalid','journal-invalid')}else if(!/^[0-9a-f]{48}$/.test(value.operationId)||!Number.isSafeInteger(value.baseRevision)||value.baseRevision<1||value.baseRevision>=MAX_REVISION||value.revision!==value.baseRevision+1)throw staged('Credential recovery data is invalid','journal-invalid');return value};
 const promote=async j=>{try{if(j.operation==='set')await files.write(bin(j.id),encrypt(j.value));else await files.remove(bin(j.id))}catch{throw staged('Credential recovery could not update secure storage','target-promote-failed')}try{await files.remove(journal(j.id))}catch{throw staged('Credential recovery could not finish securely','journal-remove-failed')}};
 const entries=async()=>{let names;try{names=await files.list()}catch{throw staged('Credential recovery data is invalid','journal-invalid')}for(const name of names)if(!/^[A-Za-z0-9-]{1,80}\.(?:bin|recover)$/.test(name))throw staged('Credential recovery data is invalid','journal-invalid');return names};
 const quarantine=async(name,reason)=>{try{await files.quarantine(name)}catch{}warn(`A stored provider key was quarantined (${reason}). Re-enter it in Settings.`)};
 const status=async id=>{let value;try{value=await recoverStatus(id)}catch{throw staged('Credential authority is unavailable','authority-unavailable')}if(!value||!Number.isSafeInteger(value.revision)||value.revision<1||typeof value.secret_change_pending!=='boolean')throw staged('Credential authority is unavailable','authority-unavailable');return value};
 const reconcileOne=async j=>{const state=await status(j.id);if(j.v===1){if(state.revision!==j.revision)throw staged('Credential authority state is ambiguous','authority-ambiguous');if(state.secret_change_pending){try{await recoverRemote(j.id,j.revision,j.operation,j.value,j.operationId)}catch{throw staged('Credential recovery could not be completed securely','remote-recovery-failed')}}else if(state.credential_status!==(j.operation==='set'?'ready':'unavailable'))throw staged('Credential authority state is ambiguous','authority-ambiguous');return promote(j)}if(state.revision===j.baseRevision&&!state.secret_change_pending){try{if(j.operation==='set')await putRemote(j.id,j.value,j.baseRevision,j.operationId);else await deleteRemote(j.id,j.baseRevision,j.operationId)}catch{throw staged('Credential operation could not be dispatched securely','remote-dispatch-failed')}return promote(j)}if(state.revision===j.revision&&state.secret_change_pending&&state.secret_change_operation_id===j.operationId){try{await recoverRemote(j.id,j.revision,j.operation,j.value,j.operationId)}catch{throw staged('Credential recovery could not be completed securely','remote-recovery-failed')}return promote(j)}if(state.revision===j.revision&&!state.secret_change_pending&&state.secret_change_operation_id===j.operationId)return promote(j);throw staged('Credential authority state is ambiguous','authority-ambiguous')};
 const ordinary=(id,operation,value)=>serialized(id,async()=>{id=valid(id);const name=journal(id);if(await files.exists(name))throw Error('Credential recovery must be reconciled before changing this provider');const state=await status(id);if(state.secret_change_pending)throw Error('Credential recovery must be reconciled before changing this provider');if(state.revision>=MAX_REVISION)throw Error('Provider revision capacity is exhausted');const desired={v:2,id,operationId:crypto.randomBytes(24).toString('hex'),baseRevision:state.revision,revision:state.revision+1,operation,...(operation==='set'?{value}:{})};await files.write(name,encrypt(JSON.stringify(desired)));try{await reconcileOne(desired);return true}catch(error){if(error?.credentialStage)throw error;throw staged(operation==='set'?'API key could not be stored securely':'API key could not be removed securely','remote-dispatch-failed')}});
 return{
  has:id=>files.exists(bin(id)),
  async set(id,value){if(!validSecret(value))throw Error('INVALID_PROVIDER_CREDENTIAL');return ordinary(id,'set',value)},
  async delete(id){return ordinary(id,'delete')},
  async recover(id,revision,operation,value,operationId){return serialized(id,async()=>{if(!Number.isSafeInteger(revision)||revision<1||!['set','delete'].includes(operation)||operation==='set'&&!validSecret(value))throw Error('INVALID_PROVIDER_CREDENTIAL');if(operationId!==undefined&&!/^[0-9a-f]{48}$/.test(operationId))throw Error('INVALID_PROVIDER_CREDENTIAL');const name=journal(id),desired={v:1,id:valid(id),revision,operation,...(operationId===undefined?{}:{operationId}),...(operation==='set'?{value}:{})};if(await files.exists(name)){const old=await readJournal(name);if(JSON.stringify(old)!==JSON.stringify(desired))throw Error('A different credential recovery is pending')}else await files.write(name,encrypt(JSON.stringify(desired)));try{await recoverRemote(id,revision,operation,value,operationId)}catch{throw staged('Credential recovery could not be completed securely','remote-recovery-failed')}await promote(desired);return true})},
  async reconcile(){for(const name of (await entries()).filter(n=>n.endsWith('.recover'))){const j=await readJournal(name);await serialized(j.id,()=>reconcileOne(j))}},
  async hydrate(){const names=await entries();if(names.some(n=>n.endsWith('.recover')))throw Error('Credential recovery must be reconciled before hydration');for(const name of names.filter(n=>n.endsWith('.bin'))){const id=name.slice(0,-4);let value;try{value=decrypt(await files.read(name));if(!validSecret(value))throw Error()}catch{await quarantine(name,'corrupt');continue}try{await hydrateRemote(id,value)}catch(error){if(error&&error.statusCode===404){await quarantine(name,'stale provider');continue}throw Error('A stored provider key could not be loaded securely')}}}
 };
}
module.exports={createSecretStore,validSecret,MAX_SECRET_CHARS,MAX_SECRET_BYTES};
