'use strict';
const fs=require('node:fs'),path=require('node:path');
const {validateSecurePathPolicyPayload,validateSecurePathPolicyResult,validateInitializePrivateAclPayload,validateInitializePrivateAclResult,validateSecureReadFilePayload,validateSecureReadFileResult}=require('./windows-native-broker');
const WINDOWS_DIR_FSYNC_UNSUPPORTED=new Set(['EPERM','EINVAL','ENOTSUP','EOPNOTSUPP']);
function createWindowsSecureFilesAdapter({broker,timeoutMs=15000}={}){
 if(!broker)throw Error('Windows native broker unavailable or unsafe');let tail=Promise.resolve();
 const serial=(fn,signal)=>{const run=tail.catch(()=>{}).then(()=>{if(signal?.aborted)throw signal.reason||Error('Windows secure operation aborted');return fn()});tail=run.catch(()=>{});return run};
 const tag=(error,operation,stage)=>{if(error&&['secure-path-policy','secure-read-file','initialize-private-acl'].includes(operation)){Object.defineProperty(error,'nativeOperation',{value:operation,configurable:true});if(error.stage==='response-schema')Object.defineProperty(error,'stage',{value:stage,configurable:true})}return error};
 const request=async(operation,...args)=>{if(typeof broker.request!=='function')throw Error('Windows native broker unavailable or unsafe');try{return await broker.request(operation,...args)}catch(error){throw tag(error,operation,error?.stage)}};
 const validate=(operation,stage,fn)=>{try{return fn()}catch(error){throw tag(error,operation,stage)}};
 const policy=(root,targets,signal)=>serial(async()=>{const payload=validateSecurePathPolicyPayload({root,targets:targets.map(x=>({path:x.path,kind:x.kind,containerPolicy:'private'}))}),result=await request('secure-path-policy',payload,timeoutMs,signal);return validate('secure-path-policy','response-schema-policy',()=>validateSecurePathPolicyResult(payload,result))},signal);
 const readFile=(root,target,maxBytes,signal)=>serial(async()=>{const payload=validateSecureReadFilePayload({root,path:target,maxBytes,containerPolicy:'private'}),result=await request('secure-read-file',payload,timeoutMs,signal);return validate('secure-read-file','response-schema-read',()=>validateSecureReadFileResult(payload,result))},signal);
 const initializePrivateAcl=(root,target,kind='directory',signal)=>serial(async()=>{const payload=validateInitializePrivateAclPayload({root,path:target,kind,containerPolicy:'private'}),result=await request('initialize-private-acl',payload,timeoutMs,signal);validate('initialize-private-acl','response-schema-initialize',()=>validateInitializePrivateAclResult(payload,result));const checkPayload=validateSecurePathPolicyPayload({root,targets:[{path:target,kind,containerPolicy:'private'}]}),checked=await request('secure-path-policy',checkPayload,timeoutMs,signal);return validate('secure-path-policy','response-schema-policy',()=>validateSecurePathPolicyResult(checkPayload,checked))[0]},signal);
 return Object.freeze({policy,readFile,initializePrivateAcl});
}
function identity(s){return `${s.dev}:${s.ino}`}
function bounds(trustedRoot,directory){trustedRoot=path.resolve(trustedRoot);directory=path.resolve(directory);const relative=path.relative(trustedRoot,directory);if(relative==='..'||relative.startsWith(`..${path.sep}`)||path.isAbsolute(relative))throw Error('Secret directory escapes trusted root');return {trustedRoot,directory,relative}}
function secureFiles(trustedRoot,directory,io=fs,options={}){
 if(typeof directory!=='string'){options=io||{};io=directory||fs;directory=trustedRoot;}const b=bounds(trustedRoot,directory);trustedRoot=b.trustedRoot;directory=b.directory;const relative=b.relative;
 if((options.platform||process.platform)==='win32')return secureFilesWindows(trustedRoot,directory,relative,io,options);
 if(typeof process.geteuid!=='function')throw Error('POSIX owner identity unavailable');
 const uid=process.geteuid();
 if(!Number.isSafeInteger(uid)||uid<0)throw Error('POSIX owner identity unavailable');
 const hooks=options.hooks||{},maxReadBytes=options.maxReadBytes||1024*1024,check=(s,kind)=>{if(s.isSymbolicLink()||(kind==='dir'?!s.isDirectory():!s.isFile())||s.uid!==uid||(s.mode&0o077)!==0)throw Error(`Unsafe secret ${kind}`)},verify=(p,kind='dir')=>{const s=io.lstatSync(p);check(s,kind);return s};
 const components=()=>relative?relative.split(path.sep).filter(Boolean):[];const verifyDir=()=>{if(trustedRoot===directory&&!io.existsSync(trustedRoot)){const parent=path.dirname(trustedRoot),before=io.lstatSync(parent);if(before.isSymbolicLink()||!before.isDirectory()||before.uid!==uid||(before.mode&0o022)!==0)throw Error('Unsafe secret container');try{io.mkdirSync(trustedRoot,{mode:0o700})}catch(e){if(e.code!=='EEXIST')throw e}const after=io.lstatSync(parent);if(identity(before)!==identity(after))throw Error('Secret container replaced during initialization');verify(trustedRoot)}let current=trustedRoot;verify(current);for(const component of components()){const parentBefore=verify(current);current=path.join(current,component);try{verify(current)}catch(e){if(e.code!=='ENOENT')throw e;hooks.beforeMkdir?.(current);io.mkdirSync(current,{mode:0o700});const created=verify(current);hooks.afterMkdir?.(current);if(identity(created)!==identity(verify(current)))throw Error('Secret parent replaced during mkdir')}if(identity(parentBefore)!==identity(verify(path.dirname(current))))throw Error('Secret parent replaced during mkdir')}const realRoot=io.realpathSync(trustedRoot),realDir=io.realpathSync(directory),r=path.relative(realRoot,realDir);if(r==='..'||r.startsWith(`..${path.sep}`)||path.isAbsolute(r))throw Error('Secret directory escapes trusted root');return verify(directory)};
 const safe=name=>{if(!/^[A-Za-z0-9-]{1,80}\.(?:bin|recover)$/.test(name))throw Error('Unsafe secret filename');return path.join(directory,name)},stable=(before,stage)=>{hooks[stage]?.(directory);if(identity(before)!==identity(verifyDir()))throw Error('Secret parent replaced')};
 const read=name=>{const parent=verifyDir(),fd=io.openSync(safe(name),io.constants.O_RDONLY|(io.constants.O_NOFOLLOW||0));try{const before=io.fstatSync(fd);check(before,'file');if(before.nlink!==1)throw Error('Unsafe secret file');if(before.size<0||before.size>maxReadBytes)throw Error('Secret file is too large');const data=io.readFileSync(fd),after=io.fstatSync(fd);if(data.length>maxReadBytes)throw Error('Secret file is too large');if(identity(before)!==identity(after)||before.size!==after.size||before.mtimeMs!==after.mtimeMs)throw Error('Unstable secret file');stable(parent,'beforeReadReturn');return data}finally{io.closeSync(fd)}};
 const syncDir=()=>{const parent=verifyDir(),fd=io.openSync(directory,'r');try{io.fsyncSync(fd)}finally{io.closeSync(fd)}stable(parent,'afterDirSync')};
 const write=(name,data)=>{const parent=verifyDir(),target=safe(name),tmp=`${target}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`,fd=io.openSync(tmp,io.constants.O_CREAT|io.constants.O_EXCL|io.constants.O_WRONLY,0o600);try{io.writeFileSync(fd,data);io.fsyncSync(fd)}finally{io.closeSync(fd)}try{stable(parent,'beforeRename');verify(tmp,'file');io.renameSync(tmp,target);stable(parent,'afterRename');verify(target,'file');syncDir()}catch(e){try{io.unlinkSync(tmp)}catch{}throw e}};
 const remove=name=>{const parent=verifyDir(),target=safe(name);try{read(name)}catch(e){if(e.code==='ENOENT')return;throw e}stable(parent,'beforeUnlink');io.unlinkSync(target);stable(parent,'afterUnlink');syncDir()};
 return {verifyDir,read,write,remove,exists:name=>{verifyDir();try{read(name);return true}catch(e){if(e.code==='ENOENT')return false;throw e}},quarantine:name=>{const p=verifyDir();read(name);stable(p,'beforeUnlink');io.unlinkSync(safe(name));stable(p,'afterUnlink');syncDir()},list:()=>{verifyDir();return io.readdirSync(directory)}};
}
function secureFilesWindows(trustedRoot,directory,relative,io,options){
 const adapter=options.windowsAdapter;if(!adapter)throw Error('Windows native broker unavailable or unsafe');const hooks=options.hooks||{},maxReadBytes=options.maxReadBytes||1024*1024,safe=name=>{if(!/^[A-Za-z0-9-]{1,80}\.(?:bin|recover)$/.test(name))throw Error('Unsafe secret filename');return path.join(directory,name)},stat=(p,kind)=>{const s=io.lstatSync(p);if(s.isSymbolicLink()||(kind==='directory'?!s.isDirectory():!s.isFile())||(kind==='file'&&s.nlink!==1))throw Error(`Unsafe secret ${kind}`);return s},policy=async(p,kind,root=trustedRoot)=>{stat(p,kind);return (await adapter.policy(root,[{path:p,kind}]))[0].identity},components=()=>relative?relative.split(path.sep).filter(Boolean):[];
 const verifyDir=async()=>{if(trustedRoot===directory&&!io.existsSync(trustedRoot)){const parent=path.dirname(trustedRoot),before=stat(parent,'directory'),beforeId=await policy(parent,'directory',parent);try{io.mkdirSync(trustedRoot,{mode:0o700})}catch(e){if(e.code==='EEXIST')throw Error('Windows private secret root initialization raced');throw e}await adapter.initializePrivateAcl(trustedRoot,trustedRoot,'directory');const after=stat(parent,'directory'),afterId=await policy(parent,'directory',parent);if(beforeId!==afterId||before.isSymbolicLink()||after.isSymbolicLink())throw Error('Secret container replaced during initialization')}let current=trustedRoot;await policy(current,'directory');for(const part of components()){const parent=current,parentId=await policy(parent,'directory');current=path.join(current,part);try{await policy(current,'directory')}catch(e){if(e.code!=='ENOENT')throw e;hooks.beforeMkdir?.(current);io.mkdirSync(current,{mode:0o700});await adapter.initializePrivateAcl(trustedRoot,current,'directory');const made=await policy(current,'directory');hooks.afterMkdir?.(current);if(made!==await policy(current,'directory'))throw Error('Secret parent replaced during mkdir')}if(parentId!==await policy(parent,'directory'))throw Error('Secret parent replaced during mkdir')}const rr=io.realpathSync(trustedRoot),rd=io.realpathSync(directory),r=path.relative(rr,rd);if(r==='..'||r.startsWith(`..${path.sep}`)||path.isAbsolute(r))throw Error('Secret directory escapes trusted root');return policy(directory,'directory')};
 const stable=async(before,stage)=>{hooks[stage]?.(directory);if(before!==await verifyDir())throw Error('Secret parent replaced')},read=async name=>{const parent=await verifyDir(),target=safe(name),result=await adapter.readFile(trustedRoot,target,maxReadBytes);await stable(parent,'beforeReadReturn');return result.data},syncDir=async()=>{const p=await verifyDir(),fd=io.openSync(directory,'r');try{try{io.fsyncSync(fd)}catch(e){if(!WINDOWS_DIR_FSYNC_UNSUPPORTED.has(e.code))throw e}}finally{io.closeSync(fd)}await stable(p,'afterDirSync')};
 const write=async(name,data)=>{const parent=await verifyDir(),target=safe(name),tmp=`${target}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`,fd=io.openSync(tmp,io.constants.O_CREAT|io.constants.O_EXCL|io.constants.O_WRONLY,0o600);try{io.writeFileSync(fd,data);io.fsyncSync(fd)}finally{io.closeSync(fd)}try{await adapter.initializePrivateAcl(trustedRoot,tmp,'file');await stable(parent,'beforeRename');await policy(tmp,'file');io.renameSync(tmp,target);await stable(parent,'afterRename');await policy(target,'file');await syncDir()}catch(e){try{io.unlinkSync(tmp)}catch{}throw e}},remove=async name=>{const p=await verifyDir(),target=safe(name);try{await read(name)}catch(e){if(e.code==='ENOENT')return;throw e}await stable(p,'beforeUnlink');io.unlinkSync(target);await stable(p,'afterUnlink');await syncDir()};
 return {verifyDir,read,write,remove,exists:async name=>{await verifyDir();try{await read(name);return true}catch(e){if(e.code==='ENOENT')return false;throw e}},quarantine:async name=>{const p=await verifyDir();await read(name);await stable(p,'beforeUnlink');io.unlinkSync(safe(name));await stable(p,'afterUnlink');await syncDir()},list:async()=>{await verifyDir();return io.readdirSync(directory)}};
}
module.exports={secureFiles,createWindowsSecureFilesAdapter,WINDOWS_DIR_FSYNC_UNSUPPORTED};
