'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {listManagedBackups}=require('./managed-backup');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const BACKUP=/^(backup|rollback)-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-\d{3}Z-[0-9a-f-]{36}\.db$/i;
const RESIDUE=/^growthmap\.db\.gm-(old|new|corrupt)-[0-9a-f-]{36}(?:\.quarantine-\d+-[0-9a-f-]{36})?$/i;
function paths(userData){return {secure:path.join(userData,'trial-marker.bin'),identity:path.join(userData,'installation-identity.bin'),state:path.join(userData,'trial-state.json')};}
function exact(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('\0')===keys.slice().sort().join('\0');}
function validIso(value){return typeof value==='string'&&Number.isFinite(Date.parse(value));}
function validDatabase(file){try{const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size<100)return false;const fd=fs.openSync(file,'r'),header=Buffer.alloc(16);try{fs.readSync(fd,header,0,16,0);}finally{fs.closeSync(fd);}return header.toString('binary')==='SQLite format 3\u0000';}catch{return false;}}
function validManagedBackup(userData){try{return listManagedBackups(userData).length>0;}catch{return false;}}
function validJsonMarker(file,kind){try{const value=JSON.parse(fs.readFileSync(file,'utf8'));return value.schemaVersion===1&&value.kind===kind&&typeof value.backupId==='string'&&validIso(value.createdAt);}catch{return false;}}
function hasPriorUse(userData,{decrypt}={}){const p=paths(userData);try{const identity=JSON.parse(decrypt(fs.readFileSync(p.identity)));if(exact(identity,['schemaVersion','kind','installationId','createdAt'])&&identity.schemaVersion===1&&identity.kind==='growthmap-installation-receipt'&&UUID.test(identity.installationId)&&validIso(identity.createdAt))return true;}catch{}
 if(validDatabase(path.join(userData,'growthmap.db'))||validManagedBackup(userData)||validJsonMarker(path.join(userData,'update-pending.json'),'update')||validJsonMarker(path.join(userData,'migration-authorization.json'),'pre-migration-backup'))return true;
 try{return fs.readdirSync(userData).some(name=>RESIDUE.test(name)&&validDatabase(path.join(userData,name)));}catch{return false;}}
function createTrialStore({userData,encrypt,decrypt,now=()=>new Date()}){const p=paths(userData);
 function secureMarker(){try{const value=JSON.parse(decrypt(fs.readFileSync(p.secure)));if(!exact(value,['schemaVersion','installationId','startedAt'])||value.schemaVersion!==1||!UUID.test(value.installationId)||!validIso(value.startedAt))throw Error('invalid');return value;}catch(error){if(error.code==='ENOENT')return null;return {corrupt:true};}}
 function jsonState(){try{const value=JSON.parse(fs.readFileSync(p.state,'utf8'));if(!exact(value,['schema_version','installation_id','started_at','last_seen_at'])||value.schema_version!==1||!UUID.test(value.installation_id)||!validIso(value.started_at)||!validIso(value.last_seen_at))throw Error('invalid');return value;}catch(error){if(error.code==='ENOENT')return null;return {corrupt:true};}}
 function prepare(){const marker=secureMarker(),state=jsonState();if(!marker&&!state&&!hasPriorUse(userData,{decrypt}))return {mode:'fresh',marker:{schemaVersion:1,installationId:crypto.randomUUID(),startedAt:now().toISOString()}};if(!marker&&!state)return {mode:'extraction',reason:'prior_installation_evidence'};if(!marker||!state||marker.corrupt||state.corrupt)return {mode:'extraction',reason:'trial_state_mismatch'};if(marker.installationId!==state.installation_id||Date.parse(marker.startedAt)!==Date.parse(state.started_at))return {mode:'extraction',reason:'trial_state_mismatch'};return {mode:'existing',marker};}
 function commit(marker){if(fs.existsSync(p.secure)||fs.existsSync(p.identity))throw Error('secure installation identity already exists');fs.mkdirSync(userData,{recursive:true,mode:0o700});const receipt={schemaVersion:1,kind:'growthmap-installation-receipt',installationId:marker.installationId,createdAt:now().toISOString()};for(const [target,value] of [[p.identity,receipt],[p.secure,marker]]){const temp=`${target}.${process.pid}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,encrypt(JSON.stringify(value)),{mode:0o600,flag:'wx'});fs.renameSync(temp,target);}}
 return {prepare,commit,read:secureMarker,paths:p};}
module.exports={createTrialStore,paths,hasPriorUse,validDatabase,validManagedBackup};
