$ErrorActionPreference='Stop'
Set-StrictMode -Version 3
$Protocol=1
$MaxLine=65536
[Console]::Error.WriteLine('HELPER_START')
Add-Type -TypeDefinition @'
using System;
using System.IO;
using System.Text;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
public static class GrowthMapBrokerNative {
 const uint OWNER_SECURITY_INFORMATION=0x00000001;
 const uint DACL_SECURITY_INFORMATION=0x00000004;
 const uint READ_CONTROL=0x00020000;
 const uint WRITE_DAC=0x00040000;
 const uint WRITE_OWNER=0x00080000;
 [StructLayout(LayoutKind.Sequential)] public struct FILETIME { public uint Low,High; }
 [StructLayout(LayoutKind.Sequential)] public struct Info { public uint Attributes; public FILETIME Creation,Access,Write; public uint VolumeSerial,SizeHigh,SizeLow,NumberOfLinks,FileIndexHigh,FileIndexLow; }
 [DllImport("kernel32.dll",SetLastError=true)] public static extern bool GetFileInformationByHandle(SafeFileHandle h,out Info i);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)] public static extern uint GetDriveTypeW(string rootPathName);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] public static extern uint GetFileAttributesW(string fileName);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern uint GetFinalPathNameByHandleW(SafeFileHandle h,StringBuilder p,uint n,uint f);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern SafeFileHandle CreateFileW(string p,uint a,uint s,IntPtr x,uint d,uint f,IntPtr t);
 [DllImport("kernel32.dll",SetLastError=true)] static extern bool SetFileInformationByHandle(SafeFileHandle h,int c,IntPtr i,uint n);
 [DllImport("kernel32.dll",SetLastError=true)] static extern bool FlushFileBuffers(SafeFileHandle h);
 [DllImport("advapi32.dll",SetLastError=true)] static extern bool SetKernelObjectSecurity(SafeFileHandle h,uint i,byte[] sd);
 [DllImport("advapi32.dll",SetLastError=true)] static extern bool GetKernelObjectSecurity(SafeFileHandle h,uint i,byte[] sd,uint n,out uint needed);
 public static Info GetInfo(SafeFileHandle h){Info i;if(!GetFileInformationByHandle(h,out i))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return i;}
 public static string FinalPath(SafeFileHandle h){var b=new StringBuilder(32768);uint n=GetFinalPathNameByHandleW(h,b,(uint)b.Capacity,0);if(n==0||n>=b.Capacity)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return b.ToString();}
 public static SafeFileHandle OpenOwner(string p){var h=CreateFileW(p,0x80010000,1,IntPtr.Zero,3,0x00200000,IntPtr.Zero);if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return h;}
 public static SafeFileHandle OpenIdentity(string p){var h=CreateFileW(p,0,7,IntPtr.Zero,3,0x02200000,IntPtr.Zero);if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return h;}
 public static SafeFileHandle OpenSecurity(string p){var h=CreateFileW(p,READ_CONTROL|WRITE_DAC|WRITE_OWNER,7,IntPtr.Zero,3,0x02200000,IntPtr.Zero);if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return h;}
 public static void SetOwnerAndDacl(SafeFileHandle h,byte[] sd){if(!SetKernelObjectSecurity(h,OWNER_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,sd))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());}
 public static byte[] GetSecurity(SafeFileHandle h){uint n;GetKernelObjectSecurity(h,OWNER_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,null,0,out n);if(n==0)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());var b=new byte[n];if(!GetKernelObjectSecurity(h,OWNER_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,b,n,out n))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return b;}
 public static void Rename(SafeFileHandle h,string target){byte[] n=Encoding.Unicode.GetBytes(target);int head=20;IntPtr p=Marshal.AllocHGlobal(head+n.Length+2);try{for(int x=0;x<head+n.Length+2;x++)Marshal.WriteByte(p,x,0);Marshal.WriteIntPtr(p,8,IntPtr.Zero);Marshal.WriteInt32(p,16,n.Length);Marshal.Copy(n,0,IntPtr.Add(p,head),n.Length);if(!SetFileInformationByHandle(h,3,p,(uint)(head+n.Length+2)))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());}finally{Marshal.FreeHGlobal(p);}}
 public static void FlushDirectory(string p){using(var h=CreateFileW(p,0x40000000,7,IntPtr.Zero,3,0x22000000,IntPtr.Zero)){if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());if(!FlushFileBuffers(h))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());}}
}
'@
[Console]::Error.WriteLine('NATIVE_TYPE_READY')
$TestFault=if($env:NODE_ENV-eq'test' -and $env:GROWTHMAP_BROKER_TEST_FAULT-in@('open','rename','flush')){$env:GROWTHMAP_BROKER_TEST_FAULT}else{''}
$TestCrashPhase=if($env:NODE_ENV-eq'test' -and $env:GROWTHMAP_BROKER_TEST_CRASH_PHASE-in@('after-old-rename-directory-flush','after-old-quarantine-directory-flush')){$env:GROWTHMAP_BROKER_TEST_CRASH_PHASE}else{''}
function Test-Crash([string]$phase){if($TestCrashPhase-ne$phase){return};$p=$env:GROWTHMAP_BROKER_TEST_CRASH_SENTINEL;if([string]::IsNullOrWhiteSpace($p)-or-not[IO.Path]::IsPathRooted($p)-or$p.StartsWith('\\')){throw 'request'};$d=[IO.Path]::GetDirectoryName($p);[IO.Directory]::CreateDirectory($d)|Out-Null;$b=[Text.Encoding]::UTF8.GetBytes($phase);$s=[IO.FileStream]::new($p,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read);try{$s.Write($b,0,$b.Length);$s.Flush($true)}finally{$s.Dispose()};NFlush $d;[Environment]::FailFast('GrowthMap allowlisted native test cutpoint')}
function NOpen([string]$p){if($TestFault-eq'open'){throw 'injected-open'};[GrowthMapBrokerNative]::OpenOwner($p)}
function NRename($h,[string]$p){if($TestFault-eq'rename'){throw 'injected-rename'};[GrowthMapBrokerNative]::Rename($h,$p)}
function NFlush([string]$p){if($TestFault-eq'flush'){throw 'injected-flush'};[GrowthMapBrokerNative]::FlushDirectory($p)}
function Canon([string]$p){if([string]::IsNullOrWhiteSpace($p)-or$p.Length-gt32767){throw 'path'};$f=[IO.Path]::GetFullPath($p);if(-not[IO.Path]::IsPathRooted($f)-or$f.StartsWith('\\')-or$f.StartsWith('\\?\')-or$f.StartsWith('\\.\')){throw 'boundary'};$root=[IO.Path]::GetPathRoot($f);if($f-ine$root){$f=$f.TrimEnd([IO.Path]::DirectorySeparatorChar)};$f}
function Info($h){$i=[GrowthMapBrokerNative]::GetInfo($h);if(($i.Attributes-band 0x450)-ne0-or$i.NumberOfLinks-ne1-or$i.VolumeSerial-eq0-or($i.FileIndexHigh-eq0-and$i.FileIndexLow-eq0)){throw 'unsafe'};$i}
function Final($h){$p=[GrowthMapBrokerNative]::FinalPath($h);if($p.StartsWith('\\?\UNC\')){throw 'network'};if($p.StartsWith('\\?\')){$p=$p.Substring(4)};Canon $p}
function Evidence($s){$s.Position=0;$sha=[Security.Cryptography.SHA256]::Create();try{$h=$sha.ComputeHash($s)}finally{$sha.Dispose()};$s.Position=0;@{sha256=[BitConverter]::ToString($h).Replace('-','').ToLowerInvariant();size=[int64]$s.Length}}
function Identity($i,[string]$p){@{platform='win32';path=$p;volumeSerial=('{0:X8}'-f$i.VolumeSerial);fileIndex=('{0:X8}{1:X8}'-f$i.FileIndexHigh,$i.FileIndexLow)}}
function Replacement-Identity($i){@{platform='win32';volumeSerial=('{0:X8}'-f$i.VolumeSerial);fileIndex=('{0:X8}{1:X8}'-f$i.FileIndexHigh,$i.FileIndexLow)}}
function Same($a,$b){$a.VolumeSerial-eq$b.VolumeSerial-and$a.FileIndexHigh-eq$b.FileIndexHigh-and$a.FileIndexLow-eq$b.FileIndexLow}
function Validate-Path([string]$p){$cur=[IO.Path]::GetDirectoryName($p);while($cur){if(([IO.File]::GetAttributes($cur)-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'reparse'};$par=[IO.Directory]::GetParent($cur);if($null-eq$par){break};$cur=$par.FullName}}
function Validate-Acl([string]$p){
 Validate-Path $p;$me=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;$trusted=@($me,'S-1-5-18','S-1-5-32-544')
 $danger=[Int64]([Security.AccessControl.FileSystemRights]::WriteData-bor[Security.AccessControl.FileSystemRights]::CreateFiles-bor[Security.AccessControl.FileSystemRights]::CreateDirectories-bor[Security.AccessControl.FileSystemRights]::AppendData-bor[Security.AccessControl.FileSystemRights]::Write-bor[Security.AccessControl.FileSystemRights]::Modify-bor[Security.AccessControl.FileSystemRights]::FullControl-bor[Security.AccessControl.FileSystemRights]::Delete-bor[Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles-bor[Security.AccessControl.FileSystemRights]::ChangePermissions-bor[Security.AccessControl.FileSystemRights]::TakeOwnership)
 foreach($x in @([IO.Path]::GetDirectoryName($p),$p)){$item=Get-Item -LiteralPath $x -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'reparse'};$acl=$item.GetAccessControl([Security.AccessControl.AccessControlSections]::Access-bor[Security.AccessControl.AccessControlSections]::Owner);try{$owner=([Security.Principal.NTAccount]$acl.Owner).Translate([Security.Principal.SecurityIdentifier]).Value}catch{$owner=([Security.Principal.SecurityIdentifier]$acl.Owner).Value};if($owner-notin$trusted){throw 'owner'};foreach($r in $acl.Access){$rsid=$r.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value;$rights=[Int64]$r.FileSystemRights;if($rsid-notin$trusted-and$r.AccessControlType-eq[Security.AccessControl.AccessControlType]::Allow-and((($rights-band$danger)-ne0)-or(($rights-band[Int64]0x40000000)-ne0)-or(($rights-band[Int64]0x10000000)-ne0))){throw 'acl'}}}
}
function Match-Evidence($a,$b){$null-ne$a-and$a.sha256-eq$b.sha256-and[int64]$a.size-eq[int64]$b.size}
function Exact-Keys($o,[string]$expected){if($null-eq$o-or$o-isnot[pscustomobject]-or((@($o.PSObject.Properties.Name|Sort-Object)-join'|')-ne$expected)){throw 'request'}}
function Strict-LocalPath([string]$raw){if([string]::IsNullOrWhiteSpace($raw)-or$raw.Length-gt4096-or$raw.IndexOf([char]0)-ge0-or$raw-notmatch'^[A-Za-z]:\\'-or$raw.Contains('/')-or$raw.Substring(2).Contains(':')-or$raw.IndexOfAny([char[]]'?*')-ge0){throw 'boundary'};$p=Canon $raw;$root=[IO.Path]::GetPathRoot($p);if([string]::IsNullOrWhiteSpace($root)-or[GrowthMapBrokerNative]::GetDriveTypeW($root)-ne3){throw 'network'};$p}
function Assert-FilePresent([string]$p){$a=[GrowthMapBrokerNative]::GetFileAttributesW($p);if($a-eq[uint32]::MaxValue){$e=[Runtime.InteropServices.Marshal]::GetLastWin32Error();if($e-in@(2,3)){throw 'missing'};throw 'state'};if(($a-band[uint32][IO.FileAttributes]::Directory)-ne0){throw 'target'}}
function Path-Parts([string]$p){,@($p.Substring(3).Split([char]'\',[StringSplitOptions]::RemoveEmptyEntries))}
function Assert-UnderRoot([string]$root,[string]$p){if($root.Substring(0,2)-ine$p.Substring(0,2)){throw 'boundary'};$r=Path-Parts $root;$x=Path-Parts $p;if($x.Count-lt$r.Count){throw 'boundary'};for($n=0;$n-lt$r.Count;$n++){if($r[$n]-ine$x[$n]){throw 'boundary'}}}
function Trusted-Sids(){@([Security.Principal.WindowsIdentity]::GetCurrent().User.Value,'S-1-5-18','S-1-5-32-544')}
function Owner-Sid($raw){if($null-eq$raw.Owner){throw 'owner'};[string]$raw.Owner.Value}
function Assert-TrustedOwner($raw){if((Owner-Sid $raw)-notin@(Trusted-Sids)){throw 'owner'}}
function Assert-SafeAcl($raw){
 Assert-TrustedOwner $raw;$trusted=@(Trusted-Sids);$danger=[Int64]([Security.AccessControl.FileSystemRights]::WriteData-bor[Security.AccessControl.FileSystemRights]::CreateFiles-bor[Security.AccessControl.FileSystemRights]::CreateDirectories-bor[Security.AccessControl.FileSystemRights]::AppendData-bor[Security.AccessControl.FileSystemRights]::Write-bor[Security.AccessControl.FileSystemRights]::Modify-bor[Security.AccessControl.FileSystemRights]::FullControl-bor[Security.AccessControl.FileSystemRights]::Delete-bor[Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles-bor[Security.AccessControl.FileSystemRights]::ChangePermissions-bor[Security.AccessControl.FileSystemRights]::TakeOwnership)
 foreach($ace in @($raw.DiscretionaryAcl)){if($ace-isnot[Security.AccessControl.KnownAce]){throw 'acl'};$sid=$ace.SecurityIdentifier.Value;if($sid-notin$trusted-and$ace.AceType-eq[Security.AccessControl.AceType]::AccessAllowed-and((([Int64]$ace.AccessMask-band$danger)-ne0)-or(([Int64]$ace.AccessMask-band[Int64]0x40000000)-ne0)-or(([Int64]$ace.AccessMask-band[Int64]0x10000000)-ne0))){throw 'acl'}}
}
function Assert-ExactPrivateAcl($raw,[bool]$isDir,[string]$currentSid){
 if((Owner-Sid $raw)-ne$currentSid){throw 'owner'};if(($raw.ControlFlags-band[Security.AccessControl.ControlFlags]::DiscretionaryAclProtected)-eq0-or$null-eq$raw.DiscretionaryAcl-or$raw.DiscretionaryAcl.Count-ne3){throw 'acl'}
 $expected=@{};foreach($sid in @(Trusted-Sids)){$expected[$sid]=1};$flags=if($isDir){[Security.AccessControl.AceFlags]([int][Security.AccessControl.AceFlags]::ContainerInherit-bor[int][Security.AccessControl.AceFlags]::ObjectInherit)}else{[Security.AccessControl.AceFlags]::None};$mask=[int][Security.AccessControl.FileSystemRights]::FullControl
 foreach($ace in $raw.DiscretionaryAcl){if($ace.GetType()-ne[Security.AccessControl.CommonAce]-or$ace.AceType-ne[Security.AccessControl.AceType]::AccessAllowed-or$ace.AceFlags-ne$flags-or$ace.AccessMask-ne$mask-or$ace-isnot[Security.AccessControl.QualifiedAce]-or$null-eq$ace.SecurityIdentifier){throw 'acl'};$sid=$ace.SecurityIdentifier.Value;if(-not$expected.ContainsKey($sid)-or$expected[$sid]-ne1){throw 'acl'};$expected[$sid]=0}
 if(@($expected.Values|Where-Object{$_-ne0}).Count-ne0){throw 'acl'}
}
function Open-CheckedIdentity([string]$p,[string]$kind){
 $h=[GrowthMapBrokerNative]::OpenIdentity($p);try{$i=[GrowthMapBrokerNative]::GetInfo($h);if(($i.Attributes-band 0x400)-ne0){throw 'reparse'};$isDir=($i.Attributes-band 0x10)-ne0;if(($kind-eq'directory'-and-not$isDir)-or($kind-eq'file'-and$isDir)){throw 'target'};if($kind-eq'file'-and$i.NumberOfLinks-ne1){throw 'unsafe'};if($i.VolumeSerial-eq0-or($i.FileIndexHigh-eq0-and$i.FileIndexLow-eq0)){throw 'identity'};if((Final $h)-ine$p){throw 'final'};@{info=$i;record=@{path=$p;identity=('{0:X8}:{1:X8}{2:X8}'-f$i.VolumeSerial,$i.FileIndexHigh,$i.FileIndexLow)}}}finally{$h.Dispose()}
}
function Validate-SecureItem([string]$p,[string]$kind){
 Validate-Path $p;$item=Get-Item -LiteralPath $p -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'reparse'}
 $h=[GrowthMapBrokerNative]::OpenSecurity($p);try{$raw=[Security.AccessControl.RawSecurityDescriptor]::new([GrowthMapBrokerNative]::GetSecurity($h),0);Assert-SafeAcl $raw}finally{$h.Dispose()}
 (Open-CheckedIdentity $p $kind).record
}
function Validate-SecureTarget([string]$root,$rootRecord,$t){Exact-Keys $t 'containerPolicy|kind|path';if([string]$t.containerPolicy-ne'private'-or[string]$t.kind-notin@('file','directory')){throw 'request'};$p=Strict-LocalPath([string]$t.path);Assert-UnderRoot $root $p;if($p-ieq$root){if([string]$t.kind-ne'directory'){throw 'target'};return $rootRecord};$relative=Path-Parts $p;$rootParts=Path-Parts $root;$cur=$root;for($n=$rootParts.Count;$n-lt($relative.Count-1);$n++){$cur=[IO.Path]::Combine($cur,$relative[$n]);[void](Validate-SecureItem $cur 'directory')};Validate-SecureItem $p ([string]$t.kind)}
function Validate-InitializationTarget([string]$p,[string]$kind){
 $item=Get-Item -LiteralPath $p -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'reparse'};$checked=Open-CheckedIdentity $p $kind
 $h=[GrowthMapBrokerNative]::OpenSecurity($p);try{$raw=[Security.AccessControl.RawSecurityDescriptor]::new([GrowthMapBrokerNative]::GetSecurity($h),0);Assert-TrustedOwner $raw}finally{$h.Dispose()};$checked.record
}
function Initialize-PrivateAcl([string]$p,[string]$kind){
 $h=[GrowthMapBrokerNative]::OpenSecurity($p);try{$before=[GrowthMapBrokerNative]::GetInfo($h);if(($before.Attributes-band 0x400)-ne0-or(Final $h)-ine$p-or$before.VolumeSerial-eq0-or($before.FileIndexHigh-eq0-and$before.FileIndexLow-eq0)){throw 'identity'};$isDir=($before.Attributes-band 0x10)-ne0;if(($kind-eq'directory'-and-not$isDir)-or($kind-eq'file'-and$isDir)-or($kind-eq'file'-and$before.NumberOfLinks-ne1)){throw 'target'}
  $preRaw=[Security.AccessControl.RawSecurityDescriptor]::new([GrowthMapBrokerNative]::GetSecurity($h),0);Assert-TrustedOwner $preRaw;$me=[Security.Principal.WindowsIdentity]::GetCurrent().User;$a=if($isDir){[Security.AccessControl.DirectorySecurity]::new()}else{[Security.AccessControl.FileSecurity]::new()};$a.SetOwner($me);$a.SetAccessRuleProtection($true,$false);$inherit=if($isDir){[Security.AccessControl.InheritanceFlags]([int][Security.AccessControl.InheritanceFlags]::ContainerInherit-bor[int][Security.AccessControl.InheritanceFlags]::ObjectInherit)}else{[Security.AccessControl.InheritanceFlags]::None};foreach($sid in @($me,[Security.Principal.SecurityIdentifier]::new('S-1-5-18'),[Security.Principal.SecurityIdentifier]::new('S-1-5-32-544'))){$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($sid,[Security.AccessControl.FileSystemRights]::FullControl,$inherit,[Security.AccessControl.PropagationFlags]::None,[Security.AccessControl.AccessControlType]::Allow))}
  [GrowthMapBrokerNative]::SetOwnerAndDacl($h,$a.GetSecurityDescriptorBinaryForm());$after=[GrowthMapBrokerNative]::GetInfo($h);if(-not(Same $before $after)-or($after.Attributes-band 0x400)-ne0-or(Final $h)-ine$p){throw 'identity'};$afterDir=($after.Attributes-band 0x10)-ne0;if($afterDir-ne$isDir-or(-not$isDir-and$after.NumberOfLinks-ne1)){throw 'target'};$raw=[Security.AccessControl.RawSecurityDescriptor]::new([GrowthMapBrokerNative]::GetSecurity($h),0);Assert-ExactPrivateAcl $raw $isDir $me.Value
  $fresh=[GrowthMapBrokerNative]::OpenIdentity($p);try{$fi=[GrowthMapBrokerNative]::GetInfo($fresh);if(-not(Same $before $fi)-or($fi.Attributes-band 0x400)-ne0-or(Final $fresh)-ine$p-or((($fi.Attributes-band 0x10)-ne0)-ne$isDir)-or(-not$isDir-and$fi.NumberOfLinks-ne1)){throw 'named'}}finally{$fresh.Dispose()};@{path=$p;identity=('{0:X8}:{1:X8}{2:X8}'-f$after.VolumeSerial,$after.FileIndexHigh,$after.FileIndexLow)}
 }finally{$h.Dispose()}
}
function Initialize-UnderRoot([string]$root,[string]$p,[string]$kind){
 if($p-ieq$root){$parent=[IO.Path]::GetDirectoryName($root);if([string]::IsNullOrWhiteSpace($parent)-or$parent-ieq$root){throw 'boundary'};$parent=Strict-LocalPath $parent;Validate-Path $parent;$ph=[GrowthMapBrokerNative]::OpenSecurity($parent);try{$pb=[GrowthMapBrokerNative]::GetInfo($ph);if(($pb.Attributes-band 0x400)-ne0-or($pb.Attributes-band 0x10)-eq0-or$pb.VolumeSerial-eq0-or($pb.FileIndexHigh-eq0-and$pb.FileIndexLow-eq0)-or(Final $ph)-ine$parent){throw 'identity'};$parentRaw=[Security.AccessControl.RawSecurityDescriptor]::new([GrowthMapBrokerNative]::GetSecurity($ph),0);Assert-SafeAcl $parentRaw;[void](Validate-InitializationTarget $p $kind);$done=Initialize-PrivateAcl $p $kind;$pa=[GrowthMapBrokerNative]::GetInfo($ph);if(-not(Same $pb $pa)-or($pa.Attributes-band 0x400)-ne0-or($pa.Attributes-band 0x10)-eq0-or(Final $ph)-ine$parent){throw 'identity'};$fresh=[GrowthMapBrokerNative]::OpenIdentity($parent);try{if(-not(Same $pb ([GrowthMapBrokerNative]::GetInfo($fresh)))-or(Final $fresh)-ine$parent){throw 'named'}}finally{$fresh.Dispose()};return $done}finally{$ph.Dispose()}}
 $rootRecord=Validate-SecureItem $root 'directory';$parts=Path-Parts $p;$rootParts=Path-Parts $root;$cur=$root;for($n=$rootParts.Count;$n-lt($parts.Count-1);$n++){$cur=[IO.Path]::Combine($cur,$parts[$n]);[void](Validate-SecureItem $cur 'directory')};[void](Validate-InitializationTarget $p $kind);Initialize-PrivateAcl $p $kind
}
function Read-LineBounded($r){$b=[Text.StringBuilder]::new();while($true){$c=$r.Read();if($c-lt0){if($b.Length-eq0){return $null};throw 'eof'};if($c-eq10){return $b.ToString().TrimEnd([char]13)};if($b.Length-ge$MaxLine){throw 'bounds'};[void]$b.Append([char]$c)}}
function Send($w,$v){$w.WriteLine(($v|ConvertTo-Json -Compress -Depth 8));$w.Flush()}
function Response($w,$id,$result){Send $w @{protocolVersion=$Protocol;id=$id;ok=$true;result=$result}}
function Error-Response($w,$id,[string]$code,[string]$stage){Send $w @{protocolVersion=$Protocol;id=$id;ok=$false;error=@{code=$code;stage=$stage}}}
function Public-Stage([string]$s){if($s-in@('busy-evidence','busy-transaction','state','target','missing','acl','evidence','path','boundary','derived','identity','final','named','owner','reparse','network','unsafe','request','action','command','injected-open','injected-rename','injected-flush')){return $s};return 'state'}
function Close-Tx(){if(-not$script:tx){return};$x=$script:tx;$script:tx=$null;foreach($v in @($x.ls,$x.ns,$x.lh,$x.nh)){if($v){try{$v.Dispose()}catch{}}}}
$pipe=$null;$reader=$null;$writer=$null;$evidenceHandles=@{};$script:tx=$null
try{
 $name=$env:GROWTHMAP_BROKER_PIPE;$nonce=$env:GROWTHMAP_BROKER_NONCE
 if($name-notmatch'^[0-9a-f]{32}$'-or$nonce-notmatch'^[0-9a-f]{64}$'){throw 'env'}
 [Console]::Error.WriteLine('ENV_READY')
 $sid=[Security.Principal.WindowsIdentity]::GetCurrent().User
 [Console]::Error.WriteLine('IDENTITY_READY')
 $security=[IO.Pipes.PipeSecurity]::new();$rights=[IO.Pipes.PipeAccessRights]::ReadWrite-bor[IO.Pipes.PipeAccessRights]::CreateNewInstance
 $security.AddAccessRule([IO.Pipes.PipeAccessRule]::new($sid,$rights,[Security.AccessControl.AccessControlType]::Allow));$security.SetAccessRuleProtection($true,$false)
 [Console]::Error.WriteLine('PIPE_SECURITY_READY')
 $pipe=[IO.Pipes.NamedPipeServerStream]::new($name,[IO.Pipes.PipeDirection]::InOut,1,[IO.Pipes.PipeTransmissionMode]::Byte,[IO.Pipes.PipeOptions]::Asynchronous-bor[IO.Pipes.PipeOptions]::WriteThrough,65536,65536,$security)
 [Console]::Error.WriteLine('SERVER_CREATED')
 [Console]::Error.WriteLine('WAIT_CLIENT')
 $ar=$pipe.BeginWaitForConnection($null,$null);if(-not$ar.AsyncWaitHandle.WaitOne(30000)){throw 'accept-timeout'};$pipe.EndWaitForConnection($ar)
 [Console]::Error.WriteLine('CLIENT_CONNECTED')
 $reader=[IO.StreamReader]::new($pipe,[Text.UTF8Encoding]::new($false),$false,4096,$true);$writer=[IO.StreamWriter]::new($pipe,[Text.UTF8Encoding]::new($false),4096,$true);$writer.NewLine="`n";$writer.AutoFlush=$true
 Send $writer @{protocolVersion=$Protocol;id=0;command='hello';nonce=$nonce}
 [Console]::Error.WriteLine('HELLO_SENT')
 $first=Read-LineBounded $reader
 $hello=$first|ConvertFrom-Json
 if ($hello.protocolVersion -ne $Protocol -or $hello.id -ne 1 -or $hello.command -ne 'hello' -or $hello.nonce -ne $nonce -or $hello.payload.challenge -notmatch '^[0-9a-f]{64}$') { throw 'auth' }
 $acl=@($security.GetAccessRules($true,$false,[Security.Principal.SecurityIdentifier])|ForEach-Object{@{sid=$_.IdentityReference.Value;rights=[int]$_.PipeAccessRights;type=$_.AccessControlType.ToString()}})
 Response $writer 1 @{protocolVersion=$Protocol;challenge=[string]$hello.payload.challenge;serverNonce=$nonce;ownerSid=$sid.Value;acl=$acl}
 while($true){$line=Read-LineBounded $reader;if($null-eq$line){break};$q=$line|ConvertFrom-Json;$id=[int]$q.id
  $keys=@($q.PSObject.Properties.Name|Sort-Object);if(($keys-join'|')-ne'command|id|nonce|payload|protocolVersion'-or$q.protocolVersion-ne$Protocol-or$id-lt2-or$q.nonce-ne$nonce-or$q.command-isnot[string]-or$null-eq$q.payload-or$q.payload-isnot[pscustomobject]){throw 'protocol'}
  try{switch([string]$q.command){
   'secure-read-file' {Exact-Keys $q.payload 'containerPolicy|maxBytes|path|root';if([string]$q.payload.containerPolicy-ne'private'-or$q.payload.maxBytes-isnot[int]-or[int]$q.payload.maxBytes-lt1-or[int]$q.payload.maxBytes-gt16777216){throw 'request'};$root=Strict-LocalPath([string]$q.payload.root);$p=Strict-LocalPath([string]$q.payload.path);Assert-UnderRoot $root $p;Assert-FilePresent $p;$rootRecord=Validate-SecureItem $root 'directory';[void](Validate-SecureTarget $root $rootRecord ([pscustomobject]@{path=$p;kind='file';containerPolicy='private'}));$h=[GrowthMapBrokerNative]::OpenOwner($p);try{$s=[IO.FileStream]::new($h,[IO.FileAccess]::Read,4096,$false);try{$before=Info $h;if((Final $h)-ine$p-or[int64]$s.Length-gt[int64]$q.payload.maxBytes){throw 'bounds'};$size=[int64]$s.Length;$mtime=([int64]$before.Write.High-shl32)-bor$before.Write.Low;$attrs=$before.Attributes;$data=[byte[]]::new([int]$size);$off=0;while($off-lt$data.Length){$n=$s.Read($data,$off,$data.Length-$off);if($n-le0){throw 'state'};$off+=$n};$after=Info $h;$afterMtime=([int64]$after.Write.High-shl32)-bor$after.Write.Low;if(-not(Same $before $after)-or[int64]$s.Length-ne$size-or$afterMtime-ne$mtime-or$after.Attributes-ne$attrs-or(Final $h)-ine$p){throw 'identity'};$fresh=[GrowthMapBrokerNative]::OpenIdentity($p);try{$fi=Info $fresh;if(-not(Same $before $fi)){throw 'named'}}finally{$fresh.Dispose()};Response $writer $id @{identity=('{0:X8}:{1:X8}{2:X8}'-f$before.VolumeSerial,$before.FileIndexHigh,$before.FileIndexLow);size=$size;dataBase64=[Convert]::ToBase64String($data)}}finally{$s.Dispose()}}finally{$h.Dispose()};continue}
   'secure-path-policy' {Exact-Keys $q.payload 'root|targets';$root=Strict-LocalPath([string]$q.payload.root);$targets=@($q.payload.targets);if($targets.Count-lt1-or$targets.Count-gt64){throw 'request'};$rootRecord=Validate-SecureItem $root 'directory';$out=@();for($n=0;$n-lt$targets.Count;$n++){$record=Validate-SecureTarget $root $rootRecord $targets[$n];$out+=@(@{index=$n;identity=$record.identity})};Response $writer $id @{identities=$out};continue}
   'initialize-private-acl' {Exact-Keys $q.payload 'containerPolicy|kind|path|root';if([string]$q.payload.containerPolicy-ne'private'-or[string]$q.payload.kind-notin@('file','directory')){throw 'request'};$root=Strict-LocalPath([string]$q.payload.root);$p=Strict-LocalPath([string]$q.payload.path);Assert-UnderRoot $root $p;$done=Initialize-UnderRoot $root $p ([string]$q.payload.kind);Response $writer $id @{identity=$done.identity;initialized=$true};continue}
   'open-evidence' {$t=[string]$q.payload.token;if($evidenceHandles.ContainsKey($t)){throw 'busy-evidence'};if($script:tx){throw 'busy-transaction'};if($t-notmatch'^[0-9a-f]{32}$'){throw 'request'};$p=Canon([string]$q.payload.path);Validate-Acl $p;$s=[IO.FileStream]::new($p,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$i=Info $s.SafeFileHandle;if((Final $s.SafeFileHandle)-ine$p){$s.Dispose();throw 'final'};$evidenceHandles[$t]=@{path=$p;stream=$s;info=$i};Response $writer $id @{identity=(Replacement-Identity $i);evidence=(Evidence $s)};continue}
   'assert-evidence' {$t=[string]$q.payload.token;if(-not$evidenceHandles.ContainsKey($t)){throw 'state'};$x=$evidenceHandles[$t];$i=Info $x.stream.SafeFileHandle;if(-not(Same $i $x.info)-or(Final $x.stream.SafeFileHandle)-ine$x.path){throw 'identity'};$fresh=[IO.FileStream]::new($x.path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$fi=Info $fresh.SafeFileHandle;if(-not(Same $fi $x.info)){throw 'named'}}finally{$fresh.Dispose()};Response $writer $id @{identity=(Replacement-Identity $i);evidence=(Evidence $x.stream)};continue}
   'close-evidence' {$t=[string]$q.payload.token;if($evidenceHandles.ContainsKey($t)){$x=$evidenceHandles[$t];$evidenceHandles.Remove($t);try{$x.stream.Dispose()}catch{}};Response $writer $id @{closed=$true};continue}
   'prepare-install' {if($evidenceHandles.Count){throw 'busy-evidence'};if($script:tx){throw 'busy-transaction'};$p=$q.payload;$live=Canon([string]$p.live);$staging=Canon([string]$p.staging);$old=Canon([string]$p.old);$capture=Canon([string]$p.capture);$tid=[string]$p.transactionId;if($tid-notmatch'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'-or$old-ine($live+'.gm-old-'+$tid)-or$staging-ine($live+'.gm-new-'+$tid)-or$capture-ine($staging+'.capture')-or[IO.Path]::GetDirectoryName($live)-ine[IO.Path]::GetDirectoryName($staging)-or[IO.File]::Exists($old)-or[IO.Directory]::Exists($old)-or[IO.File]::Exists($capture)-or[IO.Directory]::Exists($capture)){throw 'derived'};Validate-Acl $live;Validate-Acl $staging;$lh=NOpen $live;$nh=NOpen $staging;$ls=[IO.FileStream]::new($lh,[IO.FileAccess]::Read,4096,$false);$ns=[IO.FileStream]::new($nh,[IO.FileAccess]::Read,4096,$false);$li=Info $lh;$ni=Info $nh;$le=Evidence $ls;$ne=Evidence $ns;if($p.expectedOld-and-not(Match-Evidence $p.expectedOld $le)-or-not(Match-Evidence $p.expectedNew $ne)){throw 'evidence'};$script:tx=@{id=$tid;live=$live;staging=$staging;old=$old;lh=$lh;nh=$nh;ls=$ls;ns=$ns;li=$li;ni=$ni;oldEvidence=$le;newEvidence=$ne;installed=$false;quarantined=$false;rolledBack=$false};Response $writer $id @{old=@{identity=(Replacement-Identity $li);evidence=$le};new=@{identity=(Replacement-Identity $ni);evidence=$ne}};continue}
   'commit-install' {if(-not$script:tx-or$script:tx.id-ne$q.payload.transactionId-or$script:tx.installed){throw 'state'};if($TestFault-in@('rename','flush')){throw ('injected-'+$TestFault)};NRename $script:tx.lh $script:tx.old;NFlush ([IO.Path]::GetDirectoryName($script:tx.live));Test-Crash 'after-old-rename-directory-flush';NRename $script:tx.nh $script:tx.live;NFlush ([IO.Path]::GetDirectoryName($script:tx.live));$script:tx.installed=$true;Response $writer $id @{phase='installed-durable';old=@{identity=(Replacement-Identity $script:tx.li);evidence=(Evidence $script:tx.ls)};live=@{identity=(Replacement-Identity $script:tx.ni);evidence=(Evidence $script:tx.ns)}};continue}
   'assert-installed' {if(-not$script:tx-or-not$script:tx.installed-or$script:tx.quarantined-or$script:tx.rolledBack){throw 'state'};if((Final $script:tx.lh)-ine$script:tx.old-or(Final $script:tx.nh)-ine$script:tx.live){throw 'identity'};Response $writer $id @{old=(Evidence $script:tx.ls);live=(Evidence $script:tx.ns)};continue}
   'quarantine-old' {if(-not$script:tx-or-not$script:tx.installed-or$script:tx.quarantined-or$script:tx.rolledBack){throw 'state'};$to=$script:tx.old+'.quarantine';if([IO.File]::Exists($to)-or[IO.Directory]::Exists($to)){throw 'target'};NRename $script:tx.lh $to;NFlush ([IO.Path]::GetDirectoryName($to));Test-Crash 'after-old-quarantine-directory-flush';$script:tx.quarantined=$true;Response $writer $id @{evidence=(Evidence $script:tx.ls)};continue}
   'rollback-installed' {if(-not$script:tx-or-not$script:tx.installed-or$script:tx.quarantined-or$script:tx.rolledBack){throw 'state'};$failed=$script:tx.live+'.gm-failed-'+$script:tx.id;if([IO.File]::Exists($failed)-or[IO.Directory]::Exists($failed)){throw 'target'};NRename $script:tx.nh $failed;NRename $script:tx.lh $script:tx.live;NFlush ([IO.Path]::GetDirectoryName($script:tx.live));$script:tx.rolledBack=$true;Response $writer $id @{phase='rollback-durable';failed=$failed;live=@{identity=(Replacement-Identity $script:tx.li);evidence=(Evidence $script:tx.ls)}};continue}
   'recover' {if($evidenceHandles.Count){throw 'busy-evidence'};if($script:tx){throw 'busy-transaction'};$p=$q.payload;$db=Canon([string]$p.databasePath);$tid=[string]$p.transactionId;if($tid-notmatch'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'){throw 'request'};$old=$db+'.gm-old-'+$tid;$failed=$db+'.gm-failed-'+$tid;$quarantine=$old+'.quarantine';switch([string]$p.action){'rollback-live-to-failed'{$from=$db;$to=$failed};'rollback-old-to-live'{$from=$old;$to=$db};'cleanup-old-to-quarantine'{$from=$old;$to=$quarantine};default{throw 'action'}};if([IO.Path]::GetDirectoryName($from)-ine[IO.Path]::GetDirectoryName($to)-or[IO.File]::Exists($to)-or[IO.Directory]::Exists($to)){throw 'target'};Validate-Acl $from;$h=[GrowthMapBrokerNative]::OpenOwner($from);try{$s=[IO.FileStream]::new($h,[IO.FileAccess]::Read,4096,$false);try{$i=Info $h;if((Final $h)-ine$from){throw 'final'};$e=Evidence $s;if(-not(Match-Evidence $p.expected $e)){throw 'evidence'};NRename $h $to;NFlush ([IO.Path]::GetDirectoryName($to));if([string]$p.action-eq'cleanup-old-to-quarantine'){Test-Crash 'after-old-quarantine-directory-flush'};if((Final $h)-ine$to){throw 'final'};Response $writer $id @{phase='rename-durable';record=@{identity=(Replacement-Identity $i);evidence=(Evidence $s)}}}finally{$s.Dispose()}}finally{$h.Dispose()};continue}
   'close-transaction' {Close-Tx;Response $writer $id @{closed=$true};continue}
   'broker-status' {if($env:NODE_ENV-ne'test'-or$env:GROWTHMAP_BROKER_TEST_STATUS-ne'1'){throw 'command'};Response $writer $id @{evidenceCount=[int]$evidenceHandles.Count;transaction=[bool]$script:tx};continue}
   'hang' {if($env:NODE_ENV-ne'test'-or[string]::IsNullOrWhiteSpace($env:GROWTHMAP_BROKER_TEST_HANG_PID_FILE)){throw 'command'};$c=Start-Process -FilePath powershell.exe -ArgumentList @('-NoLogo','-NoProfile','-NonInteractive','-Command','Start-Sleep -Seconds 300') -WindowStyle Hidden -PassThru;[IO.File]::WriteAllText($env:GROWTHMAP_BROKER_TEST_HANG_PID_FILE,[string]$c.Id);Wait-Process -Id $c.Id;continue}
   'shutdown' {foreach($x in @($evidenceHandles.Values)){try{$x.stream.Dispose()}catch{}};$evidenceHandles.Clear();Close-Tx;Response $writer $id @{shutdown=$true};break}
   'hello' {throw 'hello-replay'}
   default {throw 'command'}
  }}catch{$raw=[string]$_.Exception.Message;Error-Response $writer $id 'NATIVE_BROKER_REJECTED' (Public-Stage $raw);if($raw-in@('protocol','auth')){throw}}
  if($q.command-eq'shutdown'){break}
 }
}catch{}finally{foreach($x in @($evidenceHandles.Values)){try{$x.stream.Dispose()}catch{}};$evidenceHandles.Clear();Close-Tx;if($reader){$reader.Dispose()};if($writer){$writer.Dispose()};if($pipe){$pipe.Dispose()}}
